DETE_Sandbox/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Abilities__c</fullName>
        <label>Additional Abilities</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <picklist>
            <picklistValues>
                <fullName>No High School Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School Education/ High School Equivalency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical or Vocational Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor&apos;s Degree or Equivalent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master&apos;s Degree or Equivalent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctorate Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Doctorate Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (please specify)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>General_Technologies__c</fullName>
        <label>General Technologies</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Industries__c</fullName>
        <label>Industries</label>
        <picklist>
            <picklistValues>
                <fullName>Accommodation and Food Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative and Support Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture, Forestry, Fishing, and Hunting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance and Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Care and Social Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management of Companies and Enterprises</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mining, Quarrying, and Oil and Gas Extraction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional, Scientific, and Technical Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate and Rental and Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation and Warehousing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation and Food Services,Administrative and Support Services,Agriculture, Forestry, Fishing, and Hunting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation and Food Services,Construction,Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture, Forestry, Fishing, and Hunting,Finance and Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction,Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction,Government,Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Employed,Utilities,Wholesale Trade</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <label>Knowledge</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode_of_Communication__c</fullName>
        <label>Mode of Communication</label>
        <picklist>
            <picklistValues>
                <fullName>Text Message(SMS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other(please specify)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Education__c</fullName>
        <label>Other_Education</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <label>Position/Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priorities_for_next_Role__c</fullName>
        <label>Priorities for next Role</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <picklist>
            <picklistValues>
                <fullName>$0 to $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 to $74,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$75,000 to $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 to $124,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$125,000 to $149,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$150,000 to $199,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$200,000 to $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Specific_Technologies__c</fullName>
        <label>Specific Technologies</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Travelling_Distance__c</fullName>
        <label>Travelling Distance</label>
        <picklist>
            <picklistValues>
                <fullName>0-5 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6-10 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11-25 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26-50 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-100 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100+ miles</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

DETE_Sandbox/src/classes/DETE_IndexPageController.cls
public with sharing class DETE_IndexPageController extends DETE_BaseClass {
    public Boolean isProfile                                                            {get; set;}
    public Boolean isJobSearch                                                          {get; set;}
    public Boolean isPassword                                                           {get; set;}
    public Boolean isLoggedIn                                                           {get; set;}
   // public String strUrlParameter                            {get; set;}
    public Contact objContact                                                           {get; set;}
    public String oldPasswordStr                                                        {get; set;}
    public String newPasswordStr                                                        {get; set;}
    public String verifyPasswordStr                                                     {get; set;}
    public User userObj;

    public DETE_IndexPageController() {
        isProfile = false;
        isJobSearch = false;
        isLoggedIn = false;
        isPassword = false;

        objContact = new Contact();
        userObj = new User();
        
       // strUrlParameter = '';

      //  String strUserName = System.currentPageReference().getParameters().get('unm');
        if (!String.isBlank(strUserName)) {
            list<User> listUser = new list<User>();
            listUser = [SELECT Id,
                               ContactId,
                               Username,
                               LastName,
                               FirstName,
                               CommunityNickname
                        FROM User
                        WHERE Username =: strUserName
                        limit 1
                       ];
            if (!listUser.isEmpty() && listUser[0].ContactId != null) {
                userObj = listUser[0];
                isLoggedIn = true;
               // strUrlParameter = '?unm=' + strUserName;

                list<Contact> listContact = new list<Contact>();
                listContact = [Select Id,
                                      FirstName,
                                      LastName,
                                      MailingCity,
                                      MailingState,
                                      MailingPostalCode,
                                      Phone,
                                      Email,
                                      Education__c,
                                      Other_Education__c,
                                      Position_Title__c,
                                      Company__c,
                                      Knowledge__c,
                                      General_Technologies__c,
                                      Salutation,
                                      Middle_Name__c,
                                      Birthdate,
                                      Additional_Abilities__c,
                                      Salary__c,
                                      Priorities_for_next_Role__c,
                                      Travelling_Distance__c,
                                      Mode_of_Communication__c,
                                      Industries__c,
                                      MailingStreet,
                                      Specific_Technologies__c,
                                      Address1__c,
                                      Address2__c
                               From Contact
                               Where Id =: listUser[0].ContactId
                               limit 1
                              ];
                if (!listContact.isEmpty()) {
                    objContact = listContact[0];
                }
            }
        }
        system.debug('aaaaaaaaa-> '+ isLoggedIn);
        system.debug('bbbbbbbbb-> '+ objContact);
        system.debug('**********'+isProfile);
        
        system.debug('&&&&&&&&'+UserInfo.getUserId());
        
    }

   /* public IndexPageController() {
        isProfile = false;
        isJobSearch = false;
        isLoggedIn = false;
        isPassword = false;

        objContact = new Contact();
        userObj = new User();

        String strUserName = System.currentPageReference().getParameters().get('unm');
        if (!String.isBlank(strUserName)) {
            list<User> listUser = new list<User>();
            listUser = [SELECT Id,
                               ContactId,
                               Username,
                               LastName,
                               FirstName,
                               CommunityNickname
                        FROM User
                        WHERE Username =: strUserName
                        limit 1
                       ];
            if (!listUser.isEmpty() && listUser[0].ContactId != null) {
                userObj = listUser[0];
                isLoggedIn = true;

                list<Contact> listContact = new list<Contact>();
                listContact = [Select Id,
                                      FirstName,
                                      LastName,
                                      MailingCity,
                                      MailingState,
                                      MailingPostalCode,
                                      Phone,
                                      Email,
                                      Education__c,
                                      Other_Education__c,
                                      Position_Title__c,
                                      Company__c,
                                      Skills__c,
                                      General_Technologies__c,
                                      Salutation
                               From Contact
                               Where Id =: listUser[0].ContactId
                               limit 1
                              ];
            
                if (!listContact.isEmpty()) {
                    objContact = listContact[0];
                }
            }
        }
        system.debug('aaaaaaaaa-> '+ isLoggedIn);
        system.debug('bbbbbbbbb-> '+ objContact);
        system.debug('**********'+isProfile);
        
        system.debug('&&&&&&&&'+UserInfo.getUserId());
        
        
    }*/
    
    public void fetchUsername() {
        //PageReference pg1 = Site.changePassword(newPasswordStr, verifyPasswordStr, oldPasswordStr);
        try {
            Site.validatePassword(userObj, newPasswordStr, verifyPasswordStr);
            System.setPassword(userObj.Id, newPasswordStr);
            ApexPages.Message msgStr = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Your password has been reset!');
            ApexPages.addMessage(msgStr);
        }
        catch(Exception exObj) {
            ApexPages.Message msgStr = new ApexPages.Message(ApexPages.Severity.Error, +exObj.getMessage());
            ApexPages.addMessage(msgStr);
        }
        //system.debug('>>> pg1 : '+pg1);
    }
}