MCA App/Release/MCA Dev Org/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Contact__c</fullName>
        <label>Bank Contact</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Phone__c</fullName>
        <label>Bank Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Business_Contact_Account__c</fullName>
        <label>Business Contact/Account #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <label>Business Phone #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Cellular_No__c</fullName>
        <label>Cellular #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Date_Business_Established__c</fullName>
        <label>Date Business Established</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID_No__c</fullName>
        <label>Federal Tax ID#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_Sales__c</fullName>
        <label>Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Landlord_Contact_Name__c</fullName>
        <label>Landlord Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Mortgagee__c</fullName>
        <label>Landlord/Mortgagee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Phone__c</fullName>
        <label>Landlord Phone #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Lease_start_date__c</fullName>
        <label>Lease start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_CC_Avg_All__c</fullName>
        <description>the average of $ Processed of all Credit Card Sales records related to the Account</description>
        <inlineHelpText>the average of $ Processed of all Credit Card Sales records related to the Account</inlineHelpText>
        <label>Monthly $ Processed Avg</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Payment__c</fullName>
        <label>Monthly Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>No_Credit_Card_Stmts__c</fullName>
        <label># Credit Card Stmts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Physical_Address_City__c</fullName>
        <label>Physical Address City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Left_On_Lease__c</fullName>
        <label>Time Left On Lease</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Entity__c</fullName>
        <label>Type of Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Sole Prop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <description>Accounts that represent banks and funders.</description>
        <label>Bank</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bank Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Account.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_Sales__c</fullName>
        <inlineHelpText>The average $ of monthly bank deposits.</inlineHelpText>
        <label>Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Owner_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner 1</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Business Owner contact can only show in Owner 1 field.</errorMessage>
            <filterItems>
                <field>Contact.Contact_Roles__c</field>
                <operation>equals</operation>
                <value>Business Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Contact_Roles__c</field>
                <operation>equals</operation>
                <value>Business Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Owner 2)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Date_Business_Established__c</fullName>
        <formula>Account.McaApp__Date_Business_Established__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Business Established</label>
        <type>Date</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.McaApp__Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>

MCA App/Release/MCA Dev Org/src/classes/DynamicFundingApplicationUtility.cls
/* 
 *  Utility class to retrun query for each field sets.
 *  Function will return query by fetching fields from field sets.
 *  Revision History: 
 * 
 *  Version           Author                 Date                 Description 
 *  1.0               Ripal Patel            10-July 2015           Initial Draft 

 */


public with sharing class DynamicFundingApplicationUtility {
	//variable declaration
	public String query1;
	public static final string owner1 = 'Owner_1__c';
	public static final string owner1LastName  = 'Owner_1__r.LastName';
	public static final string owner2 = 'Owner_2__c';
	public static final string owner2LastName = 'Owner_2__r.LastName';
	public static final string accountName = 'Account.Name';
	
	public List<Schema.FieldSetMember> getFields() {
            return SObjectType.Opportunity.FieldSets.ADDITIONAL_BUSINESS_INFORMATION.getFields();
    }
	//This method returns the list for BUSINESS INFORMATION section
	public Opportunity getOpportunityListBusiInfo(String opportunityId) {

		query1 = 'SELECT Id,';
        for(Schema.FieldSetMember f : this.getFields()) {
            query1 += f.getFieldPath() + ',';
        }
        system.debug('*****query1 field sets***'+query1);
        if(!query1.contains(owner1))
           query1 += owner1 + ',';
        if(!query1.contains(owner1LastName))
           query1 += owner1LastName + ',';
        if(!query1.contains(owner2))
           query1 += owner2 + ',';
        if(!query1.contains(owner2LastName))
           query1 += owner2LastName + ',';
        if(!query1.contains(accountName))
           query1 += accountName + ',';
        
        query1 = query1.subString(0, query1.length() - 1);
        query1 +=' FROM Opportunity';
        query1 += ' Where Id =';
        query1 += '\''+opportunityId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query1***'+query1);
        return Database.query(query1);
     }
     
     public List<Schema.FieldSetMember> getFields1() {
            return SObjectType.Opportunity.FieldSets.ADDITIONAL_OWNER_OFFICER_INFORMATION.getFields();
     }
        
     //This method returns the list for OWNER/OFFICER INFORMATION section
     public Opportunity getOpportunityListOwnerOfficerInfo(String opportunityId) {

        query1 = 'SELECT Id,';
        for(Schema.FieldSetMember f : this.getFields1()) {
            query1 += f.getFieldPath() + ',';
        }
        system.debug('*****query1 field sets***'+query1);
        if(!query1.contains(owner1))
           query1 += owner1 + ',';
        if(!query1.contains(owner1LastName))
           query1 += owner1LastName + ',';
        if(!query1.contains(owner2))
           query1 += owner2 + ',';
        if(!query1.contains(owner2LastName))
           query1 += owner2LastName + ',';
        if(!query1.contains(accountName))
           query1 += accountName + ',';
        
        query1 = query1.subString(0, query1.length() - 1);
        query1 +=' FROM Opportunity';
        query1 += ' Where Id =';
        query1 += '\''+opportunityId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query1 final ***'+query1);
        return Database.query(query1);
    }
        
	public List<Schema.FieldSetMember> getFields2() {
		return SObjectType.Opportunity.FieldSets.ADDITIONAL_2nd_OWNER_OFFICER_INFORMATION.getFields();
    }
        
    //This method returns the list for 2nd OWNER/OFFICER INFORMATION (if applicable) section
    public Opportunity getOpportunityList2ndOwnerOfficerInfo(String opportunityId) { 

        query1 = 'SELECT Id,';
        for(Schema.FieldSetMember f : this.getFields2()) {
            query1 += f.getFieldPath() + ',';
        }
            
        system.debug('*****query1 field sets***'+query1);
        if(!query1.contains(owner1))
           query1 += owner1 + ',';
        if(!query1.contains(owner1LastName))
           query1 += owner1LastName + ',';
        if(!query1.contains(owner2))
           query1 += owner2 + ',';
        if(!query1.contains(owner2LastName))
           query1 += owner2LastName + ',';
        if(!query1.contains(accountName))
           query1 += accountName + ',';
        
        query1 = query1.subString(0, query1.length() - 1);
        query1 +=' FROM Opportunity';
        query1 += ' Where Id =';
        query1 += '\''+opportunityId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query1***'+query1);
        return Database.query(query1);
     }
        
     public List<Schema.FieldSetMember> getFields3() {
        return SObjectType.Opportunity.FieldSets.ADDITIONAL_BANK_TRADE_INFORMATION.getFields();
     }
        
     //This method returns the list for BANK/TRADE INFORMATION section
     public Opportunity getOpportunityListBankTradeInfo(String opportunityId) {

        query1 = 'SELECT Id,';
        for(Schema.FieldSetMember f : this.getFields3()) {
            query1 += f.getFieldPath() + ',';
        }
        
        system.debug('*****query1 field sets***'+query1);
        if(!query1.contains(owner1))
           query1 += owner1 + ',';
        if(!query1.contains(owner1LastName))
           query1 += owner1LastName + ',';
        if(!query1.contains(owner2))
           query1 += owner2 + ',';
        if(!query1.contains(owner2LastName))
           query1 += owner2LastName + ',';
        if(!query1.contains(accountName))
           query1 += accountName + ',';
           
        query1 = query1.subString(0, query1.length() - 1);
        query1 +=' FROM Opportunity';
        query1 += ' Where Id =';
        query1 += '\''+opportunityId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query1***'+query1);
        return Database.query(query1);
    }
        
    public List<Schema.FieldSetMember> getFields4() {
		return SObjectType.Opportunity.FieldSets.ADDITIONAL_PROPERTY_INFORMATION.getFields();
    }
        
    //This method returns the list for PROPERTY INFORMATION section
    public Opportunity getOpportunityPropertyInfo(String opportunityId) {

        query1 = 'SELECT Id,';
        for(Schema.FieldSetMember f : this.getFields4()) {
            query1 += f.getFieldPath() + ',';
        }
        
        system.debug('*****query1 field sets***'+query1);
        if(!query1.contains(owner1))
           query1 += owner1 + ',';
        if(!query1.contains(owner1LastName))
           query1 += owner1LastName + ',';
        if(!query1.contains(owner2))
           query1 += owner2 + ',';
        if(!query1.contains(owner2LastName))
           query1 += owner2LastName + ',';
        if(!query1.contains(accountName))
           query1 += accountName + ',';
            
        query1 = query1.subString(0, query1.length() - 1);
        query1 +=' FROM Opportunity';
        query1 += ' Where Id =';
        query1 += '\''+opportunityId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query4***'+query1);
        return Database.query(query1);
	}
        
    public List<Schema.FieldSetMember> getFields5() {
		return SObjectType.Opportunity.FieldSets.ADDITIONAL_OTHER_INFORMATION.getFields();
    }
        
    //This method returns the list for OTHER INFORMATION section
    public Opportunity getOpportunityOtherInfo(String opportunityId) {

        query1 = 'SELECT Id,';
        for(Schema.FieldSetMember f : this.getFields5()) {
            query1 += f.getFieldPath() + ',';
        }
        
        system.debug('*****query1 field sets***'+query1);
        if(!query1.contains(owner1))
           query1 += owner1 + ',';
        if(!query1.contains(owner1LastName))
           query1 += owner1LastName + ',';
        if(!query1.contains(owner2))
           query1 += owner2 + ',';
        if(!query1.contains(owner2LastName))
           query1 += owner2LastName + ',';
        if(!query1.contains(accountName))
           query1 += accountName + ',';
        
        query1 = query1.subString(0, query1.length() - 1);
        query1+=' FROM Opportunity';
        query1 += ' Where Id =';
        query1 += '\''+opportunityId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query***'+query1);
        return Database.query(query1);
    }
    
    //This method returns the list for BUSINESS INFORMATION section
	public Account getAccountlist(String accountId) {

		query1 = 'SELECT Id,Name, Legal_Name__c, Type_of_Entity__c, Federal_Tax_ID_No__c, BillingStreet, BillingCity, BillingState,'
                 +'BillingPostalCode, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, Phone, Cellular_No__c,'
                 +'Fax, Date_Business_Established__c, Years_in_Business__c, Industry, Website, Email__c, Bank_Name__c, Bank_Contact__c,'
                 +'Bank_Phone__c, Business_Name__c, Business_Contact_Account__c, Business_Phone__c, Landlord_Mortgagee__c,'
                 +'Landlord_Contact_Name__c, Landlord_Phone__c, Lease_start_date__c, Time_Left_On_Lease__c, Monthly_Payment__c,'
                 +'Physical_Address_City__c ,Square_Footage__c, Gross_monthly_Sales__c, Monthly_CC_Avg_All__c,No_Credit_Card_Stmts__c,' 
                 +'AccountNumber,BillingCountryCode,BillingStateCode  From Account Where Id =';
        query1 += '\''+accountId+'\'' ;
        query1 +=' LIMIT 1 ';
        system.debug('*****query1***'+query1);
        return Database.query(query1); 
     } 
}