MCA App/Release/MCA Dev Org/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCA App/Release/MCA Dev Org/src/objects/ACH_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date_Time__c</fullName>
        <label>Batch Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/objects/ACH_Credentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CompanyKey__c</fullName>
        <label>CompanyKey</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Test__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Test</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LocID__c</fullName>
        <label>LocID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSS__c</fullName>
        <label>SSS</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>ACH Credentials</label>
</CustomObject>

MCA Dev/src/objects/ACH_Public_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_Recipient__c</fullName>
        <label>Email Recipient</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Tracking_Date__c</fullName>
        <label>Last Tracking Date</label>
        <type>DateTime</type>
    </fields>
    <label>ACH Public Settings</label>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Bank_Holiday__c.object
<CustomObject>
    <fields>
        <fullName>Holiday_Date__c</fullName>
        <label>Holiday Date</label>
        <type>Date</type>
    </fields>
    <label>Bank Holiday</label>
    <nameField>
        <label>Bank Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Bounce_Fees_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Fees__c</fullName>
        <label>Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Error Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Fees Setting</label>
    <nameField>
        <displayFormat>BFS-{0000}</displayFormat>
        <label>Bounce Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>ACH_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACH Batch</label>
        <referenceTo>ACH_Batch__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>Effective Date</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Transaction_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Transaction ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Fees__c</fullName>
        <formula>IF(TEXT(Transaction_Type__c) =&quot;Fee&quot;, &quot;$&quot;&amp;TEXT(Transaction_Amount__c) ,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fees</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Repayment__c</fullName>
        <label>Repayment</label>
        <referenceTo>Repayment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_Balance__c</fullName>
        <label>Running Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled. 
Settled: The ACH payment was pulled successfully from the customer&apos;s account 
Failed: Returned a failed response from the ACH provider</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fees Applied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Debit</fullName>
        <active>true</active>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Repayment__c.object
<CustomObject>
    <fields>
        <fullName>Intial_Repayment_Amount__c</fullName>
        <inlineHelpText>Initial Receivable/Repayment Amount.</inlineHelpText>
        <label>Initial Repayment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Hit_Date__c</fullName>
        <label>Next Hit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payee_Account__c</fullName>
        <label>Payer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Payment_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <inlineHelpText>The amount of the payment. For Recurring payments, this will be the amount of the incremental payments</inlineHelpText>
        <label>Installment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Frequency__c</fullName>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Repayment</label>
    <nameField>
        <displayFormat>PMT-{0000000}</displayFormat>
        <label>Payment Setting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <recordTypes>
        <fullName>ACH</fullName>
        <active>false</active>
        <label>ACH</label>
    </recordTypes>
    <recordTypes>
        <fullName>Recurring</fullName>
        <active>true</active>
        <label>Recurring</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA App/Release/MCA Dev Org/src/classes/ACHTest.cls
@isTest
private class ACHTest {

	
	@isTest 
	private static void createTransactionDailyBatch() {
        string nextHitDate = string.valueOf(ACHUtils.getValidDate(date.today().addDays(1))).split(' ')[0];
        createRepayments('Daily');

        ACH_Public_Settings__c settings = new ACH_Public_Settings__c();
        settings.Email_Recipient__c = 'test@test.test';
        insert settings;
        ACHUtils.sendErrorEmail('Test', null, 'This is a test');

        Test.startTest();
        ID batchprocessid = Database.executeBatch(new ACHCreateTransactionsBatch(nextHitDate));
        Test.stopTest();

        Repayment__c repayment = [select id from Repayment__c limit 1];

        Payment__c payment = [select id, Transaction_Amount__c, Status__c, Effective_Date__c from Payment__c limit 1];
        System.assertEquals(1000, payment.Transaction_Amount__c);
        System.assertEquals('Scheduled', payment.Status__c);
        System.assertEquals(ACHUtils.skipHolidays(ACHUtils.getValidDate(date.today().addDays(1)), repayment), payment.Effective_Date__c);
	}


	@isTest 
	private static void createTransactionWeeklyBatch() {
        string nextHitDate = string.valueOf(ACHUtils.getValidDate(date.today().addDays(1))).split(' ')[0];
        createRepayments('Weekly');
		
        Test.startTest();
        ID batchprocessid = Database.executeBatch(new ACHCreateTransactionsBatch(nextHitDate));
        Test.stopTest();

        Repayment__c repayment = [select id from Repayment__c limit 1];

        Payment__c payment = [select id, Transaction_Amount__c, Status__c, Effective_Date__c from Payment__c limit 1];
        System.assertEquals(1000, payment.Transaction_Amount__c);
        System.assertEquals('Scheduled', payment.Status__c);
        System.assertEquals(ACHUtils.skipHolidays(ACHUtils.getValidDate(date.today().addDays(1)), repayment), payment.Effective_Date__c);
	}

	@isTest 
	private static void createTransactionMonthlyBatch() {
        string nextHitDate = string.valueOf(ACHUtils.getValidDate(date.today().addDays(1))).split(' ')[0];
        createRepayments('Monthly');
		
        Test.startTest();
        ID batchprocessid = Database.executeBatch(new ACHCreateTransactionsBatch(nextHitDate));
        Test.stopTest();

        Repayment__c repayment = [select id from Repayment__c limit 1];

        Payment__c payment = [select id, Transaction_Amount__c, Status__c, Effective_Date__c from Payment__c limit 1];
        System.assertEquals(1000, payment.Transaction_Amount__c);
        System.assertEquals('Scheduled', payment.Status__c);
        System.assertEquals(ACHUtils.skipHolidays(ACHUtils.getValidDate(date.today().addDays(1)), repayment), payment.Effective_Date__c);
	}
	
	@isTest 
	private static void scheduleCreateTransactionTest() {
		ID scheduleId = System.schedule('Create Transactions Batch', '0 0 * * * ?', new ACHCreateTransactionBatchSchedule());	
        system.assertNotEquals(null, scheduleId);
	}

    @isTest
	private static void validateScheduleCreateTransBatch()
    {   
        Bank_Holiday__c holiday = new Bank_Holiday__c();
        holiday.Holiday_Date__c = Date.today().addDays(1);
        insert holiday;
        
        Map<String,Schema.RecordTypeInfo> rtMapByName = Repayment__c.SObjectType.getDescribe().getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName =  rtMapByName.get('ACH Recurring');
        Id recTypeId = rtByName.getRecordTypeId();
        
                  
        Account objAccount = new Account();
        objAccount.Name = 'Test Account';
        insert objAccount;
        Date currentDate = Date.Today();
        
        Test.starttest();
        Repayment__c objPayment = new Repayment__c();
        objPayment.Payment_Amount__c = 1000;
        objPayment.RecordTypeID=recTypeId;
        objPayment.Payment_Frequency__c = 'Daily';
        objPayment.Next_Hit_Date__c = currentDate.addDays(1);
        objPayment.Intial_Repayment_Amount__c = 10000;
        objPayment.Status__c = 'Active';
        objPayment.Payee_Account__c = objAccount.id;
        insert objPayment;
        String CRON_EXP = '0 0 0 1 1 ? 2025';  
        String jobId = System.schedule('testScheduledApex', CRON_EXP, new ACHCreateTransactionBatchSchedule() );

        CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];

        System.assertEquals(CRON_EXP, ct.CronExpression); 
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2025-01-01 00:00:00', String.valueOf(ct.NextFireTime));
        Test.stopTest();
    }


    @isTest
    private static void runningBalanceTriggerTest() {
        createPayments(1000, 'Settled', '', '');
        Payment__c payment = [select Running_Balance__c from Payment__c limit 1];
        System.assertEquals(9000, payment.Running_Balance__c);
    }


    @isTest
    private static void sendAchTransBatchTest() {
        createCredentials();
        createPayments(1000, 'Scheduled', '', '');
        
        Test.startTest();  
        //ACHSendTransactionBatch.sendAchTransBatch();
        Test.stopTest();
        Payment__c payment = [select Status__c from Payment__c limit 1];
        
        //System.assertEquals('Pending', payment.Status__c);

    }


    @isTest 
    private static void scheduleSendTransactionTest() {
        ID scheduleId = System.schedule('Send Transactions Batch', '0 0 * * * ?', new ACHSendTransactionBatchSchedule());   
        system.assertNotEquals(null, scheduleId);
    }


    @isTest
    private static void trackAchTransBatchTest() {
        ACH_Public_Settings__c settings = new ACH_Public_Settings__c();
        settings.Last_Tracking_Date__c = Date.today();
        insert settings;

        createCredentials();

        createPayments(1000, 'Scheduled', '', 'TEST1');
        createPayments(1000, 'Scheduled', '', 'TEST2');
        createFeesSettings();

        Test.startTest();
        //ACHTrackTransactionBatch.trackTrasactions();
        Test.stopTest();

        Payment__c payment = [select Status__c from Payment__c limit 1];
        //System.assertEquals('Settled', payment.Status__c);

    }


    @isTest 
    private static void scheduleTrackTransactionTest() {

        ID scheduleId = System.schedule('Track Transactions Batch', '0 0 * * * ?', new ACHTrackTransactionBatchSchedule());   
        system.assertNotEquals(null, scheduleId);
    }


    @isTest 
    private static void getACHReturnsTest() {
        createCredentials();
        system.assertEquals(null, ACHUtils.getACHReturns());
    }


    @isTest 
    private static void getACHReturnsHistTest() {
        createCredentials();
        system.assertEquals(null, ACHUtils.getACHReturnsHist(DateTime.now().addDays(-3), Datetime.now()));
    }


    @isTest
    private static void achWorksServiceCoverage() {
        createServiceCallOutCoverage();
    }


    private static void createCredentials() {
        ACH_Credentials__c auxCredential = new ACH_Credentials__c();
        auxCredential.Name = 'ACH Test';
        auxCredential.Active__c = true;
        auxCredential.Is_Test__c = true;
        auxCredential.LocID__c = '123';
        auxCredential.companyKey__c = 'company Key Test';
        auxCredential.company__c = 'Test';
        auxCredential.sss__c = 'aaa';
        insert auxCredential;
    }


    private static String createRepayments(String frequency) {
        Map<String,Schema.RecordTypeInfo> rtMapByName   = Repayment__c.SObjectType.getDescribe().getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName                  = rtMapByName.get('ACH Recurring');
        Id recTypeId                                    = rtByName.getRecordTypeId();

        Account account = new Account();
        account.Name    = 'Test';
        insert account;

        Repayment__c repayment                  = new Repayment__c();
        repayment.Status__c                     = 'Active';
        repayment.Payment_Method__c             = 'ACH';
        repayment.Intial_Repayment_Amount__c    = 10000;
        repayment.Payment_Amount__c             = 1000;
        repayment.Payee_Account__c              = account.Id;
        repayment.Payment_Frequency__c          = frequency;
        repayment.Next_Hit_Date__c              = Date.Today().addDays(1);
        repayment.RecordTypeID                  = recTypeId;
        insert repayment;

        return repayment.Id;
    }


    private static void createPayments(Double transactionAmount, String status, String frequency, String externalId) {
        Map<String,Schema.RecordTypeInfo> rtMapByName   = Payment__c.SObjectType.getDescribe().getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName                  = rtMapByName.get('Debit');
        Id recTypeId                                    = rtByName.getRecordTypeId();

        ACH_Batch__c batch          = new ACH_Batch__c();
        batch.Status__c             = 'Pending';
        batch.Batch_Date_Time__c    = DateTime.now();
        insert batch;

        Payment__c payment                  = new Payment__c();
        payment.Repayment__c                = createRepayments(frequency);
        payment.Transaction_Amount__c       = transactionAmount;
        payment.Effective_Date__c           = ACHUtils.getValidDate(date.today().addDays(1));
        payment.Status__c                   = status;
        payment.RecordTypeID                = recTypeId;
        payment.ACH_Batch__c                = batch.Id;
        payment.External_Transaction_ID__c  = externalId;
        insert payment;
    }


    private static void createFeesSettings() {
        Bounce_Fees_Settings__c feesSetting = new Bounce_Fees_Settings__c();
        feesSetting.Response_Code__c = 'TST';
        feesSetting.Fees__c = 12;
        insert feesSetting;
    }


    private static void createServiceCallOutCoverage() {

    }


}