MCA App/Release/MCA Dev Org/src/objects/ACH_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isScheduled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isScheduled</label>
        <type>Checkbox</type>
    </fields>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/objects/ACH_Payments_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_Recipient__c</fullName>
        <label>Email Recipient</label>
        <type>Email</type>
    </fields>
    <label>ACH Payments Settings</label>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Bank_Holiday__c.object
<CustomObject>
    <fields>
        <fullName>Holiday_Date__c</fullName>
        <label>Holiday Date</label>
        <type>Date</type>
    </fields>
    <label>Bank Holiday</label>
    <nameField>
        <label>Bank Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>ACH_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACH Batch</label>
        <referenceTo>ACH_Batch__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>Effective Date</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Transaction_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Transaction ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Repayment__c</fullName>
        <label>Repayment</label>
        <referenceTo>Repayment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Running_Balance__c</fullName>
        <label>Running Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled. 
Settled: The ACH payment was pulled successfully from the customer&apos;s account 
Failed: Returned a failed response from the ACH provider</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fees Applied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Debit</fullName>
        <active>true</active>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Repayment__c.object
<CustomObject>
    <fields>
        <fullName>Last_Batch_Date__c</fullName>
        <label>Last Batch Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Next_Hit_Date__c</fullName>
        <label>Next Hit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <inlineHelpText>The amount of the payment. For Recurring payments, this will be the amount of the incremental payments</inlineHelpText>
        <label>Installment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Frequency__c</fullName>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pending_Amount__c</fullName>
        <inlineHelpText>Amount submitted to the ACH processor, but not yet settled</inlineHelpText>
        <label>Total Pending Amount</label>
        <summarizedField>Payment__c.Transaction_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Scheduled, Pending</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Transaction_Type__c</field>
            <operation>equals</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Repayment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Outstanding_Amount__c</fullName>
        <formula>Intial_Repayment_Amount__c  -  Total_Amount_Settled__c - Total_Fees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total outstanding amount due</inlineHelpText>
        <label>Total Outstanding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Repayment</label>
    <nameField>
        <displayFormat>PMT-{0000000}</displayFormat>
        <label>Payment Setting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA App/Release/MCA Dev Org/src/classes/CreateTransBatch.cls
global class CreateTransBatch implements Database.Batchable<sObject>{

   global final String Query;
   global List<Payment__c> transactions;
   global static Set<Date> holidaySet;
   global CreateTransBatch(String q){
      Query=q;
      transactions = new List<Payment__c>();
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);      
   }

   global void execute(Database.BatchableContext BC, List<Repayment__c> scope){
     try{     
         holidaySet = new Set<Date>();
         List<Bank_Holiday__c> holidays = new List<Bank_Holiday__c>([select id,name,Holiday_Date__c from Bank_Holiday__c where Holiday_Date__c=THIS_YEAR and Holiday_Date__c>=Today]);
         for(Bank_Holiday__c holiday:holidays){
             holidaySet.add(holiday.Holiday_Date__c);
         }
         List<Ach_batch__c> batches = new List<Ach_Batch__c>([select id,createddate, isScheduled__c,(select id, Repayment__c from Payments__r where Effective_Date__c=tomorrow) from Ach_Batch__c 
                                                             where createddate=today order by createddate desc limit 1]);
         Ach_Batch__c batch;  
         Map<string,Payment__c> payIdTransaction = new Map<string, Payment__c>();   
         if(batches.size()>0){
             batch = batches[0];
             for(Payment__c t:batches[0].Payments__r)
                payIdTransaction.put(t.Repayment__c,t);
         }
         else{
             batch = new Ach_Batch__c();
             batch.Status__c= 'Pending';
             batch.isScheduled__c = True;
             insert batch;             
         }
         transactions = new List<Payment__c>();
         
         Map<String,Schema.RecordTypeInfo> rtMapByName = Payment__c.SObjectType.getDescribe().getRecordTypeInfosByName();
         Schema.RecordTypeInfo rtByName =  rtMapByName.get('Debit');
         string recTypeId = String.valueOf(rtByName.getRecordTypeId());
         system.debug(recTypeId);
         
         //Id recTypeId = [select Id from RecordType where SobjectType = 'ACHIT__Payment__c' and name = 'Debit' limit 1].Id;     
         for(Repayment__c pay : scope){
              Payment__c trans = new Payment__c();
              trans.ACH_Batch__c = batch.id;
              trans.Status__c = 'Scheduled';
              trans.Repayment__c = pay.id;
              trans.Transaction_Amount__c = (pay.Total_Outstanding_Amount__c - pay.Pending_Amount__c > pay.Payment_Amount__c ? pay.Payment_Amount__c :pay.Total_Outstanding_Amount__c - pay.Pending_Amount__c);
              trans.Transaction_Type__c = 'Payment';
              trans.RecordTypeId = recTypeId;   
              trans.Payment_Method__c = pay.Payment_Method__c;
              trans.Effective_Date__c = skipHolidays(pay.Next_Hit_Date__c,pay);
              trans.Running_Balance__c = pay.Total_Outstanding_Amount__c;         
              if(pay.Payment_Frequency__c!=null){
                  Date dt = getNextHitDate(pay);
                  pay.Next_Hit_Date__c = dt;
              }
              if(trans.Transaction_Amount__c > 0  && !payIdTransaction.containsKey(trans.Repayment__c))
                  transactions.add(trans);
              pay.Last_Batch_Date__c = system.now();//batch.createddate;
         }
         if(transactions.size()>0)
             insert transactions;
         for(Payment__c trans:transactions){
             string id = string.valueOf(trans.id);
             String idDate = String.valueOf(Date.today().month()) + String.valueOf(Date.today().day()) + String.valueOf(Date.today().year()).substring(2,4);
//             String idDate = String.valueOf(Date.today().month()) + String.valueOf(Date.today().day()) + String.valueOf(Date.today().year()).substring(3,5);
             trans.External_Transaction_ID__c='T' + idDate + id.substring((18 - (11 - (idDate.length()))),18);
                
         }
         if(transactions.size()>0)
             update transactions;
         update scope;
     }
     catch(Exception e){
      
      ACH_Payments_Settings__c settings = ACH_Payments_Settings__c.getOrgDefaults();
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[] {settings.Email_Recipient__c});
        email.setSubject('Batch execution Failed in salesforce organisation: CreateTransBatch');
        string html = 'Error encountered while Creating Transactions:';
        html+='<p>'+e.getMessage()+'</p>';
        html+='<p>'+e.getStackTraceString()+'</p>';
        email.setHtmlBody(html);
        emails.add(email);
        if(emails.size()>0)
            Messaging.sendEmail(emails);
     }
    }

   global void finish(Database.BatchableContext BC){       
       
   }   
   private Date getNextHitDate(Repayment__c pay){       
       if(pay.Payment_Frequency__c == 'Daily'){
           return skipHolidays(pay.Next_Hit_Date__c.addDays(1),pay);
       }
       else if (pay.Payment_Frequency__c == 'Weekly'){
           return skipHolidays(pay.Next_Hit_Date__c.addDays(7),pay);
       }
       else if (pay.Payment_Frequency__c == 'Monthly'){
           return skipHolidays(pay.Next_Hit_Date__c.addMonths(1),pay);
       }
       else
           return null;
   }
   private Date skipHolidays(Date nextHitDate,Repayment__c pay){       
       if(pay.Payments__r.size()>0 
          && pay.Payments__r[0].Status__c=='Scheduled' 
          && pay.Payments__r[0].Effective_Date__c==nextHitDate){
           nextHitDate = nextHitDate.addDays(1);
       }
       nextHitDate = getValidDate(nextHitDate);
       system.debug('%%'+nextHitDate);
       return nextHitDate;
   }
   private Date getValidDate(Date nextHitDate){
       system.debug('**'+nextHitDate+','+holidaySet.contains(nextHitDate));
       Datetime dt = DateTime.newInstance(nextHitDate, Time.newInstance(0, 0, 0, 0));       
       String dayOfWeek=dt.format('EEEE');
       system.debug('**'+dayOfWeek);
       if(dayOfWeek=='Saturday')
          return getValidDate(nextHitDate.addDays(1));
       else if(dayOfWeek=='Sunday')
          return getValidDate(nextHitDate.addDays(1));
       else if(holidaySet.contains(nextHitDate))
          return getValidDate(nextHitDate.addDays(1));
       else
           return nextHitDate;
   }
}