MCA App/Release/MCA Dev Org/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Integration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Processor Integration</label>
        <referenceTo>Processor_Integration__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Split Batch</label>
        <referenceTo>Split_Batch__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Processor_Integration__c.object
<CustomObject>
    <fields>
        <fullName>From_Addresses__c</fullName>
        <label>From Addresses</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_Number__c</fullName>
        <displayFormat>PI-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Processor Integration</label>
    <nameField>
        <label>Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processors Integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Split_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>From Address Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Messages__c</fullName>
        <label>Error Messages</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Import_Type__c</fullName>
        <label>Import Type</label>
        <picklist>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Processor_Integration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Processor Integration</label>
        <referenceTo>Processor_Integration__c</referenceTo>
        <relationshipName>Batch_Imports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rows_Imported__c</fullName>
        <label>Rows Imported</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Split Batch</label>
    <nameField>
        <displayFormat>SBN-{00000}</displayFormat>
        <label>Split Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Split Batchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/classes/PaymentsProcessEmailService.cls
global with sharing class PaymentsProcessEmailService implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        
        Attachment att = new Attachment();
        Processor_Integration__c processorIntegration = queryProcessorIntegration(email.fromAddress, email.subject);
        
        if (processorIntegration.From_Addresses__c != null && email.TextAttachments != null) {
            
            for (Messaging.Inboundemail.TextAttachment a : email.TextAttachments) {

                if (a.fileName != null && a.fileName.indexOf('.csv') != -1) {
                    
                    att.Name = 'Imported File ' + System.now().format('MM-dd-YYYY') + '.csv';
                    att.Body = Blob.valueOf(a.body);

                    Payment__c[] payments = PaymentsProcessUtils.getPayments(processorIntegration.Id, Blob.valueOf(a.body));
                    
                    if (payments != null) {
                        for (Payment__c pay : payments) {
                        	pay.Payment_Method__c = 'Split Funding';
                        }
                    
                        PaymentsProcessUtils.insertPayments(payments, processorIntegration.Id, Blob.valueOf(a.body), 'Email', email.fromAddress);
                    }
                }
            }

            if (PaymentsProcessUtils.error == null) {
                result.success = true;
            }
            else {
                result.success = false; 
                result.message = PaymentsProcessUtils.error + '\n\n' + PaymentsProcessUtils.errorMessage;
                
                Split_Batch__c bil = new Split_Batch__c();
                bil.Date_Time__c = System.now();
                bil.Processor_Integration__c = processorIntegration.Id;
                bil.Import_Type__c = 'Email';
                bil.Email__c = email.fromAddress;
                bil.Error_Messages__c = result.message;
                bil.Rows_Imported__c = 0;
                insert bil;
                
                att.ParentId = bil.Id;
                insert att; 
                
            }
        }
        else {
            result.success = false;
        }
        
        return result;
    }
    

    private Processor_Integration__c queryProcessorIntegration(String fromAddress, String subject) {
        Processor_Integration__c result = null;

        for (Processor_Integration__c pi : [SELECT Name, From_Addresses__c, Record_Number__c FROM Processor_Integration__c]) {
            if (pi.From_Addresses__c != null && pi.From_Addresses__c.contains(fromAddress)) {
                return pi;
            }
            if (pi.Record_Number__c != null && subject == pi.Record_Number__c) {
                result = pi;
            }
        }
        
        return result;
    }
}