VeraSandBox2016/src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

VeraSandBox2016/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Full_Profile_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores metadata for Full Profile pages.</description>
    <fields>
        <fullName>Fields__c</fullName>
        <description>Stores name of the field set to be used for current section</description>
        <label>Field Set Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>Page name on which this section is to be displayed. Possible values are ExpertSearchFullProfile or NominationFullProfile.</description>
        <label>Page Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <description>Name of the section on the page. Value of this field will be used to fetch complete record combined with page name value.</description>
        <label>Section Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Full Profile Setting</label>
</CustomObject>

VeraSandBox2016/src/classes/CustomRecordViewController_Test.cls
/***********************************************************************************
 * Class : NominationEvaluationController_Test
 * Created By : Ajinkya Hingne
 -----------------------------------------------------------------------------------
 * Description : Test class for testing functionalities in CustomRecordView
                 components and it's controller
 -----------------------------------------------------------------------------------
 * Version History:
 * Version    Developer Name    Date          Detail Features
   1.0        Ajinkya Hingne    20/04/2016    Initial Development
 **********************************************************************************/
@isTest
private class CustomRecordViewController_Test {

    /**
     * Test setter method of sobjectInstanceId
     */
    static testMethod void testSetSobjectInstanceId() {
        List<Account> accountRecord = TestDataFactory.createAccountData(1);
        List<Contact> contacts = TestDataFactory.createExperts(1, accountRecord[0]);

        Test.startTest();
        CustomRecordViewController controller = new CustomRecordViewController();
        controller.setSobjectInstanceId(contacts[0].Id);
        Test.stopTest();

        System.assertEquals(null, controller.sobjectInstance);
    }

    /**
     * Test setter method of page
     */
    static testMethod void testSetPage() {
        Test.startTest();
        CustomRecordViewController controller = new CustomRecordViewController();
        controller.setPage('ExpertSearchFullProfile');
        Test.stopTest();

        System.assertEquals(null, controller.sobjectInstance);
    }

    /**
     * Test setter method of Section
     */
    static testMethod void testSetSection() {
        Test.startTest();
        CustomRecordViewController controller = new CustomRecordViewController();
        controller.setSection('Expert Detail');
        Test.stopTest();

        System.assertEquals(null, controller.sobjectInstance);
    }

    /**
     * Test whether records is fetched correctly when all the setters are called
     */
    static testMethod void testSetAllComponent() {
        List<Account> accountRecord = TestDataFactory.createAccountData(1);
        List<Contact> contacts = TestDataFactory.createExperts(1, accountRecord[0]);
        TestDataFactory.createFullProfileCustomSettings();
        Test.startTest();
        CustomRecordViewController controller = new CustomRecordViewController();
        controller.setSobjectInstanceId(contacts[0].Id);
        controller.setPage('ExpertSearchFullProfile');
        controller.setSection('Expert Detail');
        controller.getSobjectInstanceId();
        controller.getPage();
        controller.getSection();
        controller.sectionColumns = 2;
        Test.stopTest();

        System.assertNotEquals(null, controller.sobjectInstance);
    }

    /**
     * Test whether records NOT fetched when custom setting record is not present
     */
    static testMethod void testSetAllComponentNoConfigData() {
        List<Account> accountRecord = TestDataFactory.createAccountData(1);
        List<Contact> contacts = TestDataFactory.createExperts(1, accountRecord[0]);
        Test.startTest();
        CustomRecordViewController controller = new CustomRecordViewController();
        controller.setSobjectInstanceId(contacts[0].Id);
        controller.setPage('ExpertSearchFullProfile');
        controller.setSection('Expert Detail');
        controller.getSobjectInstanceId();
        controller.getPage();
        controller.getSection();
        controller.sectionColumns = 2;
        Test.stopTest();

        System.assertEquals(null, controller.sobjectInstance);
    }

    /**
     * Test SOQL query exception by setting wrong field set name
     */
    static testMethod void testExceptionWrongFieldSet() {
        List<Account> accountRecord = TestDataFactory.createAccountData(1);
        List<Contact> contacts = TestDataFactory.createExperts(1, accountRecord[0]);
        TestDataFactory.createFullProfileCustomSettings();
        String pageName = 'ExpertSearchFullProfile';
        String sectionName = 'Expert Detail';
        Full_Profile_Setting__c settingToUpdate = [
                                                    SELECT
                                                        Id,
                                                        Fields__c
                                                    FROM
                                                        Full_Profile_Setting__c
                                                    WHERE
                                                        Page_Name__c = :pageName
                                                        AND Section_Name__c = :sectionName
                                                    ];
        settingToUpdate.Fields__c = 'Foo';
        update settingToUpdate;
        Test.startTest();
        CustomRecordViewController controller = new CustomRecordViewController();
        controller.setSobjectInstanceId(contacts[0].Id);
        controller.setPage(pageName);
        controller.setSection(sectionName);
        controller.getSobjectInstanceId();
        controller.getPage();
        controller.getSection();
        controller.sectionColumns = 2;
        Test.stopTest();

        System.assertEquals(null, controller.sobjectInstance);
    }
}