VeraSandBox2016/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Interested in training?</description>
        <label>Training</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

VeraSandBox2016/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Call for Nominations</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Catalog__c.object
<CustomObject>
    <label>Catalog</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Nomination__c.object
<CustomObject>
    <fields>
        <fullName>Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nomination</label>
    <nameField>
        <displayFormat>NOM-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Profile_Record__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <label>Profile Record</label>
    <nameField>
        <displayFormat>PFR-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile Records</pluralLabel>
    <recordTypes>
        <fullName>G_Employment</fullName>
        <active>true</active>
        <description>Record an Employment</description>
        <label>G- Employment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/classes/NominationFullProfileController_Test.cls
/***********************************************************************************
 * Class : NominationFullProfileController_Test
 * Created By : Ajinkya Hingne
 -----------------------------------------------------------------------------------
 * Description : Test class for testing functionalities in NominationFullProfileController
                 page and it's controller
 -----------------------------------------------------------------------------------
 * Version History:
 * Version    Developer Name    Date          Detail Features
   1.0        Ajinkya Hingne    26/04/2016    Initial Development
 **********************************************************************************/
@isTest
private class NominationFullProfileController_Test {

    /**
     * Test related records are fetched when a contact id is passed
     */
    static testMethod void testRelatedRecordsFetched() {
        TestDataFactory.createFullProfileCustomSettings();
        List<Account> accountRecord = TestDataFactory.createAccountData(1);
        List<Contact> experts = TestDataFactory.createExperts(1, accountRecord[0]);
        List<Catalog__c> catalogs = CatalogFactory.createLanguageCatalog(1);
        catalogs = CatalogFactory.insertData(catalogs);
        Profile_Record__c profile =
            TestDataFactory.createprofileRecordData(experts[0], catalogs[0], 'G_Employment');
        insert profile;
        List<Country__c> countries = TestDataFactory.createCountryData(1);
        List<Training__c> trainings = TestDataFactory.createTrainingData(1, countries[0]);
        List<Campaign> campaigns = TestDataFactory.createCampaignData(1);
        List<Nomination__c> nominations = TestDataFactory.createNominations(1,
                                            campaigns[0],
                                            trainings[0],
                                            experts[0]);

        Test.startTest();
        PageReference pageRef = Page.NominationFullProfile;
        pageRef.getParameters().put('id', nominations[0].Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController
            = new ApexPages.StandardController(nominations[0]);
        NominationFullProfileController pageCtrl
            = new NominationFullProfileController(stdController);
        Test.stopTest();

        System.assertEquals(0, pageCtrl.profileRecords.size());
    }
}