VeraSandBox2016/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Core_Expertise_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Expertise 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Area of Expertise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Experts (Core Expertise 1)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Expertise 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Area of Expertise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Experts (Core Expertise 2)</relationshipLabel>
        <relationshipName>Contacts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Expertise 3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Area of Expertise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Experts (Core Expertise 3)</relationshipLabel>
        <relationshipName>Contacts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Global_South__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stamped from Nationality</description>
        <inlineHelpText>Automatically updated based on Contact&apos;s Nationalities</inlineHelpText>
        <label>Global South</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JRRID__c</fullName>
        <displayFormat>JRR-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Main_Profession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Profession</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Profession</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Contacts (Main Profession)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Profession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Profession</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Profession</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Contacts (Secondary Profession)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Follow_up_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Follow-up By</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nomination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nomination</label>
        <referenceTo>Nomination__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Comments__c</fullName>
        <label>Overall Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Evaluation__c</fullName>
        <label>Overall Evaluation</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>EVA-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <recordTypes>
        <fullName>Nominations</fullName>
        <active>true</active>
        <description>Nominations Evaluation</description>
        <label>Nominations</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Training Evaluation</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Nomination__c.object
<CustomObject>
    <fields>
        <fullName>Application_Summary__c</fullName>
        <label>Application Summary</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_1__c</fullName>
        <formula>Contact__r.Core_Expertise_1__r.Name</formula>
        <label>Core Expertise 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_2__c</fullName>
        <formula>Contact__r.Core_Expertise_2__r.Name</formula>
        <label>Core Expertise 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_3__c</fullName>
        <formula>Contact__r.Core_Expertise_3__r.Name</formula>
        <label>Core Expertise 3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <formula>TEXT(Contact__r.Gender__c)</formula>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_South__c</fullName>
        <formula>Contact__r.Global_South__c</formula>
        <label>Global South</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Profession__c</fullName>
        <formula>Contact__r.Main_Profession__r.Name</formula>
        <label>Main Profession</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Evaluation__c</fullName>
        <description>This is a trigger-stamped average of all Overall Evaluation scores looking up to this Nomination</description>
        <label>Overall Evaluation</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Profession__c</fullName>
        <formula>Contact__r.Secondary_Profession__r.Name</formula>
        <label>Secondary Profession</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nomination</label>
    <nameField>
        <displayFormat>NOM-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>JRRID__c</fullName>
        <displayFormat>TRA-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/classes/NominationEvaluationController.cls
/***********************************************************************************
 * Class : NominationEvaluationController
 * Created By : Ajinkya Hingne
 -----------------------------------------------------------------------------------
 * Description : Controller for NominationEvaluation page
                 Class provides getter and setters for nomination records and evaluation records.
                 Also contains methods to save an evaluation record.
 -----------------------------------------------------------------------------------
 * Version History:
 * Version    Developer Name    Date          Detail Features
   1.0        Ajinkya Hingne    18/04/2016    Initial Development
 **********************************************************************************/
public with sharing class NominationEvaluationController {

    /* Getters and Setters */
    public List<Nomination__c> nominatedExperts {get; set;}
    public List<Evaluation__c> evaluations {get; set;}
    public Integer nominationCount {get; set;}
    public Integer evaluationCount {get; set;}
    public Integer nominationOffset {get; set;}
    public Integer nominationLimit {get; set;}

    // This variable is used only when page is opened through tab for selection of Training record
    public Nomination__c nominationForLookup {get; set;}
    public Nomination__c selectedNomination {get; set;}
    public Evaluation__c newEvaluation {get; set;}
    public Id trainingId {get; set;}
    public Id selectedNominationId {
        get;
        set {
            selectedNominationId = value;
        }
    }
    public Boolean isEditMode {get; set;}
    public Boolean isSaveSuccess {get; set;}
    private Map<Id, Nomination__c> nominationsIdRecordMap = new Map<Id, Nomination__c>();

    /**
     * Constructor
     * If page contains id parameter, nominations are loaded while initialization
     */
    public NominationEvaluationController() {
        trainingId = ApexPages.currentPage().getParameters().get(Constant.PARAM_ID);
        nominatedExperts = new List<Nomination__c>();
        evaluations = new List<Evaluation__c>();
        nominationCount = 0;
        evaluationCount = 0;
        isEditMode = false;
        isSaveSuccess = false;
        setDefaultOffsetLimit();
        selectedNomination = new Nomination__c();

        // Check whether page is opened from tab or training record
        if (String.isNotBlank(trainingId)) {
            loadNominations();
        } else {
            nominationForLookup = new Nomination__c();
        }
    }

    /**
     * Queries nomination object based on selected Training and populates the list of nominations
     * related to specified training
     */
    public PageReference loadNominations() {
        Boolean isTrainingChanged = false;

        // Set trainingId from the lookup variable and flag for identifying if training has changed
        if (nominationForLookup != null && nominationForLookup.Training__c != trainingId) {
            trainingId = nominationForLookup.Training__c;
            isTrainingChanged = true;
        } else if (nominationForLookup == null) {
            isTrainingChanged = true;
        }

        // Fetch nomination records related to training
        if (String.isNotBlank(trainingId) && nominationOffset >= 0) {
            nominatedExperts = [
                SELECT
                    Id,
                    Name,
                    Contact__r.JRRID__c,
                    Contact__r.Name,
                    Contact__r.Main_Profession__c,
                    Contact__r.Secondary_Profession__c,
                    Contact__r.Core_Expertise_1__c,
                    Contact__r.Core_Expertise_2__c,
                    Contact__r.Core_Expertise_3__c,
                    Contact__r.Gender__c,
                    Contact__r.Global_South__c,
                    Application_Summary__c,
                    (SELECT
                        Id
                    FROM
                        Evaluations__r
                    WHERE
                        CreatedById = :UserInfo.getUserId()
                    )
                FROM
                    Nomination__c
                WHERE
                    Training__c = :trainingId
                LIMIT
                    :nominationLimit
                OFFSET
                    :nominationOffset
            ];
            nominationsIdRecordMap = new Map<Id, Nomination__c>(nominatedExperts);
            if (isTrainingChanged) {
                nominationCount = [
                    SELECT
                        COUNT()
                    FROM
                        Nomination__c
                    WHERE
                        Training__c = :trainingId
                ];
            }
        }
        return null;
    }

    /**
     * Function called on click of a nomination record to show data related to selected nomination
     */
    public PageReference showSelectedNominationData() {
        selectedNomination = nominationsIdRecordMap.get(selectedNominationId);
        loadEvaluations();
        return null;
    }

    /**
     * Instantiates a new evaluation and toggles edit mode
     */
    public PageReference addEvaluation() {
        newEvaluation
            = new Evaluation__c(
                Nomination__c = selectedNominationId,
                RecordTypeId = RecordType_Utils.getRecordTypeId(
                    Constant.OBJECT_EVALUATION,
                    Label.Nominations_Record_Type
                )
            );
        isEditMode = true;
        isSaveSuccess = false;
        return null;
    }

    /**
     * Saves the Evaluation record to database
     */
    public PageReference saveEvaluation() {
        if (!validateRequiredFields()) {
            Utility.addPageMessage(ApexPages.Severity.ERROR, Label.All_Fields_Required_Message);
            return null;
        }
        try {
            insert newEvaluation;
            isSaveSuccess = true;
            loadNominations();
            loadEvaluations();
        } catch (DmlException dmlException) {
            Utility.addPageMessage(ApexPages.Severity.ERROR, dmlException.getMessage());
        }
        isEditMode = false;
        return null;
    }

    /**
     * Cancel returns to view mode and removes the ediatble row from table
     */
    public PageReference cancelEvaluation() {
        isEditMode = false;
        return null;
    }

    /**
     * Returns true if user has already evaluated the selected nomination
     */
    public Boolean getIsUserEvaluated() {
        Boolean isUserEvaluated = false;
        if (String.isNotBlank(selectedNominationId) &&
            nominationsIdRecordMap.containsKey(selectedNominationId)) {
            isUserEvaluated = nominationsIdRecordMap
                                .get(selectedNominationId)
                                .Evaluations__r.size() > 0;
        }
        return isUserEvaluated;
    }

    /**
     * Navigate to first page
     */
    public Void firstPage() {
        nominationOffset = Pagination_Utils.firstPage();
        loadNominations();
    }

    /**
     * Navigate to previous page
     */
    public Void previousPage() {
        nominationOffset = Pagination_Utils.previousPage(nominationOffset, nominationLimit);
        loadNominations();
    }

    /**
     * Navigate to next page
     */
    public Void nextPage() {
        nominationOffset = Pagination_Utils.nextPage(nominationOffset, nominationLimit);
        loadNominations();
    }

    /**
     * Navigate to last page
     */
    public Void lastPage() {
        nominationOffset = Pagination_Utils.lastPage(nominationLimit, nominationCount);
        loadNominations();
    }

    /**
     * Queries Evaluation object based on selected nomination
     */
    private Void loadEvaluations() {
        if (String.isNotBlank(selectedNominationId)) {
            evaluations = [
                SELECT
                    Id,
                    CreatedBy.Name,
                    CreatedById,
                    Name,
                    Overall_Evaluation__c,
                    Overall_Comments__c
                FROM
                    Evaluation__c
                WHERE
                    Nomination__c = :selectedNominationId
            ];
            evaluationCount = evaluations.size();
            isEditMode = false;
        }
    }

    /**
     * Validates required fields for Evaluation
     */
    private Boolean validateRequiredFields() {
        Boolean isValid = true;
        if (String.isBlank(newEvaluation.Overall_Comments__c) ||
            String.isBlank(newEvaluation.Overall_Evaluation__c)) {
                isValid = false;
        }
        return isValid;
    }

    /**
     * Sets default values for offset and limit
     */
    private Void setDefaultOffsetLimit() {
        nominationOffset = 0;
        nominationLimit = Integer.valueOf(System.Label.Nomination_Record_Limit);
    }

}