VeraSandBox2016/src/objects/Mission__c.object
<CustomObject>
    <fields>
        <fullName>CVIC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CVIC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FIAR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FIAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FOR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FOR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Global_South__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global South</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SGBV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SGBV</label>
        <type>Checkbox</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>CVIC_S_R__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CVIC S-R</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CVIC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CVIC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Expertise 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Catalog - Areas of Expertise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Positions (Core Expertise 1)</relationshipLabel>
        <relationshipName>Positions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Expertise 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Catalog - Areas of Expertise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Positions (Core Expertise 2)</relationshipLabel>
        <relationshipName>Positions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Expertise_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Expertise 3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Catalog - Areas of Expertise</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Positions (Core Expertise 3)</relationshipLabel>
        <relationshipName>Positions4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FIAR_S_R__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FIAR S-R</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FIAR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FIAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FOR_S_R__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FOR S-R</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FOR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FOR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Global_South__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global South</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Profession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Profession</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Catalog - Professions</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SGBV_S_R__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SGBV S-R</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SGBV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SGBV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Profession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Profession</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalog__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Catalog - Professions</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Positions (Secondary)</relationshipLabel>
        <relationshipName>Positions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/classes/PositionFactory.cls
/***********************************************************************************
 * Class : PositionFactory
 * Created By : Ashwini kr singh
 -----------------------------------------------------------------------------------
 * Description : Factory class for Position__c object
 -----------------------------------------------------------------------------------
 * Version History:
 * Version    Developer Name      Date          Detail Features
   1.0        Ashwini kr singh    03/05/2016    Initial Development
 **********************************************************************************/

public with sharing class PositionFactory {

    /**
     * Creates basic position record
     * @param numberOfRecordsas Integer for no. of records
     * @param missionId as Id for master object Mission__c
     *
     * @return list of position records 
     */
     public static List<Position__c> createBasicPosition(Integer numberOfRecords, Id missionId) {
        List<Position__c> positions = new List<Position__c>();
        for (Integer i = 1; i <= numberOfRecords; i++) {
            Position__c position = new Position__c(
                Name = 'Position'+i,
                Mission__c = missionId
            );
            positions.add(position);
        }
        return positions;
    }
    
    /**
     * Creates basic position record
     * @param numberOfRecordsas Integer for no. of records
     * @param missionId as Id for master object Mission__c
     * @param mainProfessionId as Id for master object Mission__c
     * @param secondaryprofessionId as Id for master object Mission__c
     * @param coreExpertise1 as Id for master object Mission__c
     * @param coreExpertise2 as Id for master object Mission__c
     * @param coreExpertise3 as Id for master object Mission__c
     *
     * @return list of position records 
     */
    public static List<Position__c> createPosition(
        Integer numberOfRecords,
        Id missionId,
        Id mainProfessionId,
        Id secondaryprofessionId,
        Id coreExpertise1,
        Id coreExpertise2,
        Id coreExpertise3
    ) {
        List<Position__c> positions = new List<Position__c>();
        for(Integer i = 1; i <= numberOfRecords; i++) {
            Position__c position = new Position__c(
                Name = 'Position'+i,
                Mission__c = missionId,
                SGBV__c =true,
                SGBV_S_R__c = true,
                Seniority__c = 2,
                CVIC__c = true,
                CVIC_S_R__c = true,
                FIAR__c = true,
                FIAR_S_R__c = true,
                FOR__c = true,
                FOR_S_R__c = true,
                Gender__c = 'Male',
                Global_South__c = true,
                Main_Profession__c = mainProfessionId,
                Secondary_Profession__c = secondaryprofessionId,
                Core_Expertise_1__c = coreExpertise1,
                Core_Expertise_2__c = coreExpertise2,
                Core_Expertise_3__c = coreExpertise3
            );
            positions.add(position);
        }
        return positions;
    }
    
     /**
     * Inserts position records
     */
    public static List<Position__c> insertData(List<Position__c> positions) {
        insert positions;
        return positions;
    }
}