VeraSandBox2016/src/objects/Profile_Record__c.object
<CustomObject>
    <fields>
        <fullName>Able_to_draft_report_without_translator__c</fullName>
        <label>Able to Draft Report Without Translator</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Can_Conduct_Interview_Without_Interpret__c</fullName>
        <label>Can Conduct Interview Without Interpret</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Can_Funtion_in_a_Professional_Setting__c</fullName>
        <label>Can Funtion in a Professional Setting</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Countries_of_Jurisdiction__c</fullName>
        <description>From global picklist</description>
        <inlineHelpText>Please select the country-ies that apply to your expertise</inlineHelpText>
        <label>Countries of Jurisdiction</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_of_Study__c</fullName>
        <label>Course of Study</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Degree_Name__c</fullName>
        <label>Degree Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>V = Vocational Diploma
B = Bachelor
GD = Graduate Diploma
M = Master
CAGS = Certificate of Advanced Graduate Study
D = Doctorate</inlineHelpText>
        <label>Degree Type</label>
        <picklist>
            <picklistValues>
                <fullName>VD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duties__c</fullName>
        <label>Duties</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duty_Station_City__c</fullName>
        <label>Duty Station City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty_Station_Country__c</fullName>
        <description>From global picklist</description>
        <label>Duty Station Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <label>Employer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Leave blank if current</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entry_from_Catalog__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entry from Catalog</label>
        <referenceTo>Catalog__c</referenceTo>
        <relationshipLabel>Profile Records</relationshipLabel>
        <relationshipName>Profile_Record</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expert__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Profile Records</relationshipLabel>
        <relationshipName>Expertise</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Explanation__c</fullName>
        <label>Explanation</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>General_Level__c</fullName>
        <label>General Level</label>
        <picklist>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother Tongue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JRR_Language__c</fullName>
        <label>JRR Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <inlineHelpText>If the person speaks english, french or spanish, please indicate which. If not, please indicate which language the person speaks.</inlineHelpText>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Months_Spent_in_Country__c</fullName>
        <description>How many months were spent in this country?</description>
        <label>Months Spent in Country</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of Referee</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Hours__c</fullName>
        <label>Number of Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oral_Expression__c</fullName>
        <label>Oral Expression</label>
        <picklist>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother Tongue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Oral_Understanding__c</fullName>
        <label>Oral Understanding</label>
        <picklist>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother Tongue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <description>Referee Organisation</description>
        <label>Organisation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Expertise__c</fullName>
        <description>Other expertises</description>
        <label>Other Expertise</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other_Language__c</fullName>
        <description>Language not yet in catalogue</description>
        <inlineHelpText>If the language is not available in the the catalog, please indicate the language here</inlineHelpText>
        <label>Other Language</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passport_Expiry_Date__c</fullName>
        <label>Passport Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipName>Expertise</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reading__c</fullName>
        <label>Reading</label>
        <picklist>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother Tongue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Referee Relationship</description>
        <inlineHelpText>Please specify the nature of relation (e.g. current supervisor; previous colleague, etc.)</inlineHelpText>
        <label>Relationship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>Referee Salutation</description>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Speaks_English_French_or_Spanish__c</fullName>
        <label>Speaks English, French, or Spanish</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Surname__c</fullName>
        <description>Referee Surname</description>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Position__c</fullName>
        <label>Title/Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Referee title</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Traditional_Justice_Def__c</fullName>
        <inlineHelpText>If you have selected &quot;Tradional justice system&quot;, please define</inlineHelpText>
        <label>Traditional Justice Def.</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Knowledge__c</fullName>
        <inlineHelpText>Theor = Theoretical (e.g. study) ; Prof. = Professional</inlineHelpText>
        <label>Type of Knowledge</label>
        <picklist>
            <picklistValues>
                <fullName>Theor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Writing__c</fullName>
        <label>Writing</label>
        <picklist>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother Tongue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profile Record</label>
    <nameField>
        <displayFormat>PFR-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile Records</pluralLabel>
    <recordTypes>
        <fullName>A_Nationality</fullName>
        <active>true</active>
        <description>Record a Nationality</description>
        <label>A- Nationality</label>
    </recordTypes>
    <recordTypes>
        <fullName>B_JRR_Language</fullName>
        <active>true</active>
        <description>Record a JRR Language (English, French, Spanish or Arabic)</description>
        <label>B- JRR Language</label>
    </recordTypes>
    <recordTypes>
        <fullName>C_Other_Language</fullName>
        <active>true</active>
        <description>Record a Language (other than English, French, Spanish or Arabic)</description>
        <label>C- Other Language</label>
    </recordTypes>
    <recordTypes>
        <fullName>D_Area_of_Expertise</fullName>
        <active>true</active>
        <description>Record an Area of Expertise</description>
        <label>D- Area of Expertise</label>
    </recordTypes>
    <recordTypes>
        <fullName>E_Legal_System_Expertise</fullName>
        <active>true</active>
        <description>Record a Legal System Expertise</description>
        <label>E- Legal System Expertise</label>
    </recordTypes>
    <recordTypes>
        <fullName>F_Country_Expertise</fullName>
        <active>true</active>
        <description>Record a Country Expertise</description>
        <label>F- Country Expertise</label>
    </recordTypes>
    <recordTypes>
        <fullName>G_Employment</fullName>
        <active>true</active>
        <description>Record an Employment</description>
        <label>G- Employment</label>
    </recordTypes>
    <recordTypes>
        <fullName>H_Education</fullName>
        <active>true</active>
        <description>Record an Education</description>
        <label>H- Education</label>
    </recordTypes>
    <recordTypes>
        <fullName>I_Trainings_and_Qual</fullName>
        <active>true</active>
        <description>Record a Training and Qualification</description>
        <label>I- Trainings and Qual.</label>
    </recordTypes>
    <recordTypes>
        <fullName>J_Referee</fullName>
        <active>true</active>
        <description>Record a Referee (person of reference)</description>
        <label>J- Referee</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/classes/ProfileFactory.cls
public class ProfileFactory {

    /**
    * Creates Profile record with for A- Nationality record type
    */
    public static List<Profile_Record__c> createNationalityProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 'A_Nationality');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Entry_from_Catalog__c = catalogId,
                Passport_Number__c = '123456789'+i,
                Passport_Expiry_Date__c = System.Today().addDays(i),
                Comments__c = 'Comment for A-Nationality Record type',
                Expert__c = expertId != null ? expertId : null,
                Position__c = positionId != null ? positionId : null,
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for B- JRR Language record type
    */
    public static List<Profile_Record__c> createJRRProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 'B_JRR_Language');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Entry_from_Catalog__c = catalogId,
                Expert__c = expertId != null ? expertId : null,
                Position__c = positionId != null ? positionId : null,
                JRR_Language__c = 'English',
                General_Level__c = 'Basic',
                Reading__c = 'Basic',
                Writing__c = 'Basic',
                Oral_Understanding__c = 'Basic',
                Oral_Expression__c = 'Basic',
                Can_Conduct_Interview_Without_Interpret__c = 'Yes',
                Able_to_draft_report_without_translator__c = 'Yes',
                Can_Funtion_in_a_Professional_Setting__c = 'Yes',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for C- Other Language record type
    */
    public static List<Profile_Record__c> createOtherLanguageProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 'C_Other_Language');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Entry_from_Catalog__c = catalogId != null ? catalogId : null,
                Expert__c = expertId != null ? expertId : null,
                Position__c = positionId != null ? positionId : null,
                Other_Language__c = 'Greek',
                General_Level__c = 'Basic',
                Reading__c = 'Basic',
                Writing__c = 'Basic',
                Oral_Understanding__c = 'Basic',
                Oral_Expression__c = 'Basic',
                Can_Conduct_Interview_Without_Interpret__c = 'Yes',
                Able_to_draft_report_without_translator__c = 'Yes',
                Can_Funtion_in_a_Professional_Setting__c = 'Yes',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for D- Area of Expertise record type
    */
    public static List<Profile_Record__c> createAreaOfExpertiseProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'D_Area_of_Expertise');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Entry_from_Catalog__c = catalogId,
                Expert__c = expertId != null ? expertId : null,
                Position__c = positionId != null ? positionId : null,
                Other_Expertise__c = 'Experitse'+i,
                Explanation__c = 'Explanation for '+i+ 'Record',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for E- Legal System Expertise record type
    */
    public static List<Profile_Record__c> createLegalExpertiseProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'E_Legal_System_Expertise');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Entry_from_Catalog__c = catalogId,
                Expert__c = expertId != null ? expertId : null,
                Position__c = positionId != null ? positionId : null,
                Traditional_Justice_Def__c = 'Traditional Justice'+i,
                Countries_of_Jurisdiction__c = 'Albania;Algeria',
                Explanation__c = 'Explanation'+i,
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for F- Country Expertise record type
    */
    public static List<Profile_Record__c> createCountryExpertiseProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'F_Country_Expertise');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Entry_from_Catalog__c = catalogId,
                Expert__c = expertId != null ? expertId : null,
                Position__c = positionId != null ? positionId : null,
                Months_Spent_in_Country__c = 04,
                Type_of_Knowledge__c = 'Theor.',
                Explanation__c = 'Explanation for Country Expertise Profile',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for G- Employment record type
    */
    public static List<Profile_Record__c> createEmploymentProfile(Integer numberOfRecords, 
                                                Id expertId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'G_Employment');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Expert__c = expertId != null ? expertId : null,
                Employer__c = 'Employer'+i,
                Title_Position__c = 'Teacher',
                Department__c = 'Employment',
                Duty_Station_City__c = 'AlbaniaCity',
                Duty_Station_Country__c = 'Albania',
                Start_Date__c = system.Today().addDays(i),
                End_Date__c = system.Today().addDays(i+10),
                Duties__c = 'Duties for Employment Profile',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for H- Education record type
    */
    public static List<Profile_Record__c> createEducationProfile(Integer numberOfRecords, 
                                                Id expertId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'H_Education');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Expert__c = expertId != null ? expertId : null,
                Degree_Type__c = 'Management',
                Degree_Name__c = 'MBA',
                Institution__c = 'EducationInstitution',
                City__c = 'AlbaniaCity',
                Country__c = 'Albania',
                Start_Date__c = system.Today().addDays(i),
                End_Date__c = system.Today().addDays(i+10),
                Course_of_Study__c = 'Course of Study for Education Profile',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for I- Trainings and Qual. record type
    */
    public static List<Profile_Record__c> createTrainingProfile(Integer numberOfRecords, 
                                                Id expertId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'I_Trainings_and_Qual');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Expert__c = expertId != null ? expertId : null,
                Course_Name__c = 'Engineering',
                Institution__c = 'TrainingInstitution',
                City__c = 'AlbaniaCity',
                Country__c = 'Albania',
                Start_Date__c = system.Today().addDays(i),
                End_Date__c = system.Today().addDays(i+10),
                Number_of_Hours__c = 04.50,
                Course_of_Study__c = 'Course of Study for Education Profile',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
    
    /**
    * Creates Profile record with for J- Referee Expertise record type
    */
    public static List<Profile_Record__c> createRefereeProfile(Integer numberOfRecords, 
                                                Id catalogId,
                                                Id expertId,
                                                Id positionId) {
        Id recordTypeId = RecordType_Utils.getRecordTypeId('Profile_Record__c', 
                                                           'J_Referee');
        List<Profile_Record__c> profiles = new List<Profile_Record__c>();
        for(Integer i = 0; i < numberOfRecords; i++) {
            Profile_Record__c profile = new Profile_Record__c(
                Expert__c = expertId != null ? expertId : null,
                Salutation__c = 'Mr.',
                Name__c = 'TestName'+i,
                Surname__c ='TestSurname'+i,
                Organisation__c = 'Organization'+i,
                Title__c = 'Title'+i,
                Speaks_English_French_or_Spanish__c = 'Yes',
                Relationship__c = 'previous colleague',
                Telephone_Number_1__c = '98765432'+i,
                Telephone_Number_2__c = '12345678'+i,
                Email_Address_1__c = 'firstEmail@gmail.com',
                Email_Address_2__c = 'secondEmail@gmail.com',
                Language__c = 'English',
                RecordTypeId = recordTypeId
            );
            profiles.add(profile);
        }
        return profiles;
    }
}