MCA Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA Dev/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA Dev/src/objects/FO_DEW_Calculate_Percentage_Of__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Opportunity_Field_API_Name__c</fullName>
        <label>Opportunity Field API Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percentage_Of_Value__c</fullName>
        <label>Percentage Of Value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receivable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Receivable</label>
        <type>Checkbox</type>
    </fields>
    <label>FO DEW Calculate Percentage Of</label>
</CustomObject>

MCA Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Deal_Entry_Wizard_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Keeps the check of whether user has entered the Deal Entry Wizard?</description>
        <label>Deal Entry Wizard Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Funding_Amount__c</fullName>
        <label>Funded $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payback_Amount__c</fullName>
        <label>Payback $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount__c</fullName>
        <label>Payoff $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCA Dev/src/objects/Payable__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Amount_Used__c</fullName>
        <label>Deal Amount Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsCreatedFromGrid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check-box will identify if payable s are created from Opportunity Grid.</description>
        <label>IsCreatedFromGrid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Percentage of</label>
        <picklist>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Funded Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inprogress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payee_Type__c</fullName>
        <label>Payee Type</label>
        <picklist>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Receivable_Dependency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receivable Dependency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Receivable__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Receivable__c</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Needs Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid - Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Clarification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Provider Pmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wizard_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To Check if Payable has gone through Wizard process</description>
        <label>Wizard Check</label>
        <type>Checkbox</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>PAYB-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCA Dev/src/objects/Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c - Receivable_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Amount_Used__c</fullName>
        <label>Deal Amount Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsCreatedFromGrid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check-box will identify if receivables are created from Opportunity Grid and if so receivables wont be considered for auto creating parables.</description>
        <label>IsCreatedFromGrid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Percentage of</label>
        <picklist>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Funded Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inprogress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wizard_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To Identify if Receivable has gone through wizard process</description>
        <label>Wizard Check</label>
        <type>Checkbox</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA Dev/src/classes/DEWPayablesService.cls
/*
    A Utility class for Create Contract Controller to handle the mehthods specific to Payables
*/
public with sharing class DEWPayablesService {

    public static Boolean isPayableError = false;
    public static String payErrorMsg;
    //method to fetch Payables from DB
    public static list<Payable__c> getPayablesFromDB(Id oppId)
    {

        return [Select Name,
                Memo__c,
                Type__c,
                Status__c,
                Due_Date__c,
                Amount_Due__c,
                Opportunity__c,
                Payback_Funded__c,
                Deal_Amount_Used__c,
                Account__c,
                Account__r.type,
                Payee_Type__c,
                Percentage__c,
                Receivable_Dependency__c,
                Wizard_Check__c,
                IsCreatedFromGrid__c
                From Payable__c
                Where Opportunity__c =: oppId];
    }

    //For checking payables fields null value
    public static Boolean payablesFieldsNullValidator(Payable__c objPayable)
    {
        if(objPayable.Type__c == null && objPayable.Amount_Due__c == null &&
            objPayable.Percentage__c == null &&
            objPayable.Payback_Funded__c == null &&
            objPayable.Account__c == null && objPayable.Due_Date__c == null &&
            objPayable.Status__c == null && objPayable.Memo__c == null &&
            objPayable.Receivable_Dependency__c == null )
        {
            return true;
        }

        return false;
    }
    // to add a payable Row
    public static List<Payable__c> addPayableRow(
        Id OppId,
        Opportunity objOpp,
        List<Account> accList,
        List<Receivable__c> receivableList,
        List<Payable__c> payableList)
    {
        Receivable__c objRec = new Receivable__c();
        // null check for parameters

        if(accList != null && accList.size() > 0
            && receivableList != null && receivableList.size()>0
            && payableList.size()<=0
            && objOpp != null && OppId != null) {
            Account accObj = accList[0];
            // check if Payabck is 'Payback' or 'Funded'
            if(accObj.Payback_Funded__c == 'Payback'  || accObj.Payback_Funded__c == 'Funded') {
                for(Receivable__c rec : receivableList) {
                    if(rec.Type__c == 'Commission')
                        objRec = rec;
                }
                payableList.add(new Payable__c(
                    Opportunity__c = OppId,
                    Type__c = 'Commission',
                    Percentage__c = accObj.Commission_Percentage__c,
                    Payback_Funded__c = accObj.Payback_Funded__c,
                    Due_Date__c = Date.Today()+7,
                    Amount_Due__c = calculatePayableDueAmount(accObj, objOpp),
                    Status__c = 'Open - Needs Review',
                    Receivable_Dependency__c = objRec.Id,
                    Account__c = (accObj.Id == null ? null : accObj.ID),//account.Id,
                    Deal_Amount_Used__c = objRec.Deal_Amount_Used__c,
                    Wizard_Check__c = true,
                    Memo__c = objRec.Memo__c));
            } else {
                payableList.add(new Payable__c(Opportunity__c = OppId));
            }
        } else {
            payableList.add(new Payable__c(Opportunity__c = OppId));
        }
        return payableList;
    }

    // method to calculate Amount_Due__c for the payable
    public static Decimal calculatePayableDueAmount(Account accObj, Opportunity objOpp)
    {
        Decimal amountDue = ((DEWUtility.treateNullAsZero(accObj.Commission_Percentage__c))/100);
        if(accObj.Payback_Funded__c!=null && accObj.Payback_Funded__c=='Payback') {
            amountDue =amountDue * DEWUtility.treateNullAsZero(objOpp.Payback_Amount__c);
        }
        else {
            amountDue = amountDue * DEWUtility.treateNullAsZero(objOpp.Funding_Amount__c);
        }
        return amountDue;
    }

    public static void onChangeOfPayPaybackFunded(
        List<receivable__c> receivableList,
        List<payable__c> payableList,
        Opportunity objOpp,
        Map<String, Schema.SObjectField> mapApiToOppFields,
        List<FO_DEW_Calculate_Percentage_Of__c> lstCustomStngToCalculatePercentageOf
    )
    {
        decimal receivableAmountCommission = 0.00;
        decimal receivableAmountAllRevenue = 0.00;
        decimal receivableOrgFee = 0.00;

        for(Receivable__c rec:receivableList)
        {
            if(rec.Amount__c <> null && rec.Type__c == 'Commission'){
                receivableAmountCommission += rec.Amount__c;
            }

            if(rec.Amount__c <> null && rec.Type__c == 'Origination Fee')
            {
                receivableOrgFee += rec.Amount__c;
            }

            if(rec.Amount__c <> null && rec.Status__c != 'Cancelled'){
                receivableAmountAllRevenue += rec.Amount__c;
            }
        }
        Map<String, String> mapOppFieldApIFromCustomStng = new Map<String, String>();
        String objectType = 'Opportunity';
        Map<String, schema.sObjectType> schemaMap = schema.getGlobalDescribe();
        schema.SObjectType opportunitySchema = schemaMap.get(objectType);
        Map<String, Schema.SObjectField> fieldMap = opportunitySchema.getDescribe().fields.getMap();
        Schema.DisplayType fielddataType;
        for(FO_DEW_Calculate_Percentage_Of__c cstmStng : lstCustomStngToCalculatePercentageOf) {
            if(cstmStng.Payable__c == true) {
                mapOppFieldApIFromCustomStng.put(
                    cstmStng.Percentage_Of_Value__c, cstmStng.Opportunity_Field_API_Name__c
                );
            }
        }
        for(Payable__c pay : payableList)
        {
            if(/*!pay.Wizard_Check__c &&*/ pay.Payback_Funded__c != null && pay.Percentage__c != null)
            {
                if(!mapOppFieldApIFromCustomStng.containsKey(pay.Payback_Funded__c) ) {
                    if(pay.Payback_Funded__c == 'Funded' && objOpp.Funding_Amount__c != null) {
                        pay.Deal_Amount_Used__c = objOpp.Funding_Amount__c;
                    }
                    if(pay.Payback_Funded__c == 'Payback' && objOpp.Payback_Amount__c != null) {
                        pay.Deal_Amount_Used__c = objOpp.Payback_Amount__c;
                    }
                    if(pay.Payback_Funded__c == 'Net Funded Amount') {
                        pay.Deal_Amount_Used__c = DEWUtility.treateNullAsZero(objOpp.Funding_Amount__c)
                        - DEWUtility.treateNullAsZero(objOpp.Payoff_Amount__c);
                    }
                    if(pay.Payback_Funded__c == 'Net Commission Revenue') {
                        pay.Deal_Amount_Used__c = calculatePayNetCommissionRevenue(objOpp, mapApiToOppFields);
                    }
                    if(pay.Payback_Funded__c == 'Net Origination Fee') {
                        pay.Deal_Amount_Used__c = calculatePayNetOriginationFees(objOpp, mapApiToOppFields);
                    }
                    if(pay.Payback_Funded__c == 'Commission Revenue' && objOpp.Funding_Amount__c != null) {
                        pay.Deal_Amount_Used__c = receivableAmountCommission;
                    }
                    if(pay.Payback_Funded__c == 'All Revenue' && objOpp.Funding_Amount__c != null) {
                        pay.Deal_Amount_Used__c = receivableAmountAllRevenue;
                    }
                    if(pay.Payback_Funded__c == 'Origination Fee') {
                        pay.Deal_Amount_Used__c = receivableOrgFee ;
                    }
                }
                if(mapOppFieldApIFromCustomStng.containsKey(pay.Payback_Funded__c)) {
                    String oppField = mapOppFieldApIFromCustomStng.get(pay.Payback_Funded__c);
                    if(oppField == null || oppField == '') {
                        isPayableError = true;
                        payErrorMsg = System.Label.DEW_Configure_custom_setting_msg
                        +' Opportunity Field API Name, this should not be blank.';
                        ApexPages.addMessage(new ApexPages.Message(
                            ApexPages.Severity.Error,  System.Label.DEW_Configure_custom_setting_msg
                            +' Opportunity Field API Name, this should not be blank.'));
                        return;
                    } else {
                        fielddataType = fieldMap.get(oppField).getDescribe().getType();
                    }
                    if(fielddataType == Schema.DisplayType.Double ||
                        fielddataType == Schema.DisplayType.Integer ||
                        fielddataType == Schema.DisplayType.Currency) {
                        pay.Deal_Amount_Used__c = (decimal)objOpp.get(mapOppFieldApIFromCustomStng.get(pay.Payback_Funded__c));
                    } else {
                        isPayableError = true;
                        payErrorMsg = System.Label.DEW_Configure_custom_setting_msg+pay.Payback_Funded__c;
                        ApexPages.addMessage(new ApexPages.Message(
                            ApexPages.Severity.Error,
                            System.Label.DEW_Configure_custom_setting_msg+pay.Payback_Funded__c));
                    }
                }
                pay.Amount_Due__c = DEWUtility.treateNullAsZero(pay.Deal_Amount_Used__c)
                    * (DEWUtility.treateNullAsZero(pay.Percentage__c)/100);
            }
            else
            {
                if((pay.Payback_Funded__c != null && pay.Percentage__c == null)
                    ||(pay.Payback_Funded__c == null && pay.Percentage__c != null))
                {
                    pay.Amount_Due__c = 0.00;
                }
            }
        }
    }

    public Static void onChangeOfPayPercentage(
        List<receivable__c> receivableList,
        List<payable__c> payableList,
        Opportunity objOpp,
        Map<String, Schema.SObjectField> mapApiToOppFields,
        List<FO_DEW_Calculate_Percentage_Of__c> lstCustomStngToCalculatePercentageOf
    )
    {
        decimal receivableAmountCommission = 0.00;
        decimal receivableAmountAllRevenue = 0.00;
        decimal receivableOrgFee = 0.00;

        for(Receivable__c rec: receivableList)
        {
            if(rec.Amount__c <> null && rec.Type__c == 'Commission'){
                receivableAmountCommission += rec.Amount__c;
            }
            if(rec.Amount__c <> null && rec.Type__c == 'Origination Fee'){
                receivableOrgFee += rec.Amount__c;
            }
            if(rec.Amount__c <> null && rec.Status__c != 'Cancelled'){
                receivableAmountAllRevenue += rec.Amount__c;
            }
        }

        Map<String, String> mapOppFieldApIFromCustomStng = new Map<String, String>();
        String objectType = 'Opportunity';
        Map<String, schema.sObjectType> schemaMap = schema.getGlobalDescribe();
        schema.SObjectType opportunitySchema = schemaMap.get(objectType);
        Map<String, Schema.SObjectField> fieldMap = opportunitySchema.getDescribe().fields.getMap();
        Schema.DisplayType fielddataType;

        for(FO_DEW_Calculate_Percentage_Of__c cstmStng : lstCustomStngToCalculatePercentageOf) {
            if(cstmStng.Payable__c == true) {
                mapOppFieldApIFromCustomStng.put(
                    cstmStng.Percentage_Of_Value__c, cstmStng.Opportunity_Field_API_Name__c
                );
            }
        }
        for(Payable__c pay : payableList)
        {
            if(/*!pay.Wizard_Check__c &&*/ pay.Payback_Funded__c != null && pay.Percentage__c != null)
            {
                if(!mapOppFieldApIFromCustomStng.containsKey(pay.Payback_Funded__c) ) {
                    if(pay.Payback_Funded__c == 'Funded' && objOpp.Funding_Amount__c != null) {
                        pay.Deal_Amount_Used__c = objOpp.Funding_Amount__c;
                    }
                    //For Payback
                    if(pay.Payback_Funded__c == 'Payback' && objOpp.Payback_Amount__c != null) {
                        pay.Deal_Amount_Used__c = objOpp.Payback_Amount__c;
                    }
                    //For Net Funded Amount
                    if(pay.Payback_Funded__c == 'Net Funded Amount') {
                        pay.Deal_Amount_Used__c = DEWUtility.treateNullAsZero(objOpp.Funding_Amount__c) -
                        DEWUtility.treateNullAsZero(objOpp.Payoff_Amount__c);
                    }
                    //For Net Commission Revenue
                    if(pay.Payback_Funded__c == 'Net Commission Revenue') {
                        pay.Deal_Amount_Used__c =  calculatePayNetCommissionRevenue(objOpp, mapApiToOppFields);
                    }
                    //For Net Origination Fee
                    if(pay.Payback_Funded__c == 'Net Origination Fee') {
                        pay.Deal_Amount_Used__c =  calculatePayNetOriginationFees(objOpp, mapApiToOppFields);
                    }
                    //For Commision Revenue
                    if(pay.Payback_Funded__c == 'Commission Revenue' && objOpp.Funding_Amount__c != null) {
                        pay.Deal_Amount_Used__c = receivableAmountCommission;
                    }
                    //All revenue
                    if(pay.Payback_Funded__c == 'All Revenue' && objOpp.Funding_Amount__c != null) {
                        pay.Deal_Amount_Used__c = receivableAmountAllRevenue;
                    }
                    //Origination Fee
                    if(pay.Payback_Funded__c == 'Origination Fee') {
                        pay.Deal_Amount_Used__c = receivableOrgFee ;
                    }
                }

                //For Funded
                if(mapOppFieldApIFromCustomStng.containsKey(pay.Payback_Funded__c)) {
                    String oppField = mapOppFieldApIFromCustomStng.get(pay.Payback_Funded__c);
                    if(oppField == null || oppField == '') {
                        isPayableError = true;
                        payErrorMsg = System.Label.DEW_Configure_custom_setting_msg
                        +'Opportunity Field API Name, this should not be blank.';
                        ApexPages.addMessage(new ApexPages.Message(
                            ApexPages.Severity.Error,System.Label.DEW_Configure_custom_setting_msg
                            +'Opportunity Field API Name, this should not be blank.'));
                        return;
                    } else {
                        fielddataType = fieldMap.get(oppField).getDescribe().getType();
                    }

                    if(fielddataType == Schema.DisplayType.Double ||
                        fielddataType == Schema.DisplayType.Integer ||
                        fielddataType == Schema.DisplayType.Currency) {
                        pay.Deal_Amount_Used__c = (decimal)objOpp.get(mapOppFieldApIFromCustomStng.get(pay.Payback_Funded__c));
                    }else {
                        isPayableError = true;
                        payErrorMsg =  System.Label.DEW_Configure_custom_setting_msg+pay.Payback_Funded__c;
                        ApexPages.addMessage(new ApexPages.Message(
                            ApexPages.Severity.Error,  System.Label.DEW_Configure_custom_setting_msg+pay.Payback_Funded__c));
                    }
                }

                pay.Amount_Due__c = DEWUtility.treateNullAsZero(pay.Deal_Amount_Used__c)
                    * (DEWUtility.treateNullAsZero(pay.Percentage__c)/100);
            }
            else
            {
              if((pay.Payback_Funded__c != null && pay.Percentage__c == null)||
                (pay.Payback_Funded__c == null && pay.Percentage__c != null))
              {
                  pay.Amount_Due__c = 0.00;
              }
            }
        }
    }

    public static Decimal calculatePayNetCommissionRevenue(Opportunity oppObj,
        Map<String, Schema.SObjectField> mapApiToOppFields)
    {
        decimal val = 0.00;

        if(mapApiToOppFields.get(System.Label.MCAFieldTotal_Commissions_Receivable) !=Null
            && mapApiToOppFields.get(System.Label.MCACEField_Commissions_Payable_External) != Null)
        {
            String queryStr = 'Select '+System.Label.MCAFieldTotal_Commissions_Receivable
                +','+System.Label.MCACEField_Commissions_Payable_External
                +' From Opportunity Where id = \'' +oppObj.Id+'\'';
            List<Opportunity> tempOpp = database.Query(queryStr);
            if(tempOpp != null && tempOpp.size()>0)
            {
                oppObj.put(
                    System.Label.MCAFieldTotal_Commissions_Receivable,
                    tempOpp[0].get(System.Label.MCAFieldTotal_Commissions_Receivable)
                );
                oppObj.put(
                    System.Label.MCACEField_Commissions_Payable_External,
                    tempOpp[0].get(System.Label.MCACEField_Commissions_Payable_External)
                );
                val = DEWUtility.treateNullAsZero((Decimal)(oppObj.get(
                    System.Label.MCAFieldTotal_Commissions_Receivable)))
                    - DEWUtility.treateNullAsZero((Decimal)(oppObj.get(System.Label.MCACEField_Commissions_Payable_External)));
            }
        }
        else
            val = 0.00;
        return val;
     }

    public static Decimal calculatePayNetOriginationFees(Opportunity oppObj,
        Map<String, Schema.SObjectField> mapApiToOppFields)
    {
        decimal val = 0.00;
        if(mapApiToOppFields.get(System.Label.MCAField_Total_Origination_Fees_Receivable) !=Null
         && mapApiToOppFields.get(System.Label.MCACEField_Origination_Fees_Payable_External) != Null)
        {
            String queryStr = 'Select '+System.Label.MCAField_Total_Origination_Fees_Receivable+','
            +System.Label.MCACEField_Origination_Fees_Payable_External
            +' From Opportunity Where id = \'' +oppObj.Id+'\'';
            List<Opportunity> tempOpp = database.Query(queryStr);
            if(tempOpp != Null && tempOpp.size() >0)
            {
                oppObj.put(System.Label.MCAField_Total_Origination_Fees_Receivable,
                    tempOpp[0].get(System.Label.MCAField_Total_Origination_Fees_Receivable));
                oppObj.put(System.Label.MCACEField_Origination_Fees_Payable_External,
                    tempOpp[0].get(System.Label.MCACEField_Origination_Fees_Payable_External));
                val = DEWUtility.treateNullAsZero((Decimal)(oppObj.get(System.Label.MCAField_Total_Origination_Fees_Receivable)))
                - DEWUtility.treateNullAsZero((Decimal)(oppObj.get(System.Label.MCACEField_Origination_Fees_Payable_External)));
            }
        }
        else
            val = 0.00;
        return val;
    }

    public static List<payable__c> quickSavePayable(List<payable__c> payableList,Opportunity objOpp, Id OppId)
    {
        list<Payable__c> lstPayableToUpsert = new list<Payable__c> ();
        list<Payable__c> lstPayableToDisplay = new list<Payable__c> ();
        list<Payable__c> lstPayablesWithNullValueToDelete = new list<Payable__c> ();
        if(payableList.size() > 0 )
        {
            for(Integer i=0; i<payableList.size(); i++)
            {
                if(!DEWPayablesService.payablesFieldsNullValidator(payableList[i]))
                {
                    lstPayableToUpsert.add(payableList[i]);
                    lstPayableToDisplay.add(payableList[i]);
                }
                else
                {
                    if(payableList[i].Id != null)
                    lstPayablesWithNullValueToDelete.add(payableList[i]);
                }
            }
        }
        lstPayableToUpsert = DEWUtility.checkSaveAccessForSObject(lstPayableToUpsert,UserInfo.getUserId());
        DEWUtility.upsertForSObject(lstPayableToUpsert);
        delete lstPayablesWithNullValueToDelete;
        payableList = DEWPayablesService.getPayablesFromDB(OppId);
        return payableList;
    }

    // callCommissionCreatePayable
    public static Boolean callCommissionCreatePayable(
        Opportunity objOpp,
        Id OppId,
        String labelString,
        Boolean checkAdvCommCall,
        List<Payable__c> payableList)
    {
        List<Payable__C> advComPayableList = new List<Payable__C>();
        if(/*objOpp.Deal_Entry_Wizard_Check__c == false &&*/ checkAdvCommCall == false )
        {
            type t = type.forName(Label.CommissionEngineClassName);
            //type t = type.forName(labelString);
            if(t != Null)
            {
                MCAExtensionInterface_version McaExtension = (MCAExtensionInterface_version) t.newinstance();
                advComPayableList = McaExtension.commissioncal(OppId);
                if( advComPayableList.size() > 0)
                {
                    //To indicate the commision call has been made.
                    checkAdvCommCall = true;
                }
                payableList.addAll(advComPayableList);
            }
        }
        return checkAdvCommCall;
    }

    //standardsplitcreatePayable
    public static void standardSplitCreatePayable(
            Opportunity objOpp,
            Id OppId,
            List<Account> accList,
            List<receivable__c> receivableList,
            decimal CommissionPer,
            List<Payable__c> payableList,
            String  wizardType,
            String PREVIEW_SCREEN)
    {
        if(objOpp.Deal_Entry_Wizard_Check__c == false && accList.size() > 0
            && receivableList.size() >0 && receivableList <> null)
        {
            CommissionPer = DEWUtility.treateNullAsZero(accList[0].Commission_Percentage__c);
            for (integer i=0; i<receivableList.size();i++)
            {
                //if((receivableList[i].Type__c == 'Commission' && accList[0].Payback_Funded__c == 'Commission Revenue') && receivableList[i].Wizard_Check__c == false && objOpp.Deal_Entry_Wizard_Check__c == false && receivableList[i].IsCreatedFromGrid__c == false)
                if(receivableList[i] != null && receivableList[i].Amount__c!= null
                    && (receivableList[i].Type__c == 'Commission'
                    && accList[0].Payback_Funded__c == 'Commission Revenue')
                    && receivableList[i].Wizard_Check__c == false
                    && objOpp.Deal_Entry_Wizard_Check__c == false
                    && receivableList[i].IsCreatedFromGrid__c == false)
                {
                    payableList.add(new Payable__c(Opportunity__c = OppId,
                                    Type__c = receivableList[i].Type__c,
                                    Percentage__c = CommissionPer,
                                    Payback_Funded__c =accList[0].Payback_Funded__c,
                                    Due_Date__c = Date.Today()+7,
                                    Amount_Due__c = receivableList[i].Amount__c * (CommissionPer/100),
                                    Status__c = 'Open - Needs Review',
                                    Receivable_Dependency__c = receivableList[i].Id,
                                    Memo__c = receivableList[i].Memo__c,
                                    Deal_Amount_Used__c = receivableList[i].Deal_Amount_Used__c,
                                    Wizard_Check__c = true,
                                    Account__c = accList[0].Id));
                    receivableList[i].Wizard_Check__c = true;
                }//End If
                else if((accList[0].Payback_Funded__c == 'Payback'  || accList[0].Payback_Funded__c == 'Funded')
                && receivableList[i].Wizard_Check__c == false &&
                objOpp.Deal_Entry_Wizard_Check__c == false && receivableList[i].IsCreatedFromGrid__c == false)
                {
                    if(payableList.size()<=0 && wizardType != PREVIEW_SCREEN){
                            payableList = DEWPayablesService.addPayableRow(
                                OppId,
                                objOpp,
                                accList,
                                receivableList,
                                payableList
                          );
                    }
                    receivableList[i].Wizard_Check__c = true;
                }

                else if(receivableList.size() > 0 && (receivableList[i].Type__c <> null
                    && accList[0].Payback_Funded__c == 'All Revenue')
                    && receivableList[i].Wizard_Check__c == false &&
                    objOpp.Deal_Entry_Wizard_Check__c == false && receivableList[i].IsCreatedFromGrid__c == false)
                {
                    payableList.add(new Payable__c(Opportunity__c = OppId,
                                    Type__c = receivableList[i].Type__c,
                                    Percentage__c = CommissionPer,
                                    Payback_Funded__c =accList[0].Payback_Funded__c,
                                    Due_Date__c = Date.Today()+7,
                                    Amount_Due__c = DEWUtility.treateNullAsZero(receivableList[i].Amount__c) * (CommissionPer/100),
                                    Status__c = 'Open - Needs Review',
                                    Receivable_Dependency__c=receivableList[i].Id,
                                    Memo__c = receivableList[i].Memo__c,
                                    Deal_Amount_Used__c = receivableList[i].Deal_Amount_Used__c,
                                    Wizard_Check__c = true,
                                    Account__c = accList[0].Id));
                    receivableList[i].Wizard_Check__c = true;
                }
                else
                {
                    receivableList[i].Wizard_Check__c = true;
                }
            }
            update receivableList;
        }
    }

    public static decimal calculatePayAmtTotal(Decimal payableAmtTotal, List<Payable__c> payableList)
    {
         payableAmtTotal = 0.0;
         if(payableList.size()>0)
         {
            for(Payable__c pay:payableList){
                if(pay.Amount_Due__c!=null  && pay.Status__c != 'Cancelled')
                payableAmtTotal = payableAmtTotal + pay.Amount_Due__c;
            }
         }
         return payableAmtTotal;
    }
}