MCA Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_Sales__c</fullName>
        <label>Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NDBs_Avg__c</fullName>
        <description>The average of # NDBs of all Bank Statement records related to the Account</description>
        <inlineHelpText>The average of # NDBs of all Bank Statement records related to the Account</inlineHelpText>
        <label># NDBs Avg</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSFs_Avg__c</fullName>
        <description>The average of # NSFs of all Bank Statement records related to the Account</description>
        <inlineHelpText>The average of # NSFs of all Bank Statement records related to the Account</inlineHelpText>
        <label># NSFs Avg</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <description>Accounts that represent banks and funders.</description>
        <label>Bank</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCA Dev/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Contact.object
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Credit Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

MCA Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Average_Daily_Balance__c</fullName>
        <inlineHelpText>Average Daily Balance from the business bank accounts. This will usually come from the bank statements received from the Merchant.</inlineHelpText>
        <label>Average Daily Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Avg_Number_Bank_Deposits__c</fullName>
        <inlineHelpText>The average number of monthly bank deposits.</inlineHelpText>
        <label># Deposits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Owner 1 Credit Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_Sales__c</fullName>
        <inlineHelpText>The average $ of monthly bank deposits.</inlineHelpText>
        <label>Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NDBs_avg__c</fullName>
        <inlineHelpText>Average of Bank Account NDBs</inlineHelpText>
        <label># NDBs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSFs_avg__c</fullName>
        <inlineHelpText>Average of Bank Account NSFs</inlineHelpText>
        <label># NSFs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner 1</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Business Owner contact can only show in Owner 1 field.</errorMessage>
            <filterItems>
                <field>Contact.Contact_Roles__c</field>
                <operation>equals</operation>
                <value>Business Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Industry__c</fullName>
        <formula>text(Account.Industry)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Industry</label>
        <type>Text</type>
    </fields>

MCADevOrg/src/objects/OrgwideEmailAddress__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The custom setting is used to allow use of org wide email for outgoing email sent from  submission wizard</description>
    <fields>
        <fullName>IsOrgwideEmailAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check will determine whether to use org wide email or not for the email sent out from submission wizard</description>
        <label>IsOrgwideEmailAllowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgEmailAddress__c</fullName>
        <label>OrgEmailAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OrgwideEmailAddress</label>
</CustomObject>

MCA Dev/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bank</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Bank</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funding_Amt_of_Monthly_Gross_Sales__c</fullName>
        <inlineHelpText>What is the multiple that this bank typically funds as a ratio to the merchant&apos;s monthly gross sales volume</inlineHelpText>
        <label>Funding Amt - % of Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Amount__c</fullName>
        <label>Max. Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_NDBs__c</fullName>
        <label>Max NDBs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_No_NSFs__c</fullName>
        <label>Max# NSFs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Daily_Bal__c</fullName>
        <label>Min. Avg Daily Bal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Deposit_Count__c</fullName>
        <inlineHelpText>Number of days per month where deposits are made into the bank account.</inlineHelpText>
        <label>Min. Monthly Bank Deposit Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Min. Years in Business</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA Dev/src/objects/Required_Documents__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Required Documents</relationshipLabel>
        <relationshipName>Required_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Required Document</label>
    <nameField>
        <label>Required Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/SWDefaultFilters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Submission Wizard by default only filters against the criteria for which the fields are checked in the above custom setting</description>
    <fields>
        <fullName>Attachments_Selected_on_Load__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Attachments Selected on Load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Avg_Daily_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Avg Daily Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Score</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_NDBs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Max NDBs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_NSFs__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Max NSFs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monthly_Deposits1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monthly Deposits $</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monthly_Deposits__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Monthly Deposits #</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Years in Business</label>
        <type>Checkbox</type>
    </fields>
    <label>SWDefaultFilters</label>
</CustomObject>

MCA Dev/src/classes/SubmissionWizardControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of SubmissionWizardController
 * 
 *  Date - 12-02-2014
 *
 *  Created By - Sneha P.
 *  Modified By - Shraddha P.
 */
@isTest
//(OnInstall=false) 

private class SubmissionWizardControllerTest {
    public static SubmissionWizardController controllerInstance;
    public static List<Schema.FieldSetMember> oppFieldSet;
    public static Opportunity objOpp;
    public static Account objAcc;
    public static Id programsId;
    public static List<Submission__c> lSub;
    
    public static void testData() {
        RecordType rt = [select id,Name from RecordType where SobjectType='Account' and Name='Bank' Limit 1];
        objAcc = createAccount('TestAcc',1, rt.Id);
        Contact con = createContact('TestAcc',1);
        objOpp = new Opportunity(
                    Name = 'Test Opp', AccountId = objAcc.Id, StageName ='Prospecting' ,
                    CloseDate = System.today(),Credit_Score__c = 20, Average_Daily_Balance__c=100,
                    NSFs_Avg__c = 5, NDBs_Avg__c = 5, Avg_Number_Bank_Deposits__c = 10,
                    Owner_1__c = con.id, Gross_monthly_Sales__c = 2);
        insert objOpp;
        //oppFieldSet = Schema.SObjectType.Opportunity.FieldSets.SWDealSummary.getMap().values();
        oppFieldSet = SObjectType.Opportunity.FieldSets.SWDealSummary.getFields();
        list<Program__c> lstPrograms = createPrograms(25, objAcc.Id);
        insert lstPrograms;
        programsId = lstPrograms[0].Id; 
        Required_Documents__c reqdDoc = new Required_Documents__c(Name = 'Doc 1',Program__c = lstPrograms[0].Id);
        insert reqdDoc;
        OrgwideEmailAddress__c lstOrgWideEmail = new OrgwideEmailAddress__c();
        lstOrgWideEmail.Name= 'SubmissionOrgWideEmail';
        lstOrgWideEmail.IsOrgwideEmailAllowed__c = true;
        lstOrgWideEmail.OrgEmailAddress__c = 'gabriel@cloudmybiz.com';
        insert lstOrgWideEmail;
        list<Attachment> lstAttachments = createAttachments(2, objAcc.Id);
        insert lstAttachments;
        system.assertNotEquals(null,reqdDoc.Id);
        List<SWDefaultFilters__c> defaultFilterObj = createSWDDefaultFilter(1);
        insert defaultFilterObj;
        lSub =createsubmissions(2,lstPrograms[0].Id,objOpp.Id, objAcc.Id );
        insert lSub;
        list<Required_Documents__c> lstReqdDoc = createReqDocuments(4, lstPrograms);
        insert lstReqdDoc;
    }

    static testMethod void submissionWizardValidTest() {
        SWDefaultFilters__c insertCustomSetting = createCustomSetting();
        insert insertCustomSetting;
        insertCustomSetting.Attachments_Selected_on_Load__c =false;
        update insertCustomSetting;
        testData();
        PageReference pageRef = Page.SubmissionWizard;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',objOpp.Id);
        ApexPages.currentPage().getParameters().put('accId',objAcc.Id);
        controllerInstance = new SubmissionWizardController();
        submissionWizardFilterTest();
        submitBtnTest();
        submissionWizardCheckReqDocTest();
        submissionWizardSortTest();
    }

    static testMethod void submissionWizardSortingTest() {
        SWDefaultFilters__c insertCustomSetting = createCustomSetting();     
        //to insert all test data which is required for submission wizard
        testData();
        PageReference pageRef = Page.SubmissionWizard;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',objOpp.Id);
        ApexPages.currentPage().getParameters().put('accId',objAcc.Id);
        controllerInstance = new SubmissionWizardController();      
        submissionWizardFilterTest();
        SubmissionWizardController.sortDirection = 'DESC';
        submitBtnTest();
        controllerInstance.setSortDirection('ASC');
        controllerInstance.saveme();
        controllerInstance.indexToRemove = [select Id from Attachment limit 1].Id;
        controllerInstance.deleteAttachment();
        controllerInstance.resetAttachments();
        controllerInstance.cancel();
        controllerInstance.openAttachment(); 
        controllerInstance.CollectData();
        controllerInstance.getMapSize();
    }

    //submission wizard positive test case
    public static void submissionWizardFilterTest() {
        controllerInstance.clearFilter();
        controllerInstance.prefferedProgram = true;
        controllerInstance.getPrograms();
        controllerInstance.creditScore = '0';
        controllerInstance.yearInBusiness = '0';
        controllerInstance.minMonthlyDeposite = '0';
        controllerInstance.minDepositeCount = '0';
        controllerInstance.maxNSFs = '0';
        controllerInstance.maxNDBs = '0';
        controllerInstance.minAvgDailyBalance = '0';
        controllerInstance.searchQuery = 'Tes';
        SubmissionWizardController.sortDirection = 'ASC';
        controllerInstance.sortExpression = 'Minimum_Deposit_Count__c';
        controllerInstance.getPrograms();
        controllerInstance.creditScore = 'aaa';
        controllerInstance.yearInBusiness = 'aaaa';
        controllerInstance.minMonthlyDeposite = 'aaa';
        controllerInstance.minDepositeCount = 'aaa';
        controllerInstance.maxNSFs = 'aaa';
        controllerInstance.maxNDBs = 'aaa';
        controllerInstance.minAvgDailyBalance = 'aaa';
        controllerInstance.getPrograms();
        controllerInstance.creditScore = '';
        controllerInstance.yearInBusiness = '';
        controllerInstance.minMonthlyDeposite = '';
        controllerInstance.minDepositeCount = '';
        controllerInstance.maxNSFs = '';
        controllerInstance.maxNDBs = '11111111111111111111111111';
        controllerInstance.minAvgDailyBalance = '';
        controllerInstance.getPrograms();
        controllerInstance.maxNDBs = '';
        controllerInstance.prefferedProgram = true;
        controllerInstance.getPrograms();
        controllerInstance.showMore();
        controllerInstance.closePopup();
        controllerInstance.getSortDirection();
    }

    public static void submissionWizardSortTest() {
        SubmissionWizardController.sortDirection = 'ASC';
        controllerInstance.sortExpression = 'Funding_Amt_of_Monthly_Gross_Sales__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Funding_Amt_of_Monthly_Gross_Sales__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Commission_Percentage__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Commission_Percentage__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Max_Amount__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Max_Amount__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Max_No_NSFs__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Max_No_NSFs__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Min_Avg_Daily_Bal__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Min_Avg_Daily_Bal__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Minimum_Deposit_Count__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Minimum_Deposit_Count__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Years_in_Business__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Years_in_Business__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Credit_Score__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Credit_Score__c';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'score';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'score';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Name';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Name';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Bank__r.Name';
        controllerInstance.viewSortedData_Program();
        controllerInstance.sortExpression = 'Bank__r.Name';
        controllerInstance.viewSortedData_Program();
    }

     public static void submitBtnTest() {
       controllerInstance.programWrapListLimit[0].submissionMethodValue = 'Manual';
       controllerInstance.programWrapListLimit[1].submissionMethodValue = 'Email';
       controllerInstance.programWrapListLimit[0].isSelected = true;
       controllerInstance.attachmentWrapperList[0].isRequired = true;
       controllerInstance.programWrapListLimit[1].isSelected = true;
       controllerInstance.attachmentWrapperList[1].isRequired = true;
       controllerInstance.submitToSend();
       Map<Id,Submission__c> mapProgIdsubmissionTest = new Map<Id,Submission__c>();
       mapProgIdsubmissionTest.put(programsId,lSub[0]);
       //controllerInstance.sendMail(mapProgIdsubmissionTest);
    }

    public static void submissionWizardCheckReqDocTest() {
        controllerInstance.programWrapListLimit[0].isSelected = true;
        controllerInstance.checkReqdDocument();
    }

    /**
     * To store selected  active program
     */
    public static void submissionWizardcheckSearchProgram() {
        Account acc = new Account(Name = 'Test');
        insert acc;
        createPrograms(5, acc.Id);
        controllerInstance.clearFilter();
        controllerInstance.programWrapListLimit[0].isSelected = true;
        controllerInstance.searchQuery = 'Test';
        controllerInstance.getPrograms();
        controllerInstance.toStoreSelectedProgram();
    }
    public static list<Required_Documents__c> createReqDocuments(
            Integer pCount,
            list<Program__c> lstPrograms
    ){
        list<Required_Documents__c> lstRequiredDoc = new list<Required_Documents__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstRequiredDoc.add(new Required_Documents__c(Name = 'Doc 1',Program__c = lstPrograms[0].Id));
        }
        return lstRequiredDoc;
    }

    public static SWDefaultFilters__c createCustomSetting() {
        SWDefaultFilters__c defaultfilters = new SWDefaultFilters__c();
        defaultfilters.Name = 'Test_custom Setting';
        defaultfilters.Attachments_Selected_on_Load__c = true;
        defaultfilters.Credit_Score__c = true;
        defaultfilters.Years_in_Business__c = true;
        defaultfilters.Monthly_Deposits1__c= true;
        defaultfilters.Monthly_Deposits__c= true;
        defaultfilters.Avg_Daily_Balance__c= true;
        defaultfilters.Max_NSFs__c= true;
        defaultfilters.Max_NDBs__c= true;
        defaultfilters.Industry__c= true;
        defaultfilters.State__c= true;
        defaultfilters.Preferred_Programs__c= true;
        return defaultfilters;
    }

    //The method will create dummy records of Attachments.
    public static list<Attachment> createAttachments(Integer pCount, Id pAccountId){
        list<Attachment> lstTempAttachments = new list<Attachment>();
        for(Integer index = 0; index <= pCount; index++){
            lstTempAttachments.add(new Attachment(Name = 'Test Doc' + index, 
                                                  ParentId = pAccountId, 
                                                  Body = Blob.valueOf('Test Attachment' + index)));
        }
        return lstTempAttachments;
    }//End createAttachments method.

    //The method will create dummy records of Account.
    public static Account createAccount(String pName,Integer cnt, Id recrdType){
        Account acc = new Account(
                Name = pName,Email__c = 'test@test.com'+cnt, Industry = 'Government',
                BillingState = 'CO', Years_in_Business__c = 6, NSFs_Avg__c = 5, NDBs_Avg__c = 5,
                Gross_monthly_Sales__c = 100, recordTypeId = recrdType);
        insert acc;
        return acc;
    }

    //The method will create dummy records of Contact.
    public static Contact createContact(String pName,Integer cnt){
        Contact con = new Contact(firstName = pName,lastname= pName,Email = 'test@test.com'+cnt );
        insert con;
        return con;
    }

    //The method will create dummy records of Program.
    public static list<Program__c> createPrograms(Integer pCount, Id accId){
        /*  EmailTemplate emailTemp = createEmailTemplate(1);
        insert emailTemp;*/
        EmailTemplate emailTemp = createEmailTemplate(1);
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
            User u = new User(Alias = 'standt', Email='MCA12345@CMB.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='MCA12345@CMB.com');
        System.runAs(u) 
        {
            insert emailTemp;
        }
        list<Program__c> lstTempPrograms = new list<Program__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstTempPrograms.add(new Program__c(Name= 'Test Program' + index,
                                               Bank__c = accId,
                                               Credit_Score__c = 20 + index,
                                               Min_Monthly_Deposits__c = 100 + index,
                                               Minimum_Deposit_Count__c = 10 + index,
                                               Restricted_Industry_List__c = 'Construction',
                                               Min_Avg_Daily_Bal__c = 100 + index,
                                               Max_No_NSFs__c =5 + index,
                                               Max_NDBs__c = 5 + index,
                                               Commission_Percentage__c = 10 + index,
                                               Funding_Amt_of_Monthly_Gross_Sales__c = 10 + index,
                                               Max_Amount__c = 100 + index,
                                               Years_in_Business__c = 6 + index,
                                               Preffered_Programs__c = true,
                                               Restricted_States__c = 'AK',                                               
                                               Submission_Email__c = 'test' + index + '@gmail.com',
                                               Submission_Email_CC_1__c= 'test' + index + '@gmail.com',
                                               Submission_Email_CC_2__c= 'test' + index + '@gmail.com',
                                               Email_Template_Id__c = emailTemp.Id
                                               ));
        }//End for.
        return lstTempPrograms;
    }//End createPrograms method.

    //The method will create dummy records of SubmissionMailsDetail.
    /*public static list<Submission_Mails_Detail__c> createSubmissionMailsDetail(Integer pCount){
        list<Submission_Mails_Detail__c> lstSubmissionMailsDetail = new list<Submission_Mails_Detail__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstSubmissionMailsDetail.add(new Submission_Mails_Detail__c(//Name= 'Test Program' + index,
                                               Is_Active__c = true,
                                               Message_Body__c = 'Test {!Opportunity.Name} AAA {!Opportunity.Account.Name} BBB' + 
                                                        '{!Opportunity.Owner_1__r.Name} ccc {!Program__c.Name} ddd {!SubmissionId} eee https://id={!SubmissionId}',
                                               Subject__c = 'Test Subject {!Opportunity.Account.Name}',
                                               CC_Address__c = 'test@gmail.com',
                                               Bcc_Address__c = 'test' + index + '@gmail.com'));
        }//End for.
        return lstSubmissionMailsDetail;
    }*///End SubmissionMailsDetail method.

    //The method will create dummy records of OrgWideEmail.
    public static list<OrgwideEmailAddress__c> createOrgWideEmail(Integer pCount){
        list<OrgwideEmailAddress__c> lstOrgWideEmail = new list<OrgwideEmailAddress__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstOrgWideEmail.add(new OrgwideEmailAddress__c(Name= 'SubmissionOrgWideEmail',
                                               IsOrgwideEmailAllowed__c = true,
                                               OrgEmailAddress__c = 'gabriel@cloudmybiz.com'
                                               ));
        }//End OrgWideEmail.
        return lstOrgWideEmail;
    }//End createOrgWideEmail method.

    //create custom setting records
    public static list<SWDefaultFilters__c> createSWDDefaultFilter(Integer pCount){
        list<SWDefaultFilters__c> lstDefaultFilters = new list<SWDefaultFilters__c>();
        for(Integer index = 0; index < pCount; index++) {
            lstDefaultFilters.add(new SWDefaultFilters__c(Name= 'DefaultFilter',
                                                       Industry__c = true, 
                                                       Credit_Score__c = true ,
                                                       Avg_Daily_Balance__c = true,
                                                       Max_NDBs__c = true,
                                                       Max_NSFs__c = true,
                                                       Monthly_Deposits1__c = true,
                                                       Monthly_Deposits__c = true,
                                                       Preferred_Programs__c = true,
                                                       State__c = true,
                                                       Years_in_Business__c = true
                                               ));
        }//End for.
        return lstDefaultFilters;
    }

    //The method will create dummy records of Submission.
    public static list<Submission__c> createsubmissions(Integer pCount ,Id pgmId, Id oppId, Id accId){ 
    list<Submission__c> lstSubmission = new list<Submission__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstSubmission.add(new Submission__c(//Name= 'Test Program' + index,
                                               Opportunity__c = oppId,
                                               Status__c = 'UW',
                                               Program__c = pgmId,
                                               Funder__c =accId
                                               //CC_Address__c = 'test' + index + '@gmail.com'
                                              ));
        }//End for.
          return lstSubmission;
    }//End

    public static EmailTemplate createEmailTemplate(Integer recordCount){
        EmailTemplate validEmailTemplate = new EmailTemplate();
        validEmailTemplate.isActive = true;
        validEmailTemplate.Name = 'SWEmailTemplate';
        validEmailTemplate.DeveloperName = 'SWEmailTemplate';
        validEmailTemplate.TemplateType = 'text';
        validEmailTemplate.Body = 'Hi';
        validEmailTemplate.FolderId = UserInfo.getUserId();
        return validEmailTemplate;
    }
}