MCA Dev/src/objects/DfaGrid__mdt.object
<CustomObject>
    <fields>
        <fullName>Display_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EditAll_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EditAll Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tab_Name__c</fullName>
        <label>Tab Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_Name__c</fullName>
        <label>sObject Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DfaGrid</label>
    <pluralLabel>DfaGrid</pluralLabel>
</CustomObject>

MCADevOrg/src/classes/DfaGridHomePageExtension.cls
public with sharing class DfaGridHomePageExtension{    
    
   // declaration
    private final Opportunity oppStd;
    public Map<String, DfaGrid__mdt> tabToSettingMap{get; set;}
   
    // constructor
    public DfaGridHomePageExtension(ApexPages.StandardController stdController) {
         this.oppStd = (Opportunity)stdController.getRecord();
         tabToSettingMap = new Map<String, DfaGrid__mdt> ();
         List<DfaGrid__mdt> customMetadataList = [Select Display_Check__c,
                                                                       EditAll_Check__c,
                                                                       sObject_Name__c, 
                                                                       Tab_Name__c, 
                                                                       DeveloperName From DfaGrid__mdt];
         if(!customMetadataList.isEmpty()) 
         {
            for(DfaGrid__mdt settingInstance :customMetadataList)
            {
                tabToSettingMap.put(settingInstance.DeveloperName, settingInstance);
            }
         }
         
    }

}