MCA Dev/src/objects/FO_Email_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores values for Email stips and Email offers default recipients</description>
    <fields>
        <fullName>Field_Set_API_Name__c</fullName>
        <label>Field Set API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name_for_Field_Set__c</fullName>
        <label>Object API Name for Field Set</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>FO Email Settings</label>
</CustomObject>

MCA Dev/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Chosen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Submission__c.Opportunity__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFFR-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA Dev/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/classes/EmailOffersDynamicControllerTest.cls
/**
**  Version     Author          Date(dd/mm/yyyy)        Description
**  1.0         Merul S         21/01/2017              Initial Draft[]
**  1.1         Ajinkya H       23/03/2017              Get Field Set from Custom Setting test
**
*/

@isTest
public class EmailOffersDynamicControllerTest {
    /**
    * Test offers available for opportunity
    */
    static testMethod void testOffersFieldset(){
        List<Opportunity> opprtunity = TestDataUtility.getOpportunityRecords(1);
        insert opprtunity;

        List<Submission__c> submissons = TestDataUtility.getSubmissionRecords(1, opprtunity[0].Id);
        insert submissons;

        FO_Email_Settings__c cstmSetting = new FO_Email_Settings__c(
            Name = 'Email Offers',
            Field_Set_API_Name__c = 'GRIDOfferFieldSet',
            Object_API_Name_for_Field_Set__c = 'Offer__c'
        );
        insert cstmSetting;

        List<Offer__c> offers = TestDataUtility.getOfferRecords(4,opprtunity[0].Id,submissons[0].Id);
        for(Offer__c offer :offers) {
            offer.Status__c = 'Rejected';
        }
        insert offers;
        EmailOffersDynamicController offerController = new EmailOffersDynamicController();
        offerController.getoffers();
        List<Offer__c> updatedOffers = [SELECT Id
                                             , Opportunity__c
                                        FROM Offer__c
                                        WHERE Opportunity__c =:opprtunity[0].Id];
        System.assertEquals(4, updatedOffers.size());
    }
}