MCA Dev/src/objects/MCATriggerExecuter__mdt.object
<CustomObject>
    <description>This custom metadata type will control the execution of various triggers in MCA App.</description>
    <fields>
        <fullName>IsActivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActivate</label>
        <type>Checkbox</type>
    </fields>
    <label>MCATriggerExecuter</label>
    <pluralLabel>MCATriggerExecuters</pluralLabel>
</CustomObject>

MCA Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Stip_Count__c</fullName>
        <description>COUNT of Closed Stips</description>
        <inlineHelpText>COUNT of Closed Stips</inlineHelpText>
        <label>Closed Stips</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Stip_Count__c</fullName>
        <description>COUNT of Open Stips</description>
        <inlineHelpText>COUNT of Open Stips</inlineHelpText>
        <label>Open Stips</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stips__c</fullName>
        <label>Stips</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA Dev/src/objects/Stips__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Items_Needed</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stips</label>
    <nameField>
        <label>Stip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/classes/StipsHandler.cls
/*
 *  Apex Stips Handler Class
 *
 *  Version           Author                 Date                 Description
 *  1.1               Yogesh Mahajan         24-02-2016           Added method for Before Delete on
                                                                  line no.22
 */

public class StipsHandler {

    public void onAfterInsert(list<Stips__c> stipsList){

        //For all the inserted stips pass trigger in
        //StoreChildToParentHelper objHandler = new StoreChildToParentHelper();
        //objHandler.copyField(stipsList);
         if( [select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'StipRollUpTrigger'].IsActivate__c){
                list<RollupService.fieldDefinition> fieldDefinitions_OpenStips =
                    new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Open_Stip_Count__c')
                };
                RollupService.rollUpTrigger(fieldDefinitions_OpenStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND (Status__c != \'Completed\' AND Status__c != \'Cancelled\')');

                list<RollupService.fieldDefinition> fieldDefinitions_ClosedStips =
                    new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Closed_Stip_Count__c')
                };
                RollupService.rollUpTrigger(fieldDefinitions_ClosedStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND Status__c = \'Completed\'');
         }
    }

    public void onAfterUpdate(list<Stips__c> stipsList){
        if( [select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'StipRollUpTrigger'].IsActivate__c){
                list<RollupService.fieldDefinition> fieldDefinitions_OpenStips =
                    new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Open_Stip_Count__c')
                };
                RollupService.rollUpTrigger(fieldDefinitions_OpenStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND (Status__c != \'Completed\' AND Status__c != \'Cancelled\')');

                list<RollupService.fieldDefinition> fieldDefinitions_ClosedStips =
                    new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Closed_Stip_Count__c')
                };
                RollupService.rollUpTrigger(fieldDefinitions_ClosedStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND Status__c = \'Completed\'');
         }
    }

    public void onAfterUndelete(list<Stips__c> stipsList){
        if( [select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'StipRollUpTrigger'].IsActivate__c){
                list<RollupService.fieldDefinition> fieldDefinitions_OpenStips =
                    new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Open_Stip_Count__c')
                };
                RollupService.rollUpTrigger(fieldDefinitions_OpenStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND (Status__c != \'Completed\' AND Status__c != \'Cancelled\')');

                list<RollupService.fieldDefinition> fieldDefinitions_ClosedStips =
                    new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Closed_Stip_Count__c')
                };
                RollupService.rollUpTrigger(fieldDefinitions_ClosedStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND Status__c = \'Completed\'');
         }
    }

    public void onAfterDelete(list<Stips__c> stipsList) {
        if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'StipRollUpTrigger'].IsActivate__c){
            list<RollupService.fieldDefinition> fieldDefinitions_OpenStips =
                new list<RollupService.fieldDefinition> {
                    new RollupService.fieldDefinition('COUNT','Id','Open_Stip_Count__c')
            };
            RollupService.rollUpTrigger(fieldDefinitions_OpenStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND (Status__c != \'Completed\' AND Status__c != \'Cancelled\')');

            list<RollupService.fieldDefinition> fieldDefinitions_ClosedStips =
                new list<RollupService.fieldDefinition> {
                new RollupService.fieldDefinition('COUNT','Id','Closed_Stip_Count__c')
            };
            RollupService.rollUpTrigger(fieldDefinitions_ClosedStips ,stipsList,'Stips__c','Opportunity__c','Opportunity',' AND Status__c = \'Completed\'');
        }
    }

    public void onBeforeDelete() {
        //new AttachmentService().deleteStipAttachmentAndAttachment(trigger.oldMap.keySet());
    }
}