MCA Dev/src/objects/MCATriggerExecuter__mdt.object
<CustomObject>
    <description>This custom metadata type will control the execution of various triggers in MCA App.</description>
    <fields>
        <fullName>IsActivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActivate</label>
        <type>Checkbox</type>
    </fields>
    <label>MCATriggerExecuter</label>
    <pluralLabel>MCATriggerExecuters</pluralLabel>
</CustomObject>

MCAPackagingOrg/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCACE/src/objects/Opportunity.object
    <fields>
        <fullName>McaApp__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>McaApp__Number_of_Funders__c</fullName>
        <description>COUNT of Loan Balance</description>
        <label># of Funders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>McaApp__Total_Daily_Payments__c</fullName>
        <description>SUM of Loan Balance: Payment</description>
        <label>Total Daily Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>McaApp__Total_Loan_Balances__c</fullName>
        <description>SUM of Loan Balance: Balance</description>
        <label>Total Loan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

MCAPackagingOrg/src/classes/LoanBalanceHandler.cls
/* 
 * Call in LoanBalance trigger to calculate RollUp on Opportunity
 *   
 * Version         Author                   Date                Description
 * 1.0             Shraddha P.              05-01-2016          Initial Draft[]
 */ 

public with sharing class LoanBalanceHandler {
    public LoanBalanceHandler() {
        
    }
    
    public void onAfterInsert() {       
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Daily_Payment__c', 
            'McaApp__Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Balance__c', 
            'McaApp__Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'McaApp__Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
      }
    }
    
    public void onAfterUpdate() {       
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Daily_Payment__c', 
            'McaApp__Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Balance__c', 
            'McaApp__Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'McaApp__Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
      }
    }
    
    public void onAfterUndelete(){
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Daily_Payment__c', 
            'McaApp__Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Balance__c', 
            'McaApp__Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'McaApp__Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.new, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
      }
    }
    
    public void onAfterDelete() {        
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Daily_Payment__c', 
            'McaApp__Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.old, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'McaApp__Balance__c', 
            'McaApp__Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.old, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'McaApp__Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.old, 
        'McaApp__Loan_Balance__c', 'McaApp__Opportunity__c', 'Opportunity', '');
      }
    }   
   
}