MCA Dev/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Submission__c.Opportunity__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFFR-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Opportunity.object
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>

MCA Dev/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/classes/MCANestedOffersTabControllerTest.cls
@isTest
private class MCANestedOffersTabControllerTest{
   static testMethod void MCANestedOffersTabController(){
    
        Opportunity OppRecord1 = new Opportunity(Name = 'Rocky1', CloseDate = system.today(), 
												 StageName = 'Application Sent', ForecastCategoryName = 'Pipeline',
												 Amount = 1000);
		insert OppRecord1;
		
		Submission__c submissionRecord1 = new Submission__c(Date_Submitted__c = system.today(),Opportunity__c = OppRecord1.Id);
		insert submissionRecord1;
	    
        Offer__c objOffer = new Offer__c();
        objOffer.Opportunity__c = OppRecord1.Id;
        objOffer.Submission__c = submissionRecord1.Id;
        insert objOffer;
        system.debug('****objOffer***'+objOffer);
        
        //Create a reference to the VF page
        PageReference pageRef = Page.MCATabPage;
        pageRef.getParameters().put('Id', objOffer.Id);
        system.debug('***pageRef***'+pageRef);
        Test.setCurrentPageReference(pageRef);
        

        ApexPages.StandardController sc = new ApexPages.standardController(objOffer);
        MCANestedOffersTabController obj = new MCANestedOffersTabController();
        
        obj.getOffers();
        obj.newOffer();
        obj.refresh();
        obj.saveAll();
        obj.editAll();
    }
 }