MCA Dev/src/objects/Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Receivable_Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA Dev/src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postdated Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>Revenue and other incoming funds</description>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Transaction_Line_Credit__c.object
<CustomObject>
    <description>Used to track which Receivables are being reconciled for a given Transaction, cash paid in.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Receivable__c</fullName>
        <label>Receivable</label>
        <referenceTo>Receivable__c</referenceTo>
        <relationshipLabel>Transaction Line Credit</relationshipLabel>
        <relationshipName>Transaction_Line_Credit</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transaction Line Credit</relationshipLabel>
        <relationshipName>Transaction_Line_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Line Credit</label>
    <nameField>
        <displayFormat>TLC-{0000}</displayFormat>
        <label>Transaction Line Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/classes/TransactionLineCreditHandler.cls
/* 
 *  Description - Handler for TransactionLineCreditTrigger
 *                Set the Transaction to Pending when the Transaction Line Credit is deleted
 * 
 *  Date - 15-05-2014
 *  
 *  Created by - Sneha P.
 *
 */
public with sharing class TransactionLineCreditHandler {
	
	public static final String STATUS_PENDING = 'Pending';
	
	//Function called on After Delete of Transaction line credit
	public void onAfterDelete(list<Transaction_Line_Credit__c> lineItemList){
		
		set<Id> setTransactionId = new set<Id>();
		set<Id> setReceivableId = new set<Id>();
		map<Id,Receivable__c> mapUpdatedReceivable = new map<Id,Receivable__c>();
		
		map<Id,Transaction__c> updatedTransactionMap = new map<Id,Transaction__c>();
		
		for(Transaction_Line_Credit__c lineItem : lineItemList){
			
			if(lineItem.Transaction__c != null){
				if(lineItem.Transaction__c != null)
					setTransactionId.add(lineItem.Transaction__c);
				if(lineItem.Receivable__c != null)
					setReceivableId.add(lineItem.Receivable__c);
			}
		}
		
		//Query all the Transaction related to Line Debits
		map<Id,Transaction__c> mapTransaction = new map<Id,Transaction__c>([Select Id,Amount__c,Status__c 
												 							from Transaction__c 
												 							where Id IN: setTransactionId]);
		
		map<Id,Receivable__c> mapReceivable = new map<Id,Receivable__c> ([Select Id,Receivable_Amount_Paid__c
																		  from Receivable__c 
																		  where Id IN: setReceivableId]);
		
		for(Transaction_Line_Credit__c lineItem : lineItemList){
			Transaction__c objTransaction = new Transaction__c();
			
			if(lineItem.Transaction__c != null && mapTransaction.size() > 0 
												&& mapTransaction.containsKey(lineItem.Transaction__c)){
				
				objTransaction =  (updatedTransactionMap.size() > 0 && updatedTransactionMap.containsKey(lineItem.Transaction__c) ) 
										?  updatedTransactionMap.get(lineItem.Transaction__c)
										 	: mapTransaction.get(lineItem.Transaction__c);
				objTransaction.Status__c = STATUS_PENDING;										
				updatedTransactionMap.put(objTransaction.Id,objTransaction );
			}
			
			Receivable__c objReceivable = new Receivable__c();
			if(lineItem.Receivable__c != null && mapReceivable.size() > 0 && 
										         mapReceivable.containsKey(lineItem.Receivable__c)){
				
				objReceivable = (mapUpdatedReceivable.size() > 0 && mapUpdatedReceivable.containsKey(lineItem.Receivable__c))
									? mapUpdatedReceivable.get(lineItem.Receivable__c)
										: mapReceivable.get(lineItem.Receivable__c);
				
				if( lineItem.Amount__c != null && objReceivable.Receivable_Amount_Paid__c != null &&
											      objReceivable.Receivable_Amount_Paid__c != 0){
					system.debug('*****objReceivable.Receivable_Amount_Paid__c**'+objReceivable.Receivable_Amount_Paid__c);
					system.debug('*****lineItem.Amount__c**'+lineItem.Amount__c);
					objReceivable.Receivable_Amount_Paid__c -=  lineItem.Amount__c ; 
					
					system.debug('*****lineItem.Amount__c after**'+lineItem.Amount__c);
					system.debug('*****objReceivable.Receivable_Amount_Paid__c after**'+objReceivable.Receivable_Amount_Paid__c); 
				}
				mapUpdatedReceivable.put(objReceivable.Id, objReceivable);										         	
			}
		}	
		
		try{
			if(updatedTransactionMap.size() > 0)
				update updatedTransactionMap.values();
			if(mapUpdatedReceivable.size() > 0)
				update mapUpdatedReceivable.values();
		}catch(Exception e){
			system.debug('-----'+e.getMessage());
		}											 							
	}
}