MCACE/src/objects/Commission_Rule__c.object
<CustomObject>
    <description>The commission rule object handles the commissions.</description>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Commission Rule</relationshipLabel>
        <relationshipName>Commission_Rule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Type__c</fullName>
        <label>Commission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fixed_Amount__c</fullName>
        <label>Fixed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payable_Type__c</fullName>
        <label>Payable Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Provider Amt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage_Of__c</fullName>
        <label>Percentage Of</label>
        <picklist>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Commission Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Funded Amount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Commission Rule</label>
    <nameField>
        <label>Commission Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCACE/src/objects/Commission_Rule_Entry__c.object
<CustomObject>
    <description>The commission rule entry object handles the commissions.</description>
    <fields>
        <fullName>Commission_Rule__c</fullName>
        <label>Commission Rule</label>
        <referenceTo>Commission_Rule__c</referenceTo>
        <relationshipLabel>Commission Rule Entry</relationshipLabel>
        <relationshipName>Commission_Rule_Entry</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_API__c</fullName>
        <label>Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API__c</fullName>
        <label>Object API</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Commission Rule Entry</label>
    <nameField>
        <label>Commission Rule Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCACE/MCACE-1.2Release/src/objects/Commission_Structure__c.object
<CustomObject>
    <description>Commission structure is a bucket of commission rules</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Closer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opener</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCACE/MCACE-1.2Release/src/classes/GenerateAgreementRecordsController.cls
/*
    Created by :Srikanth Pinnamaneni
    
*/
public class GenerateAgreementRecordsController {

    private ApexPages.StandardController std;

    private Commission_Rule__c[] newRules;

    private Commission_Structure__c newStructure;

    private Commission_Rule_Entry__c[] newEntries;

    private Integer validSortNumber;

    private Set < Id > ruleIds;


    public GenerateAgreementRecordsController(ApexPages.StandardController std) {

        this.std = std;

        newRules = new Commission_Rule__c[] {};

        newEntries = new Commission_Rule_Entry__c[] {};

        ruleIds = new Set < Id > ();


    }


    public PageReference init() {

        CloneCommissionStructure();

        cloneCommissionRule();

        return new Pagereference('/' + newStructure.Id);

    }


    private void cloneCommissionStructure() {


        Commission_Structure__c structure = [SELECT Id, Name, Description__c, Type__c FROM Commission_Structure__c WHERE Id = : std.getId()];

        newStructure = structure.clone(false, true, false, false);

        insert newStructure;

    }

    private void cloneCommissionRule() {

        Commission_Rule__c newRule = new Commission_Rule__c();
        Map < Id, Commission_Rule__c > ruleMap = new Map < Id, Commission_Rule__c > ();

        List < Commission_Rule__c > rules = [SELECT Id, Name, Commission_Percentage__c, Commission_Structure__c, Commission_Type__c, Description__c, Fixed_Amount__c,

            Payable_Type__c, Percentage_Of__c FROM Commission_Rule__c WHERE Commission_Structure__c = : std.getId()
        ];


        for (Commission_Rule__c rule: rules) {

            newRule = rule.clone(false, true, false, false);

            newRule.Commission_Structure__c = newStructure.id;

            newRules.add(newRule);
            ruleMap.put(rule.id, newRule);

        }

        if (!newRules.isEmpty()) {
            insert newRules;
            CloneRuleEntries(ruleMap);

        }

    }

    private void cloneRuleEntries(Map < Id, Commission_Rule__c > ruleMap) {

        Commission_Rule_Entry__c[] entries = [SELECT Id, name, Commission_Rule__c, Description__c, Field_API__c, Object_API__c, Operator__c,
            text__c FROM Commission_Rule_Entry__c WHERE Commission_Rule__c IN: rulemap.keyset()
        ];

        for (Commission_Rule_Entry__c entry: entries) {
            if (rulemap.containsKey(entry.Commission_rule__c)) {

                Commission_Rule_Entry__c newEntry = entry.clone(false, true, false, false);
                newentry.Commission_Rule__c = ruleMap.get(entry.commission_rule__c).id;
                newEntries.add(newEntry);
            }
        }

        if (!newEntries.isEmpty()) {
            insert newEntries;

        }
    }

}