merul_Dev/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

merul_Dev/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Opportunity.object
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding</relationshipLabel>
        <relationshipName>Funding</relationshipName>
        <type>Lookup</type>
    </fields>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

frn_dev_sandbox2/src/classes/VoidTravelExtTest.cls
@isTest
private class VoidTravelExtTest{
       static testMethod void test1 () {
		      Account acc = new Account();  
				acc.Name = 'tesst';  
				insert acc;  
			Contact con = new Contact();
			con.Lastname = 'test';
			insert con;
            Opportunity opp = new Opportunity();
            opp.StageName = 'In Progress';
            opp.Name = 'test'; 
			opp.Contact__c = con.id;
            opp.CloseDate = System.today();
            opp.AccountId = acc.id;
			
            insert opp; 
			 
			 Quote est = new Quote();
			 est.Name = 'test quote';
			 est.OpportunityId = opp.Id;
			 est.Status__c = 'Open';
			 insert est;
		 
            
            VoidTravelExt Controller = new VoidTravelExt();
			
            VoidTravelExt.request(opp.id,'','');
            
        
       }
}