merul_Dev/src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for
one or more positions</description>
    <fields>
        <fullName>SampleCandDate__c</fullName>
        <label>SampleCandDate</label>
        <type>Date</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job position at our company</description>
    <fields>
        <fullName>Apex__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apex</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SampleCand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SampleCand</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Position</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

merul_Dev/src/classes/TestForComponentsController.cls
public class TestForComponentsController {

 public Position__c pos{
  
 get;
 set;
 
 
 }
  
 public pagereference onload()
 {
 
 
 
 pos = [select Apex__c,Status__c,Open_Date__c,name,SampleCand__r.SampleCandDate__c from position__c where id='a009000001ykxt9AAA'];
 
 if(pos.SampleCand__r==null)
 {
 pos.SampleCand__r = new Candidate__c();
 
 }
 return null;
 
 }
 
 
 public TestForComponentsController()
 {
 /*
 pos = [select Apex__c,Status__c,Open_Date__c,name,SampleCand__r.SampleCandDate__c from position__c where id='a009000001ykxt9AAA'];
 
 if(pos.SampleCand__r==null)
 {
 pos.SampleCand__r = new Candidate__c();
 
 }
 
 */
 }
 
 public pagereference save()
 {
 
 
 
 system.debug('$$$$$$   '+ pos.SampleCand__r);
 //update pos;
 return null;
 }
 

 
 
}