merul_Dev/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

merul_Dev/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Opportunity.object
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding</relationshipLabel>
        <relationshipName>Funding</relationshipName>
        <type>Lookup</type>
    </fields>

VeraSandBox2016/src/objects/Trip__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trips</relationshipLabel>
        <relationshipName>Trips</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRI-{00000}</displayFormat>
        <label>JRRID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

frn_dev_sandbox2/src/classes/TripHandler.cls
/**
 * Class TripHandler
 *
 * Trigger Handler for the Contact SObject. This class implements the TriggerInterface
 * interface to help ensure the trigger code is bulkified and all in one place.
 */
public without sharing class TripHandler implements TriggerInterface {
	Map<string,string> oppconIdMap;
    // Constructor
    public TripHandler(){
		oppconIdMap = new Map<string,string>();
    }
 
    /**
     * bulkBefore
     *
     * This method is called prior to execution of a BEFORE trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkBefore(){   
		set<Id> oppIdset = new set<Id>();
		for(Trip__c t: (List<Trip__c>)trigger.new){
            if(t.Opportunity__c != null){
				oppIdset.add(t.Opportunity__c);
			}
        }
		List<Opportunity> oppList = new List<Opportunity>();
		for(Opportunity opp:[select id, Contact__c from Opportunity where Id IN: oppIdset]){
			oppconIdMap.put(opp.Id,opp.Contact__c);
		}
        
    }
 
    public void bulkAfter(){
        
       
    }
 
    public void beforeInsert(SObject so){        
       Trip__c tso =(Trip__c)so;
	   if(oppconIdMap.containskey(tso.Opportunity__c))
	   tso.Patient__c = oppconIdMap.get(tso.Opportunity__c);
    }
 
    public void beforeUpdate(SObject oldSo, SObject so){
		Trip__c tso =(Trip__c)so;
	   if(oppconIdMap.containskey(tso.Opportunity__c))
	   tso.Patient__c = oppconIdMap.get(tso.Opportunity__c);
    }
	 
 
    /**
     * beforeDelete
     *
     * This method is called iteratively for each record to be deleted during a BEFORE
     * trigger.
     */
    public void beforeDelete(SObject so){
       
    }
 
    public void afterInsert(SObject so){ 
       
    }
    public void afterUpdate(SObject oldSo, SObject so){
                   
    }

    public void afterDelete(SObject so){
        
    }
 
    public void afterUndelete(SObject so){
        
    }
 
    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this
     * method to accomplish any final operations such as creation or updates of other records.
     */
    public void andFinally(){
                
    }
}