MCA App/Release/MCA App 1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Acct_Nums__c</fullName>
        <label>Bank Acct Num(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Names__c</fullName>
        <label>Bank Name (s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CC_transactions_Monthly_Avg__c</fullName>
        <label>CC transactions (Monthly Avg)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIDs__c</fullName>
        <label>MID(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Monthly_Bank_Depopsit_Avg_Last_2_Months__c</fullName>
        <label>Monthly Bank Depopsit Avg - Last 2 Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Bank_Deposit_Avg_All__c</fullName>
        <label>Monthly Bank Deposit Avg - All</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_CC_Avg_All__c</fullName>
        <label>Monthly CC Avg - All</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_CC_Avg_Last_2_Months__c</fullName>
        <label>Monthly CC Avg - Last 2 Months</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_CC_Avg_Non_Amex__c</fullName>
        <label>Monthly CC Avg - Non Amex</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDBs_Avg__c</fullName>
        <label>NDBs (Avg)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSFs_Avg__c</fullName>
        <label>NSFs (Avg)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Bank_Statements_Available__c</fullName>
        <label># of Bank Stmts Avail</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_CC_Statements_Available__c</fullName>
        <label># of CC Stmts Avail</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Owners__c</fullName>
        <label>Other Owners</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_1_Name__c</fullName>
        <label>Owner #1 Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_2_name__c</fullName>
        <label>Owner #2 Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processor_Names__c</fullName>
        <label>Processor Name (s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>
    <recordTypes>
        <fullName>Merchant</fullName>
        <active>true</active>
        <label>Merchant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Processor</fullName>
        <active>true</active>
        <label>Processor</label>
    </recordTypes>
</CustomObject>

MCA App/Release/MCA App 1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bank_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Statements</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.140/src/objects/Credit_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Customer Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Credit_Cards1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MID_Account_Number__c</fullName>
        <label>MID Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01 - January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 - September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 - October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11 - November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 - December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Processor_Name__c</fullName>
        <label>Processor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Card Sales</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Card Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA App 1/src/classes/BankAccountWizard.cls
/*
	Author : Deepthi
	Create On: 18th Jun 2013
	Class Name: BankAccountWizard
	Description : Used for BankAccountWizardVF page
	Modified By : Vasu Takasi || 19th Jun 2013
*/
global with sharing class BankAccountWizard {
	public Bank_Account__c objBankAccount{get;set;}
	public Credit_Card__c objCreditCard{get;set;}	
	public Bank_Account__c objBankAccountSummary{get;set;}
	public Credit_Card__c objCreditCardSummary{get;set;}	
	public string accName{get;set;}
	public string BizAddress{get;set;}
	public string HomeAddress{get;set;}
	public boolean accInfoView{get;set;}
	public boolean cCView{get;set;}
	public boolean summaryView{get;set;}
	public boolean accView{get;set;}
	public list<Account> lstBanks{get;set;}
	public string ownerInfo{get;set;}
	string Accid;
	string key;
	public Account objAccount{get;set;}
	public string wizardType{get;set;}
	public string bankAccountNo;
	public string midAccountNo;
	
	
	public BankAccountWizard(){
		objBankAccount=new Bank_Account__c();
		objBankAccount.Year__c = string.valueOf(system.today().year());
		objBankAccountSummary=new Bank_Account__c();
		objAccount=new Account();
		objCreditCard = new Credit_Card__c();
		objCreditCard.Year__c = string.valueOf(system.today().year());
		objCreditCardSummary=new Credit_Card__c();
		
		ownerInfo='';
		BizAddress='';
		HomeAddress='';
		wizardType='';
		key='';
		accId='';
		accInfoView=true;
		cCView=false;
		summaryView=false;
		accView=true;
		if(Apexpages.currentpage().getParameters().get('key') !=null && Apexpages.currentpage().getParameters().get('key') != '')
			key=Apexpages.currentpage().getParameters().get('key');
		if(Apexpages.currentpage().getParameters().get('id') != null && Apexpages.currentpage().getParameters().get('id') != '')	
			accId=Apexpages.currentpage().getParameters().get('id');
				
				if(key == 'BankWizard'){
					accInfoView=true;
					cCView=false;
					summaryView=false;
					accView=true;
				}
				else if(key == 'CCWizard'){
					accInfoView=false;
					cCView=true;
					summaryView=false;
					accView=true;
				}
				else if(key == 'SummaryWizard'){
					accInfoView=false;
					cCView=false;
					summaryView=true;
					accView=false;
				}
				if( accId != Null && accId !=''){
					//objBankAccount.Bank_Name__c=accId;
					//objCreditCard.Processor_Name__c=accId;
					
					objBankAccount.Account__c = accId;//Changed Customer Account mapping to Account__c field on 26-08-2013 
					objCreditCard.Account__c = accId;//Changed Customer Account mapping to Account__c field on 26-08-2013
				}			
		//query all records from Banks__c 
		lstBanks=new list<account>();
		lstBanks=[select id,name from account where name != null and RecordType.Name = 'Merchant Processor/Bank' order by name limit 45000];//Added RecordType filter on 26-08-2013
			AccountDetails();
					
	}
	//function to change wizard type based on selection
	public void changeWizard(){
		if(wizardType == 'BankAccounts'){
			accInfoView=true;
			cCView=false;
			summaryView=false;
			accView=true;
		}
		else if(wizardType == 'creditCard'){
			accInfoView=false;
			cCView=true;
			summaryView=false;
			accView=true;
		}
		else if(wizardType == 'summary'){
			accInfoView=false;
			cCView=false;
			summaryView=true;
			accView=false;
		}
		lstBanks=new list<account>();
		lstBanks=[select id,name from account where name != null and RecordType.Name = 'Merchant Processor/Bank' order by name limit 45000];//Added RecordType filter on 26-08-2013
		
	}
	
	//function to get Account Details
	public void AccountDetails(){
			objAccount=new Account();
			if(Accid !=null && Accid !=''){
			try{
	    	 objAccount=[Select id,Name,BillingCity,BillingCountry,BillingState,BillingStreet,BillingPostalCode,ShippingCity,ShippingCountry,ShippingPostalCode,ShippingState,ShippingStreet,
	    	             Owner_1_Name__c,Owner_2_name__c,Other_Owners__c,Legal_Name__c,Monthly_Bank_Deposit_Avg_All__c,Monthly_Bank_Depopsit_Avg_Last_2_Months__c,Number_Bank_Statements_Available__c,
	    	             Number_CC_Statements_Available__c,Monthly_CC_Avg_All__c,Monthly_CC_Avg_Last_2_Months__c,Monthly_CC_Avg_Non_Amex__c,Bank_Names__c,Processor_Names__c,
	    	             MIDs__c,Bank_Acct_Nums__c,NDBs_Avg__c,NSFs_Avg__c,CC_transactions_Monthly_Avg__c  from Account where id=:Accid];
			}
			catch(exception e){
				apexPages.addMessages(e);
			}
			BizAddress='';
			HomeAddress='';
			if(objAccount !=null){
				if( objAccount.Name != null )
					accname=objAccount.Name;
					
				if( objAccount.BillingStreet != null )
					BizAddress=objAccount.BillingStreet+', ';
					
				if( objAccount.BillingCity != null ) 
					BizAddress += objAccount.BillingCity+', ';
					
				if( objAccount.BillingState != null )
					BizAddress +=objAccount.BillingState+', ';
					
				if( objAccount.BillingPostalCode != null)
					BizAddress +=objAccount.BillingPostalCode+', ';
					
				if( objAccount.BillingCountry != null)
					BizAddress +=objAccount.BillingCountry;
					
					BizAddress=BizAddress.removeEnd(', ');
					
				if( objAccount.ShippingStreet != null )
					HomeAddress=objAccount.ShippingStreet+', ';
					
				if( objAccount.ShippingCity != null) 
					HomeAddress +=objAccount.ShippingCity+', ';
					
				if( objAccount.ShippingState != null )
					HomeAddress +=objAccount.ShippingState+', ';
					
				if (objAccount.ShippingPostalCode != null)
					HomeAddress +=objAccount.ShippingPostalCode+', ';
					
				if( objAccount.ShippingCountry != null )
					HomeAddress +=objAccount.ShippingCountry;
					
					HomeAddress=HomeAddress.removeEnd(', ');
					
				if( objAccount.Owner_1_Name__c != null )	
					ownerInfo = objAccount.Owner_1_Name__c+', ';
					
				if( objAccount.Owner_2_Name__c != null )	
						ownerInfo += objAccount.Owner_2_Name__c+', ';
						
				if( objAccount.Other_Owners__c != null )	
						ownerInfo += objAccount.Other_Owners__c;	
						
					ownerInfo=ownerInfo.removeEnd(', ');
			}	
		}
		
	}
	
	public void saveBankAccountRec(){
		
				try{
					summaryView=false;
					cCView=false;
					accInfoView=true;
					objBankAccount.Account__c = accId;
					//string accParamId=apexpages.currentpage().getparameters().get('thePg:theFm:theComp:theBankAccComp:thePb:theBankAccPBS:BankName_lkid');
					//if( accParamId != '')
						// Accid = accParamId;
					insert objBankAccount;
					
					if(objBankAccount.id != null){
						objBankAccountSummary=new Bank_Account__c();
						objBankAccountSummary=objBankAccount;
						accInfoView=false;
						summaryView=true;
						cCView=false;
						accView=false;
						AccountDetails();
					}
					objBankAccount = new Bank_Account__c();
				}
				catch(exception e){
					apexPages.addMessages(e);
				}	
			
	}
	public void saveAndNewBankAccount(){
		objBankAccountSummary.clear();
		try{
			summaryView=false;
			cCView=false;
			accInfoView=true;
			//string accParamId=apexpages.currentpage().getparameters().get('thePg:theFm:theComp:theBankAccComp:thePb:theBankAccPBS:BankName_lkid');
			//if( accParamId != '')
			//	Accid = accParamId;
			objBankAccount.Account__c = accId;			
			insert objBankAccount;
			objBankAccountSummary=objBankAccount.clone();
			
			if(objBankAccount.id != null){
				accInfoView=true;
				summaryView=false;
				cCView=false;
				AccountDetails();
				objBankAccount.clear();
				objBankAccount.Bank_Name__c=objBankAccountSummary.Bank_Name__c;
				objBankAccount.Year__c = objBankAccountSummary.Year__c;
				objBankAccount.Bank_Account_Number__c = objBankAccountSummary.Bank_Account_Number__c;
			}
			
		}
		catch(exception e)
		{		
			apexPages.addMessages(e);			
		}
	}
	
	public pagereference saveCC(){
		try
		{
			summaryView=false;
			cCView=true;
			accInfoView=false;
			//string accParamId=apexpages.currentpage().getparameters().get('thePg:theFm:theComp:theBankAccComp:thePb:theCCPBS:procName_lkid');
			//if( accParamId != '')
				//Accid = accParamId;
				objCreditCard.Account__c = accId;
			insert objCreditCard;
			if(objCreditCard.Id != null ){
				objCreditCardSummary=new Credit_Card__c();
				objCreditCardSummary=objCreditCard;
				summaryView=true;
				cCView=false;
				accInfoView=false;
				accView=false;
				AccountDetails();
			}
			objCreditCard=new Credit_Card__c();
			return null;
		}
		catch(exception e)
		{		
			apexPages.addMessages(e);		
			return null;	
		}
	}
	
	public void saveAndNewCC(){
		objCreditCardSummary.clear();
		try
		{
				summaryView=false;
			cCView=true;
			accInfoView=false;
			//string accParamId=apexpages.currentpage().getparameters().get('thePg:theFm:theComp:theBankAccComp:thePb:theCCPBS:procName_lkid');
			//if( accParamId != '')
			//	accParamId = accParamId;
				objCreditCard.Account__c = accId;
			insert objCreditCard;
			objCreditCardSummary=objCreditCard;
			//midAccountNo=objCreditCard.MID_Account_Number__c;
			if(objCreditCard.Id != null ){
				objCreditCardSummary=objCreditCard.clone();
				summaryView=false;
				cCView=true;
				accInfoView=false;
				
				AccountDetails();
				objCreditCard.clear();
				objCreditCard.Processor_Name__c = objCreditCardSummary.Processor_Name__c;
				objCreditCard.MID_Account_Number__c = objCreditCardSummary.MID_Account_Number__c;
				//objCreditCard.Month__c = objCreditCardSummary.Month__c;
				objCreditCard.Year__c = objCreditCardSummary.Year__c;
				
			}
		}
		catch(exception e){		
			apexPages.addMessages(e);			
		}
	}
	
	//method name previousMonthAccNo
	//Descrition :The bank account number should come up when the user enters the subsequent month.
	// (The bank account number from the previous month should come up/auto fill)
	@remoteAction
	Global static string previousMonthAccNo(string month,string year,string accId){
		list<Bank_Account__c> lstBankAccount = new list<Bank_Account__c>();
		
		string accNo;
		string prevMonth;
		//query bank account records 
		if(accId !=null && accId !=''){
			lstBankAccount=[select id,Bank_Name__c,Month__c,Year__c,Name from Bank_Account__c where Bank_Name__c=:accId];
		}	
		map<string,string> mapAccNO = new map<string,string>();
		for(Bank_Account__c obj : lstBankAccount){
			mapAccNO.put(obj.Month__c+'::'+obj.Year__c,obj.name);
		} 
		if(Month != null){
			if(Month=='January')
				prevMonth = 'December';
			else if(Month=='February')
				prevMonth = 'January';
			else if(Month=='March')
				prevMonth = 'February';
			else if(Month=='April')
				prevMonth = 'March';
			else if(Month=='May')
				prevMonth = 'April';
			else if(Month=='June')
				prevMonth = 'May';
			else if(Month=='July')
				prevMonth = 'June';
			else if(Month=='August')
				prevMonth = 'July';
			else if(Month=='September')
				prevMonth = 'August';
			else if(Month=='October')
				prevMonth = 'September';
			else if(Month=='November')
				prevMonth = 'October';
			else if(Month=='December')
				prevMonth = 'November';
		}
		if( prevMonth == 'December'){
			integer intYear= integer.valueOf(year)-1;
			year = string.valueOf(intYear);
		}	
		if(!mapAccNO.isEmpty()){
			accNo = mapAccNO.get(prevMonth+'::'+year);
		}
		return accNo;
	}
}