MCA App/Release/MCA App 1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bank_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Same_as_Biz_Home_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Address Same as Biz/Home Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Average_Daily_Balance__c</fullName>
        <label>Average Daily Balance</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Owner_Name_Same_as_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business/Owner Name Same as App</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Request__c</fullName>
        <description>user can enter a quick note related to each record (e.g. “Missing Page 2” or “Need the NSF info” or “Need Transfer amounts”)</description>
        <label>Data Request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deposits__c</fullName>
        <label>Deposits</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Matching_App__c</fullName>
        <formula>IF( AND(Business_Owner_Name_Same_as_App__c = True, Address_Same_as_Biz_Home_Address__c = True),&apos;Yes&apos;,&apos;No&apos; )</formula>
        <label>Matching App?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_NSFs__c</fullName>
        <label>Number of NSFs</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Negative_Days__c</fullName>
        <label>Number of Negative Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remove</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Statements</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.140/src/objects/Credit_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Customer Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Credit_Cards1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Request__c</fullName>
        <description>user can enter a quick note related to each record (e.g. “Missing Page 2” or “Need the NSF info” or “Need Transfer amounts”)</description>
        <label>Data Request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MID_Account_Number__c</fullName>
        <label>MID Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matching_App__c</fullName>
        <formula>IF( AND(Name_Same_as_App__c = True,  Address_Same_as_App__c = True),&apos;Yes&apos;,&apos;No&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Matching App?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01 - January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 - September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 - October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11 - November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 - December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Transactions_AMEX_only__c</fullName>
        <label>Number of Transactions-AMEX only</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Transactions_All__c</fullName>
        <label># Transactions</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processor_Name__c</fullName>
        <label>Processor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remove</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Net_Processed_AMEX_only__c</fullName>
        <label>Total Net Processed-AMEX only</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Net_Processed_All__c</fullName>
        <label>$ Processed</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Card Sales</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Card Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA App 1/src/classes/PendingItemsController.cls
/*
    Author : Vasu Takasi
    Created On : 22nd July 2013
    Class Name : PendingItemsController
    Description : Used in the page called PendingItemsVF 
*/
public with sharing class PendingItemsController {
    public list<Bank_Account__c> lstPendingBankAcc{get;set;}//used to get pending Items 
    public list<Credit_Card__c> lstPendingCreditCards{get;set;}//used to get pending Items
    string accId;
    public String Bankaccountid{get;set;}//used to hold bankaccountid from page 
    public String Creditcardid{get;set;}//used to hold creditcardid from page 
    public String RecType{get;set;}//Record Type added on 8/22/2013
    public String indexofrow{get;set;}//added on 8/22/2013     
    public PendingItemsController(){
        if(ApexPages.currentPage().getParameters().get('id') != Null ){
            accId = ApexPages.currentPage().getParameters().get('id');
        }
        lstPendingBankAcc = new list<Bank_Account__c>();
        lstPendingCreditCards = new list<Credit_Card__c>();
        if(accId != Null && accId != ''){
            lstPendingBankAcc = [select id,name,year__c,month__c,remove__c,Bank_Account_Number__c,Deposits__c,Average_Daily_Balance__c,Number_of_Negative_Days__c,Number_of_NSFs__c,Data_Request__c,Matching_App__c from Bank_Account__c where Account__c = : accId 
                                And (Deposits__c = Null OR Average_Daily_Balance__c = Null OR Number_of_Negative_Days__c = NUll OR Number_of_NSFs__c = Null OR Business_Owner_Name_Same_as_App__c = False OR Address_Same_as_Biz_Home_Address__c = False) Order By Year__c,Month__c];
                                
            lstPendingCreditCards = [select id,name,year__c,month__c,Matching_App__c,Processor_Name__c,remove__c,MID_Account_Number__c ,Number_of_Transactions_All__c,Number_of_Transactions_AMEX_only__c,Total_Net_Processed_All__c,Total_Net_Processed_AMEX_only__c,Data_Request__c
                                    from Credit_Card__c where Account__c = :accId AND (Number_of_Transactions_All__c = Null OR Number_of_Transactions_AMEX_only__c = Null OR Total_Net_Processed_All__c = Null OR Total_Net_Processed_AMEX_only__c = Null) Order By Year__c,Month__c];
                                                                    
        }
    }
    //redirect to BankAccountSummaryVF
    public pageReference redirectSummaryVF(){
        PageReference ref = new pageReference('/apex/BankAccountWizardsummaryVF?id='+accId);
        ref.setRedirect(true);
        return ref;
    }
    
    //upadte BA Records
    Public void updateBankAccounts(){
      try{  
        if( lstPendingBankAcc.size()>0 )
            update lstPendingBankAcc;
      }
      catch(exception e){
        ApexPages.AddMessages(e);
      }
      updateCreditCards(); // Adde by : Ankush : Date :16/09/2013--> added for calling Save the creditcard details.
    }
    //upadte CC Records
    Public void updateCreditCards(){
      try{  
        if( lstPendingCreditCards.size()>0 )
            update lstPendingCreditCards;
      }
      catch(exception e){
        ApexPages.AddMessages(e);
      }
    }
    //Removing and Updating BankAccounts or Credit cards from page    added on 8/22/2013
    public void upadateremovebankcredit(){
        System.debug('Bankaccountid:'+Bankaccountid);
        System.debug('Type:'+RecType);
        System.debug('CreditcardId:'+Creditcardid);
        if(RecType=='bank' && Bankaccountid!=null){ 
                Bank_Account__c bankobj=new Bank_Account__c(id=Bankaccountid,Remove__c=true);
                update bankobj;           
                lstPendingBankAcc.remove(integer.valueOf(indexofrow));
        }
        else if(RecType=='credit' && Creditcardid!=null){
                Credit_Card__c creditobj=new Credit_Card__c(id=Creditcardid,Remove__c=true);
                update creditobj;
                lstPendingCreditCards.remove(integer.valueOf(indexofrow));
            
        }
        
    }
    
}