MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Funding Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Holdback__c</fullName>
        <label>Holdback%</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMT_Schedule__c</fullName>
        <label>PMT Schedule</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twice a week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payback_Amt__c</fullName>
        <formula>Amount__c *  Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payback Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amt__c</fullName>
        <label>Payment Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Chosen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <label>Term (Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Funder)</relationshipLabel>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Program__c.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Application_Number__c</fullName>
        <label>Application Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Submission Notes</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/classes/MCASubmissionsTabController.cls
public with sharing class MCASubmissionsTabController {
  
  public Submission__c[] submissions;
  public Submission__c[] newSubmissions {get; set;}
  
  public Container[] containers;
  
  public Boolean editAll {get;set;}
  public Id recordToDelete {get;set;}
  public Integer indexToRemove {get;set;}
  
  private Id opportunityId;
  
  public MCASubmissionsTabController() {
  
    opportunityId = Apexpages.currentPage().getParameters().get('id');

    refresh();
  }  

  //public Submission__c[] getSubmissions() {
  public Container[] getContainers() {
  	
    submissions = new Submission__c[] {};
    containers = new Container[] {};
    
    submissions.addAll(newSubmissions);
  
    submissions.addAll([SELECT 
                    Id,
                    Name,
                    Funder__c,
                    Date_Submitted__c,
                    Status__c,
                    Status_Date__c,
                    Contact__c,
                    Program__c,
                    Application_Number__c,
                    Notes__c,
                    (SELECT
	                     Term_Months__c,
	                     Status__c,
	                     Send__c,
	                     Rate__c,
	                     Payment_Amt__c,
	                     Payback_Amt__c,
	                     PMT_Schedule__c,
	                     Holdback__c,
	                     Funder__c,
	                     Deal_Type__c,
	                     Submission__c,
	                     Amount__c
                     FROM Offers__r)                    
                    
                FROM Submission__c
                WHERE Opportunity__c = :opportunityId]);
                
    for (Integer i = 0; i < submissions.size(); i++) {
      containers.add(new Container(submissions[i], i));
    }
                
    //return submissions;
    return containers;
  }  
  
  public void newSubmission() {
  	
  	system.debug('--DEBUG Previous ' + newSubmissions);
    newSubmissions.add(new Submission__c(Opportunity__c = opportunityId));
    system.debug('--DEBUG After ' + newSubmissions + ' ');
  }  
  
  public void refresh() {

    editAll = false;
    recordToDelete = null;
    //newSubmissions = new Set<Submission__c>();
    newSubmissions = new Submission__c[] {};
    containers = new Container[] {};
  }
  
  public void editAll() {
  
    refresh();
    editAll = true;
  }
  

  public void saveAll() {
  
    /*
    Submission__c[] recordsToUpdate = new Submission__c[] {};
    
    for (Submission__c record :submissions) {
    	
      if (MCARecordValidator.isRecordValid(record)) {
        recordsToUpdate.add(record);
      }  
    }
    */
    
    upsert submissions;

    refresh();
  }
  
  public void deleteSubmission() {
  
    if (recordToDelete != null) {
      Submission__c record = [SELECT Id FROM Submission__c WHERE Id = :recordToDelete];
      delete record;
    }
  }    
  
  public void removeSubmission() {
  
    system.debug('--DEBUG container list ' + containers + ' ');
  
    if (indexToRemove != null) {
      
      Container c = null;
      
      for (Container element :containers) {
        
        if (element.index == indexToRemove) {
          c = element;
        }
      }
      
      //containers.remove(c.index);
      newSubmissions.remove(c.index);
    }
  
  }
  
  public class Container {
  
    public Submission__c submission {get;set;}
    public Integer index {get;set;}
  
    public Container(Submission__c instance, Integer index) {
      submission = instance;
      this.index = index;
    }
  
  }

}