MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Funding Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Holdback__c</fullName>
        <label>Holdback%</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PMT_Schedule__c</fullName>
        <label>PMT Schedule</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twice a week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payback_Amt__c</fullName>
        <formula>Amount__c *  Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payback Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amt__c</fullName>
        <label>Payment Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Chosen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <label>Term (Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/classes/MCAOffersTabController.cls
public with sharing class MCAOffersTabController {

  public Offer__c[] offers;
  public Container[] containers;
  
  public Offer__c[] newOffers {get; set;}
  
  public Boolean editAll {get;set;}
  
  public Id recordToDelete {get;set;}
  public Integer indexToRemove {get;set;}
  
  private Id opportunityId;
  
  public Decimal fundingAmountHigh {get; set;}
  public Decimal fundingAmountLow {get; set;}
  
  public Decimal paybackHigh {get; set;}
  public Decimal paybackLow {get; set;}
  
  public Decimal rateHigh {get; set;}
  public Decimal rateLow {get; set;}
  
  public Decimal termsHigh {get; set;}
  public Decimal termsLow {get; set;}
  
  public Decimal holdbackHigh {get; set;}
  public Decimal holdbackLow {get; set;}
  
  public Decimal paymentAmountHigh {get; set;}
  public Decimal paymentAmountLow {get; set;}  
  
  
  public MCAOffersTabController() {
  
    opportunityId = Apexpages.currentPage().getParameters().get('id');
	
    refresh();
  }  
  
  //public Offer__c[] getOffers() {
  public Container[] getContainers() {
  
    offers = new Offer__c[] {};
    containers = new Container[] {};
    
    offers.addAll(newOffers);

    for (Offer__c off :[SELECT 
                               Term_Months__c,
                               Status__c,
                               Send__c,
                               Details__c,
                               Rate__c,
                               Payment_Amt__c,
                               Payback_Amt__c,
                               PMT_Schedule__c,
                               Holdback__c,
                               Funder__c,
                               Deal_Type__c,
                               Opportunity__c,
                               Submission__c,
                               Amount__c       
                          FROM Offer__c
                          WHERE Opportunity__c = :opportunityId]) {
                            
      offers.add(off);
      
      fundingAmountHigh = (fundingAmountHigh < off.Amount__c) ? off.Amount__c : fundingAmountHigh;
      paybackHigh = (paybackHigh < off.Payback_Amt__c) ? off.Payback_Amt__c : paybackHigh;
      termsHigh = (termsHigh < off.Term_Months__c) ? off.Term_Months__c : termsHigh;
      holdbackHigh = (holdbackHigh < off.Holdback__c) ? off.Holdback__c : holdbackHigh;
      paymentAmountHigh = (paymentAmountHigh < off.Payment_Amt__c) ? off.Payment_Amt__c : paymentAmountHigh;
      rateHigh = (rateHigh < off.Rate__c) ? off.Rate__c : rateHigh;
      
      fundingAmountLow = (fundingAmountLow > off.Amount__c) ? off.Amount__c : fundingAmountLow;
      paybackLow = (paybackLow > off.Payback_Amt__c) ? off.Payback_Amt__c : paybackLow;
      termsLow = (termsLow > off.Term_Months__c) ? off.Term_Months__c : termsLow;
      holdbackLow = (holdbackLow > off.Holdback__c) ? off.Holdback__c : holdbackLow;
      paymentAmountLow = (paymentAmountLow > off.Payment_Amt__c) ? off.Payment_Amt__c : paymentAmountLow;
      rateLow = (rateLow > off.Rate__c) ? off.Rate__c : rateLow;          
    }                
                
    sanitizeTotals();
    
    for (Integer i = 0; i < offers.size(); i++) {
      containers.add(new Container(offers[i], i));
    }
                
    
    return containers;    
    
    //return offers;
  }  
  
  public void newOffer() {
    
    newOffers.add(new Offer__c(Opportunity__c = opportunityId));
  }  
    

  public void refresh() {

    recordToDelete = null;
    editAll = false;
    newOffers = new Offer__c[] {};
    resetTotals();
  }

  public void saveAll() {
  
    /*
    Offer__c[] recordsToUpdate = new Offer__c[] {};
    
    for (Offer__c record :offers) {
      
      if (MCARecordValidator.isRecordValid(record)) {
        recordsToUpdate.add(record);
      }  
    }
    */
    upsert offers; 

    refresh();
  }
  
  public void editAll() {
  	refresh();
    editAll = true;
  }  
  
  public void deleteOffer() {
  
    if (recordToDelete != null) {
      Offer__c record = [SELECT Id FROM Offer__c WHERE Id = :recordToDelete];
      delete record;
    }
  }    
  
  public void removeOffer() {
  
    if (indexToRemove != null) {
      
      Container c = null;
      
      for (Container element :containers) {
        
        if (element.index == indexToRemove) {
          c = element;
        }
      }
      
      //containers.remove(c.index);
      newOffers.remove(c.index);
    }
  
  }  
  
  private void resetTotals() {
  
     fundingAmountHigh = 0;
     fundingAmountLow = 999999999;
    
     paybackHigh = 0;
     paybackLow = 999999999;
    
     rateHigh = 0;
     rateLow = 999999999;
    
     termsHigh = 0;
     termsLow = 999999999;
    
     holdbackHigh = 0;
     holdbackLow = 999999999;
    
     paymentAmountHigh = 0;
     paymentAmountLow = 999999999;    
  }  

  private void sanitizeTotals() {
  
     fundingAmountLow = fundingAmountLow == 999999999 ? 0 : fundingAmountLow;
  
     paybackLow = paybackLow == 999999999 ? 0 : paybackLow;
 
     rateLow = rateLow == 999999999 ? 0 : rateLow;
    
     termsLow = termsLow == 999999999 ? 0 :termsLow;
    
     holdbackLow = holdbackLow == 999999999 ? 0 :holdbackLow;
    
     paymentAmountLow = paymentAmountLow == 999999999 ? 0 : paymentAmountLow;    
  }  
  
  public class Container {
  
    public Offer__c offer {get;set;}
    public Integer index {get;set;}
  
    public Container(Offer__c instance, Integer index) {
      offer = instance;
      this.index = index;
    }
  
  }  

}