MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_Requested__c</fullName>
        <label>Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_Requested__c</fullName>
        <inlineHelpText># of months requested by the merchant</inlineHelpText>
        <label>Term Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

MCA App/Release - Imperial Advance/Imperial Advance-1.4/src/classes/LoanCalculatorControllerTest.cls
/**
 * Test class for LoanCalculatorController
 * 
 */
@isTest
private class LoanCalculatorControllerTest {

    static testmethod void testCallout() {
       
        // Set mock callout class 
        
        Opportunity  opp = new Opportunity (Name = 'Test Opp',Amount_Requested__c = 10000, Term_Requested__c = 12,
        									StageName= 'Prospecting', CloseDate = system.today());
        insert opp;

        test.startTest();
        	
        	PageReference pageRef = Page.LoanCalculator;
       		pageRef.getParameters().put('id', opp.Id);
       		test.setCurrentPageReference(pageRef);
       		
       		// Call method to test.
	        // This causes a fake response to be sent
	        // from the class that implements HttpCalloutMock. 
       		Test.setMock(HttpCalloutMock.class, new LoanCalculatorMockCallout());
       		ApexPages.StandardController sc = new ApexPages.StandardController(opp);
       		new LoanCalculatorController(sc);
       		
         test.stopTest();
    }
}