MCA App/Release/MCA Demo org/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the User Id of sales Rep</description>
        <inlineHelpText>Holds the User Id of sales Rep</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCA App/Release/MCA Demo org/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Funding Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <description>The Pick list field is refereed in Offers Grid</description>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Chosen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFFR-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Funding_Amount__c</fullName>
        <label>Funded $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <inlineHelpText>The specific amount of the individual payments that the merchant will have to pay to repay the loan. Per the term of the loan. This field correlates with the PMT Schedule field.</inlineHelpText>
        <label>PMT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Opportunity.object
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCA App/Release/MCA Demo org/src/objects/Payable__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Needs Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid - Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Clarification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Provider Pmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>PAYB-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c - Receivable_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_From_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receivables</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Syndication__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Syndication</relationshipLabel>
        <relationshipName>Syndication</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Syndication</label>
    <nameField>
        <displayFormat>SYND-{00000}</displayFormat>
        <label>Syndication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Syndications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/classes/CreateContractControllerTest.cls
public with sharing class CreateContractControllerTest {
    static testMethod void testStatisticsDataForOpportunity() {
        //create Account
        Account objAccount = new Account(Name='TestAcc', Type='Analyst', Industry='Energy');
        insert objAccount; 
        
        //Create Opportunity
        Opportunity objOppo = new Opportunity(Name='TestOpp', AccountId=objAccount.Id, CloseDate = System.today(), StageName='Prospecting', payment_Amount__c = 100, Funding_Amount__c =50);
        insert objOppo; 
        Opportunity opp = [select OwnerId from Opportunity where id=: objOppo.Id];
        system.debug('###objOppo.OwnerId'+opp.OwnerId);
        objAccount.User__c = opp.OwnerId;
        update objAccount;
        system.debug('###objAccount'+objAccount);
        //Create Programme 
        Program__c objProgramme = new Program__c(Name='Test Programme');
        insert objProgramme;
        
        //create submission
        Submission__c objSubmission = new Submission__c(Opportunity__c=objOppo.Id, Status__c='UW',Program__c=objProgramme.Id);
        insert objSubmission;
        
        // Create offer related to Opportunity
        Offer__c objoffer1 = new Offer__c(Opportunity__c=objOppo.Id, Submission__c=objSubmission.Id);
        insert objoffer1;
        
        Offer__c objoffer2 = new Offer__c( Opportunity__c=objOppo.Id, Submission__c=objSubmission.Id);
        insert objoffer2;
        
        //create Receivables related to Opportunity
        Receivable__c objInvoice = new Receivable__c(Amount__c=200.00, Status__c='Open', Due_From_Account__c = objAccount.Id, Opportunity__c=objOppo.Id);
        insert objInvoice;
        
        //create Payable related to Opportunity
        Payable__c objBill = new Payable__c(Account__c=objAccount.Id, Status__c = 'Open - Ready to Pay', Amount_Due__c=1000.00, Opportunity__c=objOppo.Id );
        insert objBill;
        
       
        Opportunity objOppo1 = new Opportunity(Name='TestOpp', AccountId=objAccount.Id, CloseDate = System.today(), StageName='Prospecting', payment_Amount__c = 100, Funding_Amount__c =50);
        insert objOppo1;
        
         // Create Contract
        Contract contract = new Contract(AccountId=objAccount.Id,Status='Draft',ContractTerm = 2, Opportunity__c = objOppo1.Id);
        insert contract;
        
        Test.startTest();
         Apexpages.Pagereference P = Page.CreateContract;
         test.setCurrentPage(p);
        
    
        p.getParameters().put('Id',objOppo1.Id);
        p.getParameters().put('stage',objOppo1.StageName);
        p.getParameters().put('accId',objOppo1.AccountId);
       
        CreateContractController controller=new CreateContractController();
        controller.OppId = ''+objOppo.Id;
        controller.objOpp = objOppo;
        
        controller.populateData();
        System.assertequals(controller.wizardType,CreateContractController.OFFER_SCREEN);
        controller.wizardType='Offer';
        controller.next();
        System.assertequals(controller.wizardType,CreateContractController.DEAL_SCREEN);
        controller.next();
         
        Receivable__c objreceivable = new Receivable__c();
        objreceivable.Type__c = 'Bonus';
        objreceivable.Amount__c =2000;
        objreceivable.Payback_Funded__c = 'Funded';
        objreceivable.Due_From_Account__c = objAccount.Id;
        controller.objOpp = objOppo;
        controller.receivable = objreceivable;
        controller.receivableList.add(objreceivable);
        controller.quickSaveReceivable();
        controller.onChangeRecPercentage();
        controller.onChangeRecPaybackFunded();
        system.debug(controller.receivableList);
        System.assertequals(1,controller.receivableList.size());
         
        Payable__c objPayable = new Payable__c();
        objPayable.Type__c='Bonus';
        objPayable.Amount_Due__c = 100;
        objPayable.Account__c = objAccount.Id;
        objPayable.Payback_Funded__c = 'Funded';
        controller.payable = objPayable;
        controller.payableList.add(objPayable);
        controller.quickSavePayable();
        controller.onChangePayPercentage();
        controller.onChangePayPaybackFunded();
        System.assertequals(1,controller.payableList.size());
        
        Syndication__c objSynd = new Syndication__c();
        objSynd.Syndication_Amt__c = 1000;
        objSynd.Servicing_Fee__c = 2500;
        objSynd.Syndicated_By__c = objAccount.Id;
        controller.syndication = objSynd;
        controller.syndicationList.add(objSynd);
        controller.quickSaveSyndication();
        System.assertequals(1,controller.syndicationList.size());
        
        Contract objContract = new Contract();
        controller.OppId = ''+objOppo.Id;
        controller.objOpp = objOppo;
        controller.AccountId = ''+ objAccount.Id;
        controller.save();
        
        controller.changeWizard();
        PageReference cancelPageRef = controller.cancel();
        System.assertEquals(cancelPageRef.getUrl(), '/'+objOppo.Id);
        
        controller.addRowOffer();
        System.assertEquals(3,controller.offerWrapperList.size());
        
        controller.addRowReceivable();
        System.assertEquals(2,controller.receivableList.size());
        Receivable__c objreceivable1 = new Receivable__c();
        objreceivable1.Type__c = 'Bonus';
        objreceivable1.Amount__c =2000;
        objreceivable1.Payback_Funded__c = 'Funded';
        objreceivable1.Due_From_Account__c = objAccount.Id;
        controller.objOpp = objOppo;
        controller.receivableList.add(objreceivable1);
        controller.wizardType = CreateContractController.RECEIVABLE_SCREEN;
        controller.next();
         
        controller.addRowPayable();
        System.assertEquals(2,controller.payableList.size());
        Payable__c objPayable1 = new Payable__c();
        objPayable1.Type__c='Bonus';
        objPayable1.Amount_Due__c = 100;
        objPayable1.Account__c = objAccount.Id;
        objPayable1.Payback_Funded__c = 'Funded';
        controller.payable = objPayable;
        controller.payableList.add(objPayable1);
        controller.wizardType = CreateContractController.PAYABLE_SCREEN;
        controller.next();
         
        controller.addRowSyndication();
        Syndication__c objSynd1 = new Syndication__c();
        objSynd1.Syndication_Amt__c = 1000;
        objSynd1.Servicing_Fee__c = 2500;
        objSynd1.Syndicated_By__c = objAccount.Id;
        controller.syndicationList.add(objSynd1);
        controller.wizardType = CreateContractController.SYNDICATION_SCREEN;
        controller.next();
        controller.previous();
        controller.wizardType = CreateContractController.SYNDICATION_SCREEN;
        controller.previous();
        controller.wizardType = CreateContractController.PAYABLE_SCREEN;
        controller.previous();
        controller.wizardType = CreateContractController.RECEIVABLE_SCREEN;
        controller.previous();
        controller.wizardType = CreateContractController.DEAL_SCREEN;
        controller.previous();
        
        controller.rowNum = 2;
        PageReference pageRef = Page.CreateContract;
        pageRef.getParameters().put('index','2');
        ApexPages.currentPage().getParameters().put('index','2');
        controller.deleteOffer();
        controller.deletPayables();
        controller.deletReceivables();
        controller.deletSyndications();
        System.currentPagereference().getParameters().put('Id',objOppo.Id);
        System.currentPagereference().getParameters().put('offerId',objoffer2.Id);
        controller.prevOfferid = objoffer2.Id;
        controller.selectedOffer();
        
        /*Opportunity objOppo1 = new Opportunity(Name='TestOpp', AccountId=objAccount.Id, CloseDate = System.today(), StageName='Prospecting', payment_Amount__c = 100, Funding_Amount__c =50);
        insert objOppo1;
        
         Apexpages.Pagereference P = Page.CreateContract;
         test.setCurrentPage(p);
        
    
        p.getParameters().put('Id',objOppo1.Id);
        p.getParameters().put('stage',objOppo1.StageName);
        p.getParameters().put('accId',objOppo1.AccountId);*/
       
        Submission__c objSubmission1 = new Submission__c(Opportunity__c=objOppo1.Id, Status__c='UW');
        insert objSubmission1;
        Offer__c objoffer3 = new Offer__c(Opportunity__c=objOppo1.Id, Submission__c=objSubmission1.Id);
        insert objoffer3;
       
        controller.OppId = ''+objOppo1.Id;
        controller.objOpp = objOppo1;
        controller.populateData();
        System.currentPagereference().getParameters().put('Id',objOppo.Id);
        System.currentPagereference().getParameters().put('offerId','');
        controller.selectedOffer();
        
        controller.wizardType = 'Preview';
        controller.changeWizard();
        Test.stopTest();
        
    }
}