MCA App/Release/MCA Demo org/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Funding Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Buy_Rate__c</fullName>
        <label>Buy Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commi__c</fullName>
        <label>Commi$</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commi_per__c</fullName>
        <label>Commi%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expected__c</fullName>
        <label>Expected %</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Holdback__c</fullName>
        <label>Holdback%</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Commi__c</fullName>
        <description>The field is referenced in Offers grid on Opportunity</description>
        <label>Max Commi%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Origination_fee__c</fullName>
        <description>It is for Origination fee currency storage.</description>
        <inlineHelpText>It is for Origination fee currency storage.</inlineHelpText>
        <label>Origination Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PMT_Schedule__c</fullName>
        <label>PMT Schedule</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twice a week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payback_Amt__c</fullName>
        <formula>Amount__c *  Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payback Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <description>The Pick list field is refereed in Offers Grid</description>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Amt__c</fullName>
        <label>Payment Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referral_Payout__c</fullName>
        <label>Referral Payout%</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Chosen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <label>Term (Months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFFR-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Origination_Fee__c</fullName>
        <label>Origination Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_Months__c</fullName>
        <label>Term (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Opportunity.object
    <fields>
        <fullName>Buy_Rate__c</fullName>
        <label>Buy Rate</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>

MCA App/Release/MCA Dev Org/src/objects/Opportunity.object
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA App/Release/MCA Demo org/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Demo org/src/classes/MCAOffersTabController.cls
public with sharing class MCAOffersTabController {

  public Offer__c[] offers;
  public Container[] containers;
  public Opportunity opportunity{get; set;}

  public Offer__c[] newOffers {get; set;}

  public Boolean editAll {get;set;}

  public Id recordToDelete {get;set;}
  public Integer indexToRemove {get;set;}

  private Id opportunityId;

  public Decimal fundingAmountHigh {get; set;}
  public Decimal fundingAmountLow {get; set;}

  public Decimal paybackHigh {get; set;}
  public Decimal paybackLow {get; set;}

  public Decimal rateHigh {get; set;}
  public Decimal rateLow {get; set;}
  
  public Decimal originationFeeHigh {get; set;}
  public Decimal originationFeeLow {get; set;}

  public Decimal termsHigh {get; set;}
  public Decimal termsLow {get; set;}

  public Decimal holdbackHigh {get; set;}
  public Decimal holdbackLow {get; set;}

  public Decimal paymentAmountHigh {get; set;}
  public Decimal paymentAmountLow {get; set;}
  
  public List<Submission__c> submissionlist {get; Set;}
  public Integer subSize {get; set;}
  public Integer offerSize {get; set;}


  public MCAOffersTabController() {

    opportunityId = Apexpages.currentPage().getParameters().get('id');
    opportunity = [select Id, Name, StageName, AccountId From Opportunity where Id =: opportunityId];

    refresh();
  }

  //public Offer__c[] getOffers() {
  public Container[] getContainers() {

    resetTotals();

    offers = new Offer__c[] {};
    containers = new Container[] {};

    offers.addAll(newOffers);

    for (Offer__c off :[SELECT
                               Term_Months__c,
                               Status__c,
                               Send__c,
                               Details__c,
                               Rate__c,
                               Payment_Amt__c,
                               Payback_Amt__c,
                               PMT_Schedule__c,
                               Origination_fee__c,
                               Holdback__c,
                               Funder__c,
                               Deal_Type__c,
                               Opportunity__c,
                               Submission__c,
                               Amount__c,
                               Buy_Rate__c,
                               Commi__c,
                               Commi_per__c,
                               Max_Commi__c,
                               Payback_Funded__c,
                               Expected__c,
                               Referral_Payout__c
                          FROM Offer__c
                          WHERE Opportunity__c = :opportunityId]) {

      offers.add(off);

      fundingAmountHigh = (fundingAmountHigh < off.Amount__c) ? off.Amount__c : fundingAmountHigh;
      paybackHigh = (paybackHigh < off.Payback_Amt__c) ? off.Payback_Amt__c : paybackHigh;
      termsHigh = (termsHigh < off.Term_Months__c) ? off.Term_Months__c : termsHigh;
      holdbackHigh = (holdbackHigh < off.Holdback__c) ? off.Holdback__c : holdbackHigh;
      paymentAmountHigh = (paymentAmountHigh < off.Payment_Amt__c) ? off.Payment_Amt__c : paymentAmountHigh;
      rateHigh = (rateHigh < off.Rate__c) ? off.Rate__c : rateHigh;
      originationFeeHigh = (originationFeeHigh < off.Origination_fee__c)? off.Origination_fee__c:originationFeeHigh;
      system.debug('@@@@@@ originationFeeHigh '+off.Origination_fee__c);
      
      
      fundingAmountLow = (fundingAmountLow > off.Amount__c) ? off.Amount__c : fundingAmountLow;
      paybackLow = (paybackLow > off.Payback_Amt__c) ? off.Payback_Amt__c : paybackLow;
      termsLow = (termsLow > off.Term_Months__c) ? off.Term_Months__c : termsLow;
      holdbackLow = (holdbackLow > off.Holdback__c) ? off.Holdback__c : holdbackLow;
      paymentAmountLow = (paymentAmountLow > off.Payment_Amt__c) ? off.Payment_Amt__c : paymentAmountLow;
      rateLow = (rateLow > off.Rate__c) ? off.Rate__c : rateLow;
       originationFeeLow = (originationFeeHigh > off.Origination_fee__c)? off.Origination_fee__c:originationFeeHigh;

    }
    offerSize = offers.size();
    sanitizeTotals();

    for (Integer i = 0; i < offers.size(); i++) {
      containers.add(new Container(offers[i], i));
    }

    getSubmissionNames();
    return containers;

    //return offers;
  }
    public void save(){}
    public List<SelectOption> getSubmissionNames()
    {
      List<SelectOption> options = new List<SelectOption>();
      submissionlist = new List<Submission__c>();
      submissionlist = [Select Id, Name,Funder__c,Funder__r.Name, Status__c FROM Submission__c where Opportunity__c =: opportunityId];
      subSize = submissionlist.size();
      //options.add(new SelectOption('--None--','--None--'));
      for (Integer j=0;j<submissionlist.size();j++)
      {
        String subName = submissionlist[j].Name;
          options.add(new SelectOption(submissionlist[j].Id,submissionlist[j].Funder__r.Name+'-'+submissionlist[j].Status__c+'-('+subName.substring(4,subName.length())+')'));
      }
      return options;
    }
    
  public void newOffer() {

    newOffers.add(new Offer__c(Opportunity__c = opportunityId));
  }


  public void refresh() {

    recordToDelete = null;
    editAll = false;
    newOffers = new Offer__c[] {};
    resetTotals();
  }

  public void saveAllOffers() {

    /*
    Offer__c[] recordsToUpdate = new Offer__c[] {};

    for (Offer__c record :offers) {

      if (MCARecordValidator.isRecordValid(record)) {
        recordsToUpdate.add(record);
      }
    }
    */
     upsert offers;
     
    system.debug('***Enter In Exception111111'+containers[0].offer.holdback__c);
    try{   
        system.debug('***Enter In Exception222222'+offers[0].holdback__c);
        system.debug('***Enter In Exception222222'+offers[0].Payment_Amt__c);
        upsert offers;
        system.debug('***Enter In Exception00000000000****');
    }
    catch(DmlException e){
        system.debug('***Enter In Exception****'+e.getMessage());
        String msg;
        if(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION, There is no submission for this offer')){
        	
        	system.debug('***Enter In Exception 1****');
            msg = 'An Offer cannot be created without a Submission. Please create a Submission record';
        }
        else{
        	system.debug('***Enter In Exception 2****');
            msg = e.getMessage();
        }
        ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.Info,msg));
    }
    refresh();
  }

  public void editAll() {
    refresh();
    editAll = true;
    newOffers = new Offer__c[] {};
    resetTotals();
  }

  public void deleteOffer() {

    if (recordToDelete != null) {
      Offer__c record = [SELECT Id FROM Offer__c WHERE Id = :recordToDelete];
      delete record;
    }
  }

  public void removeOffer() {

    if (indexToRemove != null) {

      Container c = null;

      for (Container element :containers) {

        if (element.index == indexToRemove) {
          c = element;
        }
      }

      //containers.remove(c.index);
      newOffers.remove(c.index);
    }

  }

  private void resetTotals() {

     fundingAmountHigh = 0;
     fundingAmountLow = 999999999;

     paybackHigh = 0;
     paybackLow = 999999999;

     rateHigh = 0;
     rateLow = 999999999;

     termsHigh = 0;
     termsLow = 999999999;

     holdbackHigh = 0;
     holdbackLow = 999999999;

     paymentAmountHigh = 0;
     paymentAmountLow = 999999999;
     
     originationFeeHigh = 0; 
     originationFeeLow = 0;

     
  }

  private void sanitizeTotals() {

     fundingAmountLow = fundingAmountLow == 999999999 ? 0 : fundingAmountLow;

     paybackLow = paybackLow == 999999999 ? 0 : paybackLow;

     rateLow = rateLow == 999999999 ? 0 : rateLow;

     termsLow = termsLow == 999999999 ? 0 :termsLow;

     holdbackLow = holdbackLow == 999999999 ? 0 :holdbackLow;

     paymentAmountLow = paymentAmountLow == 999999999 ? 0 : paymentAmountLow;
     
      originationFeeLow = originationFeeLow == 999999999 ? 0 : originationFeeLow ;
  }

  public class Container {

    public Offer__c offer {get;set;}
    public Integer index {get;set;}

    public Container(Offer__c instance, Integer index) {
      offer = instance;
      this.index = index;
    }

  }

}