DevOrg/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funding_Amount__c</fullName>
        <label>Funded $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payback_Amount__c</fullName>
        <label>Payback $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount__c</fullName>
        <label>Payoff $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

DevOrg/src/objects/Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c - Receivable_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Amount_Used__c</fullName>
        <label>Deal Amount Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_From_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receivables</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsCreatedFromGrid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check-box will identify if receivables are created from Opportunity Grid and if so receivables wont be considered for auto creating parables.</description>
        <label>IsCreatedFromGrid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Percentage of</label>
        <picklist>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Funded Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wizard_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To Identify if Receivable has gone through wizard process</description>
        <label>Wizard Check</label>
        <type>Checkbox</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

DevOrg/src/classes/CCReceivablesService.cls
/*
    A Utility class for Create Contract Controller to handle the mehthods specific to Receivables
*/
public with sharing class CCReceivablesService { 
    
    // method to fetch receivables from DB 
    public static list<Receivable__c> getReceivablesFromDB(Id oppId)
    {
        list<Receivable__c> receivablesListFromDB = [Select Name,
        Memo__c,
        Type__c,
        Status__c,
        Amount__c,
        Due_Date__c,
        Percentage__c,
        Payback_Funded__c,
        Deal_Amount_Used__c,
        Opportunity__c,
        Opportunity__r.Commission_Percentage__c,
        Due_From_Account__c,
        Due_From_Account__r.Commission_Percentage__c,
        Wizard_Check__c,
        Amount_Due__c,
        IsCreatedFromGrid__c
        From Receivable__c
        Where Opportunity__c =: oppId];
        return receivablesListFromDB;
    }
    
    //For checking receivales fields null value
    public static Boolean receivablesFieldsNullValidator(Receivable__c objReceivable){
        if(objReceivable.Type__c == null && objReceivable.Amount__c == null &&
            objReceivable.Percentage__c == null &&
            objReceivable.Payback_Funded__c == null &&
            objReceivable.Deal_Amount_Used__c == null &&
            objReceivable.Due_Date__c == null &&
            objReceivable.Status__c == null && objReceivable.Memo__c == null )
        {
            return true;
        }
        return false;
    }
    
    // to delete receivables
    public static void toDeletReceivables(List<Receivable__c> receivableList,Integer rowNum){
        list<Receivable__c> receivableDelList = new list<Receivable__c>();
        list<UserRecordAccess> UserRecordAccessListNullChk = new list<UserRecordAccess>();
        
        try
        {
            //rowNum = Integer.valueOf(apexpages.currentpage().getparameters().get('index'))+1;
            receivableDelList = CreateContractControllerUtility.deleteForSObject(receivableList,rowNum);
            if(receivableDelList.size()>0)
            {
                delete receivableDelList;
            }
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, MCAExceptionHandlerUtility.getErrorMessage(e)));
        }
    }
    
    public Static void onChangeOfRecPercentage(List<Receivable__c> receivableList, Decimal receivableAmtTotal)
    {
        receivableAmtTotal = 0.00;
        
        for(Receivable__c rec : receivableList)
        {
           
               // if(rec.Deal_Amount_Used__c != null && rec.Percentage__c != null)
                    rec.Amount__c = CreateContractControllerUtility.treateNullAsZero(rec.Deal_Amount_Used__c) * (CreateContractControllerUtility.treateNullAsZero(rec.Percentage__c)/100);
            
        }
        
        if(receivableList.size()>0)
        {
            for(Receivable__c rec:receivableList)
            {
                if(rec.Amount__c!=null)
                    receivableAmtTotal = receivableAmtTotal + rec.Amount__c;
            }
        }
        
    }
    
    public static void onChangeOfRecPaybackFunded(List<Receivable__c> receivableList, Decimal receivableAmtTotal, Opportunity objOpp)
    {
        receivableAmtTotal = 0.00;
        for(Receivable__c rec : receivableList)
        {
                if(rec.Payback_Funded__c == 'Funded' && objOpp.Funding_Amount__c != null)
                    rec.Deal_Amount_Used__c = objOpp.Funding_Amount__c;
                else if(rec.Payback_Funded__c == 'Payback' && objOpp.Payback_Amount__c != null)
                    rec.Deal_Amount_Used__c = objOpp.Payback_Amount__c;
                else if(rec.Payback_Funded__c == 'Net Funded Amount')
                    rec.Deal_Amount_Used__c = CreateContractControllerUtility.treateNullAsZero(objOpp.Funding_Amount__c) - CreateContractControllerUtility.treateNullAsZero(objOpp.Payoff_Amount__c);
               
               if(rec.Payback_Funded__c == null)
                  rec.Deal_Amount_Used__c = 0.00;
               
               rec.Amount__c = CreateContractControllerUtility.treateNullAsZero(rec.Deal_Amount_Used__c) * (CreateContractControllerUtility.treateNullAsZero(rec.Percentage__c)/100);
            
            
        }
        
        if(receivableList.size()>0)
        {
            for(Receivable__c rec:receivableList)
            {
                if(rec.Amount__c!=null)
                receivableAmtTotal = receivableAmtTotal + rec.Amount__c;
            }
        }
        
    }
}