DevOrg/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/src/objects/Syndication__c.object
<CustomObject>
    <fields>
        <fullName>Anticipated_Term_Months__c</fullName>
        <formula>Opportunity__r.Term_Months__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anticipated Term - Months</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Fee__c</fullName>
        <inlineHelpText>Amount paid towards commissions</inlineHelpText>
        <label>Commission Fee $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Funding_Amount__c</fullName>
        <formula>Opportunity__r.Funding_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Funding Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursment_Schedule__c</fullName>
        <label>Disbursement Schedule</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bi-weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Syndication</relationshipLabel>
        <relationshipName>Syndication</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Profit_Amount__c</fullName>
        <formula>Repayment_Amt_Gross__c -  Syndication_Amt__c -  Servicing_Fee__c -  Commission_Fee__c  - ( (Deal_Payback_Amount__c *  Syndication_per__c)* Syndication_Percentage__c   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profit $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ROR_per__c</fullName>
        <formula>IF(Syndication_Amt__c &gt; 0 , 
 Profit_Amount__c /  Syndication_Amt__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ROR %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Repayment_Amt__c</fullName>
        <formula>( Deal_Payback_Amount__c *  Syndication_per__c  ) -   Servicing_Fee__c -  Commission_Fee__c - ( (Deal_Payback_Amount__c *  Syndication_per__c)* Syndication_Percentage__c   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repayment Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Servicing_Bank__c</fullName>
        <formula>Opportunity__r.Bank_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicing Bank</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Syndicated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The entity that is participating on the deal</inlineHelpText>
        <label>Syndicated By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Syndication</relationshipLabel>
        <relationshipName>Syndication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Syndication_Amt__c</fullName>
        <inlineHelpText>Participation amount</inlineHelpText>
        <label>Syndication Amt $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Syndication_Percentage__c</fullName>
        <label>Syndication Fee %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Syndication</label>
    <nameField>
        <displayFormat>SYND-{00000}</displayFormat>
        <label>Syndication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Syndications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOrg/src/classes/CCSyndicationsService.cls
/*
    A Utility class for Create Contract Controller to handle the mehthods specific to syndications
*/
public with sharing class CCSyndicationsService { 
    
    // method to fetch syndications from DB
    public static list<Syndication__c> getSyndicationFromDB(Id oppId)
    {
        list<Syndication__c> syndicationListFromDB = [Select Name,
        Commission_Fee__c,
        ROR_per__c,
        Disbursment_Schedule__c,
        Servicing_Bank__c,
        Opportunity__c,
        Anticipated_Term_Months__c,
        Syndication_Amt__c,
        Deal_Funding_Amount__c,
        Syndication_Percentage__c,
        Profit_Amount__c,
        Syndicated_By__c,
        Repayment_Amt__c,
        Memo__c
        From Syndication__c
        Where Opportunity__c =: OppId ];
        return syndicationListFromDB;
    }
    
    //For checking Syndication fields null value
    public static Boolean syndicationFieldsNullValidator(Syndication__c objSyndication)
    {
        if(objSyndication.Syndication_Amt__c == null &&
            objSyndication.Commission_Fee__c == null &&
            objSyndication.Deal_Funding_Amount__c == null &&
            objSyndication.Servicing_Bank__c == null &&
            objSyndication.Syndication_Percentage__c == null &&
            objSyndication.Profit_Amount__c == null &&
            objSyndication.Anticipated_Term_Months__c == null &&
            objSyndication.Disbursment_Schedule__c == null &&
            objSyndication.ROR_per__c == null &&
            objSyndication.Syndicated_By__c == null && objSyndication.Memo__c == null)
        {
            return true;
        }
        return false;
    }
    
    // to delete syndications
    public static void toDeletSyndications(list<Syndication__c> syndicationList,integer rowNum)
    {
        list<Syndication__c> syndicationdelList = new list<Syndication__c>();
        try
        {
            //rowNum = Integer.valueOf(apexpages.currentpage().getparameters().get('index'));
            syndicationdelList = CreateContractControllerUtility.deleteForSObject(syndicationList,rowNum);
            
            if(syndicationdelList.size()>0){
                delete syndicationdelList;
            }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, MCAExceptionHandlerUtility.getErrorMessage(e)));
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,e.getMessage()));
            
        }
    }
}