DevOrg/src/objects/GRIDTabSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>For the Setting related Dynamic GRID.</description>
    <label>GRIDTabSetting</label>
</CustomObject>

MCADevOrg/src/objects/GRIDTabSetting__c.object
    <fields>
        <fullName>Display_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to check if that particular org is given permission to view the tab.</description>
        <label>Display Tab</label>
        <type>Checkbox</type>
    </fields>

DevOrg/src/classes/GRIDHomePageExtension.cls
public with sharing class GRIDHomePageExtension{
    
    
   // declaration
    private final Opportunity oppStd;
    //public Boolean syndDisplayTab                                                       {get; set;}
    public Map<String, GRIDTabSetting__c> tabToSettingMap                                {get; set;}
    // constructor
    public GRIDHomePageExtension(ApexPages.StandardController stdController) {
         this.oppStd = (Opportunity)stdController.getRecord();
         //syndDisplayTab = GRIDTabSetting__c.getValues('Syndications').Display_Tab__c;
         tabToSettingMap = new Map<String, GRIDTabSetting__c> ();
         tabToSettingMap = GRIDTabSetting__c.getAll();
    }

}