DevOrg/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>External_Transaction_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Transaction ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOrg/src/classes/PaymentExternalIdTriggerHelper.cls
public with sharing class PaymentExternalIdTriggerHelper {
	
	public void setExternalId(Payment__c[] newPayments) {
	    Payment__c[] payments = new Payment__c[]{};
		
	    for (Payment__c p : newPayments) {
	        
	        if (p.Id != null) {
	        	Payment__c aux = new Payment__c(Id = p.Id);
	            string id = string.valueOf(aux.id);
	            String idDate = String.valueOf(Date.today().month()) + String.valueOf(Date.today().day()) + String.valueOf(Date.today().year()).substring(2,4);
	            aux.External_Transaction_ID__c = 'T' + idDate + id.substring((18 - (11 - (idDate.length()))),18);
	            payments.add(aux);
	        }
	    }

	    RunningBalanceTriggerHelper.preventUpdate = true;
	    update payments;
	    RunningBalanceTriggerHelper.preventUpdate = false;		
	}
}