CMBSandbox4/src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <inlineHelpText>How is budgeting done for this project?</inlineHelpText>
        <label>Budget</label>
        <picklist>
            <picklistValues>
                <fullName>No budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total project hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total project fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours per task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours per person</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectHourlyRate__c</fullName>
        <inlineHelpText>If this is a billable by a project hourly rate, what is the rate?  Leave blank otherwise.</inlineHelpText>
        <label>Project Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/HarvestTimeEntry__c.object
<CustomObject>
    <description>Time entries mirrored in Harvest using Harvest2Salesforce Connect.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>Date of time entry if tracking time by duration vs. start and end time.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>Duration of time in decimal format.  Eg., 2.75 = 2 hours and 45 minutes.</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HarvestProject__c</fullName>
        <inlineHelpText>Project time is related to.</inlineHelpText>
        <label>HarvestProject</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>HarvestTimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Sent_to_Client__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Sent to Client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Description of time / notes</inlineHelpText>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <inlineHelpText>Type of time.  These values are maintained in Harvest and are one-way Harvest--&gt;SFDC.</inlineHelpText>
        <label>Task Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{YYYY}-{MM}-{0}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <label>Date Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_On_Invoice__c</fullName>
        <inlineHelpText>This will be displayed on the invoice</inlineHelpText>
        <label>Description (On Invoice)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description (Internal)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Invoices1</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Not Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - PM Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - HA Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Pending Credit &amp; Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Pending Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved &amp; Ready to Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent - Partially Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Updated_Contractor_Hours__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated Contractor Hours</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of time / notes</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HarvestProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours_Num__c</fullName>
        <label>Hours (#)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes (Don&apos;t Use)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Harvest__c</fullName>
        <formula>Time_Entry__r.HarvestProject__r.Name</formula>
        <inlineHelpText>Formula field. This reads from the time entry project.</inlineHelpText>
        <label>Project (Harvest) OLD-FORMULA</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <formula>IF(
CONTAINS(Task_Type__c,&quot;Non-Billable&quot;),0,
IF( 
Rate_Override__c &gt;0,Rate_Override__c, 
Invoice__r.Rate__c
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Task_Harvest__c</fullName>
        <description>This will be to import that tasks from harvest.</description>
        <label>Task (Harvest)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Entry</label>
        <referenceTo>HarvestTimeEntry__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Merging_Time_Entry_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Setting Contains Task Type for which the Line Items have to be merged</description>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Merging Time Entry Setting</label>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

MCAPackagingOrg/src/objects/Opportunity.object
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>

CMBSandbox4/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Bill/Invoice Status</label>
</CustomObject>

CMBSandbox4/src/classes/InvoiceHandlerTest.cls
/**
 * Description - Test Class for InvoiceHandler
 *
 * Date - 05/02/2014 
 * 
 * Created by- Sneha P.
 */
@isTest
private class InvoiceHandlerTest {

    static testMethod void myUnitTest() {
        Merging_Time_Entry_Setting__c mergeSetting = new Merging_Time_Entry_Setting__c(Name = 'Test',
                                                                        Task_Type__c = 'TestTaskType');
        insert mergeSetting;
        
        Account Acc = new Account(Name = 'Test Account');
        insert Acc;
        
        Opportunity opp = new Opportunity(Name='Test opp', AccountId = Acc.Id, StageName= 'Prospecting',
                                          CloseDate=system.today() );
        insert opp;
        
        HarvestProject__c project = new HarvestProject__c(Name = 'Test Project' ,Account__c = Acc.Id,
                                                         Budget__c = 'No Budget', Opportunity__c = opp.Id,
                                                         ProjectHourlyRate__c = 400);
        insert project;
        
        //Create 2 Time Entries which will be merged
        HarvestTimeEntry__c timeEntry1 = new HarvestTimeEntry__c(HarvestProject__c = project.Id, 
                                                                Task_Type__c = 'TestTaskType',
                                                                Duration__c = 3,
                                                                Date__c = system.today(),
                                                                Notes__c = 'Worked on ApexPage 1');
        insert timeEntry1;
                                                                
        HarvestTimeEntry__c timeEntry2 = new HarvestTimeEntry__c(HarvestProject__c = project.Id, 
                                                                Task_Type__c = 'TestTaskType',
                                                                Duration__c = 6,
                                                                Date__c = system.today(),
                                                                Notes__c = 'Worked on ApexPage 2');
        insert timeEntry2;
                                                                
        HarvestProject__c project1 = new HarvestProject__c(Name = 'Test Project1' ,Account__c = Acc.Id,
                                                         Budget__c = 'No Budget1', Opportunity__c = opp.Id,
                                                         ProjectHourlyRate__c = 500);
        insert project1;
        
        //Create 10 Time Entries for both project 
        createTimeEntry(project,10);
        createTimeEntry(project1,10);
        
        //Create Invoice and Line Items for Project        
            
            Invoice__c invoice = createInvoice(project);
            insert invoice;
            //Insert all the Line Items
            insert createLineItems(project.Id,invoice);
        //End
        
        //Create Invoice and Line Items for Project1
            Invoice__c invoice1 = createInvoice(project1);
            insert invoice1;
            
            //Insert all the Line Items
            insert createLineItems(project1.Id,invoice1);
        //End
           Invoice__c invoice2 = createInvoice(project);
            insert invoice2;
         
            Line_Item__c objLineItem= new Line_Item__c();
            objLineItem.Invoice__c =  invoice2.Id;
            objLineItem.Opportunity__c = project1.Opportunity__c;
            objLineItem.Description__c = 'test';
            insert objLineItem;
            
            Line_Item__c objLineItem1= new Line_Item__c();
            objLineItem1.Invoice__c =  invoice2.Id;
            objLineItem1.Opportunity__c = project1.Opportunity__c;
            objLineItem1.Description__c = 'test';
            insert objLineItem1;
            
          test.startTest();
            list<Invoice__c> invoiceList = new list<Invoice__c>();
            //update the invoice to sent
            invoice.Updated_Contractor_Hours__c = true;
            invoice.Status__c = InvoiceHandler.STATUS_SENT;
            invoice.Date_Sent__c = system.today();
            invoiceList.add(invoice);
            
            invoice1.Updated_Contractor_Hours__c = true;
            invoice1.Status__c = InvoiceHandler.STATUS_SENT;
            invoice1.Date_Sent__c = system.today();
            invoiceList.add(invoice1);
            //Update both the Invoice to Sent and check if the Time Entries are updated
            update invoiceList;
            
            //Query Time Entries and check if Invoice Sent to client is checked
            for (HarvestTimeEntry__c timeEntries : [Select Invoice_Sent_to_Client__c 
                                                  from HarvestTimeEntry__c where HarvestProject__c =: project.Id
                                                   or HarvestProject__c =: project1.Id]){
                //system.assert(timeEntries.Invoice_Sent_to_Client__c == false);
            }
            try{
              invoice2.Override__c=false;
              update invoice2;  
              delete invoice2;
              delete invoiceList;
            }
            catch(DmlException e)
            {
              /*System.assertequals('CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY' , 
                                 e.getDmlStatusCode(0));*/
            }
        test.stopTest();
    }
    
    public static void createTimeEntry(HarvestProject__c project,Integer cnt){
        list<HarvestTimeEntry__c> timeEntryList = new list<HarvestTimeEntry__c>();
        HarvestTimeEntry__c timeEntry ;
        for(Integer i = 0 ;i < cnt; i++  ){
            timeEntry = new HarvestTimeEntry__c(HarvestProject__c = project.Id, 
                                                Task_Type__c = 'TestTaskType'+cnt,
                                                Duration__c = 3+cnt,
                                                Date__c = system.today(),
                                                Notes__c = 'Worked on ApexPage'+cnt);
            timeEntryList.add(timeEntry);
        }
        insert timeEntryList;
        
    }
    
    public static Invoice__c createInvoice(HarvestProject__c project){
        Invoice__c invoice = new Invoice__c(Account__c = project.Account__c,
                                            Opportunity__c = project.Opportunity__c,
                                            Project_Harvest__c = project.id,
                                            Status__c = 'Open',
                                            Invoice_Type__c = 'Hours',
                                            Rate__c = project.ProjectHourlyRate__c,
                                            Description_On_Invoice__c = project.Name,
                                            Description__c = project.Name,
                                            Override__c = true);
        return invoice; 
    }
    
    public static list<Line_Item__c> createLineItems(Id projectId,Invoice__c invoice ){
        
        list<Line_Item__c> lineItemList = new list<Line_Item__c>();
        Line_Item__c lineItem;
        
        for(HarvestTimeEntry__c  timeEntry : [Select Task_Type__c,Notes__c,Date__c,Duration__c 
                                              from HarvestTimeEntry__c where HarvestProject__c =: projectId]){
            lineItem = new Line_Item__c(Task_Type__c = timeEntry.Task_Type__c,
                                                     Task_Harvest__c = timeEntry.Task_Type__c,
                                                     Invoice__c =  invoice.Id,
                                                     Time_Entry__c = timeEntry.Id,
                                                     Opportunity__c = invoice.Opportunity__c,
                                                     Description__c = timeEntry.Notes__c,
                                                     Date__c = timeEntry.Date__c,
                                                     Hours_Num__c = timeEntry.Duration__c
                                                      );
            lineItemList.add(lineItem); 
        }
        return lineItemList;    
    }
}