CMBSandbox4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Total_30_Days_Past_Due__c</fullName>
        <description>To calculate amount due from invoices per account for last 30 days.</description>
        <inlineHelpText>To calculate amount due from invoices per account for last 30 days.</inlineHelpText>
        <label>30 Days Past Due $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

CMBSandbox4/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>HarvestProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

CMBSandbox4/src/classes/InvoiceRollupAmountBatchTest.cls
/*
* Version       Date             Author         Description
*   1.0         05/10/2015       Ashwini S      Test class for Roll up on Account (Total_30_Days_Past_Due__c) from Invoice on daily basis   
*
*/
@isTest
private class InvoiceRollupAmountBatchTest {

    static testMethod void invoiceRollupAmountBatchTest() {
        //insert account record
        List<Account> listAccounts = TestUtility.getAccountRecords(1);
        insert listAccounts;
        
        List<Contact> listContacts = TestUtility.getContactRecords(1, listAccounts[0].Id);
        insert listContacts;
        System.assertNotEquals(Null, listContacts.size());
        
        //insert opportunity record
        List<Opportunity> listOpportunity = TestUtility.getOpportunityRecords(1, listAccounts[0].Id);
        insert listOpportunity;
        System.assertEquals(listAccounts[0].Id, listOpportunity[0].AccountId);
        
         List<Invoice__c> listInvoice = TestUtility.getInvoiceRecords(6,
                                listAccounts[0].Id, listContacts[0].Id, listOpportunity[0].Id);
        CheckRecursive.runAfter = true;                            
        insert listInvoice;
        System.assertNotEquals(Null, listInvoice[0].Id);
        
        
        list<HarvestProject__c> harvestProjectList = TestUtility.insertHarvestProjects(5,listOpportunity[0].Id,
        listAccounts[0].Id, listContacts[0].Id);
        insert harvestProjectList;
        
        for(Integer invoiceCount = 1; invoiceCount <= listInvoice.size(); invoiceCount++){
        List<Line_Item__c> listInvoiceLineItem = TestUtility.getInvoiceLineItemRecords(2,
                                 listOpportunity[0].Id,listInvoice[invoiceCount-1].Id, harvestProjectList[0].Id);
        CheckRecursive.runAfter = true;
        insert listInvoiceLineItem;
        }
         Test.startTest();
           string batch1= SchedulerQueryGenenrator.queryFetch(0);
           Database.executeBatch(new InvoiceRollupAmountonAccountBatch(0,batch1));
           string batch2= SchedulerQueryGenenrator.queryFetch(30);
           Database.executeBatch(new InvoiceRollupAmountonAccountBatch(30,batch2));
           string batch3= SchedulerQueryGenenrator.queryFetch(90);
           Database.executeBatch(new InvoiceRollupAmountonAccountBatch(90,batch3));
           string batch4= SchedulerQueryGenenrator.queryFetch(60);
           Database.executeBatch(new InvoiceRollupAmountonAccountBatch(60,batch4));
         Test.stopTest();
    }
}