CMBSandbox4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Billing Contact)</relationshipLabel>
        <relationshipName>BillingContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

CMBSandbox4/src/objects/Bill__c.object
<CustomObject>
    <description>This is for vendor bills</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Products &amp; Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Salary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Invoice - No Time Entries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Invoice - With Time Entries</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer (Not SFDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tip_of_The_Week__c</fullName>
        <label>Tip of The Week</label>
        <picklist>
            <picklistValues>
                <fullName>Added - Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Added - Hibernate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed by Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed by CMB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed - Vendor Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed - Client Competitor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description (Internal)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project(1)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of time / notes</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project (OLD)</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <formula>IF(
CONTAINS(Task_Type__c,&quot;Non-Billable&quot;),0,
IF( 
Rate_Override__c &gt;0,Rate_Override__c, 
Invoice__r.Rate__c
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project  look up from  change order</description>
        <inlineHelpText>Project  look up from  change order</inlineHelpText>
        <label>Project</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

MCAPackagingOrg/src/objects/Opportunity.object
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

CMBSandbox4/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects(1)</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Project(1)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects(1)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bluewolf SFMTA/src/objects/Project__c.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Construction Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Event</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

CMBSandbox4/src/objects/Transaction__c.object
<CustomObject>
    <description>This object is to record all revenue and expenses. There will be a status to deferentiate revenue and expenses. This should help with the accounting side of the business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Exp - Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exp - Hourly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exp - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exp - Pmt to Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev - Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev - Hourly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev - Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exp - Loan Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exp - Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>Revenue and other incoming funds</description>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Debit</fullName>
        <active>true</active>
        <description>For expenses and other debits</description>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Transaction__c.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>

CMBSandbox4/src/classes/TestTransactionController.cls
/**
 */
@isTest
public class TestTransactionController {

	public static final String INV_DUE_AMT_LESS_THAN_CRED_AMT_PAID	= 'Transaction Amount Exceeds Invoice Due Amount';
	
	static Id prepareTestData(){
		//Common data
		List<RecordType> recordTypes = [select Id, Name FROM RecordType Where Name='Debit' OR Name='Credit'];
		Map<String, Id> mapTransRecordTypes = new Map<String, Id>();
		for(RecordType objRecordType : recordTypes){
			mapTransRecordTypes.put(objRecordType.Name, objRecordType.Id);
		}
		
		Account objAccount = new Account(Name='Test', Type='Analyst', Sub_Type__c='Test', Industry='Energy');
		insert objAccount; 
		
		
		Contact objContact = new Contact(LastName='Last', AccountId = objAccount.Id, Contact_Type__c = 'Customer', Tip_of_The_Week__c='Added - Active');
		insert objContact;
		
		Opportunity objOpp = new Opportunity(Name='Opp1', AccountId=objAccount.Id, CloseDate = System.today(), StageName='Prospecting', ForecastCategoryName='Pipeline' );
		insert objOpp;
		
		Project__c objProject = new Project__c(Name='Test Project', Phase__c='1', Opportunity__c = objOpp.Id);
		insert objProject;
		
		Invoice__c objInvoice = new Invoice__c(Invoice_Type__c='Hours', Rate__c=20.00, 	Description__c='test desc', Account__c=objAccount.Id, Billing_Contact__c=objContact.Id, Opportunity__c=objOpp.Id, 	Project__c=objProject.Id, Status__c='Open',Updated_Contractor_Hours__c=true);
		insert objInvoice;
		
		Line_Item__c objInvoiceLineItems = new Line_Item__c(Start__c=System.now(), Finish__c = System.now().addMonths(1), Opportunity__c=objOpp.Id, Invoice__c = objInvoice.Id, Description__c ='test', Date__c = system.today(), Credit_Hrs__c=20); 
		insert objInvoiceLineItems;
		
		Transaction__c objTransaction = new Transaction__c(Date__c=System.Today(), Type__c='Rev - Other', status__c='Open', Amt_Non_Hourly__c=20000.00, Pmt_Method__c='Cash',
					 Bank_Depostied__c = 'Visa', Account__c= objAccount.Id, 	Contact__c= objContact.Id, RecordTypeId = mapTransRecordTypes.get('Credit'));
		insert objTransaction;
		
		return objTransaction.Id;
	}
	
	static Id prepareDebitTestData(){
		//Common data
		List<RecordType> recordTypes = [select Id, Name FROM RecordType Where Name='Debit' OR Name='Credit'];
		Map<String, Id> mapTransRecordTypes = new Map<String, Id>();
		for(RecordType objRecordType : recordTypes){
			mapTransRecordTypes.put(objRecordType.Name, objRecordType.Id);
		}
		
		Account objAccount = new Account(Name='Test', Type='Analyst', Sub_Type__c='Test', Industry='Energy');
		insert objAccount; 
		
		
		Contact objContact = new Contact(LastName='Last', AccountId = objAccount.Id, Contact_Type__c = 'Customer', Tip_of_The_Week__c='Added - Active');
		insert objContact;
	
		Bill__c objBill = new Bill__c(Name='Bill1', Vendor__c=objAccount.Id, Status__c = 'Open - Ready to Pay', Amount_Due__c=20000.00, Upload_to_SF__c = 'No Need' );
		insert objBill;	
		
		Transaction__c objTransaction = new Transaction__c( Date__c=System.Today(), Type__c='Rev - Other', status__c='Open', Amt_Non_Hourly__c=20000.00, Pmt_Method__c='Cash',
					 Bank_Depostied__c = 'Visa', Account__c= objAccount.Id, 	Contact__c= objContact.Id, RecordTypeId = mapTransRecordTypes.get('Debit'));
		insert objTransaction;
		
		return objTransaction.Id;
	}
	
    static testMethod void testCreditTransaction() {
    	Id objId = prepareTestData();
    	Transaction__c objTransaction = [SELECT Name, Date__c, Type__c, status__c, Amt_Non_Hourly__c, Pmt_Method__c, Bank_Depostied__c, Account__c, Contact__c, RecordTypeId 
    									 FROM Transaction__c 
    									 where Id=:objId limit 1];
    									 
        if( objTransaction != null){
        	PageReference pageRef = Page.Transaction;
        	Test.setCurrentPageReference(pageRef);
        	TransactionController objTransController = new TransactionController(new ApexPages.StandardController(objTransaction));
        	PageReference editPageRef = objTransController.Edit_val();
        	//System.assertEquals(editPageRef.getUrl(), Page.Transaction.getUrl());
        	System.assertEquals(editPageRef.getUrl(), '/'+objTransaction.Id+'/e?retURL=%2F'+objTransaction.Id);
        	
        	//update Transaction
        	objTransaction.Pmt_Method__c = 'Wire';
        	PageReference savePageRef = objTransController.save();
        	System.assertEquals(savePageRef.getUrl(), Page.Transaction.getUrl());
        	
        	PageReference cancelPageRef = objTransController.cancelEdit();
        	System.assertEquals(cancelPageRef.getUrl(), Page.Transaction.getUrl()); 
        	
        	//Create New Transaction Line Items
        	objTransController.createCreditTranscations();  
        		//get all TransactionWrapper and update those
        	objTransController.wrappers = objTransController.getInvoices();
        	objTransController.wrapper = objTransController.wrappers.get(0); 	
        	objTransController.wrapper.cred.Amount__c = 2000.00;
        	objTransController.wrapper.cred.Date__c = System.Today();
        	objTransController.wrapper.cred.Memo__c = 'test';
        	objTransController.wrapper.selected = true;
        	objTransController.processSelected();
        	
        	List<ApexPages.Message> lstMsgs = ApexPages.getMessages(); 
        	if(lstMsgs.size() > 0){
        		System.assertequals(INV_DUE_AMT_LESS_THAN_CRED_AMT_PAID,lstMsgs.get(0).getSummary());
        	}
        	
        	
        	//Create New Transaction Line Items
        	objTransController.createCreditTranscations();  
        	objTransController.totalAmount = 200000.00;
        	objTransController.wrappers = objTransController.getInvoices();
        	objTransController.wrapper = objTransController.wrappers.get(0); 	
        	objTransController.wrapper.cred.Amount__c = 200000.00;
        	objTransController.wrapper.cred.Date__c = System.Today();
        	objTransController.wrapper.cred.Memo__c = 'test';
        	objTransController.wrapper.selected = true;
        	objTransController.processSelected();
        	lstMsgs = ApexPages.getMessages(); 
        	if(lstMsgs.size() > 0){
        		System.assertEquals(Label.TRAN_LINE_ITEM_AMT_EXCEEDS_TRAN_AMT,lstMsgs.get(0).getSummary() );
        	}
        	
			//Create New Transaction Line Items
        	objTransController.createCreditTranscations();  
        	objTransController.totalAmount = null;
        	objTransController.processSelected();
        	lstMsgs = ApexPages.getMessages(); 
        	
        	//CancelCreditTransaction
        	objTransController.cancelCreditTranscations();
        	//objTransController.autoPopulate();
        	objTransController.ClonePage();
        	objTransController.getCurrentDate();
        	
        }
    }
        static testMethod void testDebitTransaction(){
    	Id objId = prepareDebitTestData();
    	Transaction__c objTransaction = [SELECT Name, Date__c, Type__c, status__c, Amt_Non_Hourly__c, Pmt_Method__c, Bank_Depostied__c, Account__c, Contact__c, RecordTypeId 
    									 FROM Transaction__c 
    									 where Id=:objId limit 1];
    									 
        if( objTransaction != null){
        	PageReference pageRef = Page.Transaction;
        	Test.setCurrentPageReference(pageRef);
        	TransactionController objTransController = new TransactionController(new ApexPages.StandardController(objTransaction));
        	PageReference editPageRef = objTransController.Edit_val();
        	//System.assertEquals(editPageRef.getUrl(), Page.Transaction.getUrl());
        	System.assertEquals(editPageRef.getUrl(), '/'+objTransaction.Id+'/e?retURL=%2F'+objTransaction.Id);
        	
        	//update Transaction
        	objTransaction.Pmt_Method__c = 'Wire';
        	PageReference savePageRef = objTransController.save();
        	System.assertEquals(savePageRef.getUrl(), Page.Transaction.getUrl());
        	
        	PageReference cancelPageRef = objTransController.cancelEdit();
        	System.assertEquals(cancelPageRef.getUrl(), Page.Transaction.getUrl()); 
        	
        	
        	//System.assertEquals(resetPageRef.getUrl(), null); 
        	
        	//Create New Transaction Line Items
        	objTransController.createCreditTranscations();  
        		//get all TransactionWrapper and update those
        	objTransController.wrappers = objTransController.getBills();
        	objTransController.wrapper = objTransController.wrappers.get(0); 	
        	objTransController.wrapper.debt.Amount__c = 2000.00;
        	objTransController.wrapper.debt.Date__c = System.Today();
        	objTransController.wrapper.debt.Memo__c = 'test';
        	objTransController.wrapper.selected = true;
        	objTransController.processSelectedDebits();
        	//System.assertequals(Label.TRAN_LINE_ITEM_AMT_EXCEEDS_TRAN_AMT,ApexPages.getMessages().get(0).getSummary());
        
        	//Test Validation	
        	objTransController.createCreditTranscations();  
        	objTransController.totalAmount = 200000.00;
        	objTransController.wrappers = objTransController.getBills();
        	objTransController.wrapper = objTransController.wrappers.get(0); 	
        	objTransController.wrapper.debt.Amount__c = 2000.00;
        	objTransController.wrapper.debt.Date__c = System.Today();
        	objTransController.wrapper.debt.Memo__c = 'test';
        	objTransController.wrapper.selected = true;
        	objTransController.processSelectedDebits();
        	List<apexPages.Message>	lstMsgs = ApexPages.getMessages(); 
        	if(lstMsgs.size() > 0){
        		System.assertEquals(Label.TRAN_LINE_ITEM_AMT_EXCEEDS_TRAN_AMT,lstMsgs.get(0).getSummary() );
        	}
        	
        	//Test Validation	
        	objTransController.createCreditTranscations();  
        	objTransController.totalAmount = null;
        	objTransController.wrappers = objTransController.getBills();
        	objTransController.wrapper = objTransController.wrappers.get(0); 	
        	objTransController.wrapper.debt.Amount__c = 2000.00;
        	objTransController.wrapper.debt.Date__c = System.Today();
        	objTransController.wrapper.debt.Memo__c = 'test';
        	objTransController.wrapper.selected = true;
        	objTransController.processSelectedDebits();
        	objTransController.autoPopulate();
        	//Exception can not be handle from page
        	
        	PageReference resetPageRef = objTransController.resetTransaction();
        	//objTransController.autoPopulate();
        }
    }
}