CMBSandbox4/src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

CMBSandbox4/src/objects/Commission__c.object
<CustomObject>
    <description>To create and track Commission</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Invoice</description>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Opportunity.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientProjectManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectType__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Custom Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundingo Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle of Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreSales (NonBillable)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Retainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Arrearage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Price_Conga__c  -   Invoice_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due2 (To be removed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description (Internal)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Conga__c</fullName>
        <formula>IF(Fee_Sum_of_RollUp__c&gt;=0.01,Fee_Sum_of_RollUp__c+ Adjustment__c -  Sum_of_Credit__c   , Cost__c +Adjustment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Due__c</fullName>
        <formula>Price_Conga__c -  Total_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Paid__c</fullName>
        <inlineHelpText>This is summarizing the Transaction Credit Line Items</inlineHelpText>
        <label>Amount Paid</label>
        <summarizedField>Transaction_Line_Credit__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction_Line_Credit__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>isPaid__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &quot;Paid&quot;),true,false)</formula>
        <inlineHelpText>IF(ISPICKVAL(Status__c, &quot;Paid&quot;),true,false)</inlineHelpText>
        <label>isPaid</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Hrs__c</fullName>
        <label>Credit (Hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Reason__c</fullName>
        <label>Credit Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit/PrePaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours Over SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMB Inefficiencies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor Ratio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of time / notes</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HarvestProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours_Num__c</fullName>
        <label>Hours (#)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ProjectType__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>New - Custom App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New - Custom Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New - Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New - MCA App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing - Monthly Retainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing - Bundle of Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing - Non Retainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other	Not Checked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreSales (NonBillable)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Opportunity.object
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

CMBSandbox4/src/objects/Transaction__c.object
<CustomObject>
    <description>This object is to record all revenue and expenses. There will be a status to deferentiate revenue and expenses. This should help with the accounting side of the business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Transaction__c.object
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

MCAPackagingOrg/src/objects/Transaction__c.object
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>

CMBSandbox4/src/objects/Transaction_Line_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Invoice__c.Status__c</field>
                <operation>contains</operation>
                <value>Open - Pending &quot;Send&quot;, Sent</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Transaction Line Credits</relationshipLabel>
        <relationshipName>Transaction_Line_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transaction Line Credits</relationshipLabel>
        <relationshipName>Transaction_Line_Credits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Line Credit</label>
    <nameField>
        <displayFormat>TLC-{0000}</displayFormat>
        <label>Transaction Line Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/InvoiceTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * Version       Date             Author         Description
 * 1.0           05/10/2015       Ashwini S      For Roll up on Account from Invoice  
 */
@isTest
private class InvoiceTriggerHandlerTest {

    static testMethod void testonInvoiceInsert() {
        // TO DO: implement unit test
       //insert account record
        List<Account> listAccounts = TestUtility.getAccountRecords(1);
        insert listAccounts;
        
        List<Contact> listContacts = TestUtility.getContactRecords(1, listAccounts[0].Id);
        insert listContacts;
        System.assertNotEquals(Null, listContacts.size());
        
        //insert opportunity record
        List<Opportunity> listOpportunity = TestUtility.getOpportunityRecords(1, listAccounts[0].Id);
        insert listOpportunity;
        System.assertEquals(listAccounts[0].Id, listOpportunity[0].AccountId);
        //insert invoice record
        List<Invoice__c> listInvoice = TestUtility.getInvoiceRecords(1,
                                listAccounts[0].Id, listContacts[0].Id, listOpportunity[0].Id);
        insert listInvoice;
        
        //insert commission records
        List<Commission__c> listCommisssion = TestUtility.getCommissionRecords(3, 
                                listAccounts[0].Id, listOpportunity[0].Id, listInvoice[0].Id);
        insert listCommisssion;
         List<Invoice__c> listInvoice1 = TestUtility.getInvoiceRecords(1,
                                listAccounts[0].Id, listContacts[0].Id, listOpportunity[0].Id);
         CheckRecursive.runAfter = true;                            
        Test.startTest();
        insert listInvoice1;
         Test.stopTest();
        System.assertNotEquals(Null, listInvoice1[0].Id);
    }
    
     static testMethod void testonInvoiceUpdate() {
        // TO DO: implement unit test
       //insert account record
        List<Account> listAccounts = TestUtility.getAccountRecords(2);
        insert listAccounts;
        
        List<Contact> listContacts = TestUtility.getContactRecords(1, listAccounts[0].Id);
        insert listContacts;
        System.assertNotEquals(Null, listContacts.size());
        
        //insert opportunity record
        List<Opportunity> listOpportunity = TestUtility.getOpportunityRecords(2, listAccounts[0].Id);
        insert listOpportunity;
        System.assertEquals(listAccounts[0].Id, listOpportunity[0].AccountId);
        
        List<Invoice__c> listInvoice = TestUtility.getInvoiceRecords(2,
                                listAccounts[0].Id, listContacts[0].Id, listOpportunity[0].Id);
        CheckRecursive.runAfter = true;                 
        insert listInvoice;
        System.assertNotEquals(Null, listInvoice[0].Id);
        
        
        List<Transaction__c> listTransaction = TestUtility.getTransactionRecords(1,
                                listAccounts[0].Id);
        CheckRecursive.runAfter = true;
        insert listTransaction;
        System.assertNotEquals(Null, listTransaction[0].Id);
        
        List<Transaction_Line_Credit__c>listTransactionLinecredit = TestUtility.getTransactionLineCreditRecords(1,
                                          listTransaction[0].Id,listInvoice[0].Id);
        listTransactionLinecredit[0].Amount__c = 10000.00;
        
        CheckRecursive.runAfter = true;
        insert listTransactionLinecredit;
        System.assertNotEquals(Null, listTransactionLinecredit[0].Id);
        
        HarvestProject__c objProject = new HarvestProject__c();
        objProject.Account__c = listAccounts[0].Id;
        objProject.Opportunity__c = listOpportunity[0].Id;
        objProject.ClientProjectManager__c = listContacts[0].Id;
        objProject.ProjectType__c = 'Implementation';
        insert objProject;
        System.assertNotEquals(null, objProject.Id);
        
        List<Line_Item__c> listInvoiceLineItem = createInvoiceLineItem(2, objProject.Id,
                                 listOpportunity[0].Id,listInvoice[0].Id);
        
        CheckRecursive.runAfter = true;
        insert listInvoiceLineItem;
        System.assertNotEquals(Null, listInvoiceLineItem[0].Id);
        Invoice__c InvoiceObj = [Select Id, Total_Amount_Due__c, Amount_Due__c, Price_Conga__c From Invoice__c  where Id =:listInvoice[0].Id Limit 1];
        
        List<Transaction_Line_Credit__c>listTransactionLinecredit1 = TestUtility.getTransactionLineCreditRecords(1,
                                          listTransaction[0].Id,listInvoice[0].Id);
        listTransactionLinecredit1[0].Amount__c = 5467.00;
        CheckRecursive.runAfter = true;
        insert listTransactionLinecredit1;
        
        Invoice__c InvoiceObj1 = [Select Id, isPaid__c, Total_Amount_Due__c,Amount_Due__c,Price_Conga__c, Total_Amount_Paid__c From Invoice__c  where Id =:listInvoice[0].Id Limit 1];               
                                
        List<Commission__c> listCommisssion = TestUtility.getCommissionRecords(3, 
                                listAccounts[0].Id, listOpportunity[0].Id, InvoiceObj1.Id);
        CheckRecursive.runAfter = true;
        insert listCommisssion;

        listInvoice[1].Opportunity__c=  listOpportunity[1].Id;
        //update the projject record
        CheckRecursive.runAfter = true;
        Test.startTest();
            update listInvoice[1];
        Test.stopTest();
        System.assertNotEquals(Null, listInvoice[0].Id);
    }
    
    static testMethod void testonInvoiceDelete() {
        // TO DO: implement unit test
       //insert account record
        List<Account> listAccounts = TestUtility.getAccountRecords(1);
        insert listAccounts;
        
        List<Contact> listContacts = TestUtility.getContactRecords(1, listAccounts[0].Id);
        insert listContacts;
        System.assertNotEquals(Null, listContacts.size());
        
        //insert opportunity record
        List<Opportunity> listOpportunity = TestUtility.getOpportunityRecords(1, listAccounts[0].Id);
        insert listOpportunity;
        System.assertEquals(listAccounts[0].Id, listOpportunity[0].AccountId);
        
         List<Invoice__c> listInvoice = TestUtility.getInvoiceRecords(3,
                                listAccounts[0].Id, listContacts[0].Id, listOpportunity[0].Id);
        
        insert listInvoice;
        System.assertNotEquals(Null, listInvoice[0].Id);
        
         CheckRecursive.runAfter = true;                            
        Test.startTest();
        delete listInvoice[2];
        Test.stopTest();
    }
    
    private static List<Line_Item__c> createInvoiceLineItem(Integer pCount, Id projectId, Id opportunityId, Id invoiceId) {
        List<Line_Item__c> listLineItem = new List<Line_Item__c>();
        
        for(Integer count =0; count <= pCount ; count++) {
            Line_Item__c objLineItem = new Line_Item__c();
            objLineItem.Date__c = system.Today();
            objLineItem.HarvestProject__c = projectId;
            objLineItem.Description__c = 'Test Description'+count;
            objLineItem.Credit_Reason__c='Deposit/PrePaid';
            objLineItem.Opportunity__c = opportunityId;
            objLineItem.Invoice__c = invoiceId;
            objLineItem.Hours_Num__c = 2;
            objLineItem.Credit_Hrs__c = 20;
            listLineItem.add(objLineItem);
        }
        return listLineItem;
    }
}