CMBSandbox4/src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

CMBSandbox4/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

CMBSandbox4/src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Total_Credit_Amount__c</fullName>
        <label>Total Credit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Hours_Credited__c</fullName>
        <formula>IF(Sum_of_Credit_Hrs__c = null,null,(Sum_of_Credit_Hrs__c /  Sum_of_Gross_Hours__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Hours Credited</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

CMBSandbox4/src/classes/ApplyCreditOnInvoicePageExtensionTest.cls
@isTest
public with sharing class ApplyCreditOnInvoicePageExtensionTest
{
    static testmethod void validateStandardController() 
    {
        List<Account> accountList = TestUtility.getAccountRecords(1);
        insert accountList;
        
        List<Opportunity> opportunityList = TestUtility.getOpportunityRecords(1, accountList[0].Id);
        insert opportunityList;
        
        List<Contact> contactList = TestUtility.getContactRecords(1, accountList[0].Id);
        insert contactList;
        
        List<Invoice__c> invoiceList = TestUtility.getInvoiceRecords(1, accountList[0].Id, contactList[0].Id, opportunityList[0].id);
        insert invoiceList;
        
        List<Credit__c> creditList = TestUtility.insertCredit(5, accountList[0].Id);
        for(integer i=0; i<5; i++) {
            creditList[i].Total_Credit_Amount__c =100+i;
        }
        insert creditList;
        
        List<ApplyCreditOnInvoicePageExtension.CreditWraper> creditwrpperList = new List<ApplyCreditOnInvoicePageExtension.CreditWraper>();
        
        test.startTest();
        
            ApexPages.StandardController stdCntrllr = new ApexPages.StandardController(invoiceList[0]);
            ApplyCreditOnInvoicePageExtension customExtension = new ApplyCreditOnInvoicePageExtension(stdCntrllr);
        
            PageReference pageRef = Page.ApplyCreditOnInvoicePage;
            pageRef.getParameters().put('id', String.valueOf(invoiceList[0].Id));
            Test.setCurrentPage(pageRef);
            
            creditwrpperList =  customExtension.getCreditWraperList();
            creditwrpperList[0].isSelected = true;
            pageRef.getParameters().put('indexToCheck', '0');
            customExtension.checkboxValidation();
            customExtension.creditFlag = true;
            customExtension.createCreditLineItem();
            customExtension.creditLineItemObj.Hours_Credited__c = 100;
            customExtension.creditLineItemObj.Credit__c = creditList[0].Id;
            customExtension.onClickApply();            
            customExtension.cancelCreate();
        
        test.stopTest();
    }
    
    static testmethod void validateCheckboxValidation() 
    {
        List<Account> accountList = TestUtility.getAccountRecords(1);
        insert accountList;
        
        List<Opportunity> opportunityList = TestUtility.getOpportunityRecords(1, accountList[0].Id);
        insert opportunityList;
        
        List<Contact> contactList = TestUtility.getContactRecords(1, accountList[0].Id);
        insert contactList;
        
        List<Invoice__c> invoiceList = TestUtility.getInvoiceRecords(1, accountList[0].Id, contactList[0].Id, opportunityList[0].id);
        insert invoiceList;
        
        List<Credit__c> creditList = TestUtility.insertCredit(5, accountList[0].Id);
        for(integer i=0; i<5; i++) {
            creditList[i].Total_Credit_Amount__c =100+i;
        }
        insert creditList;
        
        List<ApplyCreditOnInvoicePageExtension.CreditWraper> creditwrpperList = new List<ApplyCreditOnInvoicePageExtension.CreditWraper>();
        
        test.startTest();
            ApexPages.StandardController stdCntrllr = new ApexPages.StandardController(invoiceList[0]);
            ApplyCreditOnInvoicePageExtension customExtension = new ApplyCreditOnInvoicePageExtension(stdCntrllr);
        
            PageReference pageRef = Page.ApplyCreditOnInvoicePage;
            pageRef.getParameters().put('id', String.valueOf(invoiceList[0].Id));
            Test.setCurrentPage(pageRef);
            
            creditwrpperList =  customExtension.getCreditWraperList();
            creditwrpperList[0].isSelected = true;
            pageRef.getParameters().put('indexToCheck', '0');
            customExtension.checkboxValidation();
            
            creditwrpperList[0].isSelected = false;
            pageRef.getParameters().put('indexToCheck', '0');
            customExtension.checkboxValidation();
            customExtension.refreshBlock();
            customExtension.backToInvoice();
        test.stopTest();
    }
    
    static testmethod void validateCreateCreditObj() 
    {
        List<Account> accountList = TestUtility.getAccountRecords(1);
        insert accountList;
        
        List<Opportunity> opportunityList = TestUtility.getOpportunityRecords(1, accountList[0].Id);
        insert opportunityList;
        
        List<Contact> contactList = TestUtility.getContactRecords(1, accountList[0].Id);
        insert contactList;
        
        List<Invoice__c> invoiceList = TestUtility.getInvoiceRecords(1, accountList[0].Id, contactList[0].Id, opportunityList[0].id);
        insert invoiceList;
        
        List<Credit__c> creditList = TestUtility.insertCredit(5, accountList[0].Id);
        for(integer i=0; i<5; i++) {
            creditList[i].Total_Credit_Amount__c =100+i;
        }
        insert creditList;
        
        List<ApplyCreditOnInvoicePageExtension.CreditWraper> creditwrpperList = new List<ApplyCreditOnInvoicePageExtension.CreditWraper>();
        
        test.startTest();
        
            ApexPages.StandardController stdCntrllr = new ApexPages.StandardController(invoiceList[0]);
            ApplyCreditOnInvoicePageExtension customExtension = new ApplyCreditOnInvoicePageExtension(stdCntrllr);
        
            PageReference pageRef = Page.ApplyCreditOnInvoicePage;
            pageRef.getParameters().put('id', String.valueOf(invoiceList[0].Id));
            Test.setCurrentPage(pageRef);
            
            creditwrpperList =  customExtension.getCreditWraperList();
            customExtension.createCreditLineItem();
            customExtension.creditLineItemObj.Hours_Credited__c = 100;
            customExtension.creditLineItemObj.Credit__c = creditList[0].Id;
            customExtension.onClickApply();
            customExtension.creditCreated = true;
            customExtension.assignCreditHoursAndAmount();
            customExtension.cancelCreate();
        
        test.stopTest();
    }   
}