CMBSandbox4/src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HarvestProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectCode__c</fullName>
        <displayFormat>PID-{0}</displayFormat>
        <inlineHelpText>Auto-assigned project ID.  Used to sync to Harvest.</inlineHelpText>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/HarvestSyncProjectEntriesControllerTest.cls
@isTest
private class HarvestSyncProjectEntriesControllerTest {

    static testMethod void test() {
	    Account account = new Account(Name='bla');
	    insert account;
	    HarvestProject__c project = new HarvestProject__c(Name='bla', Account__c=account.Id);
	    insert project;
        DependencyManager.TestMode = true;
	    project = [SELECT Id, Name, ProjectCode__c from HarvestProject__c WHERE Id = :project.Id];
    	HarvestSyncProjectEntriesController cont = new HarvestSyncProjectEntriesController(new ApexPages.Standardcontroller(project));
    	cont.sync(); 
    	cont.toProject();
    }
}