CMBSandbox4/src/objects/Bank__c.object
<CustomObject>
    <fields>
        <fullName>API_Exposed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>API Exposed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bank_Id__c</fullName>
        <displayFormat>B-{000000}</displayFormat>
        <label>Bank Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>BK_Policy__c</fullName>
        <label>BK Policy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Amt_of_Monthly_Gross_Sales__c</fullName>
        <inlineHelpText>What is the multiple that this bank typically funds as a ratio to the merchant&apos;s monthly gross sales volume</inlineHelpText>
        <label>Funding Amt - % of Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Amount__c</fullName>
        <label>Max. Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_No_NSFs__c</fullName>
        <label>Max# NSFs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Methods_of_Repayment__c</fullName>
        <label>Method of Repayment</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holdback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Daily_Bal__c</fullName>
        <label>Min. Avg Daily Bal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_CC_Avg__c</fullName>
        <label>Min. Monthly CC Avg $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Deposits__c</fullName>
        <label>Min. Monthly Deposits</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Advance__c</fullName>
        <label>Minimum Advance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Deposit_Count__c</fullName>
        <inlineHelpText>Number of days per month where deposits are made into the bank account.</inlineHelpText>
        <label>Min. Monthly Bank Deposit Count</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ownership_Percentage_Requirement__c</fullName>
        <label>Ownership Percentage Requirement</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percentage_Net_After_Payoff__c</fullName>
        <label>Percentage Net After Payoff</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Restricted_Industry_List__c</fullName>
        <label>Restricted Industry List</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apparel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machinery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not For Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Restricted_States__c</fullName>
        <label>Restricted States</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Site_Inspection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Site Inspection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submission_Email__c</fullName>
        <label>Submission Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Tax_Lean_Policy__c</fullName>
        <label>Tax Lean Policy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_References__c</fullName>
        <label>Trade References</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required - 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required - 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required - 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Count__c</fullName>
        <label>Transaction Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Turnaround_Time__c</fullName>
        <inlineHelpText>The time (days) it takes the Bank to process an application and respond with an approval or decline.</inlineHelpText>
        <label>Turnaround Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Min. Years in Business</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Required_Documents__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Required Documents</relationshipLabel>
        <relationshipName>Required_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Required Document</label>
    <nameField>
        <label>Required Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/BankDirectoryServiceTest.cls
@isTest
public with sharing class BankDirectoryServiceTest {
	
	
	private static void setup(Boolean isAPIExposed) {
		Bank__c[] banks = new Bank__c[]{};
		for (Integer i = 0; i < 100; i++) {
		    Bank__c bank = new Bank__c();
		    bank.Name = 'Test Bank' + String.valueOf(i);
		    bank.Billing_City__c = 'Test city ' + String.valueOf(i);
			bank.Billing_Postal_Code__c = 'Test Postal Code ' + String.valueOf(i);
			bank.Billing_State__c = 'Test State ' + String.valueOf(i);
			bank.Billing_Street__c = 'Test Street ' + String.valueOf(i);
			bank.Email__c = 'Test' + String.valueOf(i) + '@Test.com';
			bank.Phone__c = '12345667890';
			bank.WebSite__c = 'Test WebSite ' + String.valueOf(i);    
			bank.API_Exposed__c = isAPIExposed;
		    banks.add(bank);
		}
		insert banks;

		banks = [select Id, Bank_Id__c, Name from Bank__c where Id = :banks];

		Program__c[] programs = new Program__c[]{};
		for (Bank__c b : banks) {
    		for (Integer i = 0; i < 2; i++) {
		        Program__c program = new Program__c();
		        program.Name = 'Test Program ' + String.valueOf(i) + ' ' + b.Name;
		        program.External_Bank__c = b.Id;
		        program.BK_Policy__c = 'Test Policy ' + String.valueOf(i);
		        program.Funding_Amt_of_Monthly_Gross_Sales__c = 1000;
		        program.Max_Amount__c = 1000;
		        program.Max_No_NSFs__c = 10000;
		        program.Methods_of_Repayment__c = 'Test Repayment Method ' + String.valueOf(i);
		        program.Min_Avg_Daily_Bal__c = 10000;
		        program.Credit_Score__c = 10000;
		        program.Min_Credit_Score__c = 10000;
		        program.Minimum_Deposit_Count__c = 1000;
		        program.Min_Monthly_CC_Avg__c = 2000;
		        program.Min_Monthly_Deposits__c = i;
		        program.Years_in_Business__c = i;
		        program.Minimum_Advance__c = 100000;
		        program.Notes__c = 'Test Notes ' + String.valueOf(i);
		        program.Ownership_Percentage_Requirement__c = 50;
		        program.Percentage_Net_After_Payoff__c = 20;
		        program.Restricted_Industry_List__c = 'Test Restricted Industry ' + String.valueOf(i);
		        program.Restricted_States__c = 'Test Restricted States ' + String.valueOf(i);
		        program.Site_Inspection__c = true;
		        program.Submission_Email__c = 'test' + String.valueOf(i) + '@test.com';
		        program.Tax_Lean_Policy__c = 'Test Tax ' + String.valueOf(i);
		        program.Trade_References__c = 'Test Trade References ' + String.valueOf(i);
		        program.Transaction_Count__c = i;
		        program.Turnaround_Time__c = i;
		        program.Ready_To_Send__c = true;
		        programs.add(program);
    		}
		}
		insert programs;
		
		programs = [select Id, Program_Id__c, Name from Program__c where Id = :programs];

		Required_Documents__c[] requiredDocuments = new Required_Documents__c[]{};

		for (Program__c prog : programs) {
		    for (Integer i = 0; i < 2; i++) {
		        Required_Documents__c document = new Required_Documents__c();
		        document.Name = 'Test Required Document ' + String.valueOf(i) + prog.Name;
		        document.Program__c = prog.Id;
		        requiredDocuments.add(document);
		    }
		}

		insert requiredDocuments;	
	}


	@isTest
	public static void testBankDirectoryServiceNoExposed() {
		setup(false);

		Test.startTest();

		Bank[] banks = BankDirectoryService.doGet(0);
		System.assertEquals(banks.size(), 0);

		Test.stopTest();
	}


	@isTest
	public static void testBankDirectoryServiceExposed() {
		setup(true);

		Test.startTest();

		Bank[] banks = BankDirectoryService.doGet(0);
		System.assertEquals(banks.size(), 100);

		Test.stopTest();
	}	
}