CMBSandbox4/src/objects/Bill__c.object
<CustomObject>
    <description>This is for vendor bills</description>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Amount_Due__c</fullName>
        <formula>Amount_Due__c   -  Bill_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>Today() + 30</defaultValue>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Needs Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Wire Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid - Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Clarification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Price_Conga__c  -   Invoice_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due2 (To be removed)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <label>Date Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>Date_Sent__c + CASE( Terms__c,
&quot;Net 15&quot;,15,
&quot;Net 30&quot;,30,
&quot;Net 45&quot;,45,
&quot;Due on Receipt&quot;,0,
0)</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_Conga__c</fullName>
        <formula>IF(Fee_Sum_of_RollUp__c&gt;=0.01,Fee_Sum_of_RollUp__c+ Adjustment__c -  Sum_of_Credit__c   , Cost__c +Adjustment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Not Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - PM Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - HA Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Pending Credit &amp; Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Pending Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved &amp; Ready to Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent - Partially Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Due__c</fullName>
        <formula>Price_Conga__c -  Total_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Paid__c</fullName>
        <inlineHelpText>This is summarizing the Transaction Credit Line Items</inlineHelpText>
        <label>Amount Paid</label>
        <summarizedField>Transaction_Line_Credit__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction_Line_Credit__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Receivable__c.object
<CustomObject>
    <description>Used to track money being received from outside parties. An Opportunity can have many Receivables</description>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c - Receivable_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCA App/Release/MCA App 1/src/objects/Receivable__c.object
    <fields>
        <fullName>Price_Conga__c</fullName>
        <formula>IF(Fee_Sum_of_RollUp__c&gt;=0.01,Fee_Sum_of_RollUp__c+ Adjustment__c - Sum_of_Credit__c , Cost__c +Adjustment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

CMBSandbox4/src/objects/Transaction__c.object
<CustomObject>
    <description>This object is to record all revenue and expenses. There will be a status to deferentiate revenue and expenses. This should help with the accounting side of the business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amt_Non_Hourly__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill</label>
        <referenceTo>Bill__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Postdated Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>Revenue and other incoming funds</description>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Debit</fullName>
        <active>true</active>
        <description>For expenses and other debits</description>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Transaction__c.object
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

CMBSandbox4/src/objects/Transaction_Line_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Invoice__c.Status__c</field>
                <operation>contains</operation>
                <value>Open - Pending &quot;Send&quot;, Sent</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Transaction Line Credits</relationshipLabel>
        <relationshipName>Transaction_Line_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transaction Line Credits</relationshipLabel>
        <relationshipName>Transaction_Line_Credits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Line Credit</label>
    <nameField>
        <displayFormat>TLC-{0000}</displayFormat>
        <label>Transaction Line Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Transaction_Line_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <referenceTo>Bill__c</referenceTo>
        <relationshipLabel>Transaction Line Debits</relationshipLabel>
        <relationshipName>Transaction_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transaction Line Debits</relationshipLabel>
        <relationshipName>Transaction_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Line Debit</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Debits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/TransactionControllerTest.cls
public with sharing class TransactionControllerTest {
    
    public Boolean disableInput {get; set;}
    public Apexpages.StandardController controller;
    public boolean blnShowBills{set;get;}
    public boolean blnEditMode{set;get;}
    public boolean blnNewMode{set;get;}
    public boolean blnTransType{set;get;}
    public String strTransName{set; get;}
    public boolean blnCreditTransLineItems{set;get;}
    public boolean blnDebitTransLineItems{set;get;}
    public boolean blnError{set;get;}
    public String strAccountName{set;get;}
    public String totalTransactionAmount{set;get;}
    public Decimal totalAmount{set;get;}
    //InvoiceList of Transaction Wrapper
    public List<TransactionWrapper> invoiceList {get; set;}
    
    public Transaction__c objTranscation{get; set;}
    //For Wrapper
    public List<TransactionWrapper> wrappers {get; set;}
    public TransactionWrapper wrapper{get;set;}

    public set<String> stInvoiceStatus = new set<String>{'Sent', 'Sent - Partially Paid'};
    public List<String> lstStatuses = new List<String>();
    public Transaction__c merch { get; set; }
    
    public static final String TRAN_LINE_ITEM_AMT_EXCEEDS_TRAN_AMT = Label.TRAN_LINE_ITEM_AMT_EXCEEDS_TRAN_AMT; 
    public static final String BILL_PAID_AMT_EXCEEDS_BALANCE_AMT = Label.BILL_PAID_AMT_EXCEEDS_BALANCE_AMT;
    public static final String TRAN_LINE_ITEM_AMT_EXCEEDS_INV_DUE_AMT = Label.TRAN_LINE_ITEM_AMT_EXCEEDS_INV_DUE_AMT;
   // public static final String TRAN_LINE_ITEM_AMT_MATCH_TRAN_AMT = Label.TRAN_LINE_ITEM_AMT_MATCH_TRAN_AMT;
    /*
    *   Set Default values to Visual Force page
    */  
     private String sortDirection = 'ASC';
       private String sortExp = 'name';
    
       public String sortExpression
       {
         get
         {
            return sortExp;
         }
         set
         {
           //if the column is clicked on then switch between Ascending and Descending modes
           if (value == sortExp)
             sortDirection = (sortDirection == 'ASC')? 'DESC' : 'ASC';
           else
             sortDirection = 'ASC';
           sortExp = value;
         }
       }
    
     public String getSortDirection()
     {
        //if not column is selected 
        if (sortExpression == null || sortExpression == '')
          return 'ASC';
        else
         return sortDirection;
     }
    
    public void setSortDirection(String value)
     {  
       sortDirection = value;
     } 
     
    public TransactionControllerTest(ApexPages.StandardController stdController) {
        try{
            controller   = stdController;
            blnShowBills = true;
            blnEditMode  = false;
            blnNewMode = true;
            //blnCreditTransLineItems = false;
            blnDebitTransLineItems = false;
            blnError = false;
            totalAmount=0.00;
            
            //Create Related List
            objTranscation = (Transaction__c)controller.getRecord();
             List<Status__c> cslstStatus = Status__c.getall().values();
             for(Status__c csObj: cslstStatus){
                lstStatuses.add(csObj.Name);
             }
             strTransName = [select Name FROM RecordType WHERE Id =: objTranscation.RecordTypeId limit 1].Name;
             if( strTransName == 'Debit'){
                blnDebitTransLineItems = true;
                blnCreditTransLineItems = false;
            }else{
                blnCreditTransLineItems = true;
                blnDebitTransLineItems = false;
            }
              //For multiple rows
              wrappers=new List<TransactionWrapper>();
            //  Id transactionId = objTranscation.Id;
            //  this.merch = getMerchandise(transactionId);
              disableInput = true;
        }
        catch(Exception e){
                ApexPages.addMessages(e);
                    //return ApexPages.currentPage();
        }
    }
    
    // Method called on click of the Clone button
    public PageReference ClonePage(){
        return new PageReference('/'+objTranscation.Id+'/e?clone=1&retURL='+objTranscation.Id);
    }
    
    //Redirect VF to Standard Edit Page of Transaction 
    public PageReference Edit_val() {
        blnEditMode = true;
        return new PageReference('/'+ objTranscation.Id+'/e?retURL=%2F'+objTranscation.Id);
    }
    
    //To Cancel Edit Fucntionality
    public PageReference cancelEdit() {
        blnEditMode = false;
       Schema.DescribeSObjectResult dsr = Transaction__c.SObjectType.getDescribe(); 
       return new Pagereference('/'+dsr.getKeyPrefix()+'/o');
        //return new PageReference('/a0P/o');
       
    }
    
   
    //Reset Transaction Line Items
    public PageReference resetTransaction() {
        totalAmount = 0.00;
        invoiceList=null;
        return null;
    }
    //Create New Transaction Line Items Again Transaction
    public void create(){
        
        system.debug('inside create()');
        List<Account> lstAccount = [select Name From Account Where Id=:objTranscation.Account__c];
        if(lstAccount.size() > 0)
            strAccountName = lstAccount.get(0).Name;
        strTransName = [select Name FROM RecordType WHERE Id =: objTranscation.RecordTypeId limit 1].Name;
        if( strTransName == 'Debit'){
            blnDebitTransLineItems = true;
             blnCreditTransLineItems = false;
             
        }else{
            blnCreditTransLineItems = true;
            blnDebitTransLineItems = false;
        }
        invoiceList=null;
        
    }     
   
    //Cancel Credit Transaction Line Items
    public PageReference cancelCreditTranscations() {
        blnDebitTransLineItems = false;
        blnCreditTransLineItems = false;
        return null;
    }
  
 //Create Multiple Transaction Line Items against Transaction. 
 public class TransactionWrapper
 {
     public Transaction_Line_Credit__c acc {get;  set;}
     public Transaction_Line_Credit__c cred {get;  set;}
     public Transaction_Line_Debit__c debitacc {get;  set;}
     public Transaction_Line_Debit__c debt {get;  set;}
     public Invoice__c invc{get;set;}
     public Bill__c bill{get;set;}
     public Boolean selected {get; set;}
    
      public TransactionWrapper(Invoice__c invoice, Transaction_Line_Credit__c credits)//Id id)
     {
          invc = invoice;
          cred = credits;
          selected = false;
     }
     
     public TransactionWrapper(Bill__c tempbill, Transaction_Line_Debit__c debits)//Id id)
     {
          bill = tempbill;
          debt = debits;
          selected = false;
     }
 }
 
    //To Sace Transaction Update
     public PageReference save() {
        autopopulate();
        if(totalAmount > objTranscation.Amt_Non_Hourly__c)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,TRAN_LINE_ITEM_AMT_EXCEEDS_TRAN_AMT);
            ApexPages.addMessage(myMsg);
            return null;
        }
        else
        {
            try{
            //controller.save();//invoke standard Save method
               //insert objTranscation;
               if(objTranscation.Id == null)
                   insert objTranscation;
               else
                   update objTranscation;
               List<Transaction_Line_Credit__c> selectedLineItems = new List<Transaction_Line_Credit__c>();
               List<Transaction_Line_Debit__c> selectedLineItemsDebit = new List<Transaction_Line_Debit__c>();
               if( strTransName == 'Credit'){
                   for(TransactionWrapper cCon: getInvoices()) {
                        if( cCon.cred.Amount__c != null){
                            if(cCon.invc.Amount_Due__c < cCon.cred.Amount__c){
                                ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR,TRAN_LINE_ITEM_AMT_EXCEEDS_INV_DUE_AMT);
                                ApexPages.addMessage(myMsg1);   
                                 return null;
                            }
                            else{
                            cCon.cred.Transaction__c = objTranscation.Id;
                            selectedLineItems.add(cCon.cred);
                            }
                        }
                    }//end of for
                insert selectedLineItems;
               }
               else{
                    for(TransactionWrapper cCon: getBills()) {
                    
                    if(cCon.debt.Amount__c != null){
                        if(cCon.bill.Bill_Amount_Due__c < cCon.debt.Amount__c){
                            ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR,BILL_PAID_AMT_EXCEEDS_BALANCE_AMT);
                            ApexPages.addMessage(myMsg1);   
                                 return null;
                        }
                        else{
                            cCon.debt.Transaction__c = objTranscation.Id;
                            selectedLineItemsDebit.add(cCon.debt);
                        }
                    }
                    }//end of for
                insert selectedLineItemsDebit;
               }
            
            }//end of try
            catch(Exception e){
                    ApexPages.addMessages(e);
                    //return ApexPages.currentPage();
                }
        }//end of else-big
        return new PageReference('/'+objTranscation.Id);//refresh current page
    }
    
    //To Get All Invoices and Create Transacton Credit Line Items
    public List<TransactionWrapper> getInvoices() {
        
        List<Account> lstAccount = [select Name From Account Where Id=:objTranscation.Account__c];
        if(lstAccount.size() > 0)
            strAccountName = lstAccount.get(0).Name;
        
        if(invoiceList == null) {
                
            invoiceList = new List<TransactionWrapper>();
            for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses]) 
            {
    
                Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                invoiceList.add(new TransactionWrapper(c, newCredit));
            }
        }   
        return invoiceList;
    }

    //To Get All Bills and Create Transacton Line Debit Items
    public List<TransactionWrapper> getBills() {
          //invoiceList = null;
        if(invoiceList == null) {
            invoiceList = new List<TransactionWrapper>();
            for(Bill__c b: [select Id, Name, Bill_Date__c, Amount_Due__c,
                            Bill_Amount_Due__c,
                             Due_Date__c,
                               Memo__c, Status__c, Bill_Amount_Paid__c, Amount_Roll_Up__c
                               From Bill__c 
                               WHERE Vendor__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses]) {
    
                Transaction_Line_Debit__c newDebit = new Transaction_Line_Debit__c(Bill__c = b.Id, Transaction__c = objTranscation.Id);
                invoiceList.add(new TransactionWrapper(b, newDebit));
            }
        }
        return invoiceList;
    }
    
    //Field set to Create detail page section
    public List<Schema.FieldSetMember> getColumn1Fields() {
        return SObjectType.Transaction__c.FieldSets.TransactionFieldSetColumn1.getFields();
    }
    
    //Field set to Create detail page section
    public List<Schema.FieldSetMember> getColumn2Fields() {
        return SObjectType.Transaction__c.FieldSets.TransactionFieldSetColumn2.getFields();
    }
    
    //Field set to Create detail page section
    public List<Schema.FieldSetMember> getColumn3Fields() {
        return SObjectType.Transaction__c.FieldSets.TransactionFieldSetColumn3.getFields();
    }
    
    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.Transaction__c.FieldSets.TransactionFieldSet.getFields();
    }
    
     public void autoPopulate1() {}
    /*
        1)On Select of Check Box: 
            Amount_Due, Paid Date and Total of Transaction LineItems autopopulated.
        2)On Blur of Amount Due Input Field:Total of Transaction LineItems Amount autopopulated.
    */
    public PageReference autoPopulate() {
        system.debug('inside autoPopulate');
        totalAmount = 0.00;
        if( strTransName == 'Debit'){
            for(TransactionWrapper cCon: getBills()) {
                if( cCon.debt.Amount__c != null){
                    totalAmount += cCon.debt.Amount__c; 
                    system.debug('**totalAmount**'+totalAmount);
                }
            }
            }else{
            //system.debug('getInvoices'+getInvoices());
            for(TransactionWrapper cCon: getInvoices()) {
                if( cCon.cred.Amount__c != null){
                    totalAmount += cCon.cred.Amount__c; 
                    system.debug('**totalAmountCredit**'+totalAmount);
                }
            }
        }
        totalAmount += getRollupAmount();
        system.debug('*after rollup*totalAmount**'+totalAmount);
        return null;
     }
     
     //To Set Current Date on Transaction Line Item. Event onChnage is applied
     public String getCurrentDate(){
        Date tempdate = System.today();
        Integer dd = tempdate.day();
        Integer mm = tempdate.month();
        Integer yyyy = tempdate.year();
        return mm+'/'+dd+'/'+yyyy;
     }
     private Decimal getRollupAmount(){
        AggregateResult[] groupedResults;//=[Select SUM(t.Amount__c)  am From Transaction_Line_Debit__c t WHERE Transaction__c =: objTranscation.Id];
        if( strTransName == 'Debit'){
            groupedResults=[Select SUM(t.Amount__c)  amt From Transaction_Line_Debit__c t WHERE Transaction__c =: objTranscation.Id];
        }else{
            groupedResults=[Select SUM(t.Amount__c)  amt From Transaction_Line_Credit__c t WHERE Transaction__c =: objTranscation.Id];
        }
        
        Decimal amount=0.00;
        for (AggregateResult ar : groupedResults)  {
            if(ar.get('amt') != null)
                amount = Decimal.valueOf(String.valueOf(ar.get('amt')));
        }
        return amount;      
     }
     
     public PageReference getCheckedValuesCredit() {
      system.debug('inside if'+invoiceList);
        invoiceList = null;         
        if(invoiceList == null) {
            system.debug('inside if');    
            invoiceList = new List<TransactionWrapper>();
             if(objTranscation.Account__c != null)
             {
                for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses]) 
            {
     system.debug('inside if'+c.Total_Amount_Due__c);
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);             
                    newCredit.Amount__c = c.Total_Amount_Due__c;
                    newCredit.Date__c = System.today();
                    TransactionWrapper tw=new TransactionWrapper(c, newCredit);
                    tw.selected = true;
                    invoiceList.add(tw);
                }
             }
        }   
        return null;
    }
    
    public PageReference getCheckedValues() {
    system.debug('inside if'+invoiceList);
         invoiceList = null;
        if(invoiceList == null) {
        system.debug('inside if');
            invoiceList = new List<TransactionWrapper>();
             if(objTranscation.Account__c != null)
             {
                 for(Bill__c b: [select Id, Name, Bill_Date__c, Amount_Due__c,
                            Bill_Amount_Due__c,
                             Due_Date__c,
                               Memo__c, Status__c, Bill_Amount_Paid__c, Amount_Roll_Up__c
                               From Bill__c 
                               WHERE Vendor__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses]) {
                system.debug('inside if'+b.Bill_Amount_Due__c);
                Transaction_Line_Debit__c newDebit = new Transaction_Line_Debit__c(Bill__c = b.Id, Transaction__c = objTranscation.Id);
                    newDebit.Amount__c = b.Bill_Amount_Due__c;
                    newDebit.Date__c = System.today();
                    TransactionWrapper tw=new TransactionWrapper(b, newDebit);
                    tw.selected = true;
                    invoiceList.add(tw);
                }
             }
        }
        return null;
    }
    
    
     
      public PageReference ViewSortedData_Name() {
       //build the full sort expression
       string sortFullExp = sortExpression  + ' ' + sortDirection;
       //string query = 
      //List<Receivable__c> lstRecevaible = Database.query('select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,Amount__c,Receivable_Amount_Paid__c, Date_Sent__c, Amount_Due__c, Due_From_Account__c From Receivable__c WHERE Due_From_Account__c =: '+objTranscation.Account__c +'AND Status__c NOT IN  '+lstStatuses+' order by '+sortFullExp);
       invoiceList = null;
       invoiceList = new List<TransactionWrapper>();
       if(sortDirection=='ASC'){
      for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Name ASC]) 
                {
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       }
       else{
        for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Name DESC]) 
                {
                   Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       
       }
       //query the database based on the sort expression
      // accounts = Database.query('Select id, Name, BillingCity, BillingCountry, Phone from Account order by ' + sortFullExp + ' limit 1000');
       return null;
   }
   
    public PageReference ViewSortedData_SentDate() {
       //build the full sort expression
       string sortFullExp = sortExpression  + ' ' + sortDirection;
       //string query = 
      //List<Receivable__c> lstRecevaible = Database.query('select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,Amount__c,Receivable_Amount_Paid__c, Date_Sent__c, Amount_Due__c, Due_From_Account__c From Receivable__c WHERE Due_From_Account__c =: '+objTranscation.Account__c +'AND Status__c NOT IN  '+lstStatuses+' order by '+sortFullExp);
       invoiceList = null;
       invoiceList = new List<TransactionWrapper>();
       if(sortDirection=='ASC'){
      for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Date_Sent__c ASC]) 
                {
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       }
       else{
        for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Date_Sent__c DESC]) 
                {
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       
       }
       //query the database based on the sort expression
      // accounts = Database.query('Select id, Name, BillingCity, BillingCountry, Phone from Account order by ' + sortFullExp + ' limit 1000');
       return null;
   }
   
   public PageReference ViewSortedData_Amount() {
       //build the full sort expression
       string sortFullExp = sortExpression  + ' ' + sortDirection;
       invoiceList = null;
       invoiceList = new List<TransactionWrapper>();
       if(sortDirection=='ASC'){
      for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Price_Conga__c ASC]) 
                {
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       }
       else{
        for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Price_Conga__c DESC]) 
                {
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       
       }
       return null;
   }
    public PageReference ViewSortedData_AmoutDue() {
       //build the full sort expression
       string sortFullExp = sortExpression  + ' ' + sortDirection;
       invoiceList = null;
       invoiceList = new List<TransactionWrapper>();
       if(sortDirection=='ASC'){
      for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Total_Amount_Due__c ASC]) 
                {
                   Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       }
       else{
        for(Invoice__c c: [select Id, Name, Date_Paid__c, Status__c,Price_Conga__c,
                               Total_Amount_Paid__c, Date_Sent__c, Total_Amount_Due__c,Amount_Due__c
                               From Invoice__c 
                               WHERE Account__c =: objTranscation.Account__c
                               AND Status__c NOT IN : lstStatuses
                                           order by Total_Amount_Due__c DESC]) 
                {
                    Transaction_Line_Credit__c newCredit = new Transaction_Line_Credit__c(Invoice__c = c.Id, Transaction__c = objTranscation.Id);
                    invoiceList.add(new TransactionWrapper(c, newCredit));
                }
       
       }
       return null;
   }
   
   public PageReference ViewSortedData_PayableName() {
       //build the full sort expression
       string sortFullExp = sortExpression  + ' ' + sortDirection;
        invoiceList = null;
       invoiceList = new List<TransactionWrapper>();
       System.debug('objTranscation.Account__c'+objTranscation.Account__c);
       string AccId = [select Id FROM Account WHERE Id =: objTranscation.Account__c limit 1].Id;
       System.debug('Id'+AccId);
       
       String query = 'select Id, Name, Bill_Date__c, Amount_Due__c, Bill_Amount_Due__c,Due_Date__c,Memo__c, Status__c, Bill_Amount_Paid__c, Amount_Roll_Up__c From Bill__c  WHERE Vendor__c = \''+AccId+'\'' +' AND Bill_Amount_Due__c > 0 order by '+sortFullExp;
       system.debug('query'+query);
       //query the database based on the sort expression
       List<Bill__c> lstPay= Database.query(query);
       for(Bill__c b:lstPay)
       {
            Transaction_Line_Debit__c newDebit = new Transaction_Line_Debit__c(Bill__c = b.Id, Transaction__c = objTranscation.Id);
            invoiceList.add(new TransactionWrapper(b, newDebit));
       }
       return null;
   }
}