CMBSandbox4/src/objects/Commission__c.object
<CustomObject>
    <description>To create and track Commission</description>
    <fields>
        <fullName>Invoice_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For the submissions whose invoice is paid.</description>
        <label>Invoice Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Invoice</description>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Opportunity.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isPaid__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &quot;Paid&quot;),true,false)</formula>
        <inlineHelpText>IF(ISPICKVAL(Status__c, &quot;Paid&quot;),true,false)</inlineHelpText>
        <label>isPaid</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Opportunity.object
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

MCAPackagingOrg/src/objects/Receivable__c.object
<CustomObject>
    <description>Used to track money being received from outside parties. An Opportunity can have many Receivables</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/CommissionUpdateService.cls
public with sharing class CommissionUpdateService {
    
    public void updateCommissions(map<Id, Invoice__c> invoiceNewMap, map<Id, Invoice__c> invoiceOldMap) {
        
        List<Opportunity> opportunityList = new List<Opportunity>();
        Set<Id> opportunityIds = new set<Id>();
        List<Commission__c> commissionList = new List<Commission__c>();
        
        if(invoiceNewMap != null) {
            for(Invoice__c invoiceObj : invoiceNewMap.values()) {
                if(invoiceOldMap != null && invoiceOldMap.containsKey(invoiceObj.Id)) {
                    Invoice__c invoiceInstance = invoiceOldMap.get(invoiceObj.Id);
                    if(invoiceInstance.isPaid__c <> invoiceObj.isPaid__c && invoiceObj.isPaid__c == true) {
                        opportunityIds.add(invoiceObj.Opportunity__c);
                    }
                } else {
                    opportunityIds.add(invoiceObj.Opportunity__c);
                }
            }
        }
        /*
        if(invoiceOldMap!= null) {
            for(Invoice__c invoiceObj : invoiceOldMap.Values) {
                opportunityIds.add(invoiceObj.Opportunity__c);
            }
        }*/
        
        if(opportunityIds !=  null && !opportunityIds.isEmpty()) {
            opportunityList = [Select id, 
                                      name, 
                                      (Select id, 
                                              Invoice_Paid__c, 
                                              Invoice__c 
                                      From Commissions__r 
                                      )
                               From Opportunity
                               Where Id in :opportunityIds];
        }
        
        if(opportunityList != null && !opportunityList.isEmpty()) {
            for(Opportunity oppObj : opportunityList) {
                for(Commission__c commissionObj : oppObj.Commissions__r) {
                    commissionObj.Invoice_Paid__c = true;
                    commissionList.add(commissionObj);
                }
            }
        }
        
        if(commissionList != null && !commissionList.isEmpty()) {
            try {
                update commissionList;
            } catch(Exception ex) {
                system.debug('>>> Error exception: ' +ex.getMessage());
            }
        }
                           
    }
}