CMBSandbox4/src/objects/Commission__c.object
<CustomObject>
    <description>To create and track Commission</description>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Due to  pay to account</description>
        <label>Due to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Invoice</description>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Opportunity.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of commission to be paid</description>
        <inlineHelpText>Current status of commission to be paid</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Request Payment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Ready to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of commission</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Commission</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Not Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - PM Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - HA Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Pending Credit &amp; Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Pending Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved &amp; Ready to Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent - Partially Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Commissions_Paid__c</fullName>
        <description>Total commission paid for this invoice.It is rollup from commission__c.</description>
        <inlineHelpText>Total commission paid for this invoice.</inlineHelpText>
        <label>Total Commissions Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Total_Commission_Paid__c</fullName>
        <description>Sum  of total commission paid, roll up from  Commission object.</description>
        <inlineHelpText>Sum  of total commission paid</inlineHelpText>
        <label>Total Commission Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Override_Paid__c</fullName>
        <description>Sum of override amount</description>
        <inlineHelpText>Sum of override amount  updated from commission.</inlineHelpText>
        <label>Total Override Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Opportunity.object
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Invoice__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </fields>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCAPackagingOrg/src/objects/Receivable__c.object
<CustomObject>
    <description>Used to track money being received from outside parties. An Opportunity can have many Receivables</description>
    <fields>
        <fullName>Due_From_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receivables</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing Residual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndication Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Override</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Bill/Invoice Status</label>
</CustomObject>

CMBSandbox4/src/classes/CommissionTriggerHandlerService.cls
/*
* Version       Date             Author         Description
*   1.0         02/10/2015       Ashwini S      For Roll up on Invoice for AmountPaid on Commission 
*   2.0         30/11/2015       Ashwini S      For Opportunity update from Commission
*/

public with sharing class CommissionTriggerHandlerService {
    
    public CommissionTriggerHandlerService(){}
//this roll up will update invoice
    public void InvoiceRollup(map<Id, Commission__c> mapNewCommissionList, map<Id, Commission__c> mapOldCommissionList){ 
        set<Id> setInvoice = new set<Id>();// to  fetch  related account
        decimal totalAmountPaid = 0;// to count unused estimated hours
        list<Invoice__c> invoiceListResult = new list<Invoice__c>(); // list of account that will be updated
        if (mapNewCommissionList!= null){
            for(Commission__c commission: mapNewCommissionList.Values()){
                if(commission.Invoice__c != null){
                    setInvoice.add(commission.Invoice__c); 
                }
            }
        }// in case of Invoice change on update
        if (mapOldCommissionList!= null){
            for(Commission__c commission: mapOldCommissionList.Values()){
                if(commission.Invoice__c != null){
                    setInvoice.add(commission.Invoice__c); 
                }
            }
        }
        list<Invoice__c> lstinvoice = [Select Id,
                                        Total_Commissions_Paid__c,
                                        (Select Invoice__c,
                                        Amount_Paid__c 
                                        From Commissions__r)
                                    From Invoice__c 
                                    Where Id IN : setInvoice];
system.debug('*****Issue update'+lstinvoice);
    if(lstinvoice != null && !lstinvoice.isEmpty()){    
       for(Invoice__c objInvoice: lstinvoice){ 
            totalAmountPaid = 0;
           for(Commission__c objcommission: objInvoice.Commissions__r){
                totalAmountPaid = totalAmountPaid + decimalValue(objcommission.Amount_Paid__c);
            }
            objInvoice.Total_Commissions_Paid__c = totalAmountPaid;
            invoiceListResult.add(objInvoice);
        }
        if(!invoiceListResult.isEmpty()){
            update invoiceListResult;
        }
    }
  }
  
  public void OpportunityUpdate(map<Id, Commission__c> mapNewCommissionList, map<Id, Commission__c> mapOldCommissionList){
   set<Id> setOppId = new set<Id>();// to  fetch  related opportunity
        decimal totalcommissionPaid = 0;// to count commission paid
        decimal totaloverridePaid=0;// to count overide paid
        list<Opportunity> opportunityListResult = new list<Opportunity>(); // list of opportunity that will be updated
        //for insert and update
        if (mapNewCommissionList!= null){
            for(Commission__c commission: mapNewCommissionList.Values()){
                if(commission.Opportunity__c!= null){
                    setOppId.add(commission.Opportunity__c); 
                }
            }
        }// for update and delete
        if (mapOldCommissionList!= null){
            for(Commission__c commission: mapOldCommissionList.Values()){
                if(commission.Opportunity__c!= null){
                    setOppId.add(commission.Opportunity__c); 
                }
            }
        }
        list<Opportunity> oppList=[Select o.Total_Override_Paid__c, 
                                          o.Total_Commission_Paid__c,
                                          o.Id,
                                          (Select Status__c,
                                                        Amount_Paid__c, 
                                                        Type__c 
                                                  From Commissions__r) 
                                          From Opportunity o
                                          where o.Id in : setOppId];
                                          
        if(oppList != null && !oppList.isEmpty()){
           for(Opportunity objOpp: oppList){
               totalcommissionPaid=0;
               totaloverridePaid=0;
               for(Commission__c objcommission: objOpp.Commissions__r){ 
                   if (objcommission.Status__c=='Paid' && objcommission.Type__c<>'Override'){
                       totalcommissionPaid=totalcommissionPaid+decimalValue(objcommission.Amount_Paid__c);
                   }else if(objcommission.Status__c=='Paid' && objcommission.Type__c=='Override')
                   {
                       totaloverridePaid=totaloverridePaid+decimalValue(objcommission.Amount_Paid__c);
                   }
               }//end commission loop
               objOpp.Total_Commission_Paid__c=totalcommissionPaid;
               objOpp.Total_Override_Paid__c=totaloverridePaid;
               opportunityListResult.add(objOpp);
           }//end opportunity loop
           if(!opportunityListResult.isEmpty()){
            update opportunityListResult;
           }//end result
        }//end if 
  }
  
  //to convert null value into decimal
  public decimal decimalValue(decimal decValue){
        return(decValue!=null?decValue:0);
  } 
}