CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Hours_Credited_This_Month__c</fullName>
        <description>Hours credited this month</description>
        <label>Hours Credited - This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Previous_Month__c</fullName>
        <label>Hours Previous Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_This_Month__c</fullName>
        <label>DEPRECIATED Hours This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/ResetProjectHoursThisMonthBatchable.cls
global with sharing class ResetProjectHoursThisMonthBatchable implements Database.Batchable<sObject> {

    public String query;
    global string mailContent=' ';
    public ResetProjectHoursThisMonthBatchable() {
        query = 'Select Name, Id, Hours_This_Month__c,Hours_Credited_This_Month__c, Hours_Previous_Month__c From HarvestProject__c';
    }
    global Database.QueryLocator start(Database.BatchableContext bContext) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bContext, list<HarvestProject__c> projectScopeList) {
        List<HarvestProject__c> toUpdateProjectList = new List<HarvestProject__c>();
        for(HarvestProject__c projectObj :projectScopeList) {
            projectObj.Hours_Previous_Month__c = projectObj.Hours_This_Month__c;
            projectObj.Hours_This_Month__c = 0;
            projectObj.Hours_Credited_This_Month__c=0;
            toUpdateProjectList.add(projectObj);
        }
        List<Database.SaveResult> results = database.update (toUpdateProjectList, false);
                for (Database.SaveResult result : results) {
                    if (!result.isSuccess()){
                        for (Database.Error err : result.getErrors()){
                          mailContent=mailcontent + 'Error: '+ err.getStatusCode() + ' ' + err.getMessage() +'</br>';
                        }
                    }
                }
    }
    global void finish(Database.BatchableContext bContext) {
      if (mailContent!=' '){
                SendErrorMail.sendErrorLog(mailContent);
      }
    }
}