CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>LastHarvestSync__c</fullName>
        <label>Last Harvest Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ProjectCodeExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>If your Harvest project already has a PROJECT CODE, enter the project code here to use the code in Harvest as the external key. If you leave this field blank, then populate the Project Code in Harvest with the auto-generated Project Code from this record.</inlineHelpText>
        <label>Project Code External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncStatus__c</fullName>
        <inlineHelpText>Indicates the status of pairing the salesforce.co HarvestProject record to an associated Project record in Harvest.</inlineHelpText>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Status Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Harvest Project Linked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harvest Project Not Found</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/HarvestTimeEntry__c.object
<CustomObject>
    <description>Time entries mirrored in Harvest using Harvest2Salesforce Connect.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>Date of time entry if tracking time by duration vs. start and end time.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>Duration of time in decimal format.  Eg., 2.75 = 2 hours and 45 minutes.</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HarvestEntryId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field is the unique ID of a time card in HarvestApp.</inlineHelpText>
        <label>Harvest Entry Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HarvestProject__c</fullName>
        <inlineHelpText>Project time is related to.</inlineHelpText>
        <label>HarvestProject</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>HarvestTimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates this time card has been invoiced in Harvest</inlineHelpText>
        <label>Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Description of time / notes</inlineHelpText>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <inlineHelpText>Name/Alias of person logging time.</inlineHelpText>
        <label>Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <inlineHelpText>Type of time.  These values are maintained in Harvest and are one-way Harvest--&gt;SFDC.</inlineHelpText>
        <label>Task Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{YYYY}-{MM}-{0}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings contain the credentials and URL of the HarvestApp org that is to be synced with this SFDC org.</description>
    <fields>
        <fullName>HarvestURL__c</fullName>
        <label>Harvest URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LastSync__c</fullName>
        <label>Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Settings</label>
</CustomObject>

CMBSandbox4/src/classes/HarvestIntegrationImpl.cls
public class HarvestIntegrationImpl implements HarvestIntegration {
	
	public static final String SYNC_STATUS_PROJECT_NOT_FOUND = 'Harvest Project Not Found'; 
	private HarvestService service;
	private Settings__c settings;
	private Logger log = DependencyManager.getLogger();
	
	public HarvestIntegrationImpl() {
		settings = [SELECT HarvestURL__c, Username__c, Password__c, 
			LastSync__c FROM Settings__c LIMIT 1];
		service = DependencyManager.getHarvestService(settings.Username__c, settings.Password__c,
		settings.HarvestURL__c);
		service.populateTasks();			
		service.populatePeople();		
		service.populateProjectIdMap();		
	}
	
	public HarvestIntegrationImpl(Boolean deferPrefetch) {
		if (deferPrefetch) {
			settings = [SELECT HarvestURL__c, Username__c, Password__c, 
				LastSync__c FROM Settings__c LIMIT 1];			
			service = DependencyManager.getHarvestService(settings.Username__c, settings.Password__c,
				settings.HarvestURL__c);
		} 
		else {
			this();
		}
	}
	
	public void populateTasks() {
		service.populateTasks();			
	}
	
	public void populatePeople() {
		service.populatePeople();		
	}
	
	public void populateProjectIdMap() {
		service.populateProjectIdMap();		
	}
	
	public void syncTimeEntriesForProjectId(String projectId) {
		DateTime startTime = Datetime.now();
		HarvestProject__c project = [SELECT Id, ProjectCodeExternalId__c 
			FROM HarvestProject__c WHERE Id = :projectId LIMIT 1];
		List<HarvestTimeEntry__c> sfEntries = new List<HarvestTimeEntry__c>();
		List<HarvestEntry> entries = null;
		try {
			entries = service.getEntriesForProject(project.ProjectCodeExternalId__c);
			project.SyncStatus__c = 'Harvest Project Linked';
			project.LastHarvestSync__c = startTime;
			for (HarvestEntry entry : entries) {
				HarvestTimeEntry__c sfEntry = sfEntryFromHarvestEntry(entry);
				sfEntry.HarvestProject__r = new HarvestProject__c(
					ProjectCodeExternalId__c = project.ProjectCodeExternalId__c);
				System.debug(sfEntry);
				sfEntries.add(sfEntry);
			}
		}
		catch (HarvestException e) {
			if (e.getMessage().startsWith(
				HarvestException.EXCEPTION_HARVEST_PROJECT_NOT_FOUND)) {
				project.SyncStatus__c = SYNC_STATUS_PROJECT_NOT_FOUND;					
			}
		}
		if (sfEntries.size() > 0) {
			upsertTimeEntries(sfEntries, true);
		}
		project.LastHarvestSync__c = startTime;
		update project;
	}
	
	public void archiveProject(Id projectId) {
		String harvestId = harvestIdFromSalesforceId(projectId);
		service.deactivateProject(harvestId); 
	}
	
	public void unarchiveProject(Id projectId) {
		String harvestId = harvestIdFromSalesforceId(projectId);
		service.activateProject(harvestId);
	}
	
	private String harvestIdFromSalesforceId(Id projectId) {
		String projectCode = [
			SELECT ProjectCodeExternalId__c FROM HarvestProject__c WHERE Id = :projectId
		].ProjectCodeExternalId__c;
		String harvestId = service.getHarvestProjectId(projectCode);
		return harvestId;		
	}
	
	private void upsertTimeEntries(List<HarvestTimeEntry__c> entries, 
			Boolean deprecateMovedEntries) {
		List<Database.Upsertresult> results = Database.upsert(entries, 
			HarvestTimeEntry__c.fields.HarvestEntryId__c, false);
		List<HarvestTimeEntry__c> entriesToRetry = new List<HarvestTimeEntry__c>();
		List<Decimal> harvestEntryIdsToDeprecate = new List<Decimal>();
		for (Integer i = 0; i < results.size(); i++) {
			Database.Upsertresult result = results[i];
			HarvestTimeEntry__c entry = entries[i];
			if (!result.isSuccess()) { 
				if (result.getErrors()[0].getStatusCode() == 
					StatusCode.INVALID_FIELD_FOR_INSERT_UPDATE && deprecateMovedEntries) {
					entriesToRetry.add(entry);
					harvestEntryIdsToDeprecate.add(entry.HarvestEntryId__c);
				} 
				else {
					log.error('failed to upsert time entry: ' + result.getErrors()[0]);
				}
			} 
		}
		if (entriesToRetry.size() > 0) {
			deprecateTimeEntries(harvestEntryIdsToDeprecate);
			upsertTimeEntries(entriesToRetry, false);
		}
	}
	
	private void deprecateTimeEntries(List<Decimal> harvestEntryIds) {
		List<HarvestTimeEntry__c> entries = [SELECT Id FROM HarvestTimeEntry__c WHERE 
			HarvestEntryId__c IN :harvestEntryIds];
		for (HarvestTimeEntry__c entry : entries) {
			entry.Duration__c = 0;
			entry.Notes__c = 'time moved';
			entry.harvestEntryId__c = null;
		}
		List<Database.Saveresult> results = Database.update(entries, false);
		for (Integer i = 0; i < results.size(); i++) {
			Database.Saveresult result = results[i];
			HarvestTimeEntry__c entry = entries[i];
			if (!result.isSuccess()) {
				log.error('failued to update time entries. ' + result.getErrors()[0]);
			}
		}
	}
	
	private HarvestTimeEntry__c sfEntryFromHarvestEntry(HarvestEntry entry) {
		HarvestTimeEntry__c sfEntry = new HarvestTimeEntry__c();
		sfEntry.HarvestEntryId__c = entry.Id;
		sfEntry.HarvestProject__r = new HarvestProject__c(ProjectCodeExternalId__c = entry.ProjectCode);
		sfEntry.Date__c = entry.SpentAt;
		sfEntry.Duration__c = entry.Hours;
		sfEntry.Person__c = entry.Person;
		sfEntry.Task_Type__c = entry.Task;
		sfEntry.Notes__c = entry.Notes;
		sfEntry.Invoiced__c = entry.IsBilled;
		return sfEntry;
	}
}