CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>DateCompleted__c</fullName>
        <inlineHelpText>Date the project was completed.  Used to stop ticker on Project Days.</inlineHelpText>
        <label>Actual Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectCodeExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>If your Harvest project already has a PROJECT CODE, enter the project code here to use the code in Harvest as the external key. If you leave this field blank, then populate the Project Code in Harvest with the auto-generated Project Code from this record.</inlineHelpText>
        <label>Project Code External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/HarvestProjectIterator.cls
global class HarvestProjectIterator implements Iterator<HarvestProject__c> { 

	List<HarvestProject__c> projects { get; set; }
	Integer i { get; set; }
	 
	public HarvestProjectIterator() { 
		Date yesterday = Date.today().addDays(-1);
		projects = new List<HarvestProject__c>();
		projects.add(new HarvestProject__c(Name=HarvestSyncProjectsBatchable.TASK_PEOPLE));
		projects.add(new HarvestProject__c(Name=HarvestSyncProjectsBatchable.TASK_TASKS));
		projects.add(new HarvestProject__c(Name=HarvestSyncProjectsBatchable.TASK_PROJECTS));
		projects.addAll([SELECT Id, Name, ProjectCodeExternalId__c FROM HarvestProject__c
			WHERE DateCompleted__c >= :yesterday OR DateCompleted__c = null]);
		i = 0;
	}
	
	global boolean hasNext() { 
		return (i < projects.size());
	}
	
	global HarvestProject__c next() {
		return projects[i++];
	}
}