CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Total_Invoice_Hours__c</fullName>
        <label>Total Invoice Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Invoiced_Amount__c</fullName>
        <label>Total Invoiced Amount $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours (Manual)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Hours__c</fullName>
        <formula>Hours_Roll_Up__c  +  Adjustments__c +  Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isPaid__c</fullName>
        <formula>IF(ISPICKVAL(Status__c, &quot;Paid&quot;),true,false)</formula>
        <inlineHelpText>IF(ISPICKVAL(Status__c, &quot;Paid&quot;),true,false)</inlineHelpText>
        <label>isPaid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isSent__c</fullName>
        <formula>or(
 CONTAINS(TEXT(Status__c), &quot;Sent&quot;),
 not(isblank(Date_Sent__c ))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>or(
 CONTAINS(TEXT(Status__c), &quot;Sent&quot;),
 not(isblank(Date_Sent__c ))
)</inlineHelpText>
        <label>isSent</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <formula>(( Rate__c  *  Hours__c) +  Fixed_Fee__c ) -  Credit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HarvestProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>HarvestProject__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <formula>IF(NOT(ISBLANK(Finish__c)),((((Finish__c -  Start__c)*1440)/60 )-  Credit_Hrs_Formula__c ), (Hours_Num__c -  Credit_Hrs_Formula__c ))</formula>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/LineItemUpdatesProjectBatchable.cls
global with sharing class LineItemUpdatesProjectBatchable implements Database.Batchable<sObject>{
    
    public String query;
    global string mailContent=' ';
    
     public LineItemUpdatesProjectBatchable() {
        query = 'Select Id,Total_Invoice_Hours__c,Total_Invoiced_Amount__c,'+
                                                  '(Select Fee__c, Hours__c '+
                                                  'From Invoice_Line_Items__r'+ 
                                                  ' where Invoice__r.isSent__c=true OR Invoice__r.isPaid__c=true)'+
                        'From HarvestProject__c';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bContext) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bContext, list<HarvestProject__c> projectScopeList) {
        system.debug('projectScopeList'+projectScopeList);
        List<HarvestProject__c> toUpdateProjectList = new List<HarvestProject__c>();
        decimal totalInvoicedFee=0;
        decimal totalHours=0;
            for (HarvestProject__c objproject: projectScopeList){
                totalInvoicedFee=0;
                totalHours=0;
                for (Line_Item__c objlineitem:objproject.Invoice_Line_Items__r ){
                    totalInvoicedFee=totalInvoicedFee +decimalValue(objlineitem.Fee__c);
                    totalHours=totalHours+decimalValue(objlineitem.Hours__c);
                }
                objproject.Total_Invoice_Hours__c=totalHours;
                objproject.Total_Invoiced_Amount__c=totalInvoicedFee;
                toUpdateProjectList.add(objproject);
            }
            List<Database.SaveResult> results = database.update (toUpdateProjectList, false);
                for (Database.SaveResult result : results) {
                    if (!result.isSuccess()){
                        for (Database.Error err : result.getErrors()){
                          mailContent=mailcontent + 'Error: '+ err.getStatusCode() + ' ' + err.getMessage() +'</br>';
                      }
                 }
            }
      }
    global void finish(Database.BatchableContext bContext) {
      if (mailContent!=' '){
                SendErrorMail.sendErrorLog(mailContent);
      }
    }
    
     public decimal decimalValue(decimal decValue){
        return(decValue!=null?decValue:0);
  } 
}