CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/HarvestProjectManager.cls
public class HarvestProjectManager {
	
	public void toggleArchived(Id projectId) { 
		HarvestIntegration integration = DependencyManager.getHarvestIntegration(false);
		HarvestProject__c project = [
			SELECT Archived__c FROM HarvestProject__c WHERE Id = :projectId
		];
		if (project.Archived__c) {
			integration.unarchiveProject(projectId); 
		}
		else {
			integration.archiveProject(projectId);
		}
		project.Archived__c = !project.Archived__c;
		update project;
	}
}