CMBSandbox4/src/objects/HarvestProject__c.object
<CustomObject>
    <description>Project object used by the Harvest&lt;&gt;SFDC system integration when client does not already have a custom object for managing projects.  For help or more information, visit http://www.akacrm.com/salesforce/harvest2salesforce.html.</description>
    <fields>
        <fullName>ProjectCode__c</fullName>
        <displayFormat>PID-{0}</displayFormat>
        <inlineHelpText>Auto-assigned project ID.  Used to sync to Harvest.</inlineHelpText>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/HarvestSyncProjectEntriesController.cls
public class HarvestSyncProjectEntriesController { 

    private final HarvestProject__c project;
    private final ApexPages.StandardController controller;
    public String ErrorMessage { get; set; }
    
    public HarvestSyncProjectEntriesController(ApexPages.StandardController cont) {
        project = (HarvestProject__c) cont.getRecord();
        controller = cont;
    }
    
    public PageReference sync() {
        PageReference pr = null;
        if (project.ProjectCode__c != null) {
            HarvestIntegration integration = DependencyManager.getHarvestIntegration(false);
            try {
            	integration.syncTimeEntriesForProjectId(project.Id);
            	pr = controller.view();
            }
            catch (Exception e) {
            	ErrorMessage = e.getMessage();
            }
        }
        return pr;
    }
    
    public PageReference toProject() {
    	return controller.view();
    }
    
}