CMBSandbox4/src/objects/Interview__c.object
<CustomObject>
    <label>Interview</label>
    <nameField>
        <label>Interview  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

LendersApp/src/objects/UWVerification__c.object
<CustomObject>
    <fields>
        <fullName>Interview__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interview</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Verifications</relationshipLabel>
        <relationshipName>Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VerificationMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Verification Master</label>
        <referenceTo>VerificationMaster__c</referenceTo>
        <relationshipName>UW_Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Verification</label>
    <nameField>
        <label>Verification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/VerificationMaster__c.object
<CustomObject>
    <label>Verification Master</label>
    <nameField>
        <label>Verification Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verification Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/VerificationSelectControllerTest.cls
@isTest
private class VerificationSelectControllerTest {
    
    @isTest
    public static void validateVerificationSelect() {
    
        Account objAcc = new Account();
        objAcc.Name = 'testAccountName';
        insert objAcc;
        
        List<Opportunity> lstOpp = new List<Opportunity>();
        Opportunity objDeal = new Opportunity();
        objDeal.AccountId = objAcc.id;
        objDeal.Name = 'testDealName';
        objDeal.StageName = 'Prospecting';
        objDeal.CloseDate = date.today().addDays(5);
        lstOpp.add(objDeal);
        insert lstOpp;
        
        UWVerification__c objUWV = new UWVerification__c();
        objUWV.Opportunity__c = objDeal.id;
        objUWV.Name = 'testUWVerificationName';
        objUWV.interview__c = true;
        insert objUWV;
        
        VerificationMaster__c objVM = new VerificationMaster__c ();
        objVM.Name = 'testName';
        insert objVM;
        
        ApexPAges.StandardsetController sc = new ApexPages.StandardsetController(lstOpp);
        VerificationSelectController con = new VerificationSelectController (sc);
        con.dealId = objDeal.id;
        con.SaveAndClose();
        con.done();
        con.newVerification();
    }
}