CMBSandbox4/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>BK_Policy__c</fullName>
        <label>BK Policy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Amt_of_Monthly_Gross_Sales__c</fullName>
        <inlineHelpText>What is the multiple that this bank typically funds as a ratio to the merchant&apos;s monthly gross sales volume</inlineHelpText>
        <label>Funding Amt - % of Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Amount__c</fullName>
        <label>Max. Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_No_NSFs__c</fullName>
        <label>Max# NSFs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Methods_of_Repayment__c</fullName>
        <label>Method of Repayment</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holdback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Daily_Bal__c</fullName>
        <label>Min. Avg Daily Bal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_CC_Avg__c</fullName>
        <label>Min. Monthly CC Avg $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Deposits__c</fullName>
        <label>Min. Monthly Deposits</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Advance__c</fullName>
        <label>Minimum Advance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Deposit_Count__c</fullName>
        <inlineHelpText>Number of days per month where deposits are made into the bank account.</inlineHelpText>
        <label>Min. Monthly Bank Deposit Count</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ownership_Percentage_Requirement__c</fullName>
        <label>Ownership Percentage Requirement</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percentage_Net_After_Payoff__c</fullName>
        <label>Percentage Net After Payoff</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Program_Directory_Status__c</fullName>
        <label>Program Directory Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Program Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Restricted_Industry_List__c</fullName>
        <label>Restricted Industry List</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apparel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machinery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not For Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Restricted_States__c</fullName>
        <label>Restricted States</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Site_Inspection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Site Inspection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submission_Email__c</fullName>
        <label>Submission Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Tax_Lean_Policy__c</fullName>
        <label>Tax Lean Policy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_References__c</fullName>
        <label>Trade References</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required - 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required - 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required - 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Count__c</fullName>
        <label>Transaction Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Turnaround_Time__c</fullName>
        <inlineHelpText>The time (days) it takes the Bank to process an application and respond with an approval or decline.</inlineHelpText>
        <label>Turnaround Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Min. Years in Business</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CMBSandbox4/src/classes/Program.cls
global with sharing class Program {

    public String  name;
    public String  bkPolicy;
    public String  externalBank;
    public Double  fundingAmtofMonthlyGrossSales;
    public Double  maxAmount;
    public Double  maxNoNSFs;
    public Double  minAvgDailyBal;
    public String  methodsOfRepayment;
    public Double  creditScore;
    public Double  minCreditScore;
    public Double  minimumDepositCount;
    public Double  minMonthlyCCAvg;
    public Double  minMonthlyDeposits;
    public Double  yearsinBusiness;
    public Double  minimumAdvance;
    public String  notes;
    public Double  ownershipPercentageRequirement;
    public Double  percentageNetAfterPayoff;
    public String  programId;
    public String  programDirectoryStatus;
    public String  restrictedIndustryList;
    public String  restrictedStates;
    public Boolean siteInspection;
    public String  submissionEmail;
    public String  taxLeanPolicy;
    public String  tradeReferences;
    public Double  transactionCount;
    public Double  turnaroundTime;
    public RequiredDocument[] requiredDocuments;
    
    
    public Program(Program__c p) {
    	name                           = p.Name;
	    bkPolicy                       = p.BK_Policy__c;
	    externalBank                   = p.External_Bank__c;
	    fundingAmtofMonthlyGrossSales  = p.Funding_Amt_of_Monthly_Gross_Sales__c;
	    maxAmount                      = p.Max_Amount__c;
	    maxNoNSFs                      = p.Max_No_NSFs__c;
	    minAvgDailyBal                 = p.Min_Avg_Daily_Bal__c;
	    methodsOfRepayment             = p.Methods_of_Repayment__c;
	    creditScore                    = p.Credit_Score__c;
	    minCreditScore                 = p.Min_Credit_Score__c;
	    minimumDepositCount            = p.Minimum_Deposit_Count__c;
	    minMonthlyCCAvg                = p.Min_Monthly_CC_Avg__c;
	    minMonthlyDeposits             = p.Min_Monthly_Deposits__c;
	    yearsinBusiness                = p.Years_in_Business__c;
	    minimumAdvance                 = p.Minimum_Advance__c;
	    notes                          = p.Notes__c;
	    ownershipPercentageRequirement = p.Ownership_Percentage_Requirement__c;
	    percentageNetAfterPayoff       = p.Percentage_Net_After_Payoff__c;
	    programId                      = p.Program_Id__c;
	    programDirectoryStatus         = p.Program_Directory_Status__c;
	    restrictedIndustryList         = p.Restricted_Industry_List__c;
	    restrictedStates               = p.Restricted_States__c;
	    siteInspection                 = p.Site_Inspection__c;
	    submissionEmail                = p.Submission_Email__c;
	    taxLeanPolicy                  = p.Tax_Lean_Policy__c;
	    tradeReferences                = p.Trade_References__c;
	    transactionCount               = p.Transaction_Count__c;
	    turnaroundTime                 = p.Turnaround_Time__c;
	    requiredDocuments              = new RequiredDocument[]{};
    }

}