CMBSandbox4/src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings contain the credentials and URL of the HarvestApp org that is to be synced with this SFDC org.</description>
    <fields>
        <fullName>AutoSyncFrequencyInHours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Auto-Sync Frequency In Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Settings</label>
</CustomObject>

CMBSandbox4/src/classes/SettingsModelTest.cls
@isTest
private class SettingsModelTest {

	@isTest
	private static void AutoSyncFrequencyChangedIsFalseByDefautl() { 
		Settings__c settings = new Settings__c(Name = 'Test1');
		SettingsModel model = new SettingsModel(settings);
		System.assertEquals(false, model.AutoSyncFrequencyChanged);
	}
	
	@isTest
	private static void cronJobExistsReturnsFalse() {
		Settings__c settings = new Settings__c(Name = 'Test1');
		settings.AutoSyncFrequencyInHours__c = 2;
		SettingsModel model = new SettingsModel(settings);
		System.assertEquals(0, model.AutoSyncFrequencyInHours = 0);
	}

}