CMBSandbox4/src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings contain the credentials and URL of the HarvestApp org that is to be synced with this SFDC org.</description>
    <fields>
        <fullName>AutoSyncFrequencyInHours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Auto-Sync Frequency In Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HarvestURL__c</fullName>
        <label>Harvest URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LastSync__c</fullName>
        <label>Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledJobId__c</fullName>
        <label>ScheduledJobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Settings</label>
</CustomObject>

CMBSandbox4/src/classes/SettingsModel.cls
public class SettingsModel {
	
	public Boolean AutoSyncFrequencyChanged { get; private set; }
	public String HarvestUrl { get; set; }
	public DateTime LastSync { get; set; }
	public String Username { get; set; }
	public String Password { get; set; }
	public Integer AutoSyncFrequencyInHours { 
		get; 
		set {
			if (AutoSyncFrequencyInHours != value) {
				AutoSyncFrequencyInHours = value;
				AutoSyncFrequencyChanged = true;
			}
		} 
	}
	public String ScheduledJobId { get; set; }
	
	public SettingsModel() {
		
	}
	
	public SettingsModel(Settings__c settings) {
		HarvestUrl = settings.HarvestUrl__c;
		LastSync = settings.LastSync__c;
		Username = settings.Username__c;
		Password = settings.Password__c;
		if (settings.AutoSyncFrequencyInHours__c > 0 
			&& cronJobExists(settings.ScheduledJobId__c)) {
			AutoSyncFrequencyInHours = settings.AutoSyncFrequencyInHours__c.intValue();		
		}
		else {
			AutoSyncFrequencyInHours = 0;
		}
		ScheduledJobId = settings.ScheduledJobId__c;
		AutoSyncFrequencyChanged = false;
	}
	
	private Boolean cronJobExists(ID jobId) {
		Integer cronTriggerCount = [SELECT COUNT() FROM CronTrigger WHERE Id = :jobId];
		return cronTriggerCount == 1;
	}
	
}