MCA App/Release/Release 2.13/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCA App/Release/Release 2.8/Core Package Org/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Average_Daily_Balance__c</fullName>
        <inlineHelpText>Average Daily Balance from the business bank accounts. This will usually come from the bank statements received from the Merchant.</inlineHelpText>
        <label>Average Daily Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Owner 1 Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Deposits__c</fullName>
        <label>Monthly Deposits</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
    <fields>
        <fullName>Industry__c</fullName>
        <formula>text(Account.Industry)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Industry</label>
        <type>Text</type>
    </fields>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/OrgwideEmailAddress__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The custom setting is used to allow use of org wide email for outgoing email sent from  submission wizard</description>
    <fields>
        <fullName>IsOrgwideEmailAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check will determine whether to use org wide email or not for the email sent out from submission wizard</description>
        <label>IsOrgwideEmailAllowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgEmailAddress__c</fullName>
        <label>OrgEmailAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OrgwideEmailAddress</label>
</CustomObject>

MCA App/Release/Release 2.8/Core Package Org/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funding_Amt_of_Monthly_Gross_Sales__c</fullName>
        <inlineHelpText>What is the multiple that this bank typically funds as a ratio to the merchant&apos;s monthly gross sales volume</inlineHelpText>
        <label>Funding % of Monthly Gross</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apparel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machinery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not For Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Amount__c</fullName>
        <label>Max. Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_NDBs__c</fullName>
        <label>Max NDBs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_No_NSFs__c</fullName>
        <label>Max# NSFs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Daily_Bal__c</fullName>
        <label>Min. Avg Daily Bal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Deposits__c</fullName>
        <label>Min. Monthly Deposits</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Deposit_Count__c</fullName>
        <inlineHelpText>Number of days per month where deposits are made into the bank account.</inlineHelpText>
        <label>Min. Monthly Bank Deposit Count</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preffered_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preferred Programs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Restricted_States__c</fullName>
        <label>Restricted States</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Hampshire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Jersey</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Submission_Email__c</fullName>
        <label>Submission Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Min. Years in Business</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Required_Documents__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Required Documents</relationshipLabel>
        <relationshipName>Required_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Required Document</label>
    <nameField>
        <label>Required Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submissions</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.8/Core Package Org/src/classes/SubmissionWizardControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of SubmissionWizardController
 * 
 *  Date - 12-02-2014
 *
 *  Created By - Sneha P.
 */
@isTest(OnInstall=false)
private class SubmissionWizardControllerTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        //Insert Custom setting record
       // list<OrgwideEmailAddress__c> lstSorgWideEmail =createOrgWideEmail(1);
        //insert lstSorgWideEmail;
        OrgwideEmailAddress__c lstOrgWideEmail = new OrgwideEmailAddress__c();
        lstOrgWideEmail.Name= 'SubmissionOrgWideEmail';
        lstOrgWideEmail.IsOrgwideEmailAllowed__c = true;
        lstOrgWideEmail.OrgEmailAddress__c = 'gabriel@cloudmybiz.com';
        insert lstOrgWideEmail;

        list<Submission_Mails_Detail__c> lstSubmissionMailsDetail = createSubmissionMailsDetail(1);
        insert  lstSubmissionMailsDetail;
        //Create Acc
        Account acc = createAccount('TestAcc',0);
        
        list<Attachment> lstAttachments = SubmissionWizardControllerTest.createAttachments(3, acc.Id);
        insert lstAttachments;

        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.Id, StageName ='Prospecting' ,
                                         CloseDate = System.today(), Credit_Score__c = 20,Average_Daily_Balance__c=100 );
        insert opp;

        //Create Programs
        list<Program__c> lstPrograms = SubmissionWizardControllerTest.createPrograms(8);
        insert lstPrograms;

        Required_Documents__c reqdDoc = new Required_Documents__c(Name = 'Doc 1',Program__c = lstPrograms[0].Id);
        insert reqdDoc;
        Test.startTest();
        PageReference pageRef = Page.SubmissionWizard;
        pageRef.getParameters().put('Id', opp.Id);
        pageRef.getParameters().put('accId', acc.Id);
        pageRef.getParameters().put('isSelected', 'true');

        test.setCurrentPage(pageRef);

        SubmissionWizardController cntl = new SubmissionWizardController();
        
        //Check if 2 programs are displayed
        //system.assertEquals(cntl.programWrapperList.size(), 10);
        cntl.getPrograms();
        //system.assert(cntl.programWrapperList.size() == 3);

        //system.assertEquals(cntl.displayPopup, true);
        // && cntl.prgmDocMap.size() == 1);
        cntl.closePopup();

        cntl.getMapSize();
        cntl.resetAttachments();

        cntl.AttachmentWrapperList[0].selectedPrograms.add(lstAttachments[0].id);
        cntl.AttachmentWrapperList[0].selectedPrograms.add(lstAttachments[1].id);
        cntl.programWrapperList[0].isSelected = true;
        cntl.mailsDetails.add(lstSubmissionMailsDetail[0]);
        cntl.sendWithoutAttachment();
        cntl.sendSelectedAttachments();
        
        cntl.AttachmentWrapperList[0].isRequired = false;
        cntl.sendSelectedAttachments();
        
        cntl.AttachmentWrapperList.clear();
        cntl.sendSelectedAttachments();
        
        cntl.mailsDetails.clear();
        cntl.sendSelectedAttachments();
        cntl.openAttachment();

        cntl.cancel();
        cntl.clearFilter();
        cntl.getStates();
        cntl.getSortDirection();
        cntl.setSortDirection('Desc');
        cntl.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        cntl.programWrapperList.sort();
        SubmissionWizardController.sortDirection = 'DESC';
        cntl.programWrapperList.sort();
        map<Id,list<Attachment>> mapPgmAttachment = new map<Id,list<Attachment>>();
        mapPgmAttachment.put(lstAttachments[0].Id,lstAttachments);
        cntl.sendMail(mapPgmAttachment);

        cntl.program.Credit_Score__c = 20;
        cntl.program.Years_in_Business__c = 5;
        cntl.program.Min_Monthly_Deposits__c = 1000;
        cntl.program.Minimum_Deposit_Count__c = 10;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = 5;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = true;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Commission_Percentage__c';
        cntl.getPrograms();
        
        cntl.programMap.put(cntl.programWrapperList[0].prgm.Id, cntl.programWrapperList[0].prgm);
        //Check if the required documents are shown in popup on click of button
        cntl.checkReqdDocument();
        
        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = 5;
        cntl.program.Min_Monthly_Deposits__c = 1000;
        cntl.program.Minimum_Deposit_Count__c = 10;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = 5;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = true;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Max_Amount__c';
        cntl.getPrograms();
        
        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = 1000;
        cntl.program.Minimum_Deposit_Count__c = 10;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = 5;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = true;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Max_No_NSFs__c';
        cntl.getPrograms();
        
        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = 1000;
        cntl.program.Minimum_Deposit_Count__c = 10;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = 5;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Max_NDBs__c';
        cntl.getPrograms();

        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = null;
        cntl.program.Minimum_Deposit_Count__c = 10;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = 5;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Min_Monthly_Deposits__c';
        cntl.getPrograms();

        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = null;
        cntl.program.Minimum_Deposit_Count__c = null;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = 5;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Minimum_Deposit_Count__c';
        cntl.getPrograms();

        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = null;
        cntl.program.Minimum_Deposit_Count__c = null;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = null;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = true;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Years_in_Business__c';
        cntl.getPrograms();
        
        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = null;
        cntl.program.Minimum_Deposit_Count__c = null;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = null;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = false;
        cntl.program.Preffered_Programs__c = true;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Min_Avg_Daily_Bal__c';
        cntl.getPrograms();
        
        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = null;
        cntl.program.Minimum_Deposit_Count__c = null;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = null;
        cntl.program.Max_NDBs__c = 5;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = false;
        cntl.program.Preffered_Programs__c = false;
        SubmissionWizardController.sortDirection = 'ASC';
        SubmissionWizardController.sortExp = 'Credit_Score__c';
        cntl.getPrograms();
        
        cntl.program.Credit_Score__c = null;
        cntl.program.Years_in_Business__c = null;
        cntl.program.Min_Monthly_Deposits__c = null;
        cntl.program.Minimum_Deposit_Count__c = null;
        cntl.program.Industry__c = 'Government';
        cntl.program.Min_Avg_Daily_Bal__c = 100;
        cntl.program.Max_No_NSFs__c = null;
        cntl.program.Max_NDBs__c = null;
        cntl.restrictedIndustry = false;
        cntl.restrictedState = false;
        cntl.program.Preffered_Programs__c = false;
        SubmissionWizardController.sortDirection = 'DESC';
        SubmissionWizardController.sortExp = 'Funding_Amt_of_Monthly_Gross_Sales__c';
        cntl.getPrograms();
        Test.stopTest();
    }
    static testMethod void testCreateWoSending() {

        OrgwideEmailAddress__c lstOrgWideEmail = new OrgwideEmailAddress__c();
        lstOrgWideEmail.Name= 'SubmissionOrgWideEmail';
        lstOrgWideEmail.IsOrgwideEmailAllowed__c = true;
        lstOrgWideEmail.OrgEmailAddress__c = 'gabriel@cloudmybiz.com';
        insert lstOrgWideEmail;
        
        Account acc = createAccount('TestAcc',0);

        list<Attachment> lstAttachments = SubmissionWizardControllerTest.createAttachments(3, acc.Id);
        insert lstAttachments;

        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.Id, StageName ='Prospecting' ,
                                         CloseDate = System.today());
        insert opp;

        //Create Programs
        list<Program__c> lstPrograms = SubmissionWizardControllerTest.createPrograms(8);
        insert lstPrograms;

        Test.startTest();
        PageReference pageRef = Page.SubmissionWizard;
        pageRef.getParameters().put('Id', opp.Id);
        pageRef.getParameters().put('accId', acc.Id);
        pageRef.getParameters().put('isSelected', 'true');
       // pageRef.getParameters().put('attId', lstAttachments[0].Id);
        test.setCurrentPage(pageRef);

        SubmissionWizardController cntl = new SubmissionWizardController();

        system.debug('****'+cntl.programWrapperList);
        cntl.programWrapperList[0].isSelected = true;
        cntl.programWrapperList[1].isSelected = true;
        cntl.programWrapperList[2].isSelected = true;

        cntl.resetAttachments();
        cntl.programMap.clear();
        cntl.createWithoutSending();

        list<Submission__c> submissionList = [Select Id, Name, Opportunity__c 
                                               from Submission__c 
                                               where Opportunity__c =: opp.Id ] ;
        system.assert(submissionList.size() == 3);
        map<Id,list<Attachment>> mapPgmAttachment = new map<Id,list<Attachment>>();
        mapPgmAttachment.put(lstAttachments[0].Id,lstAttachments);
        cntl.sendMail(mapPgmAttachment);
        Test.StopTest();
    }

    static testMethod void myUnitTest2() {
        OrgwideEmailAddress__c lstOrgWideEmail = new OrgwideEmailAddress__c();
        lstOrgWideEmail.Name= 'SubmissionOrgWideEmail';
        lstOrgWideEmail.IsOrgwideEmailAllowed__c = true;
        lstOrgWideEmail.OrgEmailAddress__c = 'gabriel@cloudmybiz.com';
        insert lstOrgWideEmail;

        Account acc = createAccount('TestAcc',0);

        list<Attachment> lstAttachments = SubmissionWizardControllerTest.createAttachments(3, acc.Id);
        insert lstAttachments;

        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.Id, StageName ='Prospecting' ,
                                         CloseDate = System.today());
        insert opp;

        //Create Programs
        list<Program__c> lstPrograms = SubmissionWizardControllerTest.createPrograms(8);
        insert lstPrograms;
        system.debug('11111&&&&&111111'+lstPrograms);
        Required_Documents__c reqdDoc = new Required_Documents__c(Name = 'Doc 1',Program__c = lstPrograms[0].Id);
        insert reqdDoc;
        Test.startTest();
        PageReference pageRef = Page.SubmissionWizard;
        pageRef.getParameters().put('Id', opp.Id);
        pageRef.getParameters().put('accId', acc.Id);
        pageRef.getParameters().put('isSelected', 'true');
        pageRef.getParameters().put('attId', lstAttachments[0].Id);
        test.setCurrentPage(pageRef);

        SubmissionWizardController cntl = new SubmissionWizardController();
        system.debug('22222&&&&&2222'+cntl.programWrapperList);
        cntl.programWrapperList[0].isSelected = true;
        cntl.programWrapperList[1].isSelected = true;
        cntl.programWrapperList[2].isSelected = true;
        cntl.resetAttachments();

        cntl.AttachmentWrapperList[0].selectedPrograms.add(lstAttachments[0].id);
        cntl.AttachmentWrapperList[0].selectedPrograms.add(lstAttachments[1].id);
        try{ 
            cntl.checkUncheckAttachements();
            cntl.mailsDetails.clear();
            cntl.sendWithoutAttachment();
            cntl.sendSelectedAttachments();
            cntl.selectDeselectAtt1();
            map<Id,list<Attachment>> mapPgmAttachment = new map<Id,list<Attachment>>();
            mapPgmAttachment.put(lstAttachments[0].Id,lstAttachments);
            cntl.sendMail(mapPgmAttachment);
        }catch(Exception e){

        system.assert(e.getMessage() == system.label.Submission_EmailLimitExceeded);
      }
        Test.stopTest();
    }//End myUnitTest2 method.

    static testMethod void myUnitTest3() {
        OrgwideEmailAddress__c lstOrgWideEmail = new OrgwideEmailAddress__c();
        lstOrgWideEmail.Name= 'SubmissionOrgWideEmail';
        lstOrgWideEmail.IsOrgwideEmailAllowed__c = true;
        lstOrgWideEmail.OrgEmailAddress__c = 'gabriel@cloudmybiz.com';
        insert lstOrgWideEmail;

        Account acc = createAccount('TestAcc',0);

        list<Attachment> lstAttachments = SubmissionWizardControllerTest.createAttachments(3, acc.Id);
        insert lstAttachments;
        Map<Id,Program__c> programMap = new Map<Id,Program__c>();
        Program__c objProgram = new Program__c ();
        objProgram.Name= 'Test Program' ;
        objProgram.Preffered_Programs__c = true;
        objProgram.Credit_Score__c = 20 ;
        objProgram.Years_in_Business__c = 5 ; 
        objProgram.Industry__c = 'Government';
        objProgram.Restricted_States__c = 'CO';
        objProgram.Min_Monthly_Deposits__c = 100;
        objProgram.Max_No_NSFs__c =10;
        objProgram.Submission_Email__c = 'test@gmail.com';

        insert objProgram;

        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.Id, StageName ='Prospecting' ,
                                         CloseDate = System.today(),
                                         Avg_Number_Bank_Deposits__c=12,
                                         Average_Daily_Balance__c = 12,
                                         Gross_monthly_Sales__c = 200);
        insert opp;
        
        //Create Programs
        list<Program__c> lstPrograms = SubmissionWizardControllerTest.createPrograms(8);
        insert lstPrograms;
        
        Required_Documents__c reqdDoc = new Required_Documents__c(Name = 'Doc 1',Program__c = objProgram.Id);
        insert reqdDoc;
        Test.startTest();
        PageReference pageRef = Page.SubmissionWizard;
        pageRef.getParameters().put('Id', opp.Id);
        pageRef.getParameters().put('accId', acc.Id);
        pageRef.getParameters().put('isSelected', 'true');
        pageRef.getParameters().put('attId', lstAttachments[0].Id);
        test.setCurrentPage(pageRef);

        SubmissionWizardController cntl = new SubmissionWizardController();
        cntl.programMap.put(objProgram.Id,objProgram);
        cntl.program.Years_in_Business__c = 5;
        cntl.program.Min_Monthly_Deposits__c= 100;
        cntl.program.Min_Avg_Daily_Bal__c = 50;
        cntl.program.Minimum_Deposit_Count__c = 40;
        cntl.program.Max_No_NSFs__c = 10;
        cntl.program.Max_NDBs__c = 5;
        cntl.program.Preffered_Programs__c = true;
        cntl.clearFilter();
        cntl.getPrograms();
        system.debug('****programMap***'+programMap);
        cntl.programWrapperList[0].isSelected = true;
        cntl.programWrapperList[1].isSelected = true;
        cntl.programWrapperList[2].isSelected = true;
        cntl.resetAttachments();
        
        cntl.AttachmentWrapperList[0].selectedPrograms.add(lstAttachments[0].id);
        cntl.AttachmentWrapperList[0].selectedPrograms.add(lstAttachments[1].id);
        try{  
            cntl.checkUncheckAttachements();
            cntl.sendWithoutAttachment();
            cntl.sendSelectedAttachments();
            cntl.selectDeselectAtt1();
            map<Id,list<Attachment>> mapPgmAttachment = new map<Id,list<Attachment>>();
            mapPgmAttachment.put(lstAttachments[0].Id,lstAttachments);
            cntl.sendMail(mapPgmAttachment);
        }catch(Exception e){
            
            system.assert(e.getMessage() == system.label.Submission_EmailLimitExceeded);
        }
        Test.stopTest();
    }//End myUnitTest2 method.

    //The method will create dummy records of Attachments.
    public static list<Attachment> createAttachments(Integer pCount, Id pAccountId){
        list<Attachment> lstTempAttachments = new list<Attachment>();
        for(Integer index = 0; index <= pCount; index++){
            lstTempAttachments.add(new Attachment(Name = 'Test Doc' + index, 
                                                  ParentId = pAccountId, 
                                                  Body = Blob.valueOf('Test Attachment' + index)));
        }
                
        return lstTempAttachments;
    }//End createAttachments method.
    
    
    //The method will create dummy records of Account.
    public static Account createAccount(String pName,Integer cnt){
        Account acc = new Account(Name = pName,Email__c = 'test@test.com'+cnt, Industry = 'Government', BillingState = 'CO', Years_in_Business__c = 6,
                                    NSFs_Avg__c = 5, NDBs_Avg__c = 5, Gross_monthly_Sales__c = 100);
        insert acc;
        return acc;
    }
    
    //The method will create dummy records of Program.
    public static list<Program__c> createPrograms(Integer pCount){
        list<Program__c> lstTempPrograms = new list<Program__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstTempPrograms.add(new Program__c(Name= 'Test Program' + index,
                                               Credit_Score__c = 20 + index,
                                               Min_Monthly_Deposits__c = 100,
                                               Minimum_Deposit_Count__c = 10,
                                               Restricted_Industry_List__c = 'Construction',
                                               Min_Avg_Daily_Bal__c = 100,
                                               Max_No_NSFs__c =5,
                                               Max_NDBs__c = 5,
                                               Years_in_Business__c = 1 + index,
                                               Preffered_Programs__c = true,
                                               Restricted_States__c = 'AK',
                                               Funding_Amt_of_Monthly_Gross_Sales__c = 100,
                                               Submission_Email__c = 'test' + index + '@gmail.com',
                                               Submission_Email_CC_1__c= 'test' + index + '@gmail.com',
                                               Submission_Email_CC_2__c= 'test' + index + '@gmail.com'));
        }//End for.
        return lstTempPrograms;
    }//End createPrograms method.
    
    //The method will create dummy records of SubmissionMailsDetail.
    public static list<Submission_Mails_Detail__c> createSubmissionMailsDetail(Integer pCount){
        list<Submission_Mails_Detail__c> lstSubmissionMailsDetail = new list<Submission_Mails_Detail__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstSubmissionMailsDetail.add(new Submission_Mails_Detail__c(Name= 'Test Program' + index,
                                               Is_Active__c = true,
                                               Message_Body__c = 'Test',
                                               Subject__c = 'Test Subject',
                                               CC_Address__c = 'test' + index + '@gmail.com',
                                               Bcc_Address__c = 'test' + index + '@gmail.com'));
        }//End for.
        return lstSubmissionMailsDetail;
    }//End SubmissionMailsDetail method.

    //The method will create dummy records of OrgWideEmail.
    public static list<OrgwideEmailAddress__c> createOrgWideEmail(Integer pCount){
        list<OrgwideEmailAddress__c> lstOrgWideEmail = new list<OrgwideEmailAddress__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstOrgWideEmail.add(new OrgwideEmailAddress__c(Name= 'SubmissionOrgWideEmail',
                                               IsOrgwideEmailAllowed__c = true,
                                               OrgEmailAddress__c = 'gabriel@cloudmybiz.com'
                                               ));
        }//End OrgWideEmail.
        return lstOrgWideEmail;
    }//End createOrgWideEmail method.
/*    
    public static list<Submission__c> createsubmission( ){ 
    list<Submission__c> lstSubmission = new list<Submission__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstSubmissionMailsDetail.add(new Submission__c(Name= 'Test Program' + index,
                                               Opportunity__c = true,
                                               Status__c = 'UW',
                                               Program__c = ,
                                               CC_Address__c = 'test' + index + '@gmail.com'));
        }//End for.
          return lstSubmission;
    }//End
    
    */
}