MCA App/Release/Release 2.13/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>
</CustomObject>

MCA App/Release/Release 2.140/src/objects/Loan_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daily_Payment__c</fullName>
        <label>Daily Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Balances</relationshipLabel>
        <relationshipName>Loan_Balances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Balances</relationshipLabel>
        <relationshipName>Loan_Balances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Balance</label>
    <nameField>
        <displayFormat>BAL-{00000}</displayFormat>
        <label>Loan Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Balances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/classes/MCALoanBalanceTabController.cls
public with sharing class MCALoanBalanceTabController {
  
 // public String inlineEdit {get; set;}

  public Loan_Balance__c[] loanBalances;
  public Container[] containers;

  public Loan_Balance__c[] newLoanBalances {get; set;}

  public Boolean editAll {get;set;}
  public Boolean isFirst;
  public Id recordToDelete {get;set;}
  public Integer indexToRemove {get;set;}

  private Id opportunityId;

  public Decimal balanceTotal {get; set;}
  public Decimal paymentTotal {get; set;}
  
  public List<Account> banklist {get; Set;}
  public Integer bankSize {get; set;}
  
  public boolean funderPicklist{get; set;}
  public Boolean isUpdated;
  public Map<Id, Loan_Balance__c> mapIDANDloanBalance;
  public List<Loan_Balance__c> listToUpdate;
  public Boolean isValidation;
  
  public MCALoanBalanceTabController() {
    isFirst=true;
    isValidation = false;
    mapIDANDloanBalance = new Map<Id, Loan_Balance__c>();
    opportunityId = Apexpages.currentPage().getParameters().get('id');
   // inlineEdit = 'false';
    funderPicklist = false;
    refresh();
  }

  public Container[] getContainers() {

    balanceTotal = 0;
    paymentTotal = 0;
    loanBalances = new Loan_Balance__c[] {};
    loanBalances.addAll(newLoanBalances);
    if(isFirst && !editAll && !isValidation) {
        isFirst=false;
        for (Loan_Balance__c lb :[SELECT
                                        Id,
                                        Active__c,
                                        Balance__c,
                                        Daily_Payment__c,
                                        Funder__c,
                                        Maturity_Date__c,
                                        Name,
                                        Notes__c 
                                    FROM Loan_Balance__c
                                    WHERE Opportunity__c = :opportunityId]) {
        loanBalances.add(lb);
        balanceTotal += lb.Balance__c != null ? lb.Balance__c : 0;
        paymentTotal += lb.Daily_Payment__c != null ? lb.Daily_Payment__c : 0;
        system.debug('****Inside query***'+loanBalances);
        }
    }else{
        for (Container containerVal: containers) {
            if (recordToDelete!=null){
                if(containerVal.loanBalance.id<> recordToDelete){
                    loanBalances.add(containerVal.loanBalance);
                }
            }else if(containerVal.index!=indexToRemove) {
                   loanBalances.add(containerVal.loanBalance);
            }
            
       }
       //reinitializing for delete and remove
       recordToDelete=null;
       indexToRemove=-99;
    }
    containers = new Container[] {};
    for (Integer i = 0; i < loanBalances.size(); i++) {
      containers.add(new Container(loanBalances[i], i));
    }
    newLoanBalances=new List<Loan_Balance__c>();
    getBankNames();
    return containers;
  }
    
  
  public void newLoanBalance() {
    saveMessage();
    newLoanBalances.add(new Loan_Balance__c(Opportunity__c = opportunityId));
  }
  
  public void saveMessage(){
    isUpdated = false;
    checkoldAndNewVal();
    if(editAll !=true && isUpdated == true){
        ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.Info,'All changes have been saved.'));
        updateInlineEditedValue();
    }
  }
  
  public void loanBalanceList(){
    mapIDANDloanBalance.clear();
    mapIDANDloanBalance = new Map<Id, Loan_Balance__c>([SELECT
                                                        Id,
                                                        Active__c,
                                                        Balance__c,
                                                        Daily_Payment__c,
                                                        Funder__c,
                                                        Maturity_Date__c,
                                                        Name,
                                                        Notes__c 
                                                    FROM Loan_Balance__c
                                                    WHERE Opportunity__c = :opportunityId]);
  }
  public void updateInlineEditedValue() {
        try{
            update listToUpdate;
        }
        catch(Exception e){
            system.debug('***Enter In Exception****');
            ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.Info,e.getMessage()));
        }
    }
    public void checkoldAndNewVal() {
        listToUpdate = new List<Loan_Balance__c>();
        Loan_Balance__c  LoanBalenceValue = new Loan_Balance__c ();
        loanBalanceList();
        for (Container containerVal: containers) {
            if(containerVal.loanBalance.id != null){
                LoanBalenceValue = mapIDANDloanBalance.get(containerVal.loanBalance.id);
                if(LoanBalenceValue!= null) {       
                    if(containerVal.loanBalance.Active__c != LoanBalenceValue.Active__c
                    || containerVal.loanBalance.Balance__c != LoanBalenceValue.Balance__c
                    || containerVal.loanBalance.Daily_Payment__c != LoanBalenceValue.Daily_Payment__c
                    || containerVal.loanBalance.Funder__c != LoanBalenceValue.Funder__c
                    || containerVal.loanBalance.Maturity_Date__c != LoanBalenceValue.Maturity_Date__c
                    || containerVal.loanBalance.Name != LoanBalenceValue.Name
                    || containerVal.loanBalance.Notes__c  != LoanBalenceValue.Notes__c) {
                        listToUpdate.add(containerVal.loanBalance);
                        isUpdated = true;
                    }
                }
            }
        }
    }

  public void refresh() {
   balanceTotal = 0;
    paymentTotal = 0;   
    isFirst=true;
    editAll = false;
    recordToDelete = null;
    newLoanBalances = new Loan_Balance__c[] {};
    containers = new Container[] {};
  }
  
   public List<SelectOption> getBankNames()
    {
      List<SelectOption> options = new List<SelectOption>();
      List<RecordType> bankRecordTypeId = [Select r.Name, r.Id From RecordType r where r.Name = 'Bank'];
      banklist = new List<Account>();
      if(bankRecordTypeId.size() > 0)
        banklist = [Select Id, Name, RecordTypeId FROM Account where RecordTypeId =: bankRecordTypeId[0].Id  order by Name];
      bankSize = banklist.size();
      //options.add(new SelectOption('','--None--'));
      for (Integer j=0;j<banklist.size();j++)
      {
          String bankName = banklist[j].Name;
          options.add(new SelectOption(banklist[j].Id,bankName));
      }
      system.debug('*****options getBankNames****'+options);
      
      return options;
    }
  
   public void editAll() {
    editAll = true;
  }

  public void save(){}
  public void saveAllLoans() {
    isValidation = false;
    try{
        upsert loanBalances;
    }
    catch(Exception e){
        isValidation = true;
        ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.Info,e.getMessage()));
    }
    refresh();
  }

  public void deleteLoanBalance() {
    saveMessage();
    if (recordToDelete != null) {
      Loan_Balance__c record = [SELECT Id FROM Loan_Balance__c WHERE Id = :recordToDelete];
      delete record;
    }
  }

  public void removeLoanBalance() {
    saveMessage();
  }

  public class Container {

    public Loan_Balance__c loanBalance {get;set;}
    public Integer index {get;set;}

    public Container(Loan_Balance__c instance, Integer index) {
      loanBalance = instance;
      this.index = index;
    }

  }

}