MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCA App/Release/Release 2.13/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Contact.object
<CustomObject>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

MCA App/Release/Release 2.140/src/objects/Credit_Card__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Card Sales</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Card Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Loan_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Balances</relationshipLabel>
        <relationshipName>Loan_Balances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Balances</relationshipLabel>
        <relationshipName>Loan_Balances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Balance</label>
    <nameField>
        <displayFormat>BAL-{00000}</displayFormat>
        <label>Loan Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Balances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.8/Core Package Org/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Opportunity.object
<CustomObject>
</CustomObject>

MCA App/Release/MCA Dev Org/src/objects/Opportunity.object
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>

MCA App/Release/MCA Dev Org/src/objects/Opportunity.object
    <fields>
        <fullName>Stips__c</fullName>
        <label>Stips</label>
        <length>32768</length>
        <type>Html</type>
    </fields>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Payable__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>PAYB-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Stips__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Items_Needed</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipName>Items_Needed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stips</label>
    <nameField>
        <label>Stips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submissions</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.12/src/objects/Syndication__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Syndication</relationshipLabel>
        <relationshipName>Syndication</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Syndication</label>
    <nameField>
        <displayFormat>SYND-{00000}</displayFormat>
        <label>Syndication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Syndications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/Release 2.1/Source Code v2.1/MCA Packaging Org/src/classes/MCABaseTabControllerTest.cls
@isTest(seeAllData=true)
public with sharing class MCABaseTabControllerTest {

  private static Opportunity objOpportunity = null;
  private static Bank_Account__c  ba = null;  
  private static Credit_Card__c cc = null;
  private static Submission__c s = null;
  private static Offer__c o = null;
  private static Task t = null;
  private static OpportunityContactRole ocr = null;
  private static Loan_Balance__c lb = null;
  private static Syndication__c sy = null;
  private static Stips__c st = null;
  private static Payable__c py = null;  
  private static Receivable__c rc = null; 
  
  static testMethod void coverSalesHistoryTabController() {

    setOpportunityParameter();
    MCASalesHistoryTabController controller = new MCASalesHistoryTabController();
    controller.getContainersCards();
    controller.getContainersStatements();
    controller.refresh();
    //controller.saveAll();
    controller.newCredit();
    controller.newStatement();
    controller.getContainersCards();
    controller.getContainersStatements();    
    system.debug(controller.getContainersCards());
    controller.indexToRemove = 0;
    controller.removeCard();
    controller.indexToRemove = 0;
    controller.removeStatement();
    controller.recordToDelete = cc.Id;
    controller.deleteCredit();
    controller.recordToDelete = ba.id;
    controller.deleteStatement();
    controller.editAll();
    
    MCABaseTabController controller1 = new MCABaseTabController('McaApp__Payable__c');
    controller1.objectName = 'McaApp__Payable__c';
    controller1.refresh();
    controller1.editAll();
    controller1.deleteRecord();
    controller1.getRecords();
    controller1.newRecord();
    controller1.newRecord();
    controller1.objectName = 'Bank_Account__c';
    MCABaseTabControllerUtils.getQuery('Bank_Account__c');
    controller1.objectName = 'Credit_Card__c';
    MCABaseTabControllerUtils.getQuery('Credit_Card__c');
    controller1.objectName = 'Submission__c';
    MCABaseTabControllerUtils.getQuery('Submission__c');
    controller1.objectName = 'Offer__c';
    MCABaseTabControllerUtils.getQuery('Offer__c');
    controller1.objectName = 'Stips__c';
    MCABaseTabControllerUtils.getQuery('Stips__c');
    controller1.objectName = 'Payable__c';
    MCABaseTabControllerUtils.getQuery('Payable__c');
    controller1.objectName = 'Receivable__c';
    MCABaseTabControllerUtils.getQuery('Receivable__c');
    controller1.objectName = 'Syndication__c';
    MCABaseTabControllerUtils.getQuery('Syndication__c');
    controller1.objectName = 'Loan_Balance__c';
    MCABaseTabControllerUtils.getQuery('Loan_Balance__c');
    controller1.objectName = 'OpportunityContactRole';
    MCABaseTabControllerUtils.getQuery('OpportunityContactRole');
    controller1.objectName = 'Task';
    MCABaseTabControllerUtils.getQuery('Task');
    controller1.saveAll();
  } 
  
  static testMethod void coverSubmissionsTabController() {

    setOpportunityParameter();
    MCASubmissionsTabController controller = new MCASubmissionsTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newSubmission();
    controller.getContainers();
    controller.indexToRemove = 0;
    controller.removeSubmission();
    controller.recordToDelete = s.Id;
    controller.deleteSubmission();
    controller.editAll();
  } 
  
  static testMethod void coverOfferTabController() {

    setOpportunityParameter();
    MCAOffersTabController controller = new MCAOffersTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newOffer();
    controller.getContainers();
    controller.indexToRemove = 0;
    controller.removeOffer();
    controller.recordToDelete = o.Id;
    controller.deleteOffer();
    controller.editAll();
  } 
  
  static testMethod void coverCommissionsTabController() {

    setOpportunityParameter();
    MCACommissionsTabController controller = new MCACommissionsTabController();
    controller.getPayables();
    controller.getReceivables();
    controller.refresh();
    //controller.saveAll();
    controller.newPayable();
    controller.newReceivable();
    controller.getPayables();
    controller.getReceivables();    
    controller.indexToRemove = 0;
    controller.removePayable();
    controller.indexToRemove = 0;
    controller.removeReceivable();
    
    controller.recordToDelete = py.Id;
    controller.deletePayable();
    controller.recordToDelete = rc.Id;
    controller.deleteReceivable();
    controller.editAll();
    
  } 
  
  static testMethod void coverStipsTabController() {

    setOpportunityParameter();
    MCAStipsTabController controller = new MCAStipsTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newStip();    
    controller.getContainers();
    controller.indexToRemove = 0;
    controller.removeStip();
    controller.recordToDelete = st.Id;
    controller.deleteStip();
    controller.editAll();
  }           
  
  static testMethod void coverSyndicationsTabController() {


    setOpportunityParameter();
    MCASyndicationTabController controller = new MCASyndicationTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newSyndication();    
    controller.getContainers();
    controller.indexToRemove = 0;
    controller.removeSyndication();
    controller.recordToDelete = sy.Id;
    controller.deleteSyndication();
    controller.editAll();
  } 
  
  static testMethod void coverLoansTabController() {


    setOpportunityParameter();
    MCALoanBalanceTabController controller = new MCALoanBalanceTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newLoanBalance();   
    controller.getContainers();
    controller.indexToRemove = 0;
    controller.removeLoanBalance();
    controller.recordToDelete = lb.Id;
    controller.deleteLoanBalance();
    controller.editAll();  
  }     
  
  static testMethod void coverContactsTabController() {

    setOpportunityParameter();
    MCAContactRolesTabController controller = new MCAContactRolesTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newContactRole();
    controller.getContainers();
    controller.indexToRemove = 0;
    controller.removeContactRole();
    controller.recordToDelete = ocr.Id;
    controller.deleteContactRole();
    controller.editAll();
  } 
  
  static testMethod void coverTasksTabController() {

    setOpportunityParameter();
    MCATasksTabController controller = new MCATasksTabController();
    controller.getContainers();
    controller.refresh();
    //controller.saveAll();
    controller.newTask();
    controller.getContainers();    
    controller.indexToRemove = 0;
    controller.removeTask();
    controller.editAll();
  }     

  
  private static void setOpportunityParameter() {
    
    createObjects();
    Apexpages.currentPage().getParameters().put('id', objOpportunity.Id);
    
  }

  private static void createObjects() {
  
    objOpportunity = new Opportunity(Name='Opp1', CloseDate = System.today(), StageName='Prospecting', ForecastCategoryName='Pipeline' );
    insert objOpportunity;
    
    Id opportunityId = objOpportunity.Id;
    
    Contact contact = new Contact(LastName = 'Test Contact'); 
    insert contact;
    
    string recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Bank').getRecordTypeId();
    
    Account account = new Account(Name = 'Test Account',RecordTypeId = recordTypeId);
    //account.RecordTypeId = recordTypeId;
    insert account;
    
    ba = new Bank_Account__c(Opportunity__c = opportunityId);
    insert ba;
    
    cc = new Credit_Card__c(Opportunity__c = opportunityId);
    insert cc;
    
    s = new Submission__c(Opportunity__c = opportunityId);
    insert s;
    
    o = new Offer__c(Opportunity__c = opportunityId, Submission__c = s.Id);
    insert o;
    
    t = new Task(WhatId = opportunityId, Status= 'Not Started', Priority = 'Normal');
    //insert t;
    
    ocr = new OpportunityContactRole(OpportunityId = opportunityId, ContactId = contact.Id);
    insert ocr;
    
    lb = new Loan_Balance__c(Opportunity__c = opportunityId, Funder__c = account.Id);
    insert lb;
    
    sy = new Syndication__c(Opportunity__c = opportunityId);
    insert sy;
    
    st = new Stips__c(Opportunity__c = opportunityId);
    insert st;
    
    py = new Payable__c(Opportunity__c = opportunityId);
    insert py;
    
    rc = new Receivable__c(Opportunity__c = opportunityId);
    insert rc;
    
  }


}