Bluewolf SFMTA/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Event_End__c</fullName>
        <label>Event End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start__c</fullName>
        <label>Event Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <inlineHelpText>Please enter just the number of the street address for the requested location. Not a mailing address.</inlineHelpText>
        <label>Street Address Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <inlineHelpText>Please enter the Street Name for the requested location. This is not a mailing address.</inlineHelpText>
        <label>Street Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uninstall_Date__c</fullName>
        <label>Uninstall Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Bluewolf SFMTA/src/objects/Error_Log__c.object
<CustomObject>
    <description>Object to keep track of errors from API callouts</description>
    <fields>
        <fullName>Trace__c</fullName>
        <label>Trace</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bluewolf SFMTA/src/objects/GeoCodingApi__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Google Maps Geocoding API Key</description>
    <fields>
        <fullName>Key__c</fullName>
        <description>Goecoding API Key</description>
        <label>Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>Geocoding URL</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>GeoCodingApi</label>
</CustomObject>

Bluewolf SFMTA/src/classes/CaseServices.cls
public  with sharing class CaseServices {
    public static void UpdateGeoCodes(List<Case> triggerNew, Map<id, Case> triggerOldMap){
        List<Id> caseList = new List<Id>();
        Boolean isInsert = (triggerOldMap == null ? true : false);
        
        for(Case newCase: triggerNew)
        {
            if(isInsert == true || newCase.Street_Address__c != triggerOldMap.get(newCase.id).Street_Address__c ||  newCase.Street_Name__c != triggerOldMap.get(newCase.id).Street_Name__c){
                caseList.add(newCase.id);                
            }
        }
        
        if(caseList.size() > 0 && !Test.isRunningTest() && !System.isFuture()){
            RetrieveGeoCodes(caseList);
        }
    }

    @future(callout = true)
    public static void RetrieveGeoCodes(List<Id> caseList){
        GeoCodingApi__c customSetting = GeoCodingApi__c.getValues('GeocodingDetails');
        List<Case> updatedCaseList = new List<Case>();
        String geoCodeApiKey = customSetting.Key__c;
        String geoCodeApiURL =customSetting.URL__c;
        try{
        List<Case> cases = [SELECT Id, Street_Name__c, Street_Address__c FROM Case WHERE id IN :caseList];
        for (Case caseVal : cases){
            geoCodeApiURL += 'address=';
            string streetAddress;
            if(caseVal.Street_Address__c != null || caseVal.Street_Address__c != ''){
                streetAddress = caseVal.Street_Address__c + ' ' + caseVal.Street_Name__c;
            }
            else{
                streetAddress = caseVal.Street_Name__c;
            }
            geoCodeApiURL += EncodingUtil.urlEncode(streetAddress+' ' + 'San'+' ' + 'Francisco' + ' ' + 'CA','UTF-8')+'&key='+geoCodeApiKey;
            Http h = new Http(); 
            HttpRequest req = new HttpRequest();

            req.setHeader('Content-type', 'application/x-www-form-urlencoded'); 
            req.setHeader('Content-length', '0'); 
            req.setEndpoint(geoCodeApiURL); 
            req.setMethod('POST');
            
            HttpResponse res = h.send(req); 
           
            // Parse JSON response to get all the field values.
        	JSONParser parser = JSON.createParser(res.getBody());
            while (parser.nextToken() != null){
                if((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'location')){
                    parser.nextToken();
                    parser.nextToken();
                    if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'lat')) {
                            parser.nextToken();
                            caseVal.Case_Location__Latitude__s = Decimal.valueOf(parser.getText());
                    }
                    parser.nextToken();
                    if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'lng')) {
                        parser.nextToken();
                        caseVal.Case_Location__Longitude__s = Decimal.valueOf(parser.getText());
                    }   
                    break;
                } 
            }
            updatedCaseList.add(caseVal);
        } 
        upsert updatedCaseList;
        }
        catch(System.Exception ex){
            LogExceptions(ex);
        }
    }
    
    //Insert exceptions into Custom object
    public static void LogExceptions(Exception ex){
        Error_Log__c log = new Error_Log__c();
        log.Trace__c = 'Type: ' + ex.getTypeName() + '\n' + 'Cause: ' + ex.getCause() + '\n' + 'Message: ' + ex.getMessage();
        insert log;  
    }

    /*
    //moved to controller for sharing reasons
    public static Case GetCaseByCaseNumber(String caseNumber){
        Case results = new Case();
        for(Case cs :[SELECT Id, CaseNumber, 
            Install_Date__c, Uninstall_Date__c, Event_Start__c, Event_End__c,
            Case_Location__Longitude__s, Case_Location__Latitude__s, RecordType.Name  
            FROM Case 
            WHERE CaseNumber = :caseNumber 
            limit 1]){

            results = cs;
        }
        return results;
    }
    */
}