MCA App/Release/MCA Packaging Org/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_Sales__c</fullName>
        <label>Gross monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NDBs_Avg__c</fullName>
        <description>The average of # NDBs of all Bank Statement records related to the Account</description>
        <inlineHelpText>The average of # NDBs of all Bank Statement records related to the Account</inlineHelpText>
        <label># NDBs Avg</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSFs_Avg__c</fullName>
        <description>The average of # NSFs of all Bank Statement records related to the Account</description>
        <inlineHelpText>The average of # NSFs of all Bank Statement records related to the Account</inlineHelpText>
        <label># NSFs Avg</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCA App/Release/MCA Packaging Org/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Contact.object
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Credit Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

MCA App/Release/MCA Packaging Org/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Average_Daily_Balance__c</fullName>
        <inlineHelpText>Average Daily Balance from the business bank accounts. This will usually come from the bank statements received from the Merchant.</inlineHelpText>
        <label>Average Daily Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Avg_Number_Bank_Deposits__c</fullName>
        <inlineHelpText>The average number of monthly bank deposits.</inlineHelpText>
        <label>Avg. # Bank Deposits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Owner 1 Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Account.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_Sales__c</fullName>
        <label>Gross monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Deposits__c</fullName>
        <label>Monthly Deposits</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NDBs_avg__c</fullName>
        <inlineHelpText>Average of Bank Account NDBs</inlineHelpText>
        <label># NDBs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSFs_avg__c</fullName>
        <inlineHelpText>Average of Bank Account NSFs</inlineHelpText>
        <label># NSFs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner 1</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Business Owner contact can only show in Owner 1 field.</errorMessage>
            <filterItems>
                <field>Contact.Contact_Roles__c</field>
                <operation>equals</operation>
                <value>Business Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/OrgwideEmailAddress__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The custom setting is used to allow use of org wide email for outgoing email sent from  submission wizard</description>
    <fields>
        <fullName>IsOrgwideEmailAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The check will determine whether to use org wide email or not for the email sent out from submission wizard</description>
        <label>IsOrgwideEmailAllowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgEmailAddress__c</fullName>
        <label>OrgEmailAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OrgwideEmailAddress</label>
</CustomObject>

MCA App/Release/MCA Packaging Org/src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bank</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Bank</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <label>Commission %</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funding_Amt_of_Monthly_Gross_Sales__c</fullName>
        <inlineHelpText>What is the multiple that this bank typically funds as a ratio to the merchant&apos;s monthly gross sales volume</inlineHelpText>
        <label>Funding % of Monthly Gross</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Amount__c</fullName>
        <label>Max. Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_NDBs__c</fullName>
        <label>Max NDBs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_No_NSFs__c</fullName>
        <label>Max# NSFs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Daily_Bal__c</fullName>
        <label>Min. Avg Daily Bal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Deposits__c</fullName>
        <label>Min. Monthly Deposits</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Deposit_Count__c</fullName>
        <inlineHelpText>Number of days per month where deposits are made into the bank account.</inlineHelpText>
        <label>Min. Monthly Bank Deposit Count</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preffered_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preferred Programs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Restricted_Industry_List__c</fullName>
        <label>Restricted Industry List</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apparel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machinery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not For Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Min. Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Required_Documents__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Required Documents</relationshipLabel>
        <relationshipName>Required_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Required Document</label>
    <nameField>
        <label>Required Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Packaging Org/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submissions</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA App/Release/MCA Packaging Org/src/classes/SubmissionWizardControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of SubmissionWizardController
 * 
 *  Date - 12-02-2014
 *
 *  Created By - Sneha P.
 */
@isTest(OnInstall=false)
private class SubmissionWizardControllerTest {

    
    static testMethod void submissionWizardValidTest() {
        Account acc = createAccount('TestAcc',1);
        
        Contact con = createContact('TestAcc',1);
         
        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.Id, StageName ='Prospecting' ,
                                         CloseDate = System.today(),Credit_Score__c = 20, Average_Daily_Balance__c=100,
                                         NSFs_Avg__c = 5, NDBs_Avg__c = 5, Avg_Number_Bank_Deposits__c = 100,
                                         Owner_1__c = con.id);
        insert opp;
         
        list<Program__c> lstPrograms = SubmissionWizardControllerTest.createPrograms(25);
        insert lstPrograms;
        
        OrgwideEmailAddress__c lstOrgWideEmail = new OrgwideEmailAddress__c();
        lstOrgWideEmail.Name= 'SubmissionOrgWideEmail';
        lstOrgWideEmail.IsOrgwideEmailAllowed__c = true;
        lstOrgWideEmail.OrgEmailAddress__c = 'gabriel@cloudmybiz.com';
        insert lstOrgWideEmail;
        
        list<Attachment> lstAttachments = SubmissionWizardControllerTest.createAttachments(2, acc.Id);
        insert lstAttachments;
        
        Required_Documents__c reqdDoc = new Required_Documents__c(Name = 'Doc 1',Program__c = lstPrograms[0].Id);
        insert reqdDoc;
        
        list<Submission_Mails_Detail__c> lstSubmissionMailsDetail = createSubmissionMailsDetail(1);
        insert  lstSubmissionMailsDetail;
        
        PageReference pageRef = Page.SubmissionWizard;
        pageRef.getParameters().put('Id', opp.Id);
        pageRef.getParameters().put('accId', acc.Id);
        pageRef.getParameters().put('isSelected', 'true');
        test.setCurrentPage(pageRef);
        SubmissionWizardController controller = new SubmissionWizardController();
        
        controller.clearFilter();
        controller.creditScore = string.ValueOf(20);
        controller.minMonthlyDeposite = string.valueOf(100);
        controller.minDepositeCount =  string.valueOf(10);
        controller.maxNSFs = string.ValueOf(5);
        controller.maxNDBs = string.ValueOf(5);
        controller.yearInBusiness = string.valueOf(8);
        controller.minAvgDailyBalance = string.valueOf(100);
        controller.prefferedProgram = true;
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Credit_Score__c';
        controller.getPrograms();
        controller.showMore();
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Minimum_Deposit_Count__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Years_in_Business__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Bank__r.Name';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Name';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Min_Monthly_Deposits__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Max_NDBs__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Min_Avg_Daily_Bal__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Max_No_NSFs__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Max_Amount__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Commission_Percentage__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'DESC';
        controller.sortExpression = 'Funding_Amt_of_Monthly_Gross_Sales__c';
        controller.ViewSortedData_Program();
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Minimum_Deposit_Count__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Years_in_Business__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Bank__r.Name';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Name';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Min_Monthly_Deposits__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Max_NDBs__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Min_Avg_Daily_Bal__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Max_No_NSFs__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Max_Amount__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Commission_Percentage__c';
        controller.ViewSortedData_Program();
        SubmissionWizardController.sortDirection = 'ASC';
        controller.sortExpression = 'Funding_Amt_of_Monthly_Gross_Sales__c';
        controller.ViewSortedData_Program();
        controller.programMap.put(lstPrograms[0].Id, lstPrograms[0]);
        controller.mailsDetails.add(lstSubmissionMailsDetail[0]);
        
        controller.checkReqdDocument();
        controller.selectDeselectAtt1();
        controller.programWrapperList1[0].isSelected =true;
        controller.createWithoutSending();
        controller.sendWithoutAttachment();
        controller.sendSelectedAttachments();
        controller.resetAttachments();
        controller.cancel();
        controller.openAttachment();
        controller.closePopup();
        map<Id,list<Attachment>> mapPgmAttachment = new map<Id,list<Attachment>>();
        mapPgmAttachment.put(lstAttachments[0].Id,lstAttachments);
        
        try {
            List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();
            
            controller.sendMail(mapPgmAttachment);
        } catch(Exception ex) {
            
        }
        
    }

    //The method will create dummy records of Attachments.
    public static list<Attachment> createAttachments(Integer pCount, Id pAccountId){
        list<Attachment> lstTempAttachments = new list<Attachment>();
        for(Integer index = 0; index <= pCount; index++){
            lstTempAttachments.add(new Attachment(Name = 'Test Doc' + index, 
                                                  ParentId = pAccountId, 
                                                  Body = Blob.valueOf('Test Attachment' + index)));
        }
                
        return lstTempAttachments;
    }//End createAttachments method.
    
    
    //The method will create dummy records of Account.
    public static Account createAccount(String pName,Integer cnt){
        Account acc = new Account(Name = pName,Email__c = 'test@test.com'+cnt, Industry = 'Government', BillingState = 'CO', Years_in_Business__c = 6,
                                    NSFs_Avg__c = 5, NDBs_Avg__c = 5, Gross_monthly_Sales__c = 100);
        insert acc;
        return acc;
    }
    
    //The method will create dummy records of Contact.
    public static Contact createContact(String pName,Integer cnt){
        Contact con = new Contact(firstName = pName,lastname= pName,Email = 'test@test.com'+cnt );
        insert con;
        return con;
    }
    
    //The method will create dummy records of Program.
    public static list<Program__c> createPrograms(Integer pCount){
        list<Program__c> lstTempPrograms = new list<Program__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstTempPrograms.add(new Program__c(Name= 'Test Program' + index,
                                               Credit_Score__c = 20 + index,
                                               Min_Monthly_Deposits__c = 100 + index,
                                               Minimum_Deposit_Count__c = 10 + index,
                                               Restricted_Industry_List__c = 'Construction',
                                               Min_Avg_Daily_Bal__c = 100 + index,
                                               Max_No_NSFs__c =5 + index,
                                               Max_NDBs__c = 5 + index,
                                               Commission_Percentage__c = 10 + index,
                                               Funding_Amt_of_Monthly_Gross_Sales__c = 10 + index,
                                               Max_Amount__c = 100 + index,
                                               Years_in_Business__c = 1 + index,
                                               Preffered_Programs__c = true,
                                               Restricted_States__c = 'AK',                                               
                                               Submission_Email__c = 'test' + index + '@gmail.com',
                                               Submission_Email_CC_1__c= 'test' + index + '@gmail.com',
                                               Submission_Email_CC_2__c= 'test' + index + '@gmail.com'));
        }//End for.
        return lstTempPrograms;
    }//End createPrograms method.
    
    //The method will create dummy records of SubmissionMailsDetail.
    public static list<Submission_Mails_Detail__c> createSubmissionMailsDetail(Integer pCount){
        list<Submission_Mails_Detail__c> lstSubmissionMailsDetail = new list<Submission_Mails_Detail__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstSubmissionMailsDetail.add(new Submission_Mails_Detail__c(//Name= 'Test Program' + index,
                                               Is_Active__c = true,
                                               Message_Body__c = 'Test {!Opportunity.Name} AAA {!Opportunity.Account.Name} BBB' + 
                                                        '{!Opportunity.Owner_1__r.Name} ccc {!Program__c.Name} ddd {!SubmissionId}',
                                               Subject__c = 'Test Subject {!Opportunity.Account.Name}',
                                               CC_Address__c = 'test@gmail.com',
                                               Bcc_Address__c = 'test' + index + '@gmail.com'));
        }//End for.
        return lstSubmissionMailsDetail;
    }//End SubmissionMailsDetail method.

    //The method will create dummy records of OrgWideEmail.
    public static list<OrgwideEmailAddress__c> createOrgWideEmail(Integer pCount){
        list<OrgwideEmailAddress__c> lstOrgWideEmail = new list<OrgwideEmailAddress__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstOrgWideEmail.add(new OrgwideEmailAddress__c(Name= 'SubmissionOrgWideEmail',
                                               IsOrgwideEmailAllowed__c = true,
                                               OrgEmailAddress__c = 'gabriel@cloudmybiz.com'
                                               ));
        }//End OrgWideEmail.
        return lstOrgWideEmail;
    }//End createOrgWideEmail method.
    
    //The method will create dummy records of Submission.
    public static list<Submission__c> createsubmission(Integer pCount, Id oppId) { 
        list<Submission__c> lstSubmission = new list<Submission__c>();
        for(Integer index = 0; index <= pCount; index++) {
            lstSubmission.add(new Submission__c(//Name= 'Test Program' + index,
                                               Opportunity__c = oppId,
                                               //Program__c = progId,
                                               Status__c = 'UW'
                                               
                                               ));
                                               //CC_Address__c = 'test' + index + '@gmail.com'));
        }//End for.
        return lstSubmission;
    }//End createsubmission
/*    
    public static list<Submission__c> createsubmission( ){ 
    list<Submission__c> lstSubmission = new list<Submission__c>();
        for(Integer index = 0; index <= pCount; index++){
            lstSubmissionMailsDetail.add(new Submission__c(Name= 'Test Program' + index,
                                               Opportunity__c = true,
                                               Status__c = 'UW',
                                               Program__c = ,
                                               CC_Address__c = 'test' + index + '@gmail.com'));
        }//End for.
          return lstSubmission;
    }//End
    
    */
}