Bizfi Production/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Main_Phone__c</fullName>
        <label>Owner Direct Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>McaApp__Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Accounts History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

Bizfi Production/src/objects/Audit_Trail__c.object
<CustomObject>
    <description>Hold the data related to Opportunity/Lead Owner/Stage changes</description>
    <fields>
        <fullName>Current_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the information of the current owner when the stage changes.</description>
        <inlineHelpText>This field stores the information of the current owner when the stage changes.</inlineHelpText>
        <label>Current Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Stage__c</fullName>
        <description>This is for current stage when the owner gets change.</description>
        <inlineHelpText>This is for current stage when the owner gets change.</inlineHelpText>
        <label>Current Status / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Time_change_was_made__c</fullName>
        <label>Date/Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Status_Stage_value__c</fullName>
        <label>New Status / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Audit Trails</relationshipLabel>
        <relationshipName>Opportunity_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates weather it is stage change or status change.</description>
        <inlineHelpText>Indicates weather it is stage change or status change.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Status / Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organic Sub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Audit Trail History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Business_Main_Phone__c</fullName>
        <label>Owner 1 Direct Phone</label>
        <type>Phone</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
<CustomObject>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Transaction Line History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

Bizfi Production/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Generate_Sales_Rep_Scorecard__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for checking active user for generating scorecard.</description>
        <inlineHelpText>If checked, the user will have a scorecard generated at midnight daily.</inlineHelpText>
        <label>Generate Sales Rep Scorecard</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Bizfi Production/src/classes/ATTestDataUtility.cls
@isTest
Public Class ATTestDataUtility
{


    public static User generateTestUser(String userName,Profile  profile,String alias,String email)
    {

        return new User(Alias = alias,
                        Email= email,
                        EmailEncodingKey='UTF-8',
                        LastName='Testing',
                        LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US',
                        ProfileId = profile.Id,
                        TimeZoneSidKey='America/Los_Angeles',
                        UserName= userName,
                        Generate_Sales_Rep_Scorecard__c = true);

    }

    public static Lead generateTestLead()
    {

        return  new Lead(LastName = 'Last',
                            FirstName = 'first',
                            Status = 'Open',
                            Phone = '12345678',
                            Business_Main_Phone__c = '1234567890',
                            Business_Email__c = 'test@testmail.com',
                            Company = 'Company');

    }

    public static Task generateTestTaskOpportunity(String whatID)
    {

        return new Task(WhatId = whatID,
                        CallType ='Outbound',
                        Type = 'Call',
                        Subject = 'Test',
                        Description = 'Description',
                        Priority='Normal',
                        status='Completed');
    }

    public static Task generateTestTaskLead(String whoID)
    {
        return new Task(WhoId = whoID,
                        CallType ='Outbound',
                        Type = 'Call',
                        Subject = 'Test3123',
                        Description = 'Description',
                        Priority='Normal',
                        status='Completed');


    }


    public static Opportunity generateTestOpportunity()
    {
        return new Opportunity(Name = 'Test Opportunity',
                                StageName = 'Prospecting',
                                CloseDate = system.today());

    }

    public static Audit_trail__c generateTestAuditTrailForStatusChange(String objectName,
                                                                     String newStatus,
                                                                     String currentStatus,
                                                                     String type,
                                                                     Opportunity tempOpp,
                                                                     Lead tempLead,
                                                                     User userInstance,
                                                                     DateTime dtTime)
    {
        return new Audit_trail__c(Object__c = objectName,
                                  New_Status_Stage_value__c = newStatus,
                                  Current_Stage__c = currentStatus,
                                  Type__c = type,
                                  Opportunity__c = tempOpp.id,
                                  Current_owner__c = userInstance.id,
                                  Date_Time_change_was_made__c = dtTime);

    }

    public static List<Account> generateAccounts(Integer count) {
        List<Account> accounts = new List<Account>();
        for(Integer i = 0; i < count; i++) {
            accounts.add(new Account(
                Name = 'TestAccount' + i
            ));
        }
        return accounts;
    }

    public static List<Opportunity> generateOpportunities(Integer count, Id accountId) {
        List<Opportunity> opps = new List<Opportunity>();
        for(Integer i = 0; i < count; i++) {
            opps.add(new Opportunity(
                Name = 'TestOpp' + i,
                AccountId = accountId,
                StageName = 'Prospecting',
                CloseDate = Date.today()
            ));
        }
        return opps;
    }

    public static List<McaApp__Receivable__c> generateReceivables(Integer count, Id oppId) {
        return generateReceivables(count, oppId, null);
    }

    public static List<McaApp__Receivable__c> generateReceivables(Integer count, Id oppId, Id receivableId) {
        List<McaApp__Receivable__c> receivables = new List<McaApp__Receivable__c>();
        for(Integer i = 0; i < count; i++) {
            McaApp__Receivable__c receivable = new McaApp__Receivable__c(
                McaApp__Opportunity__c = oppId
            );
            if(receivableId != null) {
                receivable.IsAdjustment__c = true;
                receivable.Adjustment_To__c = receivableId;
                receivable.McaApp__Amount__c = 5000;
            }
            receivables.add(receivable);
        }
        return receivables;
    }

    public static List<McaApp__Payable__c> generatePayables(Integer count, Id oppId, Id receivableId) {
        return generatePayables(count, oppId, receivableId, null);
    }

    public static List<McaApp__Payable__c> generatePayables(Integer count, Id oppId, Id receivableId, Id payableId) {
        List<McaApp__Payable__c> payables = new List<McaApp__Payable__c>();
        for(Integer i = 0; i < count; i++) {
            McaApp__Payable__c payable = new McaApp__Payable__c(
                McaApp__Opportunity__c = oppId,
                McaApp__Receivable_Dependency__c = receivableId,
                McaApp__Percentage__c = 10,
                McaApp__Payback_Funded__c = 'Commission Revenue'
            );
            if(payableId != null) {
                payable.IsAdjustment__c = true;
                payable.Adjustment_To__c = payableId;
            }
            payables.add(payable);
        }
        return payables;
    }

}