Bizfi Production/src/objects/Accounting_Calendar_Month__c.object
<CustomObject>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Accounting Calendar Month History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Accounting Calendar Month</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Calendar Months</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Bizfi Production/src/classes/AccountingCalendarMonthTriggerTest.cls
@isTest
private class AccountingCalendarMonthTriggerTest{

    static TestMethod void insertAccountingCalendarMonthTest(){

        List<Accounting_Calendar_Month__c> acmList = new List<Accounting_Calendar_Month__c>();

        Test.StartTest();

        for(Integer i = 0; i < 10; i++){
            Accounting_Calendar_Month__c acm = new Accounting_Calendar_Month__c();

            acmList.add(acm);            
        }
        
        insert acmList;

        for(Integer i = 0; i < 5; i++){        
        
            acmList[i].locked__c = true;

            update acmList;        
        }

        delete acmList[0];

        Test.StopTest();

    }

}