Bizfi Production/src/objects/Audit_Trail__c.object
<CustomObject>
    <description>Hold the data related to Opportunity/Lead Owner/Stage changes</description>
    <fields>
        <fullName>Current_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the information of the current owner when the stage changes.</description>
        <inlineHelpText>This field stores the information of the current owner when the stage changes.</inlineHelpText>
        <label>Current Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This store info for new owner after owner ship transfer</description>
        <inlineHelpText>This store info for new owner after owner ship transfer</inlineHelpText>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail</relationshipName>
        <type>Lookup</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Audit Trail History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Sales_Rep_Report_Card__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sales Rep ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Report_Card</relationshipName>
        <type>Lookup</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Scorecards History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Sales Rep Scorecard</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/SCTimeframe_Metric__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SCTimeframe Metric</label>
</CustomObject>

Bizfi Production/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Generate_Sales_Rep_Scorecard__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for checking active user for generating scorecard.</description>
        <inlineHelpText>If checked, the user will have a scorecard generated at midnight daily.</inlineHelpText>
        <label>Generate Sales Rep Scorecard</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Bizfi Production/src/classes/SCAuditTrailBatchExecuter.cls
public class SCAuditTrailBatchExecuter
{
   
    public void auditTrailExecute(List<SObject> scope,Map<ID,Sales_Rep_Report_Card__c> mapOfSalesRep,Map<String,SCTimeframe_Metric__c> mapOfCustSetTimeFrame)
    {
        
        Sales_Rep_Report_Card__c resultSC;
        for(Audit_Trail__c audtrail:(List<Audit_Trail__c>)scope)
        {
                 // checking calculation based on current owner 
                 if(audtrail.current_owner__c != null && audtrail.current_owner__r.Generate_Sales_Rep_Scorecard__c && audtrail.current_owner__r.isActive)
                 {
                 
                       if(mapOfSalesRep.containsKey(audtrail.current_owner__c))
                       {
                             Sales_Rep_Report_Card__c existSC = mapOfSalesRep.get(audtrail.current_owner__c);
                             if(existSC != null)
                             {
                               resultSC = new SCCalculateTimeLineHelper().calculateBasedOnTimeLine(existSC,audtrail,mapOfCustSetTimeFrame);
                             }
                       }
                       else
                       {
                               Sales_Rep_Report_Card__c tempSC = new SCResetToZero().resetToZero(mapOfCustSetTimeFrame);
                               tempSC.Sales_Rep__c = audtrail.current_owner__c;
                               tempSC.Sales_Rep_ID__c = audtrail.current_owner__r.id;
                               resultSC = new SCCalculateTimeLineHelper().calculateBasedOnTimeLine(tempSC,audtrail,mapOfCustSetTimeFrame);
                       }
                   
                       if(resultSC != null)
                       {
                              mapOfSalesRep.put(audtrail.current_owner__c,resultSC);
                            
                       }
                    
                 
                 }   
          
                 
                 
                 // checking calculation based on New owner 
                 if(audtrail.New_owner__c != null && audtrail.New_owner__r.Generate_Sales_Rep_Scorecard__c && audtrail.New_owner__r.isActive)
                 {
                 
                       if(mapOfSalesRep.containsKey(audtrail.New_owner__c))
                       {
                             Sales_Rep_Report_Card__c existSC = mapOfSalesRep.get(audtrail.New_owner__c);
                             if(existSC != null)
                             {
                               resultSC = new SCCalculateTimeLineHelper().calculateBasedOnTimeLine(existSC,audtrail,mapOfCustSetTimeFrame);
                             }
                       }
                       else
                       {
                               Sales_Rep_Report_Card__c tempSC = new SCResetToZero().resetToZero(mapOfCustSetTimeFrame);
                               tempSC.Sales_Rep__c = audtrail.New_owner__c;
                               tempSC.Sales_Rep_ID__c = audtrail.New_owner__r.id;
                               resultSC = new SCCalculateTimeLineHelper().calculateBasedOnTimeLine(tempSC,audtrail,mapOfCustSetTimeFrame);
                       }
                   
                       if(resultSC != null)
                       {
                              mapOfSalesRep.put(audtrail.New_owner__c,resultSC);
                            
                       }
                    
                 
                 }  
          
          
          
          
         
        }
        
         
    
    }
    
    
}