Bizfi Production/src/objects/Audit_Trail__c.object
<CustomObject>
    <description>Hold the data related to Opportunity/Lead Owner/Stage changes</description>
    <fields>
        <fullName>Date_Time_change_was_made__c</fullName>
        <label>Date/Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Status_Stage_value__c</fullName>
        <label>New Status / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This store info for new owner after owner ship transfer</description>
        <inlineHelpText>This store info for new owner after owner ship transfer</inlineHelpText>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Old_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the information of old owner after owner ship transfer.</description>
        <inlineHelpText>This field stores the information of old owner after owner ship transfer.</inlineHelpText>
        <label>Old Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Audit Trails</relationshipLabel>
        <relationshipName>Opportunity_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates weather it is stage change or status change.</description>
        <inlineHelpText>Indicates weather it is stage change or status change.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Status / Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organic Sub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Audit Trail History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <label>Lead ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <label>Lead ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Transaction Line History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

Bizfi Production/src/classes/OpportunityOnInsertFutureClass.cls
global class OpportunityOnInsertFutureClass
{
    
    
    @future
    public static void onAfterInsertFutureCall(Set<ID> sOfOppID)
    {
        
        Map<String,Opportunity> mapOfIdOpp = new Map<String,Opportunity>();
        Map<ID,String> mapOfNewOppIDLeadID = new Map<ID,String>();
        Map<ID,ID> mapOfLeadIDLeadOwnerID = new Map<ID,ID>();
        List<Opportunity> lOfOppID = new  List<Opportunity>();
        
        lOfOppID  = [select id,Lead_ID__c,ownerId,StageName,LastModifiedDate from opportunity where id IN: sOfOppID];
        
        if(lOfOppID != null && lOfOppID.size() > 0)
        {
            
            
           
            for(Opportunity newOpp: lOfOppID){
                
                mapOfIdOpp.put(newOpp.id,newOpp);
                if(!String.isBlank(newOpp.Lead_ID__c))
                {
                    mapOfNewOppIDLeadID.put(newOpp.id,newOpp.Lead_ID__c);
                }
                
            }
            
            for(Lead tempLead : [Select id,ownerID from Lead where id IN : mapOfNewOppIDLeadID.values()])
            {
                
                mapOfLeadIDLeadOwnerID.put(tempLead.id,tempLead.ownerID);
                
            }
            
            
            //Checking whether the oppertunity is created manually or by lead convert.
            List<Audit_Trail__c> lAuditTrail = new  List<Audit_Trail__c>();
            for(Opportunity newOpp: lOfOppID )
            {
                
                
               Audit_Trail__c tempAuditTrail = new Audit_Trail__c(New_owner__c = newOpp.ownerId,
                                                                   New_Status_Stage_value__c = newOpp.StageName,
                                                                   Opportunity__c = newOpp.Id,
                                                                   Object__c = 'Opportunity',
                                                                   Date_Time_change_was_made__c = newOpp.LastModifiedDate,
                                                                   Type__c = 'Create');
                
                if(!String.isBlank(newOpp.Lead_ID__c))
                {
                   if(newOpp.ownerId != mapOfLeadIDLeadOwnerID.get(newOpp.Lead_ID__c))
                   {
                    tempAuditTrail.old_owner__c = mapOfLeadIDLeadOwnerID.get(newOpp.Lead_ID__c);
                   } 
                }
                                                        
             
                
                
                lAuditTrail.add(tempAuditTrail);
                
            }
            
            
            
            try
            {  
               // insert lAuditTrail;
                database.insert(lAuditTrail,false);
                
            }
            catch(Exception ex)
            {
                system.debug('$$$$$ Exception in auditTrailCreationAfterInsertLead'+ex);
            }
            
            
        }
    }
}