Bizfi Production/src/objects/Audit_Trail__c.object
<CustomObject>
    <description>Hold the data related to Opportunity/Lead Owner/Stage changes</description>
    <fields>
        <fullName>Current_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the information of the current owner when the stage changes.</description>
        <inlineHelpText>This field stores the information of the current owner when the stage changes.</inlineHelpText>
        <label>Current Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Stage__c</fullName>
        <description>This is for current stage when the owner gets change.</description>
        <inlineHelpText>This is for current stage when the owner gets change.</inlineHelpText>
        <label>Current Status / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Time_change_was_made__c</fullName>
        <label>Date/Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Status_Stage_value__c</fullName>
        <label>New Status / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This store info for new owner after owner ship transfer</description>
        <inlineHelpText>This store info for new owner after owner ship transfer</inlineHelpText>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Old_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the information of old owner after owner ship transfer.</description>
        <inlineHelpText>This field stores the information of old owner after owner ship transfer.</inlineHelpText>
        <label>Old Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Trail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Old_Status_Stage_value__c</fullName>
        <label>Old Status / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Audit Trails</relationshipLabel>
        <relationshipName>Opportunity_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates weather it is stage change or status change.</description>
        <inlineHelpText>Indicates weather it is stage change or status change.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Status / Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organic Sub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Audit Trail History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Organic_Sub__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Organic Sub</label>
        <type>Checkbox</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Transaction Line History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSDemo/src/objects/Opportunity.object
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

Bizfi Production/src/classes/OpportunityAuditOnUpdate.cls
public with sharing class OpportunityAuditOnUpdate {
    public  List<Audit_Trail__c> lstAuditTrail;
    //public  Audit_Trail__c auditTrail;
    public  Audit_Trail__c auditTrailForOwnerChange;
    public  Audit_Trail__c auditTrailForOrgSubChange;
    public  Audit_Trail__c auditTrailForStageChange;
    public OpportunityAuditOnUpdate(){
        lstAuditTrail = new List<Audit_Trail__c>();
    }
    public void onOpportunityOwnerStatusUpdate(Map<Id,Opportunity> oldmap, List<Opportunity> newList)
    {
        
        for(Opportunity opportunity: newList)
        {
           
            if(oldmap.containsKey(opportunity.Id) && opportunity.OwnerId != oldmap.get(opportunity.Id).OwnerId)
            {
                auditTrailForOwnerChange = basicAuditTrailInfo(opportunity);
                auditTrailForOwnerChange.Old_owner__c =(oldmap.get(opportunity.Id).OwnerId);
                auditTrailForOwnerChange.New_owner__c = (opportunity.OwnerId);
                auditTrailForOwnerChange.Type__c = 'Owner';
                auditTrailForOwnerChange.Current_Stage__c = opportunity.StageName;
                lstAuditTrail.add(auditTrailForOwnerChange);
                
            }
            
           
            
            if(oldmap.containsKey(opportunity.Id) && opportunity.StageName != oldmap.get(opportunity.Id).StageName)
            {
                auditTrailForStageChange = basicAuditTrailInfo(opportunity);
                auditTrailForStageChange.Old_Status_Stage_value__c = oldmap.get(opportunity.Id).StageName;
                auditTrailForStageChange.New_Status_Stage_value__c = opportunity.StageName;
                auditTrailForStageChange.Type__c = 'Status / Stage';
                auditTrailForStageChange.Current_Owner__c = (opportunity.OwnerId);
                lstAuditTrail.add(auditTrailForStageChange ); 
            }
            
             // For organic Subs
            if(oldmap.containsKey(opportunity.Id) && opportunity.Organic_Sub__c != oldmap.get(opportunity.Id).Organic_Sub__c)
            {   
                //track Audit trail only id  OrgSub is checked 
                if(opportunity.Organic_Sub__c)
                {
                    auditTrailForOrgSubChange = basicAuditTrailInfo(opportunity);
                    auditTrailForOrgSubChange.Type__c = 'Organic Sub';
                    auditTrailForOrgSubChange.Current_Owner__c = opportunity.OwnerId;
                    auditTrailForOrgSubChange.Current_Stage__c = opportunity.StageName;
                    lstAuditTrail.add(auditTrailForOrgSubChange);
                }
                
            }
           
            
        }
        try
        {
            if(lstAuditTrail != null && lstAuditTrail.size() > 0)
            database.upsert(lstAuditTrail,false);
        }
        catch(Exception e)
        {
            system.debug('****'+e);
        }
        
    }
    
     public Audit_Trail__c basicAuditTrailInfo(Opportunity opportunity)
     {
            return new Audit_Trail__c(Object__c = 'Opportunity',
                                      Opportunity__c = opportunity.Id,
                                      Date_Time_change_was_made__c = opportunity.LastModifiedDate);
            
     
     }
    
}