Bizfi Production/src/objects/Lead.object
<CustomObject>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Lead.object
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bank, ISO, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

Bizfi Production/src/objects/Sales_Rep_Report_Card__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lead Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Report_Card</relationshipName>
        <type>Lookup</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Scorecards History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Sales Rep Scorecard</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/UpdateUserWorkloadTest.cls
@isTest
public with sharing class UpdateUserWorkloadTest {
    
    @testSetup
    public static void createLeads() {
        
        Sales_Rep_Report_Card__c scoreCard = new Sales_Rep_Report_Card__c();
        scoreCard.Sales_Rep__c = UserInfo.getUserId();
        insert scoreCard;

        //Lead l = new Lead();
        //l.FirstName = 'Test';
        //l.LastName = 'Lead';
        //l.Company = 'ACME';
        //l.Phone = '(323) 319-3663';
        //insert l;
    }


    @isTest
    public static void UpdateUserWorkloadTest() {
       
        
        Test.startTest();
        
            Lead l = new Lead();
            l.FirstName = 'Test';
            l.LastName = 'Lead 2';
            l.Company = 'ACME';
            l.Phone = '(323) 319-3663';
            insert l;

        Test.stopTest();

        Sales_Rep_Report_Card__c scoreCard = [SELECT Lead_Count__c FROM Sales_Rep_Report_Card__c WHERE Sales_Rep__c = :UserInfo.getUserId()];
        System.assertEquals(1, scoreCard.Lead_Count__c);
    }
}