Bizfi Production/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Source__c</fullName>
        <description>The source of the campaign.</description>
        <label>Campaign Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lazarus_ID__c</fullName>
        <label>Lazarus ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>McaApp__Sub_Status__c</fullName>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Looking for Startup Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time in Business too Short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Information Inaccurate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Sales Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraudulent Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Merchant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/TaskTriggerBizfiTest.cls
@isTest
private class TaskTriggerBizfiTest {


	@testSetup
	static void testData() {
		
		List<Lead> leadList = new List<Lead>();
		List<String> stats = new List<String>{'Closed - Lost', 'Closed - Future Client', 'Closed - Unqualified', 'Open - Not Contacted'};
		
		for(Integer i = 0; i < 4; i++){
			Lead l = new Lead(
				LeadSource = 'Lead Partner',
				Campaign_Source__c = 'don\' matter',
				Company = 'Laz '+i,
				LastName = 'Surname-'+i,
				Email = 'surname-'+i+'@lazcompany.com',
				Phone = '(646) 604-8215',
				Status = stats[i]
				);

			if(i < 3) { l.McaApp__Sub_Status__c = 'Looking for Startup Capital'; }

			leadList.add(l);
		}

		insert leadList;

	}

	@isTest
	static void unqual() {
		// Given
		Id lostId = [SELECT Id FROM Lead WHERE Status = 'Closed - Unqualified' LIMIT 1].Id;

		List<Task> taskList = new List<Task>();

		for(Integer i = 0; i < 199; i++){
			Task t = new Task(
				WhoId = lostId,
				Subject = 'Inbound Call',
				isdc_inbound_number_dialed__c = '(717) 773-7887', 
				Status = 'Complete',
				Priority = 'Normal');

			taskList.add(t);
		}

		Task t = new Task(
				WhoId = lostId,
				Subject = 'Inbound Call - All - Radiance Call Center - (584) 387-2822',
				isdc_inbound_number_dialed__c = '(717) 773-7887', 
				Status = 'Complete',
				Priority = 'Normal');

		taskList.add(t);

		// When
		test.startTest();
		insert taskList;

		Lead lost = [SELECT Id, Lazarus_ID__c FROM Lead WHERE Status = 'Closed - Unqualified' LIMIT 1];
		test.stopTest();

		// Then
		System.assertEquals(lost.Lazarus_ID__c, 'Radiance Call Center');
	}

	@isTest
	static void freebandzClient() {
		// Given
		Id lostId = [SELECT Id FROM Lead WHERE Status = 'Closed - Future Client' LIMIT 1].Id;

		List<Task> taskList = new List<Task>();

		for(Integer i = 0; i < 199; i++){
			Task t = new Task(
				WhoId = lostId,
				Subject = 'Inbound Call',
				isdc_inbound_number_dialed__c = '(717) 773-7887', 
				Status = 'Complete',
				Priority = 'Normal');

			taskList.add(t);
		}

		Task t = new Task(
				WhoId = lostId,
				Subject = 'Inbound Call - All - Radiance Call Center - (584) 387-2822',
				isdc_inbound_number_dialed__c = '(717) 773-7887', 
				Status = 'Complete',
				Priority = 'Normal');

		taskList.add(t);

		// When
		test.startTest();
		insert taskList;

		Lead lost = [SELECT Id, Lazarus_ID__c FROM Lead WHERE Status = 'Closed - Future Client' LIMIT 1];
		test.stopTest();

		// Then
		System.assertEquals(lost.Lazarus_ID__c, 'Radiance Call Center');
	}

	@isTest
	static void negTest() {
		// Given
		Id lostId = [SELECT Id FROM Lead WHERE Status = 'Open - Not Contacted' LIMIT 1].Id;

		List<Task> taskList = new List<Task>();

		for(Integer i = 0; i < 199; i++){
			Task t = new Task(
				WhoId = lostId,
				Subject = 'Inbound Call',
				isdc_inbound_number_dialed__c = '(717) 773-7887', 
				Status = 'Complete',
				Priority = 'Normal');

			taskList.add(t);
		}

		Task t = new Task(
				WhoId = lostId,
				Subject = 'Inbound Call - All - Radiance Call Center - (584) 387-2822',
				isdc_inbound_number_dialed__c = '(717) 773-7887', 
				Status = 'Complete',
				Priority = 'Normal');

		taskList.add(t);

		// When
		test.startTest();
		insert taskList;

		Lead lost = [SELECT Id, Lazarus_ID__c FROM Lead WHERE Status = 'Open - Not Contacted' LIMIT 1];
		test.stopTest();

		// Then
		System.assert(String.isBlank(lost.Lazarus_ID__c));
	}


}