Bizfi Production/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Days_since_Reassigned_to_Rep_48_Hr_Rule__c</fullName>
        <description>Used for the 48 hour rule.</description>
        <formula>ROUND((NOW() - Reassigned_to_Rep_48_Hr_Rule_Date_Time__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days since Reassigned to Rep-48 Hr Rule</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reassigned_to_Rep_48_Hr_Rule_Date_Time__c</fullName>
        <label>Reassigned to Rep - 48 Hr Rule Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>cmblre__Reassign_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reassign Lead</label>
        <type>Checkbox</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/AutoReassignOpenLeadsBatch.cls
global class AutoReassignOpenLeadsBatch implements Database.Batchable<sObject> {
    
    String query;
    
    global AutoReassignOpenLeadsBatch() {

        query = 'select Id from Lead where Status = \'Open - Not Contacted\' and Days_since_Reassigned_to_Rep_48_Hr_Rule__c >= 2 and IsConverted = false';
    }

    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }


    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        for (Lead l : (Lead[]) scope) {

            l.cmblre__Reassign_Lead__c = true;
            l.Reassigned_to_Rep_48_Hr_Rule_Date_Time__c = Datetime.now();
        
        }

        update scope;
    }

    
    global void finish(Database.BatchableContext BC) {
        
    }    


    public static void start() {

        Database.executeBatch(new AutoReassignOpenLeadsBatch(), 100);
    }
}