Bizfi Production/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Path_Id__c</fullName>
        <description>Checks values of Call Path fields and takes non-null value.</description>
        <formula>/* WARNING: Formula Return Type MUST be Text.  DO NOT CHANGE.
   Update table below as exceptions are added */
/*
Rep Queue ID     Call Path Name
180218           Open - New Lead ResponsePop - Opener
180290           Cust - Bizfi2
179228           Cust - Bizfi Espanol
179642           Close - New Lead ResponsePop - Closer
180104           Cust - PTIN
179748           Cust - Credit Karma
179912           Cust - Delivery.com
180124           Cust - Xero
180022           Cust - NYSRA
180298           Cust - National Benefits Program
179756           Cust - Lightspeed
180052           Cust - Profitstars
180212           Cust - TouchSuite
180310           Cust - Transfirst
180294           Cust - ConEd
179882           Cust - Credico
179960           Cust - Illinois Restaurant Association
180010           Cust - Nav Marketplace
190064           Cust - Doctor&apos;s Funding Group
7976             Test Call Path
*/


IF( AND( Campaign_Source__c = &quot;BizFi&quot;,  FirstName = &quot;valerie&quot;, LastName = &quot;papa&quot; ), &quot;7976&quot;,

IF( OR( ISPICKVAL (  LeadSource , &quot;Data Source&quot; ), ISPICKVAL (  LeadSource , &quot;Hybrid Lead Partner&quot; ), ISPICKVAL (  LeadSource , &quot;Hybrid Submission Partner&quot; ), ISPICKVAL (  LeadSource , &quot;Mailer&quot; ), ISPICKVAL (  LeadSource , &quot;Other&quot; )), &quot;180218&quot;, 

IF( Campaign_Source__c = &quot;5linx&quot;, &quot;179642&quot;,

IF( Campaign_Source__c = &quot;Doctors Funding Group&quot;, &quot;190064&quot;,

IF( OR ( Campaign_Source__c = &quot;ACD: Bizfi2&quot;, Campaign_Source__c = &quot;Bizfi2&quot; ), &quot;180290&quot;,

IF( OR ( Campaign_Source__c = &quot;ACD: Bizfi Espanol&quot;, Campaign_Source__c = &quot;BizfiEspanol&quot; ), &quot;179228&quot;,

IF( OR ( ISPICKVAL ( LeadSource, &quot;Digital&quot; ), CONTAINS ( Campaign_Source__c, &quot;Prosper&quot; ), CONTAINS ( Campaign_Source__c, &quot;MVF Global&quot; ) ), &quot;179642&quot;,

IF( CONTAINS ( Campaign_Source__c , &quot;PTIN&quot; ), &quot;180104&quot;, 

IF( CONTAINS ( Campaign_Source__c, &quot;Karma&quot; ), &quot;179748&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;delivery&quot; ), &quot;179912&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;Xero&quot; ), &quot;180124&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;NYSRA&quot; ), &quot;180022&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;National Benefit&quot; ), &quot;180298&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;Lightspeed&quot; ), &quot;179756&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;Profit&quot; ), &quot;180052&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;TouchSuite&quot; ), &quot;180212&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;Transfirst&quot; ), &quot;180310&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;ConEd&quot; ), &quot;180294&quot;,

IF( OR ( CONTAINS ( Campaign_Source__c, &quot;Credico&quot; ), Campaign_Source__c = &quot;SalesTeam&quot; ), &quot;179882&quot;,

IF( CONTAINS ( Campaign_Source__c, &quot;Illinois Restaurant&quot; ), &quot;179960&quot;,

IF( OR ( CONTAINS ( Campaign_Source__c, &quot;Creditera&quot; ), CONTAINS ( Campaign_Source__c, &quot;Nav Direct&quot; ), CONTAINS ( Campaign_Source__c, &quot;Nav Market&quot; ), CONTAINS ( Campaign_Source__c, &quot;Nav Live&quot; ), CONTAINS ( Campaign_Source__c, &quot;Nav Referral&quot; ) ), &quot;180010&quot;,

IF( OR ( Campaign_Source__c = &quot;ACD: Connexions&quot;, Campaign_Source__c = &quot;ACD: Conexus&quot;, CONTAINS ( Campaign_Source__c, &quot;Trafficjamming&quot; ) , CONTAINS ( Campaign_Source__c, &quot;Rev Funding&quot; ), ISPICKVAL ( LeadSource, &quot;Lead Partner&quot; ), ISPICKVAL ( LeadSource, &quot;Lead Source&quot; ) ), &quot;180218&quot;,

NULL))))))))))))))))))))))</formula>
        <label>Call Path Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Sent_to_InsideSales_Date_Time__c</fullName>
        <label>First Sent to InsideSales Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_to_InsideSales__c</fullName>
        <formula>/*
AND( OwnerId = &apos;00Go0000002BKq2&apos;, 
FirstName  = &apos;valerie&apos;, 
LastName = &apos;papa&apos;,
Campaign_Source__c = &apos;BizFi&apos;,
Is_API_Lead__c,
Lead_Status_Category__c = &apos;Active&apos;,
NOT(Inside_Sales_Unanswered__c), Do not remove
NOT(Inside_Sales_Answer__c), Do not remove
NOT(ISNULL(Phone)) Do not remove
)
*/

AND(
OwnerId = &apos;00Go0000002BKq2&apos;,
AND( NOT ( FirstName = &apos;valerie&apos; ) , NOT ( LastName = &apos;papa&apos; ) , NOT ( Phone = &apos;2125551212&apos; ) ),
Is_API_Lead__c,
NOT( Inside_Sales_Unanswered__c ),
NOT( Inside_Sales_Answer__c ),
NOT( ISNULL( Phone )),
ISPICKVAL( Duplicate_Reason__c, &quot;&quot; ),
ISPICKVAL( Status, &quot;Open - Not Contacted&quot; )
)</formula>
        <label>Send to InsideSales</label>
        <type>Checkbox</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/SendToInsideSalesBatch.cls
global class SendToInsideSalesBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    String query;
    
    
    global SendToInsideSalesBatch() {
        
        query = 'select First_Sent_to_InsideSales_Date_Time__c, Call_Path_Id__c from Lead where Send_to_InsideSales__c = true and IsConverted = false';
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        SendToInsideSales client = new SendToInsideSales((Lead[]) scope);
        client.send(false);             
    }
    
    
    global void finish(Database.BatchableContext BC) {
            
        start();
    }   


    public static void start() {

        System.scheduleBatch(new SendToInsideSalesBatch(), 'Send to InsideSales Service', 5);

    }
}