Bizfi Production/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Search_Id__c</fullName>
        <formula>RIGHT(Id, 8)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Search Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Searchable_via_Widget__c</fullName>
        <formula>IF (  AND(Owner:User.LastName = &apos;Storage Account&apos;,  ISPICKVAL(Status, &apos;Open - Attempting Contact&apos;)), true, false)</formula>
        <label>Searchable via Widget</label>
        <type>Checkbox</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Leads History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/LeadSearchWidgetController.cls
public without sharing class LeadSearchWidgetController {
	
	public Boolean showSearch { get; set; }
	public Boolean showName { get; set; }
	public Boolean showLink { get; set; }

	public String searchId { get; set; }
	public String leadName { get; set; }
	public String leadId { get; set; }
	private Lead lead;

	
	public LeadSearchWidgetController() {
		searchId = '';
		leadName = '';
		leadId = '';
		showSearch = true;
		showName = false;
		showLink = false;
	}


	public void searchLead() {

		for (Lead l : [select Name from Lead where Search_Id__c = :searchId and Searchable_via_Widget__c = true]) {
			lead = l;
			leadName = l.Name;
			showSearch = false;
			showName = true;			
		}
	}


	public void cancel() {
		searchId = '';
		leadName = '';
		leadId = '';
		showSearch = true;
		showName = false;
		showLink = false;		
	}


	public void assignLead() {

		lead.OwnerId = UserInfo.getUserId();
		update lead;

		leadId = lead.Id;
		showName = false;
		showLink = true;		
	}
}