Bizfi Production/src/objects/Sales_Rep_Report_Card__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Report_Card</relationshipName>
        <type>Lookup</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Scorecards History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Sales Rep Scorecard</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/UpdateUserWorkloadSchedule.cls
global class UpdateUserWorkloadSchedule implements Schedulable {
    
    global void execute(SchedulableContext sc) {

        Set<Id> salesRepsIds = new Set<Id>();

        for (Sales_Rep_Report_Card__c scoreCard : [SELECT Sales_Rep__c FROM Sales_Rep_Report_Card__c]) {

            salesRepsIds.add(scoreCard.Sales_Rep__c);
        }        

        Database.executeBatch(new UpdateUserWorkloadBatch(salesRepsIds), 1);
    }


    public static void start() {

        System.schedule('Agent Workload Recalculation', '0 0 6 * * ?', new UpdateUserWorkloadSchedule());
    }
}