Bizfi Production/src/objects/Sales_Rep_Report_Card__c.object
<CustomObject>
    <fields>
        <fullName>Submissions_Today__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Submissions Today</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>10</archiveRetentionYears>
        <description>Scorecards History</description>
        <gracePeriodDays>1</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Sales Rep Scorecard</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Bizfi Production/src/classes/ResetSubmissionScheduler.cls
global class ResetSubmissionScheduler implements Database.Batchable<sobject>, Schedulable {
    
    global void execute(SchedulableContext sc){
        ResetSubmissionScheduler obj = new ResetSubmissionScheduler();
        database.executeBatch(obj);
    }
    
    global database.querylocator start(Database.BatchableContext bc){
        
        return database.getQueryLocator('Select id from Sales_Rep_Report_Card__c');
    }
    
    global void execute(Database.BatchableContext bc, List<Sales_Rep_Report_Card__c> lstCards){
        
        for(Sales_Rep_Report_Card__c rep: lstCards){
            rep.Submissions_Today__c = 0;
        }
        
        update lstCards;
        
    }
    
    global void finish(Database.BatchableContext bc){
        
        
    }
    
}