LendersApp/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>McaApp__Gross_monthly_Sales__c</fullName>
        <label>Gross monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>McaApp__Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/DealDefaultFieldValue__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Default Deal field values</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Program_Id__c</fullName>
        <label>Bank Program Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Gross__c</fullName>
        <defaultValue>0.15</defaultValue>
        <label>Max % Gross</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>DealDefaultFieldValue</label>
</CustomObject>

LendersApp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Rating__c</fullName>
        <label>Deal Rating</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Gross__c</fullName>
        <label>Max % Gross</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>McaApp__Credit_Score__c</fullName>
        <label>Owner 1 Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>McaApp__Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microloan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Receivable Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Processing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>McaApp__Funding_Amount__c</fullName>
        <label>Funded $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>McaApp__Gross_monthly_Sales__c</fullName>
        <label>Gross monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>McaApp__Rate__c</fullName>
        <label>Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>McaApp__Term_Months__c</fullName>
        <label>Term (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Positions__c</fullName>
        <label>Open Positions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramType__c</fullName>
        <label>Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Terms_To_Offer__c</fullName>
        <label>Term(s) To Offer</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/ProgramMaster__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BuyRateNew__c</fullName>
        <label>Factor Rate - New</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DealScore__c</fullName>
        <label>Deal Rating</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Max_Gross__c</fullName>
        <label>Max % Gross</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Open_Positions__c</fullName>
        <label>Max. Open Positions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Gross_Sales__c</fullName>
        <label>Min. Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Offer_Amount__c</fullName>
        <label>Min. Offer Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Time_in_business__c</fullName>
        <label>Min. Time in business</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term (Months)</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Fee_Percentage__c</fullName>
        <label>Upfront Fee %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Upfront_Fees__c</fullName>
        <label>Upfront Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Program Master</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/GenerateOffers.cls
global class GenerateOffers {

    webservice static String processDetails(String oppID) {

        system.debug('**************in the class');
        Set<Integer> setTerms;
        Set<String> setTypes = new Set<String>();
        String message='';

        List<McaApp__Offer__c> lstOffer = new List<McaApp__Offer__c>();

        Opportunity opp = [SELECT Id, Account.Name, Deal_Rating__c, McaApp__Gross_monthly_Sales__c,
                                Account.McaApp__Years_in_Business__c, McaApp__Credit_Score__c,
                                ProgramType__c, Terms_to_Offer__c, Max_Gross__c, Open_Positions__c,
                                McaApp__Funding_Amount__c, Name FROM Opportunity  WHERE Id = :oppId];

        system.debug('**************in the opp ' + opp);

        if (opp.ProgramType__c == null) {

            message += 'Program Type';

            system.debug('**** message *****' + message);
        }

        if (opp.Terms_to_Offer__c == null) {

            message += '\nTerm(s) To Offer';
            system.debug('**** message *****' + message);
        }

        //if(opp.McaApp__Funding_Amount__c == NULL)
             //message += '\nFunded $';

        if (opp.Deal_Rating__c == NULL) {

            message += '\nDeal Rating';
            system.debug('**** message *****' + message);
        }

        if (opp.Open_Positions__c == NULL) {

            message += '\nOpen Positions';
            system.debug('**** message *****' + message);
        }

        if (opp.McaApp__Credit_Score__c == NULL) {

            message += '\nCredit Score';
            system.debug('**** message *****' + message);
        }

        if (opp.McaApp__Gross_monthly_Sales__c == NULL) {

            message += '\nGross monthly Sales';
            system.debug('**** message *****' + message);
        }

        if (opp.Account.McaApp__Years_in_Business__c == NULL) {

            message += '\nAccount:Years in Business';
            system.debug('**** message *****' + message);

            system.debug('**** message length*****' + message.length());
        }

        if (message.length() <= 0) {

            system.debug('**** message *****' + message.length());

            McaApp__Submission__c[] submission = [SELECT Id, McaApp__Opportunity__c FROM McaApp__Submission__c WHERE McaApp__Opportunity__c = :opp.Id];

            system.debug('***submission ***********in the submission ' + submission );

            if (submission.isEmpty()) {

                DealDefaultFieldValue__c customSetting = DealDefaultFieldValue__c.getOrgDefaults();
                McaApp__Submission__c auxSubmission = new McaApp__Submission__c();
                auxSubmission.McaApp__Opportunity__c = opp.Id;
                auxSubmission.McaApp__Funder__c = customSetting.Account_Id__c;
                auxSubmission.McaApp__Program__c = customSetting.Bank_Program_Id__c;

                insert auxSubmission;
                submission.add(auxSubmission);
            }
            //split terms and create set for query
            if (opp.Terms_to_Offer__c != null) {

                setTerms = new Set<Integer>();

                for (String i : opp.Terms_to_Offer__c.split(';')) {

                    setTerms.add(Integer.valueOf(i.trim()));
                }
            }
        //split deal types  and create set for query
            if (opp.ProgramType__c != null) {

                for (String i : opp.ProgramType__c.split(';')) {

                    setTypes.add(i.trim());
                }
            }

            List<ProgramMaster__c> lstProgramMaster = new List<ProgramMaster__c>();

            String query = 'SELECT Id, Name, DealScore__c, Term__c, Program_Type__c, BuyRateNew__c, Upfront_Fee_Percentage__c,' +
                            'Upfront_Fees__c, Min_Credit_Score__c, Min_Monthly_Gross_Sales__c, Min_Time_in_business__c,' +
                            'Max_Gross__c, Max_Open_Positions__c, Min_Offer_Amount__c FROM ProgramMaster__c WHERE Active__c = true ';

            query += (setTypes != NULL && setTypes.size() > 0) ? ' AND (Program_Type__c IN : setTypes OR Program_Type__c=NULL)' : '';
            query += (setTerms != NULL && setTerms.size() > 0) ? ' AND (Term__c IN : setTerms OR Term__c=NULL)' : '';
            //query += opp.McaApp__Funding_Amount__c != NULL?' AND Min_Offer_Amount__c<='+opp.McaApp__Funding_Amount__c:'';
            query += opp.Deal_Rating__c != NULL ? ' AND DealScore__c INCLUDES (\'' + opp.Deal_Rating__c + '\')' : '';
            //system.debug('22222222222'+setOverrideFilter);
            //if(!setOverrideFilter){
            query += opp.Open_Positions__c != NULL ? ' AND ( Max_Open_Positions__c>=' + opp.Open_Positions__c + ' OR Max_Open_Positions__c=NULL)' : '';
            query += opp.McaApp__Credit_Score__c != NULL ? ' AND (Min_Credit_Score__c<=' +  opp.McaApp__Credit_Score__c + ' OR Min_Credit_Score__c=NULL)' : '';
            query += opp.McaApp__Gross_monthly_Sales__c != NULL ? ' AND (Min_Monthly_Gross_Sales__c<=' +  opp.McaApp__Gross_monthly_Sales__c + ' OR Min_Monthly_Gross_Sales__c=NULL)' : '';
            query += opp.Account.McaApp__Years_in_Business__c != NULL ? ' AND (Min_Time_in_business__c<=' + opp.Account.McaApp__Years_in_Business__c + ' OR Min_Time_in_business__c=NULL)' : '';
            //}
            query += ' order by name';

            system.debug('11111 query 111111111' + query);

            lstProgramMaster = database.query(query);
            system.debug('22222222222' + lstProgramMaster);

            for (ProgramMaster__c objProgram : lstProgramMaster) {

                McaApp__Offer__c objOffer = new McaApp__Offer__c(McaApp__Term_Months__c = Integer.valueOf(objProgram.Term__c), McaApp__Rate__c = objProgram.BuyRateNew__c,
                                            McaApp__Deal_Type__c = objProgram.Program_Type__c, Orig_Fee_Percentage__c = objProgram.Upfront_Fee_Percentage__c,
                                            Orig_Fee__c = objProgram.Upfront_Fees__c,
                                            McaApp__Opportunity__c = opp.Id, McaApp__Submission__c = submission[0].Id);//, McaApp__Submission__c = submission[0].Id);

                if (objProgram.Max_Gross__c != null) {

                    objOffer.Max_Gross__c = objProgram.Max_Gross__c;
                    lstOffer.add(objOffer);
                }
                else {

                    objOffer.Max_Gross__c = opp.Max_Gross__c;
                    lstOffer.add(objOffer);
                }
            }

            insert lstOffer;
            system.debug('333333333333'+lstOffer);

            if (lstOffer != NULL && lstOffer.size() > 0) {

                message = 'Offers are generated successfully.';
            }
            else {

                message = 'Criteria not matches.';
            }

            return message;
        }
        else {

            return 'Please fill below information:\n' + message;
        }
    }
}