LendersApp/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>McaApp__Gross_monthly_Sales__c</fullName>
        <label>Gross monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>McaApp__Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Account.object
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

LendersApp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Rating__c</fullName>
        <label>Deal Rating</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>McaApp__Credit_Score__c</fullName>
        <label>Owner 1 Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>McaApp__Funding_Amount__c</fullName>
        <label>Funded $</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>McaApp__Gross_monthly_Sales__c</fullName>
        <label>Gross monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>McaApp__ISO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ISO that has submitted the deal</inlineHelpText>
        <label>ISO</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (ISO)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Positions__c</fullName>
        <label>Open Positions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramType__c</fullName>
        <label>Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Terms_To_Offer__c</fullName>
        <label>Term(s) To Offer</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/ProgramMaster__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DealScore__c</fullName>
        <label>Deal Rating</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Min_Credit_Score__c</fullName>
        <label>Min. Credit Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Monthly_Gross_Sales__c</fullName>
        <label>Min. Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Offer_Amount__c</fullName>
        <label>Min. Offer Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Time_in_business__c</fullName>
        <label>Min. Time in business</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term (Months)</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program Master</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/GenerateOffersTest.cls
@isTest
private class GenerateOffersTest {

    private static Opportunity opp = null;
    private static Account account = null;
    private static ProgramMaster__c pMaster = null;
    
    @isTest
    public static void myUnitTest() {

        // TO DO: implement unit test
        createAccount();
        createProgramMaster();
        createOpportunity();
        GenerateOffers.processDetails(opp.id);
    }

    private static void createOpportunity() {

        opp = new Opportunity();
        opp.Name =  'TestOpp';
        opp.StageName = 'Prospecting'; 
        opp.CloseDate = Date.today();
        opp.AccountId = account.Id;
        opp.McaApp__ISO__c = account.Id;
        opp.Terms_to_Offer__c = '02';
        opp.ProgramType__c = 'MCA';
        opp.Deal_Rating__c = 'A';
        opp.McaApp__Credit_Score__c = 500;
        opp.McaApp__Gross_monthly_Sales__c = 5000;
        opp.McaApp__Funding_Amount__c = 100;
        opp.Open_Positions__c = 2;
        insert opp;

    }

    private static void createAccount() {

        account = new Account();
        account.Name = 'Test Account'; 
        RecordType[] rt = [SELECT Id, Name, SobjectType, DeveloperName FROM RecordType WHERE Name = 'Bank' AND SobjectType = 'Account'];
        account.RecordType = rt[0];
        account.McaApp__Years_in_Business__c = 5;

        insert account;
    }

    private static void createProgramMaster() {

        pMaster = new ProgramMaster__c();
        pMaster.Active__c = true;
        pMaster.Term__c = 2;
        pMaster.Program_Type__c = 'MCA';
        pMaster.DealScore__c = 'A';
        pMaster.Min_Credit_Score__c = 500;
        pMaster.Min_Monthly_Gross_Sales__c = 5000;
        pMaster.Min_Time_in_business__c = 5;
        pMaster.Min_Offer_Amount__c = 100;
        
        insert pMaster;
    }
}