LendersApp/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

LendersApp/src/objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Lead.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

LendersApp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>McaApp__Factor_Rate__c</fullName>
        <label>Factor Rate</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>McaApp__Origination_Fee__c</fullName>
        <label>Origination Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter Assignment Rule Member</label>
        <referenceTo>Underwriter_Assignment_Rule_Member__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Load_Balancing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Load Balancing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quotas__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quotas</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Template__c</fullName>
        <label>Underwriter Assignment Template</label>
        <referenceTo>Underwriter_Assignment_Template__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rules</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Underwriter Assignment Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule__c</fullName>
        <label>Underwriter Assignment Rule</label>
        <referenceTo>Underwriter_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rule Entries</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Underwriter Assignment Rule Entry</label>
    <nameField>
        <displayFormat>UAE-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule_Member__c.object
<CustomObject>
    <fields>
        <fullName>Last_Assignment_Date_Time__c</fullName>
        <label>Last Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule__c</fullName>
        <label>Underwriter Assignment Rule</label>
        <referenceTo>Underwriter_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rule Members</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rule_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Underwriter_Assignment_Rule_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Underwriter Assignment Rule Member</label>
    <nameField>
        <displayFormat>UAM-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Template__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Underwriter Assignment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/UnderwriterAssignmentTest.cls
@isTest
private class UnderwriterAssignmentTest {
    
    public static Underwriter_Assignment_Template__c[] assignmentTemplateList = null;
    public static Underwriter_Assignment_Template__c assignmentTemplate = null;
    public static Underwriter_Assignment_Rule__c assignmentRule = null;
    public static Underwriter_Assignment_Rule_Entry__c assignmentEntry = null;
    public static Underwriter_Assignment_Rule_Member__c assignmentMember = null;
    public static Opportunity opp = null;
    public static Account acc = null;
    


    @isTest 
    public static void SortOrderTriggerHandler() {
        
        createAssignmentTemplate();
        createAssignmentTemplateList();
        createAssignmentRule();
        createUnderwriterAssignmentRuleEntry();
        createAssignmentRuleMember();

        Underwriter_Assignment_Rule__c failingRule = new Underwriter_Assignment_Rule__c(); 
        failingRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;
        failingRule.Sort_Order__c = 1;
        try {
            insert failingRule;
        }
        catch(Exception ex) {

        }
        
        //System.assertEquals(null, failingRule.Id);
    }

    @isTest 
    public static void testAssignmentRule() { 

        createAccount();
        createOpportunity();
        createAssignmentTemplate();
        createAssignmentRule();
        createUnderwriterAssignmentRuleEntry();
        createAssignmentRuleMember();
        

        assignmentRule = [SELECT Id, Sort_Order__c, Quotas__c, Load_Balancing__c, (SELECT Id, Field_API_Name__c, Operator__c, Value__c FROM Underwriter_Assignment_Rule_Entries__r), (SELECT Id, Underwriter__c, Last_Assignment_Date_Time__c, Quota__c FROM Underwriter_Assignment_Rule_Members__r) FROM Underwriter_Assignment_Rule__c WHERE Id = :assignmentRule.Id];
        
        UnderwriterAssignmentRule controller = new UnderwriterAssignmentRule(assignmentRule);
        
        System.debug(assignmentRule.Underwriter_Assignment_Rule_Entries__r + '   ' + assignmentEntry.Underwriter_Assignment_Rule__c + '  ' + assignmentRule.Id );
        

        //controller.evaluateRule(opp); Constructor has opportunity
        controller.getObjectFields();
        controller.useLoadBalancing = true;
        controller.useQuotas = true;    
        controller.getAssignmentRuleMember();
    }

    @isTest 
    public static void testUnderwriterAssignmentRuleEntry() {

        createAccount();
        createOpportunity();
        createAssignmentTemplate();
        createAssignmentRule();
        createUnderwriterAssignmentRuleEntry();
        createAssignmentRuleMember();

        assignmentEntry.Value__c = 'Id';
        UnderwriterAssignmentRuleEntry controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        //Focus on logical operators
        assignmentEntry.Operator__c = 'not equal to';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Operator__c = 'greater than';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Operator__c = 'less than';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Operator__c = 'greater or equal';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Operator__c = 'less or equal';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Operator__c = 'nothing';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        //Focus on FieldType
        assignmentEntry.Field_API_Name__c = 'McaApp__Origination_Fee__c';
        assignmentEntry.Value__c = '12.50';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Field_API_Name__c = 'cmbla__Completed__c';
        assignmentEntry.Value__c = 'true';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Field_API_Name__c = 'CloseDate';
        assignmentEntry.Value__c = '08/14/2011';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);

        assignmentEntry.Field_API_Name__c = 'McaApp__Factor_Rate__c';
        assignmentEntry.Value__c = '15';
        controller = new UnderwriterAssignmentRuleEntry(assignmentEntry);
        controller.evaluateRuleEntry(opp);



    }

    

    public static void createAssignmentTemplateList() { 
    
        assignmentTemplateList = new Underwriter_Assignment_Template__c[]{};
        insert assignmentTemplateList;
    }
    
    public static void createAssignmentTemplate() {

        assignmentTemplate = new Underwriter_Assignment_Template__c();
        assignmentTemplate.Active__c = true;
        insert assignmentTemplate;
    }
    
    public static void createAssignmentRule() {

        assignmentRule = new Underwriter_Assignment_Rule__c();
        assignmentRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;
        assignmentRule.Sort_Order__c = 1;
        //assignmentRule.Enable_Quotas__c = true;
        //assignmentRule.Enable_Load_Balancing__c = true;

        insert assignmentRule;
    }
    
    public static void createUnderwriterAssignmentRuleEntry() {

        assignmentEntry = new Underwriter_Assignment_Rule_Entry__c();
        assignmentEntry.Underwriter_Assignment_Rule__c = assignmentRule.Id;
        //assignmentEntry.Object_API__c = 'Lead';
        assignmentEntry.Description__c = 'descr';
        assignmentEntry.Field_API_Name__c = 'StageName';
        assignmentEntry.Operator__c = 'equal';
        assignmentEntry.Value__c = 'Prospecting';

        insert assignmentEntry;
    }
    
    public static void createAssignmentRuleMember() {

        assignmentMember = new Underwriter_Assignment_Rule_Member__c();
        assignmentMember.Underwriter_Assignment_Rule__c = assignmentRule.Id;
        assignmentMember.Quota__c = 0;
        insert assignmentMember;
    }
    
    public static void createOpportunity() { 

        opp = new Opportunity();
        opp.Name = 'Test Name';
        opp.StageName = 'Underwriting';
        opp.CloseDate = Date.today();
        opp.AccountId = acc.Id;
        insert opp;
    }

    public static void createAccount() {

        acc = new Account();
        acc.Name = 'test';
        insert acc;
    }


    

}