LendersApp/src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Account.object
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

LendersApp/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Opportunity.object
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <businessProcess>Standard Sales Process</businessProcess>
        <label>Default</label>
    </recordTypes>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

LendersApp/src/objects/UWVerification__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Verifications</relationshipLabel>
        <relationshipName>Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>PreQualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VerificationMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Verification Master</label>
        <referenceTo>VerificationMaster__c</referenceTo>
        <relationshipName>UW_Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Verification</label>
    <nameField>
        <label>Verification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/VBUDefaultFilters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Default list of filters for Verification  bulk update</description>
    <fields>
        <fullName>StageFilter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>VBU Default Filters for stage</description>
        <label>StageFilter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusFilter__c</fullName>
        <description>VBU Default Filters for status</description>
        <label>StatusFilter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>VBU Default Filters</label>
</CustomObject>

LendersApp/src/objects/VerificationMaster__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>PreQualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Verification Master</label>
    <nameField>
        <label>Verification Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verification Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/VerificationBulkUpdateControllerTest.cls
@isTest
private class VerificationBulkUpdateControllerTest {

    private static Account createAccount() {
        
        // recordtype for account 
        RecordType rcrdtypObj = [Select Id, Name, SobjectType 
                                 From RecordType 
                                 Where name = 'Bank' 
                                 And SobjectType = 'Account'];
        
        Account accountObj = new Account();
        accountObj.Name = 'AccountTest';
        accountObj.RecordtypeId = rcrdtypObj.Id;
        
        return accountObj;
    }
    
    private static Opportunity createOpportunity(Id pAccountId) {

        Opportunity opportunityObj = new Opportunity();
        opportunityObj.Name = 'OpportunityTest'; 
        opportunityObj.AccountId = pAccountId;
        opportunityObj.CloseDate = System.Today()+20;
        opportunityObj.StageName = 'Prospecting';
        
        
        return opportunityObj;
    }
    
    private static VerificationMaster__c createMaster() {

        VerificationMaster__c masterObj = new VerificationMaster__c ();
        masterObj.Name = 'MasterTest';
        
        return masterObj;
    }
    
    private static List<UWVerification__c> createVerification(Integer pCount, Id pOpportunityId, Id pMasterId) {

        List<UWVerification__c> VerificationLst = new List<UWVerification__c>();
         
        for (Integer i = 0; i < pCount; i++) {

            UWVerification__c verificationObj = new UWVerification__c();
            verificationObj.Name = 'VerificationTest';
            verificationObj.Opportunity__c = pOpportunityId;
            verificationObj.VerificationMaster__c = pMasterId;
            verificationObj.Stage__c = 'Underwriting';
            verificationObj.Status__c ='In Progress';
            VerificationLst.add(verificationObj);
        }
        
        return VerificationLst;
    }
    
    private static List<VBUDefaultFilters__c> createDefaultFilter(Integer pCount) {

        List<VBUDefaultFilters__c> listDefaultFilter = new List<VBUDefaultFilters__c>();
        
        for (Integer i = 0; i < pCount; i++) {

            VBUDefaultFilters__c defaultFilter = new VBUDefaultFilters__c();
            defaultFilter.Name ='Default Filter';
            //defaultFilter.StageFilter__c = true;
            defaultFilter.StatusFilter__c = 'Pending';
            listDefaultFilter.add(defaultFilter);
        }

        return listDefaultFilter;
    }
    
    @isTest
    public static void testInitMethod() { 
                
        Account objAccount = VerificationBulkUpdateControllerTest.createAccount();
        insert objAccount;
        
        Opportunity objOpportunity = VerificationBulkUpdateControllerTest.createOpportunity(objAccount.Id);
        insert objOpportunity;
        
        VerificationMaster__c objMaster = VerificationBulkUpdateControllerTest.createMaster();
        insert objMaster;
        
        List<UWVerification__c> lstVerification = VerificationBulkUpdateControllerTest.createVerification(5, objOpportunity.Id, objMaster.Id);
        insert lstVerification;
        
        List<VBUDefaultFilters__c> lstDefaultFilter = VerificationBulkUpdateControllerTest.createDefaultFilter(1);
        insert lstDefaultFilter;
    
        test.startTest();
             
        //Test.setCurrentPage(pageRef);
        ApexPages.StandardsetController controller = new ApexPages.StandardsetController(lstVerification);
        
        VerificationBulkUpdateController cntrllrObj = new VerificationBulkUpdateController(controller);
        pageReference pageRef = page.VerificationBulkUpdate;

        pageRef.getParameters().put('Id',objOpportunity.Id);
        //cntrllrObj.actionLink = pageRef;
        cntrllrObj.myVerifications = true;
        cntrllrObj.selectedstage = 'Underwriting';
        //cntrllrObj.selectedstatus =lstDefaultFilter[0].StageFilter__c ;
        List<VerificationBulkUpdateController.VerificationWrapper> wrprList = new List<VerificationBulkUpdateController.VerificationWrapper>();
    
        for(Integer i = 0; i <= lstVerification.size(); i++) {
           
           VerificationBulkUpdateController.VerificationWrapper wrapperObj = new VerificationBulkUpdateController.VerificationWrapper(lstVerification[0], 0);
           wrprList.add(wrapperObj);
        }
    
        List<String> stageList = cntrllrObj.verificationStages;
        List<String> statusList = cntrllrObj.verificationStatus;
        
        cntrllrObj.init();
        cntrllrObj.saveVerifications();
        cntrllrObj.applyFilter();
        cntrllrObj.clearFilter();
        cntrllrObj.verificationWrapperLst = wrprList;
        //cntrllrObj.saveVerifications();
        cntrllrObj.updateRecords();
                  
        test.stopTest();
    }

}