LendersApp/src/objects/MerchantInterviewQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Merchant Interview Questions</relationshipLabel>
        <relationshipName>Merchant_Interview_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Verification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Verification</label>
        <referenceTo>UWVerification__c</referenceTo>
        <relationshipLabel>Merchant Interview Questions</relationshipLabel>
        <relationshipName>Merchant_Interview_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Merchant Interview Question</label>
    <nameField>
        <displayFormat>MIQ-{0000000}</displayFormat>
        <label>Question No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Interview Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interview Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interview_Completed_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interview Completed Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interview_Total_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interview Total Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Verifications_Completed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Verifications Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Verifications_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Verifications Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/UWVerification__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Verifications</relationshipLabel>
        <relationshipName>Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>PreQualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Verification</label>
    <nameField>
        <label>Verification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/OpportunityRollUpHandler.cls
public with sharing class OpportunityRollUpHandler {
    
    UWVerification__c[] verificationList = new UWVerification__c[] {};
    MerchantInterviewQuestion__c[] questionList = new MerchantInterviewQuestion__c[] {};
    UWVerification__c[] allVerifications= new UWVerification__c[] {};
    MerchantInterviewQuestion__c[] allQuestions = new MerchantInterviewQuestion__c[] {};
    Set<Id> oppIds = new Set<Id>();
    Opportunity[] opps = new Opportunity[]{};
    Opportunity[] oppsToUpdate = new Opportunity[]{};


   
    public OpportunityRollUpHandler(List<SObject> newassets) {
        

        if (newassets[0].getSObjectType() == Schema.UWVerification__c.getSObjectType()) {

            verificationList = (List<UWVerification__c>)newassets;
        }
        else if (newassets[0].getSObjectType() == Schema.MerchantInterviewQuestion__c.getSObjectType()) {

            questionList = (List<MerchantInterviewQuestion__c>)newassets;
        }


        updateValues();

    }

  
    public void updateValues() {

        if ( !verificationList.isEmpty() ) {

            for ( UWVerification__c auxVerification : verificationList ) {

                oppIds.add(auxVerification.Opportunity__c);
            }
        }

        else if (!questionList.isEmpty()) {

            for ( MerchantInterviewQuestion__c auxQuestion : questionList ) {

                oppIds.add(auxQuestion.Opportunity__c);
            }   
        }


        opps = [SELECT Id FROM Opportunity WHERE Id IN :oppIds];

        allVerifications = [SELECT Id, Completed__c, Stage__c, Opportunity__c FROM UWVerification__c WHERE Opportunity__c = :oppIds];
        allQuestions = [SELECT Id, Completed__c, Verification__c, Opportunity__c FROM MerchantInterviewQuestion__c WHERE Opportunity__c = :oppIds];


        for ( Opportunity opp : opps ) {

            opp.Interview_Completed_Count__c = countMerchantCompleted(opp);
            opp.Interview_Total_Count__c = countMerchantTotal(opp);
            opp.Verifications_Completed__c = countVerificationCompleted(opp);
            opp.Verifications_Total__c = countVerificationTotal(opp);

            oppsToUpdate.add(opp);

        }

        update oppsToUpdate;
    }


    public Integer countMerchantCompleted(Opportunity opp) {

        Integer result = 0;

        for ( MerchantInterviewQuestion__c question : allQuestions) {

            if ( question.Opportunity__c == opp.Id && question.Completed__c ) {
            
                result++;
            }
        }

        return result;
    }


    public Integer countMerchantTotal(Opportunity opp) {

        Integer result = 0;

        for ( MerchantInterviewQuestion__c question : allQuestions) {
            
            if (question.Opportunity__c == opp.Id ) {
                
                result++;    
            }
        }

        return result;
    }

    public Integer countVerificationPrequalificationCompleted(Opportunity opp) {

        Integer result = 0;

        for ( UWVerification__c verification : allVerifications) {
            
            if ( verification.Opportunity__c == opp.Id && verification.Stage__c == 'PreQualification' && verification.Completed__c ) {

                result++;
            }
        }

        return result;
    }

    public Integer countVerificationPrequalificationTotal(Opportunity opp) {

        Integer result = 0;

        for ( UWVerification__c verification : allVerifications) {
            
            if ( verification.Opportunity__c == opp.Id && verification.Stage__c == 'PreQualification' ) {

                result++;
            }
        }

        return result;
    }

    public Integer countVerificationCompleted(Opportunity opp) {

        Integer result = 0;

        for ( UWVerification__c verification : allVerifications) {
            
            if ( verification.Opportunity__c == opp.Id && verification.Completed__c ) {

                result++;
            }
        }

        return result;
    }

    public Integer countVerificationTotal(Opportunity opp) {

        Integer result = 0;

        for ( UWVerification__c verification : allVerifications) {
            
            if ( verification.Opportunity__c == opp.Id ) {
                
                result++;
            }
        }

        return result;
    }

}