LendersApp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reassign_Underwriter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reassign Underwriter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter Assignment Rule Member</label>
        <referenceTo>Underwriter_Assignment_Rule_Member__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Load_Balancing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Load Balancing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quotas__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quotas</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Template__c</fullName>
        <label>Underwriter Assignment Template</label>
        <referenceTo>Underwriter_Assignment_Template__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rules</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Underwriter Assignment Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule__c</fullName>
        <label>Underwriter Assignment Rule</label>
        <referenceTo>Underwriter_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rule Entries</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Underwriter Assignment Rule Entry</label>
    <nameField>
        <displayFormat>UAE-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule_Member__c.object
<CustomObject>
    <fields>
        <fullName>Last_Assignment_Date_Time__c</fullName>
        <label>Last Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule__c</fullName>
        <label>Underwriter Assignment Rule</label>
        <referenceTo>Underwriter_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rule Members</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rule_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Underwriter_Reassignment_Enabled__c</fullName>
        <formula>Underwriter__r.Underwriter_Reassignment_Enabled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Underwriter Reassignment Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Underwriter_Assignment_Rule_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Underwriter Assignment Rule Member</label>
    <nameField>
        <displayFormat>UAM-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Template__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Underwriter Assignment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Underwriter_Reassignment_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Underwriter Reassignment Enabled</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

LendersApp/src/classes/UnderwriterAssignmentHandler.cls
public with sharing class UnderwriterAssignmentHandler {

    private UnderwriterAssignmentRule[] assignmentRules;
    private Opportunity opportunity;


    public UnderwriterAssignmentHandler(Opportunity opportunity) {
        
        assignmentTemplates();
        queryOpportunity(opportunity.Id); 
    }


    public void assign() {

        UnderwriterAssignmentRuleMember assignmentRuleMember;

        for (UnderwriterAssignmentRule assignmentRule : assignmentRules) {

            if (assignmentRule.evaluateRule(opportunity)) {

                assignmentRuleMember = assignmentRule.getAssignmentRuleMember();

                if (assignmentRuleMember != null) {
                    
                    break;
                }
            }
        }

        if (assignmentRuleMember != null) {

            opportunity.Underwriter__c = assignmentRuleMember.underwriter;
            //system.assert(false, 'RULEMEMBER NOT NULL ' + opportunity.Id + opportunity.Underwriter__c);

            opportunity.Underwriter_Assignment_Rule_Member__c = assignmentRuleMember.id;
            opportunity.Reassign_Underwriter__c = false;

            update opportunity;

            assignmentRuleMember.updateRecord();
        }
    }


    private void assignmentTemplates() {

        assignmentRules = new UnderwriterAssignmentRule[]{};

        for (Underwriter_Assignment_Rule__c assignmentRule : [SELECT Sort_Order__c,
                                                                     Quotas__c,
                                                                     Load_Balancing__c,

                                                                     (SELECT Field_API_Name__c,
                                                                             Operator__c,
                                                                             Value__c
                                                                        FROM Underwriter_Assignment_Rule_Entries__r),

                                                                     (SELECT Underwriter__c,
                                                                             Quota__c,
                                                                             Last_Assignment_Date_Time__c
                                                                        FROM Underwriter_Assignment_Rule_Members__r
                                                                        WHERE Underwriter__r.Underwriter_Reassignment_Enabled__c = true                                                   
                                                                    ORDER BY Last_Assignment_Date_Time__c ASC NULLS FIRST)

                                                                FROM Underwriter_Assignment_Rule__c
                                                               WHERE Underwriter_Assignment_Template__r.Active__c = true
                                                            ORDER BY Sort_Order__c ASC]) {

            assignmentRules.add(new UnderwriterAssignmentRule(assignmentRule));
        }
    }


    private void queryOpportunity(String opportunityId) {

        Set<String> opportunityFields = new Set<String>();

        for (UnderwriterAssignmentRule assignmentRule : assignmentRules) {

            opportunityFields.addAll(assignmentRule.getObjectFields());
        }


        String query = 'SELECT Id ';

        for (String field : opportunityFields) {

            query += ', ' + field;
        }

        query += ' FROM Opportunity WHERE Id =: opportunityId';

        
        for (Opportunity o : (Opportunity[]) Database.query(query)) {

            opportunity = o;
        }
    }
}