LendersApp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Count_Against_Pipeline__c</fullName>
        <formula>IF(OR(TEXT(StageName) = &quot;Closed Won&quot;, TEXT(StageName) = &quot;Closed Lost&quot;), False, True)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count Against Pipeline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter Assignment Rule Member</label>
        <referenceTo>Underwriter_Assignment_Rule_Member__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule_Member__c.object
<CustomObject>
    <label>Underwriter Assignment Rule Member</label>
    <nameField>
        <displayFormat>UAM-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler{

    public static void checkAssignmentRuleMemberForCapacity(List<Opportunity> opportunitiesNew) {

        for (Opportunity myOpportunity : opportunitiesNew) {

            if (myOpportunity.get('Count_Against_Pipeline__c') != NULL) {

                if (!myOpportunity.Count_Against_Pipeline__c) {
                	
                    myOpportunity.Underwriter_Assignment_Rule_Member__c = null;
                }   
            }
        }
    }       
}