LendersApp/src/objects/Underwriter_Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Template__c</fullName>
        <label>Underwriter Assignment Template</label>
        <referenceTo>Underwriter_Assignment_Template__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rules</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Underwriter Assignment Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Rule_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assignment_Rule__c</fullName>
        <label>Underwriter Assignment Rule</label>
        <referenceTo>Underwriter_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Underwriter Assignment Rule Entries</relationshipLabel>
        <relationshipName>Underwriter_Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Underwriter Assignment Rule Entry</label>
    <nameField>
        <displayFormat>UAE-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/objects/Underwriter_Assignment_Template__c.object
<CustomObject>
    <label>Underwriter Assignment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LendersApp/src/classes/UnderwriterValidatorTest.cls
@isTest
public with sharing class UnderwriterValidatorTest {
	
	@isTest 
	public static void fieldTypeIsString() {

		User user = [SELECT Id FROM User WHERE IsActive = true AND Id <> :UserInfo.getUserId() AND Name <> 'Kevin Lee' LIMIT 1];

        Underwriter_Assignment_Template__c assignmentTemplate = new Underwriter_Assignment_Template__c();
        assignmentTemplate.Name = 'Test Template';
        insert assignmentTemplate;

        Underwriter_Assignment_Rule__c assignmentRule = new Underwriter_Assignment_Rule__c();
        assignmentRule.Sort_Order__c = 1;
        assignmentRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;
        insert assignmentRule;


		Underwriter_Assignment_Rule_Entry__c assignmentRuleEntry = new Underwriter_Assignment_Rule_Entry__c();


		//Test first the cases WHERE everything should be fine.
		//assignmentRuleEntry.Object_API__c = '';
		assignmentRuleEntry.Operator__c   = 'equals';
		assignmentRuleEntry.Field_API_Name__c  = 'Interviewee__c';
		assignmentRuleEntry.Value__c      = 'TEST';
		assignmentRuleEntry.Underwriter_Assignment_Rule__c = [SELECT Id FROM Underwriter_Assignment_Rule__c WHERE Id =: assignmentRule.Id LIMIT 1][0].Id;

		insert assignmentRuleEntry;

		assignmentRuleEntry.Operator__c   = 'not equal to';

		update assignmentRuleEntry;

		assignmentRuleEntry.Operator__c   = 'contains';

		update assignmentRuleEntry;


		//Should fail here
		try {

			assignmentRuleEntry.Operator__c   = 'greater than';

			update assignmentRuleEntry; 

		} 
		catch (Exception e) {

			system.assert(true);
		}
	}

	@isTest 
	public static void fieldTypeIsDate() {

		User user = [SELECT Id FROM User WHERE IsActive = true AND Id <> :UserInfo.getUserId() AND Name <> 'Kevin Lee' LIMIT 1];

        Underwriter_Assignment_Template__c assignmentTemplate = new Underwriter_Assignment_Template__c();
        assignmentTemplate.Name = 'Test Template';
        insert assignmentTemplate;

        Underwriter_Assignment_Rule__c assignmentRule = new Underwriter_Assignment_Rule__c();
        assignmentRule.Sort_Order__c = 1;
        assignmentRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;

        insert assignmentRule;

		Underwriter_Assignment_Rule_Entry__c assignmentRuleEntry = new Underwriter_Assignment_Rule_Entry__c();

		//Test first the cases WHERE everything should be fine.
		//assignmentRuleEntry.Object_API__c = 'Lead';
		assignmentRuleEntry.Operator__c   = 'equals';
		assignmentRuleEntry.Field_API_Name__c  = 'McaApp__Current_Balance_Date__c';
		assignmentRuleEntry.Value__c      = '01/15/1983';
		assignmentRuleEntry.Underwriter_Assignment_Rule__c = [SELECT Id FROM Underwriter_Assignment_Rule__c WHERE Id =: assignmentRule.Id LIMIT 1][0].Id;

		insert assignmentRuleEntry;

		assignmentRuleEntry.Operator__c   = 'not equal to';

		update assignmentRuleEntry;

		
		assignmentRuleEntry.Operator__c   = 'greater than';

		update assignmentRuleEntry; 

		//Should fail here
		try{
		
			assignmentRuleEntry.Operator__c   = 'contains';

			update assignmentRuleEntry;
			
		} 
		catch (Exception e) {

			system.assert(true);

		}

	}

	@isTest 
	public static void fieldTypeIsBoolean() {

		User user = [SELECT Id FROM User WHERE IsActive = true AND Id <> :UserInfo.getUserId() AND Name <> 'Kevin Lee' LIMIT 1];

        Underwriter_Assignment_Template__c assignmentTemplate = new Underwriter_Assignment_Template__c();
        assignmentTemplate.Name = 'Test Template';
        insert assignmentTemplate;

        Underwriter_Assignment_Rule__c assignmentRule = new Underwriter_Assignment_Rule__c();
        assignmentRule.Sort_Order__c = 1;
        assignmentRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;

        insert assignmentRule;

		Underwriter_Assignment_Rule_Entry__c assignmentRuleEntry = new Underwriter_Assignment_Rule_Entry__c();

		//Test first the cases WHERE everything should be fine.
		//assignmentRuleEntry.Object_API__c = 'Lead';
		assignmentRuleEntry.Operator__c   = 'equals';
		assignmentRuleEntry.Field_API_Name__c  = 'McaApp__Bank_Statements__c';
		assignmentRuleEntry.Value__c      = 'true';
		assignmentRuleEntry.Underwriter_Assignment_Rule__c = [SELECT Id FROM Underwriter_Assignment_Rule__c WHERE Id =: assignmentRule.Id LIMIT 1][0].Id;

		insert assignmentRuleEntry;

		assignmentRuleEntry.Operator__c   = 'not equal to';

		update assignmentRuleEntry;

		
		assignmentRuleEntry.Operator__c   = 'equals';

		update assignmentRuleEntry; 

		//Should fail here
		try {
		
			assignmentRuleEntry.Operator__c   = 'contains';

			update assignmentRuleEntry;
			
		}
		catch(Exception e) {

			system.assert(true);
		}
	}	

	@isTest 
	public static void fieldTypeIsNumeric() {

		User user = [SELECT Id FROM User WHERE IsActive = true AND Id <> :UserInfo.getUserId() AND Name <> 'Kevin Lee' LIMIT 1];

        Underwriter_Assignment_Template__c assignmentTemplate = new Underwriter_Assignment_Template__c();
        assignmentTemplate.Name = 'Test Template';
        insert assignmentTemplate;

        Underwriter_Assignment_Rule__c assignmentRule = new Underwriter_Assignment_Rule__c();
        assignmentRule.Sort_Order__c = 1;
        assignmentRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;

        insert assignmentRule;

		Underwriter_Assignment_Rule_Entry__c assignmentRuleEntry = new Underwriter_Assignment_Rule_Entry__c();

		//Test first the cases WHERE everything should be fine.
		//assignmentRuleEntry.Object_API__c = 'Lead';
		assignmentRuleEntry.Operator__c   = 'equals';
		assignmentRuleEntry.Field_API_Name__c  = 'McaApp__Factor_Rate__c';
		assignmentRuleEntry.Value__c      = '6757647';
		assignmentRuleEntry.Underwriter_Assignment_Rule__c = [SELECT Id FROM Underwriter_Assignment_Rule__c WHERE Id =: assignmentRule.Id LIMIT 1][0].Id;

		insert assignmentRuleEntry;

		assignmentRuleEntry.Operator__c   = 'not equal to';

		update assignmentRuleEntry;

		
		assignmentRuleEntry.Operator__c   = 'greater than';

		update assignmentRuleEntry; 

		//Should fail here
		try {
		
			assignmentRuleEntry.Operator__c   = 'contains';

			update assignmentRuleEntry;
			
		}
		catch (Exception e) {

			system.assert(true);
		}
	}



	@isTest 
	public static void fieldTypeIsDateTime() {
		
		User user = [SELECT Id FROM User WHERE IsActive = true AND Id <> :UserInfo.getUserId() AND Name <> 'Kevin Lee' LIMIT 1];

        Underwriter_Assignment_Template__c assignmentTemplate = new Underwriter_Assignment_Template__c();
        assignmentTemplate.Name = 'Test Template';
        insert assignmentTemplate;

        Underwriter_Assignment_Rule__c assignmentRule = new Underwriter_Assignment_Rule__c();
        assignmentRule.Sort_Order__c = 1;
        assignmentRule.Underwriter_Assignment_Template__c = assignmentTemplate.Id;

        insert assignmentRule;

		Underwriter_Assignment_Rule_Entry__c assignmentRuleEntry = new Underwriter_Assignment_Rule_Entry__c();

		//Test first the cases WHERE everything should be fine.
		//assignmentRuleEntry.Object_API__c = 'Lead';
		assignmentRuleEntry.Operator__c   = 'equals';
		assignmentRuleEntry.Field_API_Name__c  = 'Date_Interview__c';
		assignmentRuleEntry.Value__c      = '3/14/2016 6:39 AM';
		assignmentRuleEntry.Underwriter_Assignment_Rule__c = [SELECT Id FROM Underwriter_Assignment_Rule__c WHERE Id =: assignmentRule.Id LIMIT 1][0].Id;

		insert assignmentRuleEntry;

		assignmentRuleEntry.Operator__c   = 'not equal to';

		update assignmentRuleEntry;

		
		assignmentRuleEntry.Operator__c   = 'greater than';

		update assignmentRuleEntry; 

		//Should fail here
		try {
		
			assignmentRuleEntry.Operator__c   = 'contains';

			update assignmentRuleEntry;
			
		}
		catch (Exception e) {

			system.assert(true);
		}

	}



}