LendersApp/src/objects/Underwriter_Assignment_Rule_Member__c.object
<CustomObject>
    <fields>
        <fullName>Last_Assignment_Date_Time__c</fullName>
        <label>Last Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Underwriter_Assignment_Rule_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Underwriter Assignment Rule Member</label>
    <nameField>
        <displayFormat>UAM-{000000}</displayFormat>
        <label>Underwriter Assignment Rule Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Assignment Rule Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendersApp/src/classes/UnderwriterAssignmentRuleMember.cls
public with sharing class UnderwriterAssignmentRuleMember {
    
    private Underwriter_Assignment_Rule_Member__c assignmentRuleMember;
    
    public String id { get; set; }
    public String underwriter { get; set; }
    public Datetime lastAssignmentDatetime { get; set; }
    public Integer quota { get; set; }


    public UnderwriterAssignmentRuleMember(Underwriter_Assignment_Rule_Member__c assignmentRuleMember) {
        
        this.assignmentRuleMember = assignmentRuleMember;   

        id = assignmentRuleMember.Id;
        underwriter = assignmentRuleMember.Underwriter__c;
        lastAssignmentDatetime = assignmentRuleMember.Last_Assignment_Date_Time__c;

        if (assignmentRuleMember.Quota__c != null) {
        
            quota = Integer.valueOf(assignmentRuleMember.Quota__c);
        }
        else {

            quota = 0;
        }           
    }

    
    public void updateRecord() {

        assignmentRuleMember.Last_Assignment_Date_Time__c = lastAssignmentDatetime;
        update assignmentRuleMember;
    }   
}