MCADevOrg/src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCADevOrg/src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

MCADevOrg/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Opportunity.object
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding</relationshipLabel>
        <relationshipName>Funding</relationshipName>
        <type>Lookup</type>
    </fields>

MCADevOrg/src/objects/Payable__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Needs Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid - Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Clarification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>PAYB-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c - Receivable_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_From_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receivables</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receivable_Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Add Status of Receivable</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Ready to Pay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCADevOrg/src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Depostied__c</fullName>
        <label>Bank Acct</label>
        <picklist>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citibank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wells Fargo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pmt_Method__c</fullName>
        <label>Pmt Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QuickPay</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postdated Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>Revenue and other incoming funds</description>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Debit</fullName>
        <active>true</active>
        <description>For expenses and other debits</description>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Transaction_Line_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receivable__c</fullName>
        <label>Receivable</label>
        <referenceTo>Receivable__c</referenceTo>
        <relationshipLabel>Transaction Line Credit</relationshipLabel>
        <relationshipName>Transaction_Line_Credit</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transaction Line Credit</relationshipLabel>
        <relationshipName>Transaction_Line_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Line Credit</label>
    <nameField>
        <displayFormat>TLC-{0000}</displayFormat>
        <label>Transaction Line Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Transaction_Line_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payable__c</fullName>
        <label>Payable</label>
        <referenceTo>Payable__c</referenceTo>
        <relationshipLabel>Transaction Line Debit</relationshipLabel>
        <relationshipName>Transaction_Line_Debit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transaction Line Debit</relationshipLabel>
        <relationshipName>Transaction_Line_Debit</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Line Debit</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Debit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCADevOrg/src/classes/TestTransactionLineCreditHandler.cls
@isTest
public with sharing class TestTransactionLineCreditHandler {
	public static final string COMPLETED = 'Completed';
	public static final string PENDING = 'Pending';
	static Id prepareTestData(){
        //Common data
        List<RecordType> recordTypes = [select Id, Name FROM RecordType Where Name='Debit' OR Name='Credit'];
        Map<String, Id> mapTransRecordTypes = new Map<String, Id>();
        for(RecordType objRecordType : recordTypes){
            mapTransRecordTypes.put(objRecordType.Name, objRecordType.Id);
        }
        
        Account objAccount = new Account(Name='Test', Type='Analyst', Industry='Energy');
        insert objAccount; 
        
        Contact objContact = new Contact(LastName='Last', AccountId = objAccount.Id);
        insert objContact;
        
        Opportunity objOpp = new Opportunity(Name='Opp1', AccountId=objAccount.Id, CloseDate = System.today(), StageName='Prospecting');
        insert objOpp;  
        
        Receivable__c objInvoice = new Receivable__c( Status__c='Open', Due_From_Account__c = objAccount.Id, Amount__c=1000);
        insert objInvoice;
        
        Receivable__c objInvoice1 = new Receivable__c( Status__c='Open', Due_From_Account__c = objAccount.Id, Amount__c=2000);
        insert objInvoice1;
        
        Transaction__c objTransaction = new Transaction__c( Date__c=System.Today(), Amount__c =1000.00, Pmt_Method__c='Cash',Bank_Depostied__c = 'Visa', Account__c= objAccount.Id,   Contact__c= objContact.Id, RecordTypeId = mapTransRecordTypes.get('Credit'));
        insert objTransaction;
        
        Transaction_Line_Credit__c objLineCredit = new Transaction_Line_Credit__c(Amount__c=500, Receivable__c=objInvoice.Id, Transaction__c=objTransaction.Id);
        insert objLineCredit;
        
        Transaction_Line_Credit__c objLineCredit1 = new Transaction_Line_Credit__c(Amount__c=500, Receivable__c=objInvoice.Id, Transaction__c=objTransaction.Id);
        insert objLineCredit1;
        
        return objTransaction.Id;
    }
    
    static Id prepareDebitTestData(){
        //Common data
        List<RecordType> recordTypes = [select Id, Name FROM RecordType Where Name='Debit' OR Name='Credit'];
        Map<String, Id> mapTransRecordTypes = new Map<String, Id>();
        for(RecordType objRecordType : recordTypes){
            mapTransRecordTypes.put(objRecordType.Name, objRecordType.Id);
        }
        
        Account objAccount = new Account(Name='Test', Type='Analyst', Industry='Energy');
        insert objAccount; 
        
        Opportunity objOpp = new Opportunity(Name='Opp1', AccountId=objAccount.Id, CloseDate = System.today(), StageName='Prospecting');
        insert objOpp;
        
        Contact objContact = new Contact(LastName='Last', AccountId = objAccount.Id);
        insert objContact;
    
        Payable__c objPayable = new Payable__c(Account__c=objAccount.Id, Status__c = 'Open - Ready to Pay', Amount_Due__c=21000.00 );
        insert objPayable; 
        
        Payable__c objPayable1 = new Payable__c(Account__c=objAccount.Id, Status__c = 'Open - Ready to Pay', Amount_Due__c=2000.00 );
        insert objPayable1;
        
        Transaction__c objTransaction = new Transaction__c(Date__c=System.Today(), status__c='Open', Amount__c=1000.00, Pmt_Method__c='Cash', Bank_Depostied__c = 'Visa', Account__c= objAccount.Id, Contact__c= objContact.Id, RecordTypeId = mapTransRecordTypes.get('Debit'));
        insert objTransaction;
        
        Transaction_Line_Debit__c objLineDebit = new Transaction_Line_Debit__c(Amount__C = 500, Payable__c = objPayable.Id, Transaction__c = objTransaction.Id);
        insert objLineDebit;
        
        Transaction_Line_Debit__c objLineDebit1 = new Transaction_Line_Debit__c(Amount__C = 500, Payable__c = objPayable.Id, Transaction__c = objTransaction.Id);
        insert objLineDebit1;
        return objTransaction.Id;
    }
    
    static testMethod void testCreditTransaction() {
    	 Id objId = prepareTestData();
    	 Transaction__c objTransaction = new Transaction__c();
        objTransaction = [SELECT Name, Date__c, status__c, Amount__c, Pmt_Method__c, Bank_Depostied__c, Account__c, Contact__c, RecordTypeId 
                                         FROM Transaction__c 
                                         where Id=:objId limit 1];
        
        test.startTest();                           
       // System.assertEquals(COMPLETED,objTransaction.Status__c);
        
        List<Transaction_Line_Credit__c> lstLineCredit = [Select Id, Name, Receivable__c,Receivable__r.Receivable_Amount_Paid__c from Transaction_Line_Credit__c where Transaction__c=:objTransaction.Id];
        System.assertEquals(1000,lstLineCredit[0].Receivable__r.Receivable_Amount_Paid__c);
        
        if(lstLineCredit.size()>0)
        	delete lstLineCredit[0];
        
        objTransaction = [SELECT Name, Date__c, status__c, Amount__c, Pmt_Method__c, Bank_Depostied__c, Account__c, Contact__c, RecordTypeId 
                                         FROM Transaction__c 
                                         where Id=:objId limit 1];	
        System.assertEquals(PENDING,objTransaction.Status__c);
        
        Receivable__c objReceivable1 = [select Id, Name, Receivable_Amount_Paid__c from Receivable__c where id =: lstLineCredit[0].Receivable__r.Id];
        System.assertEquals(500,objReceivable1.Receivable_Amount_Paid__c);
        test.stopTest();
    }
    
     static testMethod void testDebitTransaction() {
     	Id objId = prepareDebitTestData();
     	
     	Transaction__c objTransaction = new Transaction__c();
        objTransaction = [SELECT Name, Date__c, status__c, Amount__c, Pmt_Method__c, Bank_Depostied__c, Account__c, Contact__c, RecordTypeId 
                                         FROM Transaction__c 
                                         where Id=:objId limit 1];
        
        test.startTest();                           
        //System.assertEquals(COMPLETED,objTransaction.Status__c);
        
        List<Transaction_Line_Debit__c> lstLineDebit = [select Id, Name, Amount__c from Transaction_Line_Debit__c where Transaction__c =: objTransaction.Id];
        if(lstLineDebit.size()>0)
        	delete lstLineDebit[0];
        	
        objTransaction = [SELECT Name, Date__c, status__c, Amount__c, Pmt_Method__c, Bank_Depostied__c, Account__c, Contact__c, RecordTypeId 
                                         FROM Transaction__c 
                                         where Id=:objId limit 1];	
        
       	System.assertEquals(PENDING,objTransaction.Status__c);
     }
}