MCADevOrg/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Merchant</fullName>
        <active>true</active>
        <description>Businesses seeking funding or other services - The customer</description>
        <label>Merchant</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merul_Dev/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

MCADevOrg/src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

MCADevOrg/src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>GridTesting</fullName>
        <active>true</active>
        <businessProcess>Standard Sales Process</businessProcess>
        <label>GridTesting</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCADevOrg/src/classes/GRIDTestDataFactory.cls
public with sharing class GRIDTestDataFactory {
     
     // method for Account
     public static Account getAccountRecord() {

        Account accountObj = new Account();
        accountObj = MCAOrgTestDataFactory.getOrgAccountRecord(accountObj, 1);
        accountObj.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Merchant').getRecordTypeId();
           
        return accountObj;
    }
    
    // method for Opportunity
    public static Opportunity getOpportunityRecord(Id pParentAccId) {
        
        Opportunity opportunityObj = new Opportunity();
        opportunityObj = MCAOrgTestDataFactory.getOrgOpportunityRecord(opportunityObj, 1);
        //opportunityObj.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('GridTesting').getRecordTypeId();
        opportunityObj.AccountId = pParentAccId;
        
        return opportunityObj;
    }
    
    // method for Submission
    public static Submission__c getSubmissionRecord(Id pParentOppId) {
        Submission__c submissionObj = new Submission__c();
        submissionObj= MCAOrgTestDataFactory.getOrgSubmissionRecord(submissionObj, pParentOppId);
        submissionObj.Opportunity__c = pParentOppId;
        
        return submissionObj;
    }
    // method for contact
    public static Contact getGRIDContactRecord(Id pParentAccId) {
        Contact conObj = new Contact();
        conObj = MCAOrgTestDataFactory.getOrgContactRecord(conObj, 1);
        conObj.AccountId = pParentAccId;
        
        return conObj;
    }
    
    // method for Attchment
    public static Attachment getGRIDAttachmentRecord(Id pParentOppId) {
        Attachment attchmntObj = new Attachment();
        attchmntObj = MCAOrgTestDataFactory.getOrgAttachmentRecord(attchmntObj);
        attchmntObj.ParentId = pParentOppId;
        attchmntObj.Name = 'testAttachment';
        attchmntObj.body = Blob.valueOf('Unit Test Attachment Body');
        
        return attchmntObj;
    }
}