MCADevOrg/src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address (Line 1)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address (Line 2)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Amount_Requested__c</fullName>
        <label>Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Balances__c</fullName>
        <label>Current Loan Balances</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <label>Federal Tax ID</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Credit_Card_Sales__c</fullName>
        <label>Monthly Credit Card Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montly_Gross_Sales__c</fullName>
        <label>Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_1_Email_Address__c</fullName>
        <label>Owner 1 Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Owner_1_First_Name__c</fullName>
        <label>Owner 1 First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_1_Home_Phone__c</fullName>
        <label>Owner 1 Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Owner_1_Last_Name__c</fullName>
        <label>Owner 1 Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_1_Mobile__c</fullName>
        <label>Owner 1 Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Owner_1_Ownership__c</fullName>
        <label>Owner 1 % Ownership</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Owner_1_SSN__c</fullName>
        <label>Owner 1 SSN</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Owner_2_Email_Address__c</fullName>
        <label>Owner 2 Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Owner_2_First_Name__c</fullName>
        <label>Owner 2 First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_2_Home_Phone__c</fullName>
        <label>Owner 2 Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Owner_2_Last_Name__c</fullName>
        <label>Owner 2 Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_2_Mobile__c</fullName>
        <label>Owner 2 Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Owner_2_Ownership__c</fullName>
        <label>Owner 2 % Ownership</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Owner_2_SSN__c</fullName>
        <label>Owner 2 SSN</label>
        <length>15</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Funding__c</fullName>
        <label>Purpose of Funding</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Business Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upload Attachments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_By_Client__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted By Client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_Time__c</fullName>
        <label>Submitted Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Application_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Documents</relationshipLabel>
        <relationshipName>Application_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <label>Attachment Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Document</label>
    <nameField>
        <label>Application Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Application_Portal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Return_URL__c</fullName>
        <label>Return URL</label>
        <type>Url</type>
    </fields>
    <label>Application Portal Settings</label>
</CustomObject>

DETE_Sandbox/src/objects/Industry__c.object
<CustomObject>
    <description>Industries from O*Net</description>
    <label>Industry</label>
    <nameField>
        <label>Industry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount_Requested__c</fullName>
        <label>Amount Requested</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_CC_Sale__c</fullName>
        <inlineHelpText>Average monthly credit card sales</inlineHelpText>
        <label>Monthly Credit Card Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Gross_Sales__c</fullName>
        <label>Monthly Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Funding__c</fullName>
        <label>Purpose of Funding</label>
        <picklist>
            <picklistValues>
                <fullName>Working Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay Bills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing/Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Business_Phone__c</fullName>
        <label>Business Phone #</label>
        <type>Phone</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <description>Enter the Federal Tax ID of the merchant.</description>
        <inlineHelpText>Enter the Federal Tax ID of the merchant.</inlineHelpText>
        <label>Federal Tax ID#</label>
        <length>10</length>
        <type>Text</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Owner_1_Ownership__c</fullName>
        <label>Owner 1 Ownership %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Owner_2_First_Name__c</fullName>
        <label>Owner 2 First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Owner_2_Last_Name__c</fullName>
        <label>Owner 2 Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Owner_2_Mobile__c</fullName>
        <label>Owner 2 Mobile</label>
        <type>Phone</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Owner_2_Ownership__c</fullName>
        <label>Owner 2 Ownership %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>

Bizfi Production/src/objects/Lead.object
    <fields>
        <fullName>Owner_2_SSN__c</fullName>
        <label>Owner 2 SSN</label>
        <length>11</length>
        <type>Text</type>
    </fields>

MCADevOrg/src/classes/ApplicationSubmissionController.cls
public with sharing class ApplicationSubmissionController {
	
	public String stage { get; set; }
	public String logoId { get; set; }
	public String email { get; set; }
	public String applicationNumber { get; set; }
	public String error { get; set; }
	//public String helpText { get; set; }
	
	public Application__c app { get; set; }

	public Application_Document__c bankStatement { get; set; }
	public Application_Document__c creditCardStatement { get; set; }
	public Application_Document__c driverLicense { get; set; }
	public Application_Document__c voidedCheck { get; set; }

	public transient Blob bankStatementsFileBody { get; set; }
    public transient Blob creditCardStmtsFileBody { get; set; }
    public transient Blob driversLicenseFileBody { get; set; }
    public transient Blob voidedCheckFileBody { get; set; }	
    
    public Application_Portal_Settings__c settings { get; set; }
    
    public SelectOption[] industries {get; set;}
	
	public ApplicationSubmissionController() {

        settings = Application_Portal_Settings__c.getOrgDefaults();

        if (settings == null) {
        	settings = new Application_Portal_Settings__c();
        }

        Schema.DescribeFieldResult f = Lead.Industry.getDescribe();
        List<Schema.PicklistEntry> elems = f.getPicklistValues();

        industries = new SelectOption[] {};
        for (Schema.PicklistEntry elem :elems) {
            industries.add(new SelectOption(elem.getLabel(), elem.getLabel()));
        }

		stage = 'stage1';
		
		for (Document d : [select Id from Document where DeveloperName = 'Application_Site_Logo' limit 1]) {
			logoId = d.Id;
		}		

		app = new Application__c();

		bankStatement = new Application_Document__c();
		creditCardStatement = new Application_Document__c();
		driverLicense = new Application_Document__c();
		voidedCheck = new Application_Document__c();

		queryApplicationById(ApexPages.currentPage().getParameters().get('id'));
		
		if (app.Id == null) {
			queryLead(ApexPages.currentPage().getParameters().get('lid'));
		}


		if (ApexPages.currentPage().getParameters().get('oid') != null) {

			app.Opportunity__c = ApexPages.currentPage().getParameters().get('oid');
		}
	}
	
	
	private void queryLead(String leadId) {
		Lead lead;
		if (leadId != null) {
			for (Lead l : [select Id
			                    , Street
			                    , City
			                    , State
			                    , PostalCode
			                    , Country 
			                    , Company
			                    , Email
			                    , Phone
			                    , FirstName
			                    , LastName
			                    //, Years_in_Business__c
			                    //, Monthly_Gross_Sales__c
			                    //, Average_Monthly_CC_Sale__c
			                    //, Purpose_of_Funding__c
			                    , Industry
			                 from Lead
			                where Id = : leadId]) {
				lead = l;
			}
			
			app.Business_Name__c = lead.Company; 
			app.First_Name__c = lead.FirstName;
			app.Last_Name__c = lead.LastName;
			app.Business_Phone__c = lead.Phone;
			app.Email_Address__c = lead.Email; 
			//app.Years_in_Business__c = lead.Years_in_Business__c;
			//app.Montly_Gross_Sales__c = lead.Monthly_Gross_Sales__c;
			//app.Monthly_Credit_Card_Sales__c = lead.Average_Monthly_CC_Sale__c;
			app.Address_Line_1__c = lead.Street;
			app.City__c = lead.City;
			app.State__c = lead.State;
			app.Zip_Postal_Code__c = lead.PostalCode;
			//app.Purpose_of_Funding__c = lead.Purpose_of_Funding__c;
			app.Industry__c = lead.Industry;
			app.Lead__c = lead.Id;
		}
	}


	private void queryApplicationById(String aid) {
		if (aid != null) {
			for (Application__c a : [select Business_Name__c
											, First_Name__c
											, Last_Name__c
											, Business_Phone__c   
											, Email_Address__c
											, Current_Loan_Balances__c
											, Amount_Requested__c
											, Years_in_Business__c
											, Montly_Gross_Sales__c
											, Monthly_Credit_Card_Sales__c
											, Address_Line_1__c
											, Address_Line_2__c
											, City__c
											, State__c
											, Zip_Postal_Code__c
											, Purpose_of_Funding__c
											, Industry__c
											, Federal_Tax_ID__c
											, Owner_1_First_Name__c
											, Owner_1_Last_Name__c 
											, Owner_1_Email_Address__c
											, Owner_1_Home_Phone__c
											, Owner_1_Mobile__c
											, Owner_1_SSN__c
											, Owner_1_Ownership__c
											, Owner_2_First_Name__c
											, Owner_2_Last_Name__c 
											, Owner_2_Email_Address__c
											, Owner_2_Home_Phone__c
											, Owner_2_Mobile__c
											, Owner_2_SSN__c
											, Owner_2_Ownership__c
											, Stage__c
											, Submitted_Time__c
											, Submitted_By_Client__c
										 from Application__c
										where Id = :aid]) {
				app = a;

				if (a.Stage__c == 'Business Information') {
                    stage = 'stage1';
                }
                else if (a.Stage__c == 'Personal Information') {
                    stage = 'stage2';
                }
                else if (a.Stage__c == 'Upload Attachments') {
                    stage = 'stage3';
                }
                else if (a.Stage__c == 'Submit') {
                    stage = 'stage4';
                }
			}

			for (Application_Document__c ad : [select Name
													, File_Name__c
													, Attachment_Id__c
												 from Application_Document__c
												where Application__c = :aid]) {
				if (ad.Name == 'Bank Statement') {
					bankStatement = ad;
				}
				else if (ad.Name == 'Credit Card Statement') {
					creditCardStatement = ad;
				}
				else if (ad.Name == 'Copy of Drivers License') {
					driverLicense = ad;
				}
				else if (ad.Name == 'Copy of Voided Check') {
					voidedCheck = ad;
				}
			}

		}
	}	
	
	
	public void queryApplicationByApplicationNumber() {
		String aid;
        if (applicationNumber != null) {
            for (Application__c a : [select Business_Name__c
                                            , First_Name__c
                                            , Last_Name__c
                                            , Business_Phone__c   
                                            , Email_Address__c
                                            , Current_Loan_Balances__c
                                            , Amount_Requested__c
                                            , Years_in_Business__c
                                            , Montly_Gross_Sales__c
                                            , Monthly_Credit_Card_Sales__c
                                            , Address_Line_1__c
                                            , Address_Line_2__c
                                            , City__c
                                            , State__c
                                            , Zip_Postal_Code__c
                                            , Purpose_of_Funding__c
                                            , Industry__c
                                            , Federal_Tax_ID__c
                                            , Owner_1_First_Name__c
                                            , Owner_1_Last_Name__c 
                                            , Owner_1_Email_Address__c
                                            , Owner_1_Home_Phone__c
                                            , Owner_1_Mobile__c
                                            , Owner_1_SSN__c
                                            , Owner_1_Ownership__c
                                            , Owner_2_First_Name__c
                                            , Owner_2_Last_Name__c 
                                            , Owner_2_Email_Address__c
                                            , Owner_2_Home_Phone__c
                                            , Owner_2_Mobile__c
                                            , Owner_2_SSN__c
                                            , Owner_2_Ownership__c
                                            , Stage__c
                                            , Submitted_Time__c
                                            , Submitted_By_Client__c
                                         from Application__c
                                        where Name = :applicationNumber
                                          and Email_Address__c = :email]) {
                app = a;
                aid = a.Id;

                if (a.Stage__c == 'Business Information') {
                    stage = 'stage1';
                }
                else if (a.Stage__c == 'Personal Information') {
                    stage = 'stage2';
                }
                else if (a.Stage__c == 'Upload Attachments') {
                    stage = 'stage3';
                }
                else if (a.Stage__c == 'Submit') {
                    stage = 'stage4';
                }
            }

            for (Application_Document__c ad : [select Name
                                                    , File_Name__c
                                                    , Attachment_Id__c
                                                 from Application_Document__c
                                                where Application__c = :aid]) {
                if (ad.Name == 'Bank Statement') {
                    bankStatement = ad;
                }
                else if (ad.Name == 'Credit Card Statement') {
                    creditCardStatement = ad;
                }
                else if (ad.Name == 'Copy of Drivers License') {
                    driverLicense = ad;
                }
                else if (ad.Name == 'Copy of Voided Check') {
                    voidedCheck = ad;
                }
            }

        }
        
        if (aid == null) {
        	error = '* There is no application for the email ' + email + ' or the application number ' + applicationNumber + ' is incorrect. Please review'; 
        }
        else {
        	error = '';
        }
        
    }   


	public void changeStage() {
		error = '';
		
		if (stage == 'stage4') {
			addDocument(bankStatement, 'Bank Statement', bankStatementsFileBody);						
			addDocument(creditCardStatement, 'Credit Card Statement', creditCardStmtsFileBody);						
			addDocument(driverLicense, 'Copy of Drivers License', driversLicenseFileBody);						
			addDocument(voidedCheck, 'Copy of Voided Check', voidedCheckFileBody);						
		}
	}


	private void addDocument(Application_Document__c doc, String docName, Blob file) {
		if (file != null) {
			save();

			if (doc.Application__c == null) {
				doc.Application__c = app.Id;
			}

			doc.Name = docName;
			upsert doc;

			Attachment a = (doc.Attachment_Id__c != null ? new Attachment(Id = doc.Attachment_Id__c) : new Attachment(ParentId = app.Id));
			a.Name = doc.File_Name__c;
			a.Body = file;
			upsert a;

			doc.Attachment_Id__c = a.Id;
			update doc;
		}
	}


	public void save() {
		if (stage == 'stage1') {
			app.Stage__c = 'Business Information';
		}
		else if (stage == 'stage2') {
			app.Stage__c = 'Personal Information';
			app.Owner_1_Email_Address__c = app.Email_Address__c;
            app.Owner_1_First_Name__c = app.First_Name__c;
            app.Owner_1_Last_Name__c = app.Last_Name__c;
            app.Owner_1_Home_Phone__c = app.Business_Phone__c;
		}
		else if (stage == 'stage3') {
			app.Stage__c = 'Upload Attachments';
		}
		else if (stage == 'stage4') {
			app.Stage__c = 'Submit';
		}
		upsert app;
	}


	public PageReference submitApplication() {
		app.Submitted_Time__c = DateTime.now();
		app.Submitted_By_Client__c = true;
		app.Stage__c = 'Completed';

        stage = 'stage5';
        save();

        if (settings.Return_URL__c != null) {

            PageReference p = new PageReference(settings.Return_URL__c);
            p.setRedirect(true);

            System.debug('PageReference p ' + p);
            return p;
        }
        
		
        return null;
	}

	
	public void deleteAttachment() {
		String aid = ApexPages.currentPage().getParameters().get('aid');
		
		if (aid == bankStatement.Id) {
			delete bankStatement;
			bankStatement = new Application_Document__c();
		}
		else if (aid == creditCardStatement.Id) {
			delete creditCardStatement;
			creditCardStatement = new Application_Document__c();
		}
		else if (aid == driverLicense.Id) {
			delete driverLicense;
			driverLicense = new Application_Document__c();
		}
		else if (aid == voidedCheck.Id) {
			delete voidedCheck;
			voidedCheck = new Application_Document__c();
		}
	}	
}