MCADevOrg/src/objects/Bank_Holiday__c.object
<CustomObject>
    <fields>
        <fullName>Holiday_Date__c</fullName>
        <label>Holiday Date</label>
        <type>Date</type>
    </fields>
    <label>Bank Holiday</label>
    <nameField>
        <label>Bank Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Payment__c.object
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Payment__c.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>Effective Date</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>

MCADevOrg/src/objects/Payment__c.object
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

MCADevOrg/src/objects/Payment__c.object
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

MCADevOrg/src/objects/Payment__c.object
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCADevOrg/src/objects/Payment__c.object
    <fields>
        <fullName>Repayment__c</fullName>
        <label>Repayment</label>
        <referenceTo>Repayment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

MCADevOrg/src/objects/Payment__c.object
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled. 
Settled: The ACH payment was pulled successfully from the customer&apos;s account 
Failed: Returned a failed response from the ACH provider</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fees Applied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCAPackagingOrg/src/objects/Repayment__c.object
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <label>Repayment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Intial_Repayment_Amount__c</fullName>
        <inlineHelpText>Initial Receivable/Repayment Amount.</inlineHelpText>
        <label>Initial Repayment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Last_Batch_Date__c</fullName>
        <label>Last Batch Date</label>
        <type>DateTime</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Next_Hit_Date__c</fullName>
        <label>Next Hit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <inlineHelpText>The amount of the payment. For Recurring payments, this will be the amount of the incremental payments</inlineHelpText>
        <label>Installment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Payment_Frequency__c</fullName>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Pending_Amount__c</fullName>
        <inlineHelpText>Amount submitted to the ACH processor, but not yet settled</inlineHelpText>
        <label>Total Pending Amount</label>
        <summarizedField>Payment__c.Transaction_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Scheduled, Pending</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Transaction_Type__c</field>
            <operation>equals</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Repayment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

MCADevOrg/src/objects/Repayment__c.object
    <fields>
        <fullName>Total_Outstanding_Amount__c</fullName>
        <formula>Intial_Repayment_Amount__c  -  Total_Amount_Settled__c - Total_Fees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total outstanding amount due</inlineHelpText>
        <label>Total Outstanding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

MCA App/Release/Release 2.9_2.10_2.11/Core Package Org/src/objects/Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payable/Receivable Status</label>
</CustomObject>

MCA Dev/src/classes/scheduleCreateTransBatch.cls
global class scheduleCreateTransBatch implements Schedulable {
   global static Set<Date> holidaySet;
   global void execute(SchedulableContext SC) {
      holidaySet = new Set<Date>();
      List<Bank_Holiday__c> holidays = new List<Bank_Holiday__c>([select id,name,Holiday_Date__c from Bank_Holiday__c where Holiday_Date__c=THIS_YEAR and Holiday_Date__c>=Today]);
      for(Bank_Holiday__c holiday:holidays){
          holidaySet.add(holiday.Holiday_Date__c);
      }
      string nextHitDate = string.valueOf(getValidDate(date.today().addDays(1))).split(' ')[0];
      string query = 'select id,Payment_Amount__c,Last_Batch_Date__c,Payment_Frequency__c,Next_Hit_Date__c,Intial_Repayment_Amount__c,'+
            '(select id,Effective_Date__c,Status__c from Payments__r order by Effective_Date__c desc),'+
            ' Pending_Amount__c,Payment_Method__c,Total_Outstanding_Amount__c'+
            ' from Repayment__c'+
            ' where Next_Hit_Date__c = '+nextHitDate+
            ' and Total_Outstanding_Amount__c > 0 and Status__c = \'Active\' order by Createddate desc';
       CreateTransBatch transBatch = new CreateTransBatch(query);
       ID batchprocessid = Database.executeBatch(transBatch);
   }
   private Date getValidDate(Date nextHitDate){
       Datetime dt = DateTime.newInstance(nextHitDate, Time.newInstance(0, 0, 0, 0));       
       String dayOfWeek=dt.format('EEEE');
       if(dayOfWeek=='Saturday')
          return getValidDate(nextHitDate.addDays(1));
       else if(dayOfWeek=='Sunday')
          return getValidDate(nextHitDate.addDays(1));
       else if(holidaySet.contains(nextHitDate))
          return getValidDate(nextHitDate.addDays(1));
       else
           return nextHitDate;
   }
}