MCADevOrg/src/objects/Bounce_Fees_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fees__c</fullName>
        <label>Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Error Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Fees Setting</label>
    <nameField>
        <displayFormat>BFS-{0000}</displayFormat>
        <label>Bounce Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCADevOrg/src/classes/BounceFeesSettingsController.cls
public class BounceFeesSettingsController
    {
         public List<Bounce_Fees_Settings__c> lstBounceFees {get;set;}
         public List<Bounce_Fees_Settings__c> lstAddBounceFees {get;set;}
         public Bounce_Fees_Settings__c objBounceFees{get;set;}
         public Integer totalCount {get;set;}
         public Integer rowIndex {get;set;}
         public BounceFeesSettingsController(ApexPages.StandardController controller)
         {
            lstBounceFees = [select Response_Code__c,Description__c,Fees__c from Bounce_Fees_Settings__c];
             totalCount = lstBounceFees.size();
             objBounceFees = new Bounce_Fees_Settings__c();
         }
         public void save()
         {
             upsert lstBounceFees;
         } 
         public void addRow()
         {
             lstAddBounceFees = new List<Bounce_Fees_Settings__c>();
             lstBounceFees.add(new Bounce_Fees_Settings__c());
         }
        public void deleteRow()
        {
            rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));            
            system.debug('$$'+rowIndex);            
            system.debug('$$'+lstBounceFees.size());
            if(lstBounceFees[rowIndex].id!=null)
                delete lstBounceFees[rowIndex];
            lstBounceFees.remove(rowIndex);         
        }
    }