MCADevOrg/src/objects/GRIDTabSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For the Setting related Dynamic GRID.</description>
    <fields>
        <fullName>Display_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to check if that particular org is given permission to view the tab.</description>
        <label>Display Tab</label>
        <type>Checkbox</type>
    </fields>
    <label>GRIDTabSetting</label>
</CustomObject>

merul_Dev/src/objects/GRIDTabsSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Display_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Tab</label>
        <type>Checkbox</type>
    </fields>
    <label>GRIDTabsSetting</label>
    <pluralLabel>GRIDTabsSettings</pluralLabel>
</CustomObject>

merul_Dev/src/classes/GRIDHomePageExtension.cls
public with sharing class GRIDHomePageExtension{
    
    
   // declaration
    private final Opportunity oppStd;
    public Map<String, GRIDTabsSetting__mdt> tabToSettingMap{get; set;}
   
    // constructor
    public GRIDHomePageExtension(ApexPages.StandardController stdController) {
         this.oppStd = (Opportunity)stdController.getRecord();
         //syndDisplayTab = GRIDTabSetting__c.getValues('Syndications').Display_Tab__c;
         tabToSettingMap = new Map<String, GRIDTabsSetting__mdt> ();
         tabToSettingMap = GRIDOnloadStaticVariable.getCustomMetaDataMap();
          
        
    }

}