MCADevOrg/src/objects/Loan_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daily_Payment__c</fullName>
        <label>Daily Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Balances</relationshipLabel>
        <relationshipName>Loan_Balances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Balance</label>
    <nameField>
        <displayFormat>BAL-{00000}</displayFormat>
        <label>Loan Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Balances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCA Dev/src/objects/MCATriggerExecuter__mdt.object
<CustomObject>
    <description>This custom metadata type will control the execution of various triggers in MCA App.</description>
    <fields>
        <fullName>IsActivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActivate</label>
        <type>Checkbox</type>
    </fields>
    <label>MCATriggerExecuter</label>
    <pluralLabel>MCATriggerExecuters</pluralLabel>
</CustomObject>

MCADevOrg/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Cash Advance Company Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Funders__c</fullName>
        <description>COUNT of Loan Balance</description>
        <inlineHelpText>COUNT of Loan Balance</inlineHelpText>
        <label># of Funders</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Daily_Payments__c</fullName>
        <description>SUM of Loan Balance: Payment</description>
        <inlineHelpText>SUM of Loan Balance: Payment</inlineHelpText>
        <label>Total Daily Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Loan_Balances__c</fullName>
        <description>SUM of Loan Balance: Balance</description>
        <inlineHelpText>SUM of Loan Balance: Balance</inlineHelpText>
        <label>Total Loan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCADevOrg/src/classes/LoanBalanceHandler.cls
/* 
 * Call in LoanBalance trigger to calculate RollUp on Opportunity
 *   
 * Version         Author                   Date                Description
 * 1.0             Shraddha P.              05-01-2016          Initial Draft[]
 */ 

public with sharing class LoanBalanceHandler {
    public LoanBalanceHandler() {
        
    }
    
    public void onAfterInsert() {       
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Daily_Payment__c', 
            'Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Balance__c', 
            'Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
      }
    }
    
    public void onAfterUpdate() {       
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Daily_Payment__c', 
            'Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Balance__c', 
            'Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
      }
    }
    
    public void onAfterUndelete(){
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Daily_Payment__c', 
            'Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Balance__c', 
            'Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.new, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
      }
    }
    
    public void onAfterDelete() {        
      if([select IsActivate__c from MCATriggerExecuter__mdt where DeveloperName = 'LoanBalanceRollUpTrigger'].IsActivate__c){
        list<RollupService.fieldDefinition> fieldDefinitions_dailypayment = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Daily_Payment__c', 
            'Total_Daily_Payments__c')
            };
        RollupService.rollUpTrigger(fieldDefinitions_dailypayment, trigger.old, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');

        list<RollupService.fieldDefinition> fieldDefinitions_Balance = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('SUM', 'Balance__c', 
            'Total_Loan_Balances__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_Balance, trigger.old, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
        
        list<RollupService.fieldDefinition> fieldDefinitions_funders = 
        new list<RollupService.fieldDefinition> {
            new RollupService.fieldDefinition('COUNT', 'Id', 
            'Number_of_Funders__c')
             };
         RollupService.rollUpTrigger(fieldDefinitions_funders, trigger.old, 
        'Loan_Balance__c', 'Opportunity__c', 'Opportunity', '');
      }
    }   
   
}