MCAPackagingOrg/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VeraSandBox2016/src/objects/Contact.object
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard JRR Contact (non-expert)</description>
        <label>Contact</label>
    </recordTypes>

MCAPackagingOrg/src/objects/Offer__c.object
<CustomObject>
    <description>Used to track offers to lend money to the merchant.  An offer is always related to a submission. An opportunity can have many Offers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Funding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <description>The Pick list field is refereed in Offers Grid</description>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Submission__c.Opportunity__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCADevOrg/src/objects/Opportunity.object
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>

MCAPackagingOrg/src/objects/Payable__c.object
<CustomObject>
    <description>Used to track money being paid to outside parties. An Opportunity can have many Payables</description>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Amount_Used__c</fullName>
        <label>Deal Amount Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Percentage of</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Funded Amount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>PAYB-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Program__c.object
<CustomObject>
    <description>Used to track the bank programs for a lender.</description>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Payback/Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Receivable__c.object
<CustomObject>
    <description>Used to track money being received from outside parties. An Opportunity can have many Receivables</description>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c - Receivable_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Amount_Used__c</fullName>
        <label>Deal Amount Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payback_Funded__c</fullName>
        <label>Percentage of</label>
        <picklist>
            <picklistValues>
                <fullName>Payback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Funded Amount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Receivable</label>
    <nameField>
        <displayFormat>RCVB-{00000}</displayFormat>
        <label>Receivable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Submission__c.object
<CustomObject>
    <description>Used to track to which Programs an Opportunity was submitted. Each Submission will always be related to one Program. Submissions are created via the Submission Wizard.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Syndication__c.object
<CustomObject>
    <description>Used to track syndication for an Opportunity. An Opportunity can have many Syndication records.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Syndication</relationshipLabel>
        <relationshipName>Syndication</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Syndication</label>
    <nameField>
        <displayFormat>SYND-{00000}</displayFormat>
        <label>Syndication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Syndications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MCAPackagingOrg/src/classes/MCAOrgTestDataFactory.cls
/**********************************************************************************************
Class to assign value to record to satisfy thet system validations and other mandatory fields.

**********************************************************************************************/
public with sharing class MCAOrgTestDataFactory { 
    
    // method for Account
    public static Account getOrgAccountRecord(Account pAcc, Integer pIterator) {
        pAcc.Name = 'TestAccount' +pIterator;        
        
        return pAcc;        
    }
    
    // method for Contact
    public static Contact getOrgContactRecord(Contact pCon, Integer pIterator) {
        pCon.LastName = 'TestContact' +pIterator;
        
        return pCon;
    }
    
    // method for Opportunity
    public static Opportunity getOrgOpportunityRecord(Opportunity pOpp, Integer pIterator) {
        pOpp.Name = 'TestOpportunity' +pIterator;
        pOpp.CloseDate = System.Today() +pIterator;
        pOpp.StageName = 'Prospecting';
        
        return pOpp;
    }
    
    // method for Offers
    public static Offer__c getOrgOfferRecord(Offer__c pOffer, Id pOppParent, Id pSubmissionParent) {
        pOffer.Opportunity__c = pOppParent;
        pOffer.Submission__c = pSubmissionParent;
        
        return pOffer;
    }
    
    // method for submission
    public Static Submission__c getOrgSubmissionRecord(Submission__c pSubmission, Id pOppParent) {
        pSubmission.Opportunity__c = pOppParent;
 
        return pSubmission;
    }
    
    // method for submission
    public Static Syndication__c getOrgSyndiactionRecord(Syndication__c pSyndication, Id pOppParent) {
        pSyndication.Opportunity__c = pOppParent;
 
        return pSyndication;
    }
    
    // method for Program
    public Static Program__c getOrgProgramRecord(Program__c pProgram) {
        pProgram.Name = 'TestProgram';
            
        return pProgram;
    }
    
    // method for payable
    public static Payable__c getOrgPayableRecord(Payable__c pPayable) {
        pPayable.Percentage__c = 10;
        pPayable.Deal_Amount_Used__c = 10000;
        pPayable.Payback_Funded__c = 'Funded';
        pPayable.Amount_Due__c = 1000;
        
        return pPayable;
    }
    
    // method for recievable
    public static Receivable__c getOrgReceivableRecord(Receivable__c pReceivable) {
        pReceivable.Percentage__c = 10;
        pReceivable.Deal_Amount_Used__c = 10000;
        pReceivable.Payback_Funded__c = 'Funded';
        pReceivable.Amount__c = 1000;
        
        return pReceivable;
    }
    
    public static Attachment getOrgAttachmentRecord(Attachment pAttachment) {
    
        return pAttachment;
    }
    
    public static EmailTemplate getOrgEmailTemplate(EmailTemplate pEmailTemplate) {
        pEmailTemplate.isActive = true;
        pEmailTemplate.Name = 'TestEmailTemplate';
        pEmailTemplate.DeveloperName = 'TestEmailTemplate';
        pEmailTemplate.TemplateType = 'text';
        pEmailTemplate.FolderId = UserInfo.getUserId();
        
        return pEmailTemplate;
    }
        
}