MCAPackagingOrg/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

MCAPackagingOrg/src/objects/Bank_Account__c.object
<CustomObject>
    <description>Used to track bank statements of the merchant and relevant data. An Opportunity can have many Bank Statements.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bank_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MCAPackagingOrg/src/classes/BankAccountHandlerServiceBefore.cls
/*
* Version       Date             Author         Description
*   1.0         23/10/2015       Ashwini S      Updating Account field on bank Account object.
*/
public without sharing class BankAccountHandlerServiceBefore {

public BankAccountHandlerServiceBefore(){}
// Updating account  if  account is not selected by user on  Bankstatements currently called on Before Update and Before insert.
public void updateAccount(map<Id,Bank_Account__c > oldBankAccMap, list<Bank_Account__c> BankAccountList, String frmOperation ){
        set<Id> setOpportunity = new set<Id>();
        
        for(Bank_Account__c objBA: BankAccountList){
            if( objBA.Opportunity__c != null && (frmOperation == BankAccountHandler.frmInsert || (frmOperation == BankAccountHandler.frmUpdate && 
                                                    (objBA.Opportunity__c != oldBankAccMap.get(objBA.Id).Opportunity__c || 
                                                     objBA.Account__c == null)
                                                 ))){
                setOpportunity.add(objBA.Opportunity__c);
            }
        }
        
        map<Id,Opportunity> oppMap;
        
        if(!setOpportunity.isEmpty())
            oppMap = new map<Id, Opportunity>([Select AccountId from Opportunity where Id IN: setOpportunity]);
        
        for(Bank_Account__c objBA: BankAccountList){
            if((frmOperation == BankAccountHandler.frmInsert || (frmOperation == BankAccountHandler.frmUpdate && 
                                               (objBA.Opportunity__c != oldBankAccMap.get(objBA.Id).Opportunity__c || 
                                                objBA.Account__c == null)
                                              )) 
                                    && objBA.Opportunity__c != null && oppMap != null && !oppMap.isEmpty() 
                                    && oppMap.containsKey(objBA.Opportunity__c)
                                    && objBA.Account__c == null){
                objBA.Account__c = oppMap.get(objBA.Opportunity__c).AccountId;
            }
        }
    }
}